### ISSUE TITLE
Regression in uv 5.10 installing from directory/git package with pyproject.toml

### ISSUE THREAD

**Issue by peterroelants** [astral-sh/uv#10039]
`uv pip install` a directory with a `pyproject.toml` fails with uv version 0.5.10 (and works with `uv<0.5.10`)

```
❯ uv pip install <package-name> @ git+ssh://git@<package_github_url>
Using Python 3.11.11 environment at: ~/miniforge3/envs/uv_test
 Updated ssh://git@<package_github_url> (abcdefg)
  × Failed to download and build `<package-name> @
  │ git+ssh://git@<package_github_url>`
  ├─▶ Failed to parse: `/home/peter/.cache/uv/git-v0/checkouts/asduhasdf/abcdefg/pyproject.toml`
  ╰─▶ TOML parse error at line 1, column 1
        |
      1 | [project]
        | ^^^^^^^^^
      `pyproject.toml` is using the `[project]` table, but the required `project.version` field is neither set nor present in the `project.dynamic` list
```

`pyproject.toml` looks like:
```toml
[project]
name = "<package-name>"
description = "Package discription"
version = "0.0.1"
readme = "README.md"
license = {text = "Proprietary/Confidential"}
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.9"
dynamic = [
  "dependencies",
]

[build-system]
requires = ["setuptools>=67", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["env/requirements.txt"]}

[tool.setuptools.packages.find]
where = ["./src"]

[project.urls]
source = "<package_github_url>"
```

I can successfully install the package with `uv-0.5.9` using `uv pip install <package-name> @ git+ssh://git@<package_github_url>`.
