### ISSUE TITLE
A command to install/get version of the package from `uv.lock`

### ISSUE THREAD

**Issue by paduszyk** [astral-sh/uv#10082]
In some circumstances, one may need a package installed using an exact version pinned in `uv.lock`.

For instance, this is the case when one wants to run `ruff check` on `ruff format` in CI and use the same version of the Ruff as the one installed in the environment &mdash; in fact, in the case of linting/formatting with `ruff`, the `ruff` is the only dependency required.

The following workflow:

```yaml
# ...

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      # Check out.
      # Set up Python. 
      - run: uv add ruff
      - run: uv run ruff check
      - run: uv run ruff format
```

will use the latest version compatible with Python set up &mdash; It does not have to be the same as the one in `uv.lock`.

One can circumvent this by using:

```yaml
    - run: uv sync --only-group ruff --frozen
```

with the `ruff` dependency group available in `pyproject.toml`. But is there any sense to define a separate group for a single development dependency?

I think that adding an extra command that would either return the exact version or install the pinned package would be an interesting feature. If the former, the version could be used as input for GitHub Actions...

Note that similar ideas were tried to be added to other dependency managers, e.g. python-poetry/poetry#3570.
