### ISSUE TITLE
Allow environment variables expansion in `pyproject.toml`

### ISSUE THREAD

**Issue by ShaiAvr** [astral-sh/uv#10096]
A feature I'd really like to see implemented is the ability to expand environment variables in the `pyproject.toml` file. My use-case is as follows: I am working on a library to simplify my work on other projects. In the future, I'd like to publish the library to PyPi. When I work on my projects, however, I want to use my library as a local editable dependency so I can quickly make changes and see them applied. So I have an example project with the following `pyproject.toml`:
```toml
[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "my-lib",
]

[tool.uv.sources]
my-lib = { path = "/path/to/my/library/my-lib", editable = true }
```
The problem is I am using an absolute path for my library, so I need to modify it if I work on multiple computers, and it's not something I'd want to push to GitHub. A better solution would be to have an environment variable that defines the location of the library on my local machine: `MY_LIB_PATH="/path/to/my/library/my-lib"`. That way, I can define the environment variable as necessary on different machines and my `pyproject.toml` file will simply use this variable:
```toml
[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "my-lib",
]

[tool.uv.sources]
my-lib = { path = "${MY_LIB_PATH}", editable = true }
```
This isn't possible at the moment, and I think expanding environment variables in the `pyproject.toml` file could solve my use case and other similar use cases.

**Comment by woutervh** [comment]
I would reference a local symlink  src/<my-lib>  --> /absolute/path/to/my-lib

**Comment by ShaiAvr** [comment]
@woutervh I don’t think a symbolic link should be uploaded to git. The contents of the link won’t be portable.

**Comment by charliermarsh** [comment]
Similar (but not identical) to #5734.

**Comment by dpnova** [comment]
would love to be able to do something like this:

```toml
[tool.uv.sources]
foo = { git = "https://${GITHUB_TOKEN}@github.com/fooco/foo.git" }
```
