### ISSUE TITLE
No version of package when using explicit index

### ISSUE THREAD

**Issue by hongbo-miao** [astral-sh/uv#10137]
# Experiment 1

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.10.0"
dependencies = [
  "detectron2",
  "magic-pdf[full]==0.10.6"
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "myhloli"
url = "https://wheels.myhloli.com"
explicit = true

[tool.uv.sources]
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git" }
magic-pdf = { index = "myhloli" }
```
fails with
```
uv sync
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of magic-pdf[full]==0.10.6 and your project depends on magic-pdf[full]==0.10.6, we can conclude that your project's requirements are unsatisfiable.
```

# Experiment 2

If I use same uv and Python version install by

```sh
uv pip install magic-pdf[full] --extra-index-url https://wheels.myhloli.com
Resolved 33 packages in 2.33s
⠸ Preparing packages... (0/2)
pdfminer-six ------------------------------ 32.00 KiB/5.36 MiB
botocore   ------------------------------ 14.92 KiB/12.68 MiB                                           
```

it works.

Any ideas? Thanks! ☺️
