### ISSUE TITLE
Conditionally allow dependencies to resolve where specific versions conflict with optional dependency bounds

### ISSUE THREAD

**Issue by mjlbach** [astral-sh/uv#10154]
# Description of problem
Some optional dependencies can introduce additional version constraints. E.g., I may introduce a package that requires numpy pinned to version 1.x.x. I would ideally like this not to impact the resolved packages when not using this optional dependency.

### pyproject toml
```toml
[project]
name = "uv-test"
version = "0.1.0"
description = "an example showing conflict resolution"
requires-python = ">=3.12.7"
dependencies = [
  "numpy>=2.0.0",
]

[project.optional-dependencies]
mediapipe = [
    "mediapipe>=0.10.20",
]

```

###  Sync the dependencies
```
❯ uv sync
Using CPython 3.12.7
Creating virtual environment at: .venv
  × No solution found when resolving dependencies:
  ╰─▶ Because your project depends on numpy>=2.0.0 and mediapipe==0.10.20 depends on
      numpy<2, we can conclude that mediapipe==0.10.20 and your project are incompatible.
      And because only mediapipe<=0.10.20 is available, we can conclude that
      mediapipe>=0.10.20 and your project are incompatible.
      And because uv-test[mediapipe] depends on mediapipe>=0.10.20 and your project
      requires uv-test[mediapipe], we can conclude that your project's requirements are
      unsatisfiable.
```

## Workaround

```toml
[project]
name = "uv-test"
version = "0.1.0"
description = "an example showing conflict resolution"
requires-python = ">=3.12.7"
dependencies = []

[dependency-groups]
numpy = [
  "numpy>=2.0.0",
]

[tool.uv]
default-groups = ["numpy"]
conflicts = [
    [
      { group = "numpy" },
      { extra = "mediapipe" },
    ],
]

[project.optional-dependencies]
mediapipe = [
    "mediapipe>=0.10.20",
]
```

## Ugly workaround
```
uv sync --extra mediapipe --no-group numpy
```

Anything I'm missing?
