### ISSUE TITLE
`uv lock --locked --offline` doesn’t work with projects that use dynamic versions

### ISSUE THREAD

**Issue by vivodi** [astral-sh/uv#10176]
### Summary
> The requested feature, ideally, wouldn't involve actually resolving any dependencies and could be performed in a CICD pipeline that may not have the correct connections set up to update the uv.lock file
 _Originally posted by @butterlyn in [#7639](https://github.com/astral-sh/uv/issues/7639#issuecomment-2368401456)_

According to https://github.com/astral-sh/uv/issues/7639#issuecomment-2368419143, we can use `uv lock --locked --offline` to check if the `pyproject.toml` has been modified since the creation of the current `uv.lock` file. However, this approach does not offline work for projects with dynamic versions.

### Poetry works, but uv doesn’t
`poetry check --lock` can be used offline for projects with dynamic versions, while `uv lock --locked --offline` cannot. Here’s my speculation on the reasons:

1. Poetry does not write project information (such as version numbers and project names) into the `poetry.lock` file; it only writes dependency information, so `hatchling` is not needed when locking. This information is directly read from the `pyproject.toml` file when building the project.
   
2. Poetry writes a hash of the contents of `pyproject.toml` into the `poetry.lock` file to offline check the consistency between `pyproject.toml` and `poetry.lock`, whereas `uv.lock` does not include a hash.

### Possible solutions

1. `uv lock` could write only the dependency information into the `uv.lock` file, while the project's version information is directly read from the `pyproject.toml` during the build. This would avoid the need for the `hatchling` dependency to obtain the current project version when running `uv lock`.

2. Include a hash of the `pyproject.toml` content in the `uv.lock` file, so that the consistency between `uv.lock` and `pyproject.toml` can be verified based solely on the hash.

Related issues: https://github.com/astral-sh/uv/issues/7639#issuecomment-2368401456 #10167 #9653

### Log
[Log](https://results.pre-commit.ci/run/github/908488856/1735234912.h9kunT3vRaGetP3P1E4UBA):
```
uv-lock..................................................................Failed
- hook id: uv-lock
- exit code: 2

warning: `VIRTUAL_ENV=/pc/clone/JLKubma3TtiMMhmWEG5Gxg/py_env-python3` does not match the project environment path `.venv` and will be ignored
Using CPython 3.12.7 interpreter at: /usr/bin/python3.12
error: Failed to generate package metadata for `myproject==1.0.0 @ editable+.`
  Caused by: Failed to resolve requirements from `build-system.requires`
  Caused by: No solution found when resolving: `hatchling`
  Caused by: Because hatchling was not found in the cache and you require hatchling, we can conclude that your requirements are unsatisfiable.

hint: Packages were unavailable because the network was disabled. When the network is disabled, registry packages may only be read from the cache.
```

pyproject.toml:
```toml
[project]
name = "myproject"
requires-python = ">=3.12"
dynamic = ["version"]

[tool.hatch.version]
path = "myproject/version.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

.pre-commit-config.yaml
```yaml
repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.11
  hooks:
    - id: uv-lock
      args: ["--locked", "--offline"]
```
