### ISSUE TITLE
Explicitly declare extra depenendcy conflicts

### ISSUE THREAD

**Issue by martinitus** [astral-sh/uv#10238]
Hey  folks,
I have a followup question  / issue to the "conflicting extras / groups" features that were merged the last weeks (e.g. #8976).

I would like to declare conflicting extras - however these dependencies have no _inherent_ conflict in the package or version. Instead they happen to use the same module namespace  - `databricks-connect` and `pyspark` both use `pyspark` as module names.

So my goal is to have a package, for which the user has to explicitly enable either of the two extras, but cannot enable both.

What I tried so far was

```toml

[project.optional-dependencies]
databums = ["databricks-connect>=16.0.0",]
vanilla = ["pyspark>=3.5.4",]

[tool.uv]
conflicts = [
    [
        {extra = "databums" },
        {extra = "vanilla" },
    ]
]
```

However, when I run `uv lock` or `uv pip install -v -e  .[databums,vanilla]` or even just `uv pip -e .` it happily installs both packages (and screws up the site-package directory afaik).

I presume the current implementation only prevents scenarios where the dependency resolution would have failed due to conflicting optional dependencies. Whereas what I want is explicitly declaring dependencies as conflicting?

Let me know if I missed something and this should actually be possible!

BTW: I also tried it with optional groups, but groups are not exposed to pip (yet, afaik). As I want to be able to install my package with pip on downstream systems, dependency groups seem to not be an option yet.
