### ISSUE TITLE
Bug: Circular dependencies at build-time cause hang without error

### ISSUE THREAD

**Issue by CarrotManMatt** [astral-sh/uv#10255]
When a project uses a package for building that has the original project as a runtime dependency, all build/lock/sync commands hang without any message or error.

# Steps to reproduce

1. Create project `foo` with the following `pyproject.toml`

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "foo"
version = "1.0.0"
description = "My package foo"

[tool.hatch.build]
only-packages = true

[tool.uv]
no-binary-package = ["foo"]
no-build = true
package = true
trusted-publishing = "always"
```

2. Create the package `foo` within the project
```bash
mkdir foo/ && touch foo/__init__.py
```

3. Build the project as a wheel & sdist
```bash
uv build --no-sources --build
```

4. Publish the project to testpypi (package names will need to be changed to avoid collisions)
```bash
uv publish --publish-url https://test.pypi.org/legacy/
```

5. Create a new project bar with the following pyproject.toml
```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["foo"]
name = "bar"
version = "2.0.0"
description = "My package bar (Has a dependency!)"

[tool.hatch.build]
only-packages = true

[tool.uv]
no-binary-package = ["foo"]
no-build = true
package = true
trusted-publishing = "always"
```

6. Create the package `bar` within the project
```bash
mkdir bar/ && touch bar/__init__.py
```

7. Build the project as a wheel only
```bash
uv build --no-sources --build --wheel
```

8. Publish the built wheel to testpypi (package names will need to be changed to avoid collisions)
```bash
uv publish --publish-url https://test.pypi.org/legacy/
```

9. Edit the `pyproject.toml` of the `foo` project
```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "bar"]
```

10. Run the following build command on project `foo`. Compared to step 3 this will now hang indefinetly
```bash
uv build --no-sources --build
```

I think this is a regression as the build of `foo` using `bar` as a build requirement worked successfully in uv version 0.5.11, but in 0.5.13 it fails (I have not verified this however). Is there something I am missing with this kind of circular dependency not being allowed? I would expect the build dependencies to be isolated and just use the existing published wheel, rather than installing the local project (which is what i think is happening)

**Comment by charliermarsh** [comment]
Hmm. Why would this work, though? Even if we install `bar` from a wheel, we still have to install its requirements, which include `foo`. I think this should probably error due to a cycle (but not hang).

**Comment by CarrotManMatt** [comment]
Gotcha, many thanks for helping out. I think I didn't fully appreciate that there was a full dependency cycle during the build stage too, due to my setup possibly being outdated with the `foo` package version.

A more helpful error message rather than just hanging would be appreciated for people running into this issue in the future.

**Comment by charliermarsh** [comment]
So I took the time to publish these as https://test.pypi.org/project/circular-one/ and https://test.pypi.org/project/circular-two/, and this actually works for me?

Specifically, this works `uv build --no-sources --build --index https://test.pypi.org/simple --index-strategy unsafe-best-match --verbose` given:

```toml
[project]
name = "circular-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charlie Marsh", email = "charlie.r.marsh@gmail.com" }
]
requires-python = ">=3.13.0"
dependencies = []

[build-system]
requires = ["hatchling", "circular-two"]
build-backend = "hatchling.build"

[tool.hatch.build]
only-packages = true

[tool.uv]
no-binary-package = ["circular-one"]
no-build = true
package = true
trusted-publishing = "always"
```

My guess is it might fail if I re-publish with:

```toml
[build-system]
requires = ["hatchling", "circular-two"]
build-backend = "hatchling.build"
```
