### ISSUE TITLE
Bug: cannot build local project package even when listed in `no-binary-package`

### ISSUE THREAD

**Issue by CarrotManMatt** [astral-sh/uv#10252]
I have a bit of a peculiar workflow. I like to use wheels for all my dependencies and never let them be built from sdists unless explicitly stated in the `no-binary-package` setting. An example of my `[tool.uv]` settings could look like this:

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "my-cool-project"
version = "0.1.0"
dependencies = ["dependency-a", "dependency-b"]

[tool.uv]
no-binary-package = ["my-cool-project", "dependency-a"]
no-build = true
package = true
```
Where `dependency-a` publishes only sdists, and `dependency-b` publishes sdists and wheels.

To build my project I would then do: `uv build --no-sources --build`, However this hangs during the build process and never completes. (This also makes other commands which rely on building the project like `uv lock` & `uv sync` to also hang.

I believe this is a regression as I recall this functionality working correctly with uv version 0.5.11.

Is there any way to achieve my desired functionality or am I abusing some bug by using the `--build` flag when running `uv build`? Should I just remove the `[tool.uv.no-binary-package]` & `[tool.uv.no-build]` keys and rely on uv's building of sdist dependencies when necessary? I much prefer being explicit over which dependencies I allow to be built from sdists.
