### ISSUE TITLE
some musllinux wheels are missing

### ISSUE THREAD

**Issue by Freed-Wu** [astral-sh/uv#10260]
https://pypi.org/project/uv/#files

There are 3 archs for musllinux

- uv-0.5.13-py3-none-musllinux_1_1_x86_64.whl (15.1 MB view details)
- uv-0.5.13-py3-none-musllinux_1_1_i686.whl (14.6 MB view details)
- uv-0.5.13-py3-none-musllinux_1_1_armv7l.whl (14.2 MB view details) 

However, there are 

uv-0.5.13-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.0 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_s390x.manylinux2014_s390x.whl (20.0 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl (15.2 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_ppc64.manylinux2014_ppc64.whl (15.5 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_i686.manylinux2014_i686.whl (14.9 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.whl (14.2 MB view details)
uv-0.5.13-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_1_aarch64.whl (13.6 MB view details) 

Why some muslinux are missing?

**Comment by charliermarsh** [comment]
We don't ship musl builds for PPC or S390x. There just isn't demand for them, and it takes work to maintain them unfortunately.

(Note that there _is_ a musl build for aarch64 at the bottom of your list.)

**Comment by Freed-Wu** [comment]
> there is a musl build for aarch64

Thanks.

> There just isn't demand for them

I build https://github.com/pypa/cibuildwheel
Now I have to skip some platforms because I want to use uv:

```toml
[tool.cibuildwheel]
build-frontend = "build[uv]"
skip = "*_armv7l *-musllinux_s390x *-musllinux_ppc64*"
```

**Comment by charliermarsh** [comment]
Ok. I would say those platforms aren't particularly common. NumPy and SciPy, for example, don't build for any of them. Pydantic has `_armv7l` but neither of the other two.

**Comment by Freed-Wu** [comment]
> aren't particularly common

I see however If we want to use uv in cibuildwheel, they are required due to cibuildwheel support it by default, except you use `skip = "..."`.

**Comment by Freed-Wu** [comment]
For anyone use uv in cibuildwheel, here is a solution:

```toml
[tool.cibuildwheel]
build-frontend = "build[uv]"

[[tool.cibuildwheel.overrides]]
select = ["*-musllinux_s390x", "*-musllinux_ppc64*"]
build-frontend = "build"
```
