### ISSUE TITLE
[UV ADD] How does it perform in cyclic dependencies??

### ISSUE THREAD

**Issue by dsantiago** [astral-sh/uv#10302]
I will try to put here each step done to make sense when trying to install a package...

```bash

uv init -p 3.11 AAA # Created a new project for test with python 3.11
cd AAA # Moved to project folder

uv add genaibook # 1st try. Tried to add desired package but got ERROR for for bitsandbytes package wheel
uv add bitsandbytes # Tried direct but ofc same error
uv add https://github.com/bitsandbytes-foundation/bitsandbytes.git # So added via git and now it's OK

uv add genaibook # 2nd try. Now appear to have some cyclic dependencies problem (llvmlite)
uv add llvmlite # Ok (adding previously mentioned packages)

uv add genaibook # 3rd try. Still more packages  cyclic problem (numba)
uv add numba # Ok

uv add genaibook # 4th try. Now it runs!!

 uv run python # So now I could run python and import it
```

Also pyproject was like this:

```toml
[project]
name = "aaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bitsandbytes",
    "genaibook>=0.1.1",
    "llvmlite>=0.43.0",
    "numba>=0.60.0",
]

[tool.uv.sources]
bitsandbytes = { git = "https://github.com/bitsandbytes-foundation/bitsandbytes.git" }
```

The question is if all these errors are because this is the **right** way to add dependencies or is there alternative ways to do it with **less** workaround?
