### ISSUE TITLE
PyTorch optional GPU docs not working

### ISSUE THREAD

**Issue by jbohnslav** [astral-sh/uv#10326]
I found the [Configuring accelerators with optional dependencies](https://docs.astral.sh/uv/guides/integration/pytorch/#configuring-accelerators-with-optional-dependencies) section of the PyTorch docs didn't work in my case. 

```toml
[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.10.0"
dependencies = []

[project.optional-dependencies]
cpu = [
  "torch>=2.5.1",
]
cu121 = [
  "torch>=2.5.1",
]

[tool.uv]
conflicts = [
  [
    {extra = "cpu"},
    {extra = "cu121"},
  ],
]

[tool.uv.sources]
torch = [
  {index = "pytorch-cpu", extra = "cpu"},
  {index = "pytorch-cu121", extra = "cu121"},
]

[[tool.uv.index]]
explicit = true
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"

[[tool.uv.index]]
explicit = true
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
```

Executing
```bash
uv sync --extra cpu
```

Gave this error:
```bash
error: Distribution `torch==2.5.1 @ registry+https://download.pytorch.org/whl/cpu` can't be installed because it doesn't have a source distribution or wheel for the current platform
```

I had to explicitly set the version in the optional-dependencies section:
```toml
[project.optional-dependencies]
cpu = [
  "torch==2.5.1+cpu",
]
cu121 = [
  "torch==2.5.1+cu121",
]
```
