### ISSUE TITLE
Allow default index for conflicting groups (torch cpu/cuda)

### ISSUE THREAD

**Issue by sglbl** [astral-sh/uv#10360]
Suggestion, not a bug: Allow default index for conflicting groups (torch cpu/cuda)

```toml
# This template toml file works with pytorch cpu and gpu versions @sglbl
# using 'uv sync --extra cpu' or 'uv sync --extra gpu' command
[project]
name = "digit-classification"
version = "0.1.0"
description = "Digit classification project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio==5.6.0",
    "matplotlib==3.9.2",
    "numpy==2.1.3",
    "opencv-python>=4.10.0.84",
    "transformers>=4.46.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.3.3",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.5.1",
]
gpu = [
  "torch>=2.5.1",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "gpu" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
  { index = "pytorch-gpu", extra = "gpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.pytest.ini_options]
pythonpath = "."
filterwarnings = ["ignore::DeprecationWarning", "ignore::FutureWarning"]
```

Is there a way to set a default extra so that it installs pytorch gpu/cuda version without adding extra flag? 
(something like putting the flag `set-default = true` under one of the `[[tool.uv.index]]`)

**Comment by zanieb** [comment]
Similar to [`default-groups`](https://docs.astral.sh/uv/reference/settings/#default-groups)?

**Comment by sglbl** [comment]
@zanieb Yes. Actually I tried to solve the torch cpu/gpu issue with `dependency-groups`, but it didn't work because of the conflicts. 
So something like default-groups would be really nice

**Comment by zanieb** [comment]
We support conflicting group declarations in the same was as extras.

**Comment by sglbl** [comment]
@zanieb Also, is there a way to set a global default python version (like `asdf` does)?
Because now when I initialize uv, it initializes with my latest python version installed (if I haven't created .python-version file already). It's the same for virtual environment.

I have `Ubuntu 24.04 Gnome/Wayland` with `python3.12` preinstalled. And in every project I use `python3.10`. That's why I'm trying to set a default global python version without needing uninstall my Ubuntu Python.

**Comment by zanieb** [comment]
You can `cd ~ && uv python pin 3.10`

**Comment by HichemAK** [comment]
I still have a problem with `default-groups`. For example, in the following setup:

```toml
[project]
name = "example"
version = "0.1.0"
description = "XXXXX"
readme = "README.md"
authors = [
    { name = "Hichem Ammar Khodja", email = "hichem5696@gmail.com" }
]
requires-python = ">=3.9.7"
dependencies = [
    "torch>=2.0.0",
]

[tool.uv]
default-groups = ["cu118"]

[dependency-groups]
cpu = [
  "torch",
]
cu118 = [
  "torch",
]
cu121 = [
  "torch",
]
cu124 = [
  "torch",
]


[tool.uv.sources]
torch = [
  { index = "torch-cpu", extra = "cpu"},
  { index = "torch-cu118", extra = "cu118"},
  { index = "torch-cu121", extra = "cu121"},
  { index = "torch-cu124", extra = "cu124"},
]

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "torch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[[tool.uv.index]]
name = "torch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
```

uv returns the following error:
```
error: Failed to generate package metadata for `example==0.1.0 @ editable+.`
  Caused by: Source entry for `torch` only applies to extra `cpu`, but the `cpu` extra does not exist. When an extra is present on a source (e.g., `extra = "cpu"`), the relevant package must be included in the `project.optional-dependencies` section for that extra (e.g., `project.optional-dependencies = { "cpu" = ["torch"] }`).
```

However, if I replace `[dependency-groups]` to `[project.optional-dependencies]` (as the error suggests) to include all `extra`s in optional dependencies, uv tells me that default groups must be mentioned in the dependency table group :
```
error: Default group `cu118` (from `tool.uv.default-groups`) is not defined in the project's `dependency-group` table
```

Am I missing something ?
