### ISSUE TITLE
`index` in uv.toml in parent directory not recognized

### ISSUE THREAD

**Issue by NicholasPini** [astral-sh/uv#10436]
I have a bunch of separated python projects. Since they all have the same private index in their pyproject.toml, I figured it is better to move the index definition to a uv.toml file in a parent directory:

```toml
# uv.toml

required-version = ">=0.5.16"

[[index]]
name = "my_index"
url = "..."
explicit = true
```

```toml
# pyproject.toml

# other stuff...

[tool.uv.sources]
my_private_dependency = { index = "my_index" }

```

The problem is that this is not recognized by uv, it says that
```
Failed to parse entry: `my_private_dependency`
  ╰─▶ Package `my_private_dependency` references an undeclared index: `my_index`
```

Note that putting the exact same index definition inside the pyproject.toml works, so the definition itself is correct.

Maybe indices are not supposed to go into a common uv.toml file, but I don't get any error about `index` not being permitted in uv.toml (like I would with, for example, the `source` settings). 

Also, the uv.toml file itsefil is read: again, if I for example put a `source` definition, I get an error saying that it is not permitted, thus uv is reading the uv.toml file as expected.

EDIT: Ok, after a bit more testing, the uv.toml is completely ignored. It does give an error if I add the `source` section, but otherwise it is not read at all. For example, setting `required-version = ">=0.5.17"` doesn't make uv fail the command (I'm using version 0.5.16). So basically the uv.toml is parent directories is completely ignored if a pyproject.toml file is present, but for some reason it complained about `source` being present.

EDIT2: I think I get what is happening. If there is a single `[tool.uv]` in the pyproject.toml file, the uv.toml file in parent directories is ignored. The problem is that I found no way to define `source` without using `[tool.uv.sources]`, and I'm forced to have that in the pyproject.toml file, so I think uv prevents me from using a global uv.toml as I intended.
