### ISSUE TITLE
Using UV with Nexus repository and ignored environment variables for authentication

### ISSUE THREAD

**Issue by MYCL94** [astral-sh/uv#10468]
**Issue description:**

I'm experiencing issues authenticating with my Nexus repository when using `uv pip`. The repository is configured in my `pyproject.toml` file as follows:

```toml
[[tool.uv.index]]
name = 'nexus-repository'
url = 'https://my-repo.com/packages/'
explicit = true

[tool.uv.sources]
my_package = { index = 'nexus-repository' }
```

I've set environment variables `UV_INDEX_NEXUS_REPOSITORY_USERNAME` and `UV_INDEX_NEXUS_REPOSITORY_PASSWORD` to provide the necessary credentials. However, when running `uv pip install -r pyproject.toml`, I receive a 401 Unauthorized error due to a lack of valid authentication credentials. (will be necessary in our CI)

I tried this on windows powershell with `set UV_INDEX_NEXUS_REPOSITORY_USERNAME=user` ,`set UV_INDEX_NEXUS_REPOSITORY_PASSWORD=pw`and running `uv pip install -r pyproject.toml` after that

But when I provide an .env file the authentication seems to work since the error changes.
Running `uv run --env-file uv.env --verbose` results in the following output

**Verbose output:**

```
error: Received some unexpected HTML from https://my-repo.com/packages/my_package/
Caused by: Unexpected fragment (expected `#sha256=...` or similar) on URL: browse/browse:python
```

**Environment:**

*   `uv` version: 0.5.16

**Additional information:**

The path to the `.whl` file is as follows:

```
https://my-repo.com/packages/my_package/<version>/my_package-<version>-py3-none-any.whl
```
