### ISSUE TITLE
Support (editable) sources when exporting requirements.txt when building a Docker image

### ISSUE THREAD

**Issue by tibbe** [astral-sh/uv#10663]
We have a monorepo with multiple libraries, some which depend on each other, and multiple executables, which depend on (some of) the libraries. We're trying to build a Docker image for AWS Lambda for each of the executables.

Since not all executables have compatible dependencies we cannot use a workspace as per our testing and as per https://docs.astral.sh/uv/concepts/projects/workspaces/#when-not-to-use-workspaces.

What we do instead is to use (editable) dependencies like so:

```toml
# executable-a/pyproject.toml
[project]
name = "executable-a"
dependencies = [
  "lib-a"
]

[tool.uv.sources]
lib-a = { path = "../lib-a", editable = true }
```

```toml
# lib-a/pyproject.toml
[project]
name = "lib-a"
dependencies = [
  "lib-b"
]

[tool.uv.sources]
lib-b = { path = "../lib-b", editable = true }
```

The folder structure looks something like:

```
.
├── Dockerfile.a
├── Dockerfile.b
├── executable-a
├── executable-b
├── lib-a
└── lib-b
```

The reason we use editable dependencies is that we frequently need to change code in both libraries and executables at the same time and having to `uv sync` between each code change hurts the development flow.

What I _think_ we want to do in our Docker image is something similar to https://github.com/astral-sh/uv/blob/73cade13862c88bf2d5344759e9b1b7035b63743/docs/guides/integration/aws-lambda.md, namely first installing 3rd party dependencies followed by the libraries and the executable.

Issues:
- We need an equivalent of `uv export --no-emit-workspace` for (editable) sources such that we can create a Docker layer of the 3rd party dependencies, including the 3rd party dependencies of the libraries. `--no-sources` doesn't seem to be quite it as we still do want the 3rd party dependencies of the sources.
- We want the result to have no editable dependencies, which seems to happen even if you use `uv export --no-editable`, as long as `editable = true` is defined in `pyproject.toml`.
