### ISSUE TITLE
In a workspace, `uv sync` does not respect some environment variables for workspace members

### ISSUE THREAD

**Issue by wsascha** [astral-sh/uv#10680]
It seems that the `UV_INDEX_*_USERNAME` and `UV_INDEX_*_PASSWORD` env vars are not considered for / propagated to workspace members when calling `uv sync`.

An MWE could look like the following (given that you have an index at hand that requires auth):

### Workspace `pyproject.toml`

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["bar"]

[tool.uv.sources]
bar = { workspace = true }

[tool.uv.workspace]
members = ["packages/bar"]
```

### Member `packages/bar/pyproject.toml`

```toml
[project]
name = "bar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["baz"]

[tool.uv.sources]
baz = { index = "my-index" }

[[tool.uv.index]]
name = "my-index"
# url = "https://<USERNAME>:<PASSWORD>@example.com/simple"
url = "https://example.com/simple"
explicit = true
```

If I explicitly provide `<USERNAME>` and `<PASSWORD>` in the URL (commented out line) the "baz" project can be retrieved.

If I set the URL as is and provide the env vars as in

```sh
UV_INDEX_MY_INDEX_USERNAME=<USERNAME> UV_INDEX_MY_INDEX_PASSWORD=<PASSWORD> uv sync
```

the "baz" project download fails with `401 Unauthorized`.

### Workaround

If I explicitly set the index in the workspace `pyproject.toml`, adding

```toml
[[tool.uv.index]]
name = "my-index"
url = "https://example.com/simple"
explicit = true
```

the project can be retrieved.

### Conclusion

I think this is undesired behavior, thus opening this issue.

Thanks for your great work, I really love `uv`.
