### ISSUE TITLE
how to fallback source if workspace is not available

### ISSUE THREAD

**Issue by KevinNitroG** [astral-sh/uv#10731]
Currently I have a monorepo project. But each subrepos inside (git submodules) aren't published to Pypi.

this is the structure

```
 packages
├──  cli   <---- cpn-cli
├──  core  <---- cpn-core
└──  docs  <---- cpn-docs
```

the cli require the core one, and I have set the source of the core in side the cli:

```toml
...
[tool.uv.sources]
cpn-core = { git = "https://github.com/check-phat-nguoi/cpn-core/" }
...
```

Also with the docs, require cli and core

The large repo has the pyproject.toml:

```toml
[project]
dependencies = []

[tool.uv.sources]
cpn-core = { workspace = true }
cpn-cli = { workspace = true }
cpn-docs = { workspace = true }

[tool.uv.workspace]
members = ["packages/cli", "packages/core", "packages/docs"]
```

---

The problem is with the core, cli, docs repo on github themselves, cannot resolve the source of their deps. For ex the `cli` doesn't know where the source of the `core` is, without defining the source in cli's pyproject. But, if it the source is defined, then it will override the large's repo source, which make no sense.
