### ISSUE TITLE
Spurious warning with `--no-project --only-group <group>`?

### ISSUE THREAD

**Issue by woodruffw** [astral-sh/uv#10743]
Hello! As always, thanks for all the amazing work you've done on `uv` and `ruff`.

I tried searching for an open issue for this, and couldn't find one. Please close with prejudice if there is one that I've missed!

## Problem

This isn't a breaking problem per se, since it appears to work. However, it produces a spurious warning that I suspect is a holdover from an earlier restriction 🙂 

I have a `pyproject.toml` that looks like this:

```toml
[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "bin"

[dependency-groups]
docs = ["mkdocs ~= 1.6", "mkdocs-material[imaging] ~= 9.5"]
```

Notably, the `pyproject.toml` has no `[project]` section (since it's a Maturin-based pure-Rust project that pulls all metadata from `Cargo.toml`). My goal is to ideally keep it that way, to reduce duplication between the two files.

With that configuration, I'm using `uv run --no-project --only-group docs mkdocs build` to build my (`mkdocs`-based) documentation.

## Expected behavior

I expect `uv run --no-project --only-group docs mkdocs build` to produce no warnings, and run `mkdocs` correctly.

## Actual behavior

The command warnings that `--only-group docs` and `--no-project` have no effect alongside each other, but then runs successfully:

```bash
$ uv run --no-project --only-group docs mkdocs build
warning: `--only-group docs` has no effect when used alongside `--no-project`
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /<blah>/zizmor/site_html
INFO    -  Documentation built in 0.84 seconds
```

## Workarounds

I can add a dummy `[project]` section containing just a `name` key, which hushes the warning. However I think the warning is still spurious, since (IIUC) the semantics of PEP 735 dep groups are not dependent on project metadata at all.
