### ISSUE TITLE
uv export doesn't seem to respect --no-dev

### ISSUE THREAD

**Issue by dodumosu** [astral-sh/uv#10755]
thanks for all the hard work on this. i have a project using this, and i added ipython to my dev dependencies to make shell work with async a bit more easy. i have a pre-commit hook with uv export set up, and i noticed that ipython was included in the exported requirements.txt. here's the set up for uv in my pre-commit configuration:

```yaml
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.8
    hooks:
    -   id: uv-lock
    -   id: uv-export
        args: ["--no-dev"]
```

**Comment by znicholls** [comment]
(Chiming in out of nowhere, I thought I had a related issue but I think it's different because I could not reproduce this with the MRE below)

uv version: uv 0.5.11 (c4d0caaee 2024-12-19)
operating system: MacOS M2 chip

<details><summary>`pyproject.toml`</summary>
<p>

```toml
# pyproject.toml
[project]
name = "mwe"
version = "0.1.0"
description = "Minimal working example to demonstrate resolving issue"
authors = [
    { name = "Zebedee Nicholls", email = "zebedee.nicholls@climate-energy-college.org" },
]
requires-python = ">=3.9"
dependencies = [ ]

[dependency-groups]
docs = [
    "ipython>=8.18.1",
]
```

</p>
</details> 

<details><summary>Command output</summary>
<p>

This seems fine?

```sh
$ uv export --no-dev
Using CPython 3.13.1 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Resolved 20 packages in 0.62ms
# This file was autogenerated by uv via the following command:
#    uv export --no-dev
```

</p>
</details>
