### ISSUE TITLE
Bug? Can't run uv sync on package with --no-build

### ISSUE THREAD

**Issue by Chasarr** [astral-sh/uv#10778]
When trying to create a new package with say `uv init --package`, add a dependency, say the progress package, with `uv add progress`. My pyprojects.toml looks like this:
```toml
[project]
name = "hatch-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "My Name", email = "my@e.mail" }
]
requires-python = ">=3.12"
dependencies = [
    "progress>=1.6",
]

[project.scripts]
hatch-demo = "hatch_demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

```

Company policy is to ensure that we don't use source distributions (only prebuilt binary wheel dependencies) which we used to do with `pip install -r requirements.txt --no-compile`. We are now trying to switch over to uv, but `uv sync --no-build` returns
`error: Distribution `hatch-demo==0.1.0 @ editable+.` can't be installed because it is marked as `--no-build` but has no binary distribution`

Although I can see why this returns an error, the purpose of --no-build for us should be to not build dependencies when building our package, not to inhibit us from building the package itself. We could technically do `uv sync --no-build-package pkg1 --no-build-package pkg2 ... --no-build-package pkgN` for all dependencies, but that doesn't seem like a very elegant solution.

Not sure if a fix for this problem aligns with the goals of uv.

TLDR: I want to 1) uv sync dependencies with --no-build and then 2) build the package with said dependencies.
