### ISSUE TITLE
[tool.uv.sources] uv is trying to normalize the path, even when the system platform differs from the marker

### ISSUE THREAD

**Issue by campanya** [astral-sh/uv#10777]
My dev platform is Windows; trying to deploy to a linux docker image.

I have this in my pyproject.toml:

```toml
[tool.uv.sources]
python-ldap = { path = "/uti/Python/python_ldap-3.4.4-cp312-cp312-win_amd64.whl", marker = "sys_platform  == 'win32'" }
```

This causes an error with Docker (even though the Docker image is Linux):

```bash
> [stage-0 6/6] RUN uv sync --frozen:
0.264 Using CPython 3.12.5 interpreter at: /usr/bin/python3.12
0.264 Creating virtual environment at: .venv
0.278 error: Failed to parse `uv.lock`
0.278   Caused by: TOML parse error at line 228, column 5
0.278     |
0.278 228 |     { name = "python-ldap", marker = "sys_platform == 'win32'", path = "../../uti/Python/python_ldap-3.4.4-cp312-cp312-win_amd64.whl" },
0.278     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.278 path could not be normalized: /app/../../uti/Python/python_ldap-3.4.4-cp312-cp312-win_amd64.whl
```

I'm not sure if this is a bug. Maybe uv could ignore the source when the marker indicates it's a dependency for another platform and avoid trying to normalize the path.

**Comment by charliermarsh** [comment]
I'm not sure what to do here. We definitely shouldn't ignore this due to the markers. But arguably it should be a non-fatal failure.

**Comment by charliermarsh** [comment]
Can you please share the complete `uv.lock`? I can't reproduce it.

**Comment by campanya** [comment]
The problem seems to be in the normalization of the path.  You can modify the Dockerfile to make it work:

**Dockerfile**
```dockerfile
FROM ghcr.io/astral-sh/uv:python3.12-bookworm

RUN apt-get update && apt-get install -y libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

# **we'll get an error:** path could not be normalized: /app/../../../uti/Python/python_ldap-3.4.4-cp312-cp312-win_amd64.whl
# WORKDIR /app
# COPY . /app

# this works
WORKDIR /app/projects/uv_test
COPY . /app/projects/uv_test

RUN  uv sync --frozen --no-editable

ENV PATH="/app/.venv/bin:$PATH"
```

**pyproject.toml**
```toml
[project]
name = "uv_test"
version = "1.0"

dependencies = ["python-ldap"]

[tool.uv.sources]
python-ldap = { path = "/uti/Python/python_ldap-3.4.4-cp312-cp312-win_amd64.whl", marker = "sys_platform  == 'win32'" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

```
