### ISSUE TITLE
Q: Using private repositories as dependencies

### ISSUE THREAD

**Issue by c90x** [astral-sh/uv#10810]
I have a question, how would I be able to use private repositories as dependencies in this way:
```toml
# pyproject.toml
[project]
dependencies = ["private_repo"]

[tool.uv.sources]
private_repo = { git = "https://github.com/company/private_repo" }
```
On my machine I can do `git clone https://github.com/company/private_repo` without any issues but when doing `uv sync` it fails. I can't seem to find any direct solutions in the docs
