### ISSUE TITLE
Unable to install pytorch audio with very simple pyproject.toml

### ISSUE THREAD

**Issue by zackees** [astral-sh/uv#10825]
### Summary

I can execute `uv pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121`

But the following fails:

```[build-system]
requires = ["setuptools", "wheel"]     
build-backend = "setuptools.build_meta"

[project]
name = "project"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
  "torchaudio==2.2.0+cu121",
  "torch==2.1.2+cu121",
]

[tool.uv.sources]
torch = [
  { index = 'pytorch-cu121'},
]
torchaudio = [
  { index = "pytorch-cu121" },
]
[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
```

Other configurations where dependencies:
```
dependencies = [
  "torchaudio==2.2.0",
  "torch==2.1.2",
]
```

Also don't work.

What would be the right pyproject.toml that would do the command above?

### Platform

Windows 10

### Version

uv 0.5.13 (c456bae5e 2024-12-27

### Python version

Python 3.11.5

## Output:

```
$ uv run pwd
warning: `VIRTUAL_ENV=C:\Users\niteris\dev\iso-env/.venv` does not match the project environment path `.venv` and will be ignored
  × No solution found when resolving dependencies:
  ╰─▶ Because torchaudio==2.2.0+cu121 depends on torch==2.2.0 and your project depends on torch==2.1.2+cu121, we can
      conclude that your project and torchaudio==2.2.0+cu121 are incompatible.
      And because your project depends on torchaudio==2.2.0+cu121, we can conclude that your project's requirements are      
      unsatisfiable.
```

**Comment by charliermarsh** [comment]
What's wrong with:

```toml
requires = ["setuptools", "wheel"]     
build-backend = "setuptools.build_meta"

[project]
name = "project"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
  "torchaudio",
  "torch",
]

[tool.uv.sources]
torch = [
  { index = 'pytorch-cu121'},
]
torchaudio = [
  { index = "pytorch-cu121" },
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
```

**Comment by charliermarsh** [comment]
(It looks like torchaudio 2.2.0 is not compatible with torch 2.1.2, but you're pinning to those specific versions.)

**Comment by zackees** [comment]
Let me try

**Comment by zackees** [comment]
Okay that seems to work and now it's downloading. I'll try pinning the dep to the correct one.

**Comment by charliermarsh** [comment]
I think they just need to be in sync? Like:

```toml
dependencies = [
  "torchaudio==2.2.0",
  "torch==2.2.0",
]
```
