### ISSUE TITLE
Sub-dependencies from private index cannot be resolved when explicit is true

### ISSUE THREAD

**Issue by olafdeleeuw** [astral-sh/uv#10850]
### Summary

I want to add a dependency, let's say `my-private-package` which is published in Azure Artifacts. 
The package `my-private-package` has a dependency itself which is also published in Azure Artifacts: `my-private-sub-package`.

I have the following setup in my `pyproject.toml`:

```toml
[tool.uv.sources]
my-private-package = { index = "my-private-index" }

[[tool.uv.index]]
name = "dna-nl-library"
url = "https://<subscription>.pkgs.visualstudio.com/<project>/_packaging/my-private-index/pypi/simple/"
explicit = true
```

If I run `uv add my-private-package` I get the following error:

  × No solution found when resolving dependencies for split (python_full_version == '3.11.*'):
  ╰─▶ Because my-private-sub-package was not found in the package registry and my-private-package depends on my-private-sub-package, we can conclude that my-private-package cannot be used.

Apparently, `explicit=true` says only `my-private-package` must be searched in "my-private-index". `uv` doesn't apply this index on the dependencies of `my-private-package`.

I tried adding `my-private-sub-package` to the `[tool.uv.source]` section, but this doesn't help.

The only two solutions are:

- set `explicit=False`
- add `my-private-sub-package` manually as a dependency 

It would be nice if the setting `explicit=true` holds also for the dependencies of the sources listed under `[tool.uv.source]`.
