### ISSUE TITLE
Platform-dependent dependency bug (`sling-mac-arm64`)

### ISSUE THREAD

**Issue by smackesey** [astral-sh/uv#10945]
### Summary

On macOS w/ Apple Silicon, installing `sling` should also install `sling-mac-arm64`. However, I find that an install of `sling` in a fresh virtual environment using `--no-cache` will instead install `sling-linux-amd64`. If I do not disable the cache, then sometimes I correctly get `sling-mac-arm64`

### Platform

macOS 15 arm64

### Version

uv 0.5.22 (Homebrew 2025-01-21)

### Python version

3.11.9

**Comment by charliermarsh** [comment]
It looks like the package ships with incorrect metadata inside it. I'll see if we can avoid respecting it.

**Comment by smackesey** [comment]
Interesting-- FWIW I do not encounter the same behavior when I use `pip`.

**Comment by charliermarsh** [comment]
Right, pip doesn't read this metadata.

**Comment by charliermarsh** [comment]
If helpful, you should be able to add this to your configuration file in the interim:

```toml
[[tool.uv.dependency-metadata]]
name = "sling"
version = "1.4.0"
requires-dist = [
    "sling-linux-arm64==1.4.0 ; sys_platform == 'linux' and platform_machine == 'aarch64'",
    "sling-linux-amd64==1.4.0 ; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sling-windows-amd64==1.4.0 ; sys_platform == 'win32' and platform_machine == 'x86_64'",
    "sling-mac-arm64==1.4.0 ; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "sling-mac-amd64==1.4.0 ; sys_platform == 'darwin' and platform_machine == 'x86_64'",
]
```
