### ISSUE TITLE
Automatically install and use an older uv version to satisfy `requires-version`.

### ISSUE THREAD

**Issue by mjpieters** [astral-sh/uv#11065]
### Summary

We have some projects running with an older, pinned `uv` version in docker containers, but the lock file is updated by developers with the most recent `uv` version installed. This can lead to problems:

- 0.5.19 added support for omitting dynamic package versions from the lock file. We have some projects with such dynamic versions, but locking with 0.5.19 or newer makes the lock file unreadable by older uv versions.
- If a 0.6.x version was released with explicit backward compatibility conflicts, we'd be further up the creek without a paddle.

We can set `required-version` to prevent using newer uv versions:

```toml
[tool.uv]
required-version = ">=0.5.0,<0.5.19"
```

but then anyone with a newer `uv` can't update the  lockfile. **UNLESS** they use `uv tool run` to install the older `uv` version to do the work:

```sh
% uv lock
error: Required uv version `>=0.5.0, <0.5.19` does not match the running version `0.5.25`
% uv tool run --with 'uv>=0.5.0,<0.5.19' uv lock
Resolved 149 packages in 994ms
```

Could `uv` do this _directly_ please? Specifically, when the `required-version` requirement can't be met by the current `uv` version, `uv` finds a version of itself that _does_ match the requirement and run the desired command with that version instead.

### Example

When running `uv` with a version that doesn't satisfy the `required-version` requirements for the current project, instead of exiting with an error, `uv` finds a version of itself that does satisfy the requirements:

```sh
% cd "$(mktemp -d)"
% uv init
Initialized project `tmp-luczgh2pmf`
% cat >>pyproject.toml <<EOF
heredoc> [tool.uv]
heredoc> required-version=">=0.5.0,<0.5.19"
heredoc> EOF
% uv sync   # executes as `uv tool run --with 'uv>=0.5.0,<0.5.19' uv sync`
Resolved 1 package in 7ms
Audited in 0.02ms
```

**Comment by mjpieters** [comment]
Our current work-around is to alias `uv`:

```sh
alias uv='uv tool run --with "uv$(yq -r '.tool.uv.required-version // ""' pyproject.toml)" uv'
```

(which requires that you have [`yq` installed](https://mikefarah.gitbook.io/yq#install)).

**Comment by juftin** [comment]
Adding an example from my duplicate issue:

### Example

You have `uv==0.4.0` on your local machine and the following `pyproject.toml`:
```toml
[project]
name = "example"
version = "1.2.3"
description = "Example Project Description"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "apache-airflow==2.8.0"
]

[tool.uv]
required-version = ">=0.6.0,<0.7.0"
```

Rather than raising an error that your `uv` version doesn't comply with the `required-version` when running `uv lock`, `uv` would instead essentially run `uvx "uv>=0.5.0,<0.6.0" lock`
