### ISSUE TITLE
Add pytorch documentation section on how to install for Intel GPUs

### ISSUE THREAD

**Issue by natemcintosh** [astral-sh/uv#11079]
### Summary

Pytorch 2.6 [adds support for Intel GPUs](https://pytorch.org/docs/main/notes/get_start_xpu.html). The current [uv pytorch install docs](https://docs.astral.sh/uv/guides/integration/pytorch/#using-a-pytorch-index) include instructions for:
- CPU only
- Various CUDA versions
- ROCm

But not yet for Intel GPUs.

My current attempt at mimicking the docs for existing GPUs is
```pyproject.toml
# pyproject.toml
[project]
name = "pytorch-intel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.6.0"]

[[tool.uv.index]]
name = "pytorch-intel-gpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-intel-gpu", marker = "platform_system == 'Linux'" }]

```

```python
# hello.py
import torch


print(torch.xpu.is_available())
```
Running `uv run hello.py` produces
```sh
  × No solution found when resolving dependencies for split (sys_platform
  │ == 'linux'):
  ╰─▶ Because there is no version of pytorch-triton-xpu{platform_machine
      == 'x86_64' and sys_platform == 'linux'}==3.2.0 and torch==2.6.0+xpu
      depends on pytorch-triton-xpu{platform_machine == 'x86_64'
      and sys_platform == 'linux'}==3.2.0, we can conclude that
      torch==2.6.0+xpu cannot be used.
      And because only the following versions of torch{sys_platform ==
      'linux'} are available:
          torch{sys_platform == 'linux'}<2.6.0
          torch{sys_platform == 'linux'}==2.6.0+xpu
      and your project depends on torch{sys_platform == 'linux'}>=2.6.0, we
      can conclude that your project's requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
I think this works:

```toml
# pyproject.toml
[project]
name = "pytorch-intel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.6.0", "pytorch-triton-xpu"]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch", marker = "sys_platform == 'linux'" }]
pytorch-triton-xpu = [{ index = "pytorch" }]
```

Can you give it a try?
