### ISSUE TITLE
Question about best practices for cross-compat with `pip install -e .[dev]` (pre PEP 735 support)

### ISSUE THREAD

**Issue by tlambert03** [astral-sh/uv#11093]
### Question

I ❤️ uv and want to be able to just run `uv sync` in all of my projects and bring along all of the dev dependencies (let's assume no `uv.lock` exists yet).  However, in some cases, I also need to work with others who don't use uv and want to be able to run the classic `pip install -e .[dev]`... and if I'm not mistaken, pip does not yet support PEP 735? (https://github.com/pypa/pip/issues/12963)

My question is how best to accomplish this.  I know I can just use `uv sync --extra dev` (but would like to just use `uv sync`).

Would this be the best way to accomplish this until pip supports dependency groups?

```toml
[project.optional-dependencies]
dev = ["pytest", "ruff"]   # dev deps still go in the dev extra for now

[dependency-groups]
dev = ["my-package[dev]"]  # reference dev extra in dependency-groups.dev

[tool.uv.sources]
my-package = { workspace = true }   # declare local source
```

other tips?
