### ISSUE TITLE
Error installing package using * asterisk in data path on windows

### ISSUE THREAD

**Issue by javier-garcia-tilburg** [astral-sh/uv#11099]
### Summary

Installing a package with `*` in their data paths raises an error on windows.

## Reproduction

Create a new project with

```toml
# pyproject.toml
[project]
name = "dummy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "quadax==0.2.5",
]
```

Run `uv sync` on a powershell terminal and it fails with

```
Resolved 51 packages in 1ms
  × Failed to download `quadax==0.2.5`
  ├─▶ Failed to extract archive
  ╰─▶ failed to create directory `C:\Users\user\AppData\Local\uv\cache\.tmpK76oK4\quadax-0.2.5.data/data/*`: The filename, directory name, or volume label syntax is incorrect. (os error 123)
  help: `quadax` (v0.2.5) was included because `dummy` (v0.1.0) depends on `quadax`
```

## Details

Inspecting the file `quadax-0.2.5-py3-none.whl` reveals that it contains data fails
```
quadax-0.2.5.data/data/_/requirements.txt
quadax-0.2.5.data/data/_/requirements-dev.txt
```
while `quadax-0.2.5.dist-info/RECORD` refers to them in the following manner
```
quadax-0.2.5.data/data/*/requirements-dev.txt,sha256=f5QMec-IahYECs4OvocQWWqO2IXiwWKKNbsD7V6yoTk,556
quadax-0.2.5.data/data/*/requirements.txt,sha256=l4H4ACI11gQsGwguQ2h45GLLxTODDgyu4YbHP9_KUcE,79
```

Taking a look at the repository [f0uriest/quadax](https://github.com/f0uriest/quadax) we can see that it was generated using this `setup.cfg` configuration
```
[options.data_files]
* =
  *.txt
```

### Platform

Windows 10 x64

### Version

uv 0.5.25 (9c07c3fc5 2025-01-28)

### Python version

Python 3.12.8
