### ISSUE TITLE
No solution found when resolving dependencies for split (platform_python_implementation == 'PyPy')

### ISSUE THREAD

**Issue by kdebrab** [astral-sh/uv#11151]
### Summary

Following resolution failure *looks* like a bug to me:

Running `uv lock` with following pyproject.toml:
```toml
[project]
name = "pythonproject"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = ["urllib3==2.3.0"]
optional-dependencies.test = [
"vcrpy==7.0.0 ; platform_python_implementation != 'PyPy'",
]
```
yields:
```
  x No solution found when resolving dependencies for split (platform_python_implementation == 'PyPy'):
  `-> Because only the following versions of urllib3{platform_python_implementation == 'PyPy'} are available:
          urllib3{platform_python_implementation == 'PyPy'}==0.3
          urllib3{platform_python_implementation == 'PyPy'}==1.0
          urllib3{platform_python_implementation == 'PyPy'}==1.0.1
          [...]
          urllib3{platform_python_implementation == 'PyPy'}==1.26.20
          urllib3{platform_python_implementation == 'PyPy'}>2
      and urllib3{platform_python_implementation == 'PyPy'}>=1.25,<=1.25.1 was yanked (reason: Broken release), we can conclude that urllib3{platform_python_implementation ==      
      'PyPy'}>=1.25,<=1.25.1 depends on urllib3<=1.24.3.
      And because vcrpy==7.0.0 depends on urllib3{platform_python_implementation == 'PyPy'}<2 and pythonproject[test] depends on vcrpy{platform_python_implementation !=
      'PyPy'}==7.0.0, we can conclude that pythonproject[test] depends on one of:
          urllib3<=1.24.3
          urllib3>=1.25.2,<=1.26.20

      And because your project depends on urllib3==2.3.0 and your project requires pythonproject[test], we can conclude that your project's requirements are unsatisfiable.
```
Note that especially `And because vcrpy==7.0.0 depends on urllib3{platform_python_implementation == 'PyPy'}<2 and pythonproject[test] depends on vcrpy{platform_python_implementation != 'PyPy'}==7.0.0` seems a conflicting statement.

### Platform

Windows

### Version

uv 0.5.26 (5ef3d5139 2025-01-30)

### Python version

Python 3.12.8

**Comment by charliermarsh** [comment]
Try adding:

```toml
[tool.uv]
environments = ["platform_python_implementation != 'PyPy'"]
```

**Comment by kdebrab** [comment]
Thanks, that works for me!

However, I have the feeling that this is merely a work-around. E.g., it wouldn't be a solution if one would really want to target PyPy for the application (excluding `vcrpy`).

I would expect that if a marker excludes a certain dependency for a certain implementation, that that would be propagated to its dependencies. In particular, `vcrpy{platform_python_implementation != 'PyPy'}==7.0.0` should never depend on `urllib3{platform_python_implementation == 'PyPy'}<2`

**Comment by charliermarsh** [comment]
Yes it's a limitation in the resolver. If you had two dependencies, like:

```toml
[project]
name = "pythonproject"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = ["urllib3==2.3.0"]
optional-dependencies.test = [
    "vcrpy==7.0.0 ; platform_python_implementation != 'PyPy'",
    "vcrpy==6.0.0 ; platform_python_implementation == 'PyPy'",
]
```

Then we would correctly "fork" the resolution and solve for both marker values. But if there's only one value, we attempt to solve without "forking", since it's much more expensive to "fork" for every marker value that we see at any time during resolution. We've considered doing that kind of "aggressive" forking by default, but have deferred it.
