### ISSUE TITLE
Adding a dependency without its own dependencies `--no-deps` like no deps in pip

### ISSUE THREAD

**Issue by harisarang** [astral-sh/uv#11215]
### Question

I would like add a package named `scann` where `tensorflow` is a dependency. But I would like to add `scann` with `tensorflow`
```bash
uv pip install scann --no-deps
```
This command doesn't install `tensorflow`
But is there way I could run the similar with `uv add` with tensorflow ?

### Platform

Ubuntu 22.04 (amd)

### Version

v0.5.27

**Comment by zanieb** [comment]
I'm not sure the semantics of this make sense with `uv add`. If the package says it depends on `tensorflow`, we respect that.

The best you can do now is override the metadata for `scann` to say it has no dependencies

https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata

**Comment by lagamura** [comment]
@zanieb Trying the workaround with `dependency-metadata` the `requires-python` field does not precedes as would be expected(?):
minimal example:
```toml
[project]
name = "dep-meta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["rioxarray>=0.22"]

[tool.uv]
dependency-metadata = [
  { name = "rioxarray", requires-dist = [""], requires-python = ">=3.11"}
]
```

shell:
```txt
uv lock
warning: Failed to parse `pyproject.toml` during settings discovery:
  TOML parse error at line 11, column 42
     |
  11 |   { name = "rioxarray", requires-dist = [""], requires-python = ">=3.11"}
     |                                          ^^
  Empty field is not allowed for PEP508

  ^

Using CPython 3.11.13
  × No solution found when resolving dependencies for split (markers: python_full_version == '3.11.*'):
  ╰─▶ Because the requested Python version (>=3.11) does not satisfy Python>=3.12 and rioxarray==0.22.0 depends on Python>=3.12, we can conclude that rioxarray==0.22.0 cannot be used.
      And because only rioxarray<=0.22.0 is available and your project depends on rioxarray>=0.22, we can conclude that your project's requirements are unsatisfiable.

      hint: The `requires-python` value (>=3.11) includes Python versions that are not supported by your dependencies (e.g., rioxarray==0.22.0 only supports >=3.12). Consider using a more restrictive `requires-python` value (like >=3.12). 
```
