### ISSUE TITLE
uv sync ignores user config file

### ISSUE THREAD

**Issue by mneumei** [astral-sh/uv#11235]
### Summary

I have a uv.toml at "%APPDATA%\uv\uv.toml" with the content:

[[index]]
url = "https:/<my_index>/simple"
default = true

python-downloads = "never"

When i run uv sync, it will still try to download python.

How can i verify where it will actually read the config from, and which values were taken? Is there any similar function like pip config list?

### Platform

win11 x86_64

### Version

uv 0.5.25 (9c07c3fc5 2025-01-28)

### Python version

Python 3.11.4

**Comment by charliermarsh** [comment]
Unfortunately not in `uv.toml`, it's just top-level vs. nested :(

In `pyproject.toml` it's a bit clearer, since you have:

```toml
[tool.uv]
python-downloads = "never"

[[tool.uv.index]]
url = "https://google.com"
default = true
```

But that isn't applicable to user- or system-level settings like that.
