### ISSUE TITLE
Should my team's project structure work as a uv workspace?

### ISSUE THREAD

**Issue by omer54463** [astral-sh/uv#11344]
### Question

My team uses a certain project structure:

1. The code is divided into python packages (each with its own pyproject.toml) inside a source directory.
2. The (pytest) tests are their own module, just like pytest likes it.

Currently, we have a PowerShell installation script that installs all those packages in editable mode, and that's the way we work.

```yaml
- source:
  - package_1:
    - pyproject.toml
    - package_1:
      - __init__.py
      - py.typed
      - ...
  - package_2:
    - pyproject.toml
    - package_2:
      - __init__.py
      - py.typed
      - ...
- test:
  - __init__.py
  - conftest.py
  - unit:
    - __init__.py
    - test_something.py
    - ...
```
I created an [example](https://github.com/omer54463/example) of the same structure, and added my [attempt](https://github.com/omer54463/example/tree/refactor/uv) at converting it into a uv workspace.

I encountered two problems:

1. I can't install development dependencies. `uv pip install .[dev]` fails with "Failed to parse metadata from built wheel".
2. I am not sure if there's an automatic way I can tell uv to install all my workspace packages.

Any help would be much appreciated. uv is awesome and incredibly fast, and I would love to use it!

### Platform

Windows 11 x86_64

### Version

uv 0.5.29 (ca73c4754 2025-02-05)
