### ISSUE TITLE
`requires-python` in workspace

### ISSUE THREAD

**Issue by T-256** [astral-sh/uv#11424]
### Question

ref https://github.com/astral-sh/uv/issues/10204

```toml
# pyproject.toml
[dependency-groups]
dev = []

[tool.uv.workspace]

```

On every command I see this warning:
```sh
>uv add --dev requests
Using CPython 3.7.9 interpreter at: C:\p\python.exe
Removed virtual environment at: .venv
Creating virtual environment at: .venv
warning: No `requires-python` value found in the workspace. Defaulting to `>=3.7`.
Resolved 8 packages in 2.30s
Prepared 4 packages in 4.90s
Installed 5 packages in 49ms
 + certifi==2025.1.31
 + charset-normalizer==3.4.1
 + idna==3.10
 + requests==2.31.0
 + urllib3==2.0.7
```

Could there `requires-python` for workspace:
```toml
# pyproject.toml

[dependency-groups]
dev = []

[tool.uv.workspace]
requires-python = ">=3.7"
```
which then members could directly use it:
```toml
# member1/pyproject.toml

[project]
...
dynamic = ["requires-python"]

[uv.project]  # or [uv.backend.project]
requires-python = { workspace = true }
```
