### ISSUE TITLE
Dynamic version is not omitted when fields other than `version` are marked as dynamic

### ISSUE THREAD

**Issue by edgarrmondragon** [astral-sh/uv#11460]
### Summary

Consider this project

```toml
# pyproject.toml
[project]
name = "uv-more-dynamic"
dynamic = [
    "version",
]
requires-python = ">=3.13"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
```

which results in the lock file

```toml
version = 1
requires-python = ">=3.13"

[[package]]
name = "uv-more-dynamic"
source = { editable = "." }
```

However, marking `dependencies` or `optional-dependencies` as dynamic results in the version being added to `uv.lock`:

```diff
  [project]
  name = "uv-more-dynamic"
  dynamic = [
+     "dependencies",
      "version",
  ]
```

```diff
  version = 1
  requires-python = ">=3.13"

  [[package]]
  name = "uv-more-dynamic"
+ version = "0.1.dev0+d20250212"
  source = { editable = "." }
```

### Platform

Darwin 24.3.0 arm64

### Version

uv 0.5.30 (ddbc6e315 2025-02-10)

### Python version

Python 3.13.1
