### ISSUE TITLE
`uv export` includes duplicates for projects with conflicts

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#11559]
E.g., given:

```toml
[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = ["anyio"]

[project.optional-dependencies]
cpu = [
  "idna<=1",
]
cu124 = [
  "idna<=2",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
]
```

Then `uv export` produces:

```
❯ uv export
Using CPython 3.13.0
Resolved 9 packages in 0.64ms
# This file was autogenerated by uv via the following command:
#    uv export
anyio==1.3.1 ; extra == 'extra-7-project-cpu' or extra == 'extra-7-project-cu124' \
    --hash=sha256:a46bb2b7743455434afd9adea848a3c4e0b7321aee3e9d08844b11d348d3b5a0 \
    --hash=sha256:f21b4fafeec1b7db81e09a907e44e374a1e39718d782a488fdfcdcf949c8950c
anyio==4.8.0 ; (extra == 'extra-7-project-cpu' and extra == 'extra-7-project-cu124') or (extra != 'extra-7-project-cpu' and extra != 'extra-7-project-cu124') \
    --hash=sha256:1d9fe889df5212298c0c0723fa20479d1b94883a2df44bd3897aa91083316f7a \
    --hash=sha256:b5011f270ab5eb0abf13385f851315585cc37ef330dd88e27ec3d34d651fd47a
async-generator==1.10 ; extra == 'extra-7-project-cpu' or extra == 'extra-7-project-cu124' \
    --hash=sha256:01c7bf666359b4967d2cda0000cc2e4af16a0ae098cbffcb8472fb9e8ad6585b \
    --hash=sha256:6ebb3d106c12920aaae42ccb6f787ef5eefdcdd166ea3d628fa8476abe712144
idna==3.10 ; (extra == 'extra-7-project-cpu' and extra == 'extra-7-project-cu124') or (extra != 'extra-7-project-cpu' and extra != 'extra-7-project-cu124') \
    --hash=sha256:12f65c9b470abda6dc35cf8e63cc574b1c52b11df2c86030af0ac09b01b13ea9 \
    --hash=sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3
sniffio==1.3.1 \
    --hash=sha256:2f6da418d1f1e0fddd844478f41680e794e6051915791a034ff65e5f100525a2 \
    --hash=sha256:f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc
typing-extensions==4.12.2 ; (python_full_version < '3.13' and extra != 'extra-7-project-cpu' and extra != 'extra-7-project-cu124') or (extra == 'extra-7-project-cpu' and extra == 'extra-7-project-cu124') \
    --hash=sha256:04e5ca0351e0f3f85c6853954072df659d0d13fac324d0072316b67d7794700d \
    --hash=sha256:1a7ead55c7e559dd4dee8856e3a88b41225abfe1ce8df57b7c13915fe121ffb8
```

I believe I know how to fix this; we applied a fix to `Installable` that wasn't carried over to the export logic.
