### ISSUE TITLE
Allow dependency groups to define a separate `requires-python`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#11606]
### Summary

Right now, the `[dependency-groups]` have the same `requires-python` as the `[project]` defines, but this causes problems when a group is only intended to be used with a different Python version range, e.g., you could only care about 3.12+ for building your documentation but 3.9+ matters for publishing your library.

See

- #11605

As a meta-note, I know this was discussed elsewhere but cannot find it.

### Example

```toml
[project]
name = "example"
version = "0.0.0"
requires-python = ">=3.10"

[tool.uv.dependency-groups.foo]
requires-python = ">=3.12"
```
