### ISSUE TITLE
Package-specific find-links, without using other indices

### ISSUE THREAD

**Issue by JWCS** [astral-sh/uv#11634]
### Question

Installing just one package from a find-links with pip was [(source)](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip)
``` bash
pip install mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.4/index.html
```
I'm trying to replicate this functionality via the pyproject.toml configuration. 
The most that I can see allowed is:
(Validated with `uv lock --upgrade`)
``` toml
dependencies = [ "mmcv==2.2.0" ]
[tool.uv]
environments = [ "sys_platform == 'linux' and implementation_name == 'cpython' and platform_machine == 'x86_64'" ]
find-links = [ "https://download.openmmlab.com/mmcv/dist/cu121/torch2.4/index.html" ]
# ^ Is this is exposed to all other packages? Do all other package installs check this/these links?
# [tool.uv.sources]
# mmcv = { index = "mmcv-cu121" }
# [[tool.uv.index]]
# name = "mmcv-cu121"
# explicit = true
# url = "" # None? Exclude all other indices ? Not documented
```
Ideally, I'd only want the particular package to use that find-links, and I'd also want it to be excluded from searching other indices (ie pypi and other non-explicits). 
I might happen to have several other packages with this same install condition in the same project.
Am I just missing something in the documentation, or is this non-functionality?

### Platform

Ubuntu 20.04 amd64

### Version

uv 0.6.1
