### ISSUE TITLE
uv can install more than one version of a package at a time

### ISSUE THREAD

**Issue by jbms** [astral-sh/uv#11648]
### Summary

When there are dependency groups with conflicts, uv can incorrectly install more than one version of a package at a time.

pyproject.toml

```toml
[project]
name = "uv-dep-test"
version = "0.1.0"

requires-python = ">=3.13"
dependencies = []

[dependency-groups]
c = [
"sphinx",
]
a = [
"sphinx<5",
]
b = [
"sphinx>5",
]

[tool.uv]
conflicts = [
  [
    { group = "a" },
    { group = "b" },
  ],
]
```

Run:

```shell
uv sync --group a --group c
uv pip list
```

Output:

```
Package                       Version
----------------------------- ---------
alabaster                     0.7.16
alabaster                     1.0.0
babel                         2.17.0
certifi                       2025.1.31
charset-normalizer            3.4.1
docutils                      0.17.1
docutils                      0.21.2
idna                          3.10
imagesize                     1.4.1
jinja2                        3.1.5
markupsafe                    3.0.2
packaging                     24.2
pygments                      2.19.1
requests                      2.32.3
roman-numerals-py             3.0.0
snowballstemmer               2.2.0
sphinx                        4.5.0
sphinx                        8.2.0
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
urllib3                       2.3.0
```

Note that group a and group c do NOT conflict.  The expected result is for uv to install sphinx 4.5.0 to satisfy the requirements of both groups.

### Platform

Linux

### Version

uv 0.6.1

### Python version

Python 3.13.0
