### ISSUE TITLE
uv sync --only-group and --no-extra still evaluates other package sources not specified, source = path

### ISSUE THREAD

**Issue by JWCS** [astral-sh/uv#11675]
### Summary

MRE:
`chmod +x Dockerfile && ./Dockerfile && docker run --network host -it --rm --entrypoint sh mre-exclude-groups:latest`
``` Dockerfile
#!/usr/bin/env -S docker build -t mre-exclude-groups:latest . -f
FROM ghcr.io/astral-sh/uv:python3.10-alpine

WORKDIR /app

COPY pyproject.toml .
# ideally, reusing existing uv.lock file; but the chicken-egg problem is without uv.lock file; see --inexact

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

RUN uv venv

# BUG 1
# This doesn't work because "distribution not found at <this path>", for unspecified group/package groundingdino
#RUN uv sync --inexact --only-group legacy-setup-req

# Ok, install, try again
RUN apk add git && git clone --depth 1 --single-branch https://github.com/IDEA-Research/GroundingDINO.git

# BUG 2 (might be the same)
#RUN uv sync --inexact --only-group legacy-setup-req
# Failed to build groundingdino at <this path>, no module named torch

# What I want to do
#RUN uv sync --inexact --only-group legacy-setup-req
#RUN uv sync --inexact --no-default-groups --no-install-project
#RUN uv sync --inexact --all-groups --no-install-project
#RUN uv sync -U
```
``` toml
[project]
name = "uv-exclude-groups-mre"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
  "numpy<2",
  "torch==1.13.1+cu116",
  "torchvision==0.14.1+cu116",
]
[dependency-groups]
legacy-setup-req = [ "setuptools", "torch" ]
groundingdino = [ {include-group="legacy-setup-req"}, "groundingdino" ]

[tool.uv]
package = false
environments = [
  "sys_platform == 'linux' and implementation_name == 'cpython' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch       = { index = "pytorch-cu116" }
torchvision = { index = "pytorch-cu116" }
groundingdino = { path = "GroundingDINO", editable = false }

[[tool.uv.index]]
name = "pytorch-cu116"
url = "https://download.pytorch.org/whl/cu116"
explicit = true

# stop uv from building workaround https://github.com/astral-sh/uv/issues/6321
[tool.setuptools]
py-modules = []
```
Granted, I know that FWIW, these are all just "temporary" (but crucial) hacks around some cleaner mechanism for dealing with setup.py/pytorch packages; there's a handful of such issues around the repo. Ex #7390 #7722
It's a pain to uv `pip install torch` not pinned to the version/source specified in the pyproject.toml, and then tier the builds. Ex, this does work:

However, I'm also getting this issue with "optional-dependencies":
``` diff
> git diff
diff --git a/Dockerfile b/Dockerfile
index e350a25..f37b630 100755
--- a/Dockerfile
+++ b/Dockerfile
@@ -17,8 +17,14 @@ RUN uv venv
 # Ok, install, try again
 RUN apk add git && git clone --depth 1 --single-branch https://github.com/IDEA-Research/GroundingDINO.git

-# BUG 2 (might be the same)
-#RUN uv sync --inexact --only-group legacy-setup-req
+# BUG 3: considers optionals!
+RUN --mount=type=cache,target=/root/.cache/uv \
+   uv sync --inexact --no-extra compile # FAILS, tries to parse GroundingDino/setup.py
+RUN --mount=type=cache,target=/root/.cache/uv \
+   uv sync --inexact # FAILS, tries to parse GroundingDino/setup.py
+RUN --mount=type=cache,target=/root/.cache/uv \
+   uv sync --inexact --extra build # FAILS, tries to parse GroundingDino/setup.py
+RUN --mount=type=cache,target=/root/.cache/uv \
+   uv sync --inexact --extra build --extra compile
 # Failed to build groundingdino at <this path>, no module named torch

 # What I want to do
diff --git a/pyproject.toml b/pyproject.toml
index 4c1d845..9b9ea3b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -7,9 +7,10 @@ dependencies = [
   "torch==1.13.1+cu116",
   "torchvision==0.14.1+cu116",
 ]
-[dependency-groups]
-legacy-setup-req = [ "setuptools", "torch" ]
-groundingdino = [ {include-group="legacy-setup-req"}, "groundingdino" ]
+
+[project.optional-dependencies]
+build = ["setuptools", "torch"]
+compile = ["groundingdino"]

 [tool.uv]
 package = false
```
The 3 uv sync commands which shouldn't be considering groundingdino all try evaluating its setup.py, which on first run, no torch is installed. 

### Platform

Alpine x64 (uv docker image)

### Version

uv 0.6.1

### Python version

Python 3.10
