### ISSUE TITLE
Platform specific indexes not working

### ISSUE THREAD

**Issue by FredrikNoren** [astral-sh/uv#11776]
### Summary

This `pyproject.toml` fails when I run uv sync:

```
[project]
name = "uvtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.6.0", "torchvision>=0.21.0"]

[tool.uv.sources]
torch = { index = "pytorch_cu124", marker = "sys_platform == 'linux'" }
torchvision = { index = "pytorch_cu124", marker = "sys_platform == 'linux'" }

[[tool.uv.index]]
name = "pytorch_cu124"
url = "https://download.pytorch.org/whl/cu124"
```

The error is:
```
uvtest git:(master) ✗ uv sync
Resolved 30 packages in 1.77s
error: Found duplicate package `torchvision==0.21.0+cu124 @ registry+https://download.pytorch.org/whl/cu124`
```

### Platform

Darwin 23.6.0 arm64

### Version

v0.6.3

### Python version

Python 3.12.4

**Comment by charliermarsh** [comment]
Strange, thanks.

**Comment by charliermarsh** [comment]
For what it's worth, I think you want `explicit = true` on that index (which does work as expected):

```toml
[project]
name = "uvtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.6.0", "torchvision>=0.21.0"]

[tool.uv.sources]
torch = { index = "pytorch_cu124", marker = "sys_platform == 'linux'" }
torchvision = { index = "pytorch_cu124", marker = "sys_platform == 'linux'" }

[[tool.uv.index]]
name = "pytorch_cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
```
