### ISSUE TITLE
Installation of workspace member's dev dependencies depends on whether the root has a [project] section

### ISSUE THREAD

**Issue by thorbenk** [astral-sh/uv#11797]
### Question

In my minimal "project with workspace member" setup (https://github.com/thorbenk/uv_workspace_dev_issue , just run `./issue.sh` to reproduce),
I have the following:

- a workspace member `mypkg`
  - declares a dev dependency on `loguru`
- a root `pyproject.toml` file  

I want to understand when the development dependency is part of the virtual environment after `uv sync`.
Apparently it differs depending on whether the root `pyproject.toml` declares a project or not.

If I just have

```toml
[tool.uv.workspace]
members = ["packages/mypkg"]
```

the **dev dependency is installed**.

However, if I have

```toml
[project]
name = "wsplay_root"
version = "0.1.0"
requires-python = ">=3.12.6"
dependencies = ["mypkg"]

[tool.uv.workspace]
members = ["packages/mypkg"]

[tool.uv.sources]
mypkg = { workspace = true }
```

then **the dev dependency ist NOT installed**.

Is this a bug? Or expected behavior?

### Version

uv 0.6.3
