### ISSUE TITLE
Guidance on `uv.toml` format as an alternative to `pyproject.toml`

### ISSUE THREAD

**Issue by juan-op** [astral-sh/uv#11810]
### Question

I haven't found any guide or examples on how to format a `uv.toml` file to use instead of `pyproject.toml`.

For example, how would a basic `pyproject.toml` like this one translate to `uv.toml`?

```toml
[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas==1.5.2",
    "polars==1.23.0",
]
```

I'd appreciate some clarification on this matter and perhaps adding a section in the documentation about this topic.

### Platform

Windows 11 x86_64

### Version

uv 0.6.3
