### ISSUE TITLE
pip compile: explicit index + requirements.in

### ISSUE THREAD

**Issue by juftin** [astral-sh/uv#11848]
### Summary

I've found that explicit indexes aren't compatible with dependencies defined in a `requirements.in` file. I would expect `uv pip compile requirements.in` to work - I've used [pyproject from test.pypi.org](https://test.pypi.org/project/pyproject/0.0.1/) and [uv from pypi.org](https://pypi.org/project/uv/0.6.3/) as an example:

```txt
uv==0.6.3
pyproject==0.0.1
```

```toml
[tool.uv.sources]
uv = { index = "pypi" }
pyproject = { index = "test" }

[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple/"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
explicit = true
```

```console
❯ uv pip compile requirements.in
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of pyproject==0.0.1 and you require pyproject==0.0.1, we can conclude that your requirements are unsatisfiable.
```

----- 

On the other hand, this works just fine when running from a `pyproject.toml`:

```toml
[project]
name = "test"
version = "0.1.0"
dependencies = [
    "uv==0.6.3",
    "pyproject==0.0.1",
]

[tool.uv.sources]
uv = { index = "pypi" }
pyproject = { index = "test" }

[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple/"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
explicit = true
```

```console
❯ uv pip compile pyproject.toml
Resolved 2 packages in 16ms
# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml
pyproject==0.0.1
    # via test (pyproject.toml)
uv==0.6.3
    # via test (pyproject.toml)
```

### Platform

macOS 14

### Version

uv 0.6.3 (a0b9f22a2 2025-02-24)

### Python version

3.12.0
