### ISSUE TITLE
Custom installation options present in the pyproject.toml

### ISSUE THREAD

**Issue by hongbo-miao** [astral-sh/uv#11887]
### Summary

I have some projects that need install by

```sh
uv sync --extra=build
uv sync --extra=build --extra=compile
```

base on https://docs.astral.sh/uv/concepts/projects/config/#build-isolation

Currently Renovate cannot upgrade dependencies for these projects.

I originally asked at https://github.com/renovatebot/renovate/discussions/33811

This would need uv side to support to let Renovate know what is proper steps to install. It would be great to support it, thanks! ☺️

**Comment by nathanjmcdougall** [comment]
Related: https://peps.python.org/pep-0771/

As a workaround for now, you could duplicate the `extra` information in a dependency group, and set the dependency to install by default:
https://docs.astral.sh/uv/concepts/projects/dependencies/#default-groups

**Comment by hongbo-miao** [comment]
Thanks @nathanjmcdougall . In my case, the installation order is also important. For example,

```toml
[project]
name = "mineru"
version = "1.0.0"
requires-python = "~=3.12.0"

[project.optional-dependencies]
build = [
  "setuptools",
  "torch",
]
compile = [
  "detectron2",
  "magic-pdf[full]==1.1.0",
]
paddlepaddle-gpu = [
  "paddlepaddle-gpu==3.0.0b2",
]

[dependency-groups]
dev = [
  "poethepoet==0.32.2",
  "pytest-cov==6.0.0",
  "pytest==8.3.4",
]

[tool.uv]
package = false
prerelease = "allow"
no-build-isolation-package = ["detectron2"]

[tool.uv.sources]
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "main" }
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu118"
explicit = true

[tool.poe.tasks]
dev = "python src/main.py"
test = "pytest --verbose --verbose"
test-coverage = "pytest --cov=. --cov-report=xml"

```

I have to install based on order
```sh
uv sync --extra=build
uv sync --extra=build --extra=compile
uv sync --extra=build --extra=compile --extra=paddlepaddle-gpu
uv sync --extra=build --extra=compile --extra=paddlepaddle-gpu --dev
```

I listed the reason why have to install like this at [here](https://github.com/opendatalab/MinerU/discussions/1374#discussion-7750775) if you are curious about why.

I assume you are referring to [project.optional-dependencies](https://docs.astral.sh/uv/concepts/projects/dependencies/#optional-dependencies):

![Image](https://github.com/user-attachments/assets/9d04e3b2-1404-46aa-a00e-42824d03ad53)

which I do not think can help installing based on certain order. 😔
