### ISSUE TITLE
"uv pip install" not installing packages from workspace/path sources

### ISSUE THREAD

**Issue by djcopley** [astral-sh/uv#11989]
### Question

Hey everyone, I am attempting to work the uv workspaces flow into my monorepo, but I'm running into some unexpected behavior.

My `pyproject.toml`:

```toml
[tool.uv.workspace]
members = ["packages/package-a"]

[tool.uv.sources]
package-a = { workspace = true }
package-b = { path = "packages/package-b", editable = true }
```

When I run `uv pip install package-a` or `uv pip install package-b`, I get 

```
No solution found when resolving dependencies:
-> Because package_a was not found in the package registry and you require package_a, we can conclude that your requirements are unsatisfiable.
```

Does the `pip install` interface not consider `uv.sources` workspace or path? It seems to be considering my `{ index = "alternative" }` sources.

---

For additional context, I'm trying to integrate uv with my existing hatch environment workflow which uses uv pip install for synchronizing its virtual environment.

### Platform

Ubuntu 22.04 x86_64

### Version

uv 0.5.29
