### ISSUE TITLE
Won't resolve source distribution locally if dynamic version is set in Cargo.toml with maturin

### ISSUE THREAD

**Issue by idealseal** [astral-sh/uv#11998]
### Summary

I'm trying to vendor `pydantic-core` in my local source tree. I have a dependency on `pydantic` and put

```toml 
[tool.uv.sources]
pydantic = { path = "src/foo/vendor/pydantic" } 
pydantic-core = { path = "src/foo/vendor/pydantic-core" } 
```

in my `pyproject.toml`.

Running `uv sync -v` shows that `pydantic` is used from the local source distribution, `pydantic-core` is downloaded.

I guess this is because it can't resolve the version of `pydantic-core` and ignores the local installation.

Is this out-of-scope for uv? Is there a way to communicate this from the build system to uv? Is this a `maturin` issue?

### Platform

Linux

### Version

uv 0.6.4

### Python version

Irrelevant
