### ISSUE TITLE
uv cache seems don't work on github action

### ISSUE THREAD

**Issue by shenxiangzhuang** [astral-sh/uv#12031]
### Question

The github action setting:
```yaml
name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      UV_HTTP_TIMEOUT: 900 # max 15min to install deps
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          # Adding cache-dependency-path for better cache invalidation
          cache-dependency-path: |
            pyproject.toml
          cache-key: ${{ runner.os }}-${{ matrix.python-version }}-uv

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint with Mypy
        run: uv run mypy .

      - name: Lint with Ruff
        run: uv run ruff check

```

Take [this](https://github.com/ai-glimpse/toyllm/actions/runs/13713720918/job/38354800810) run for example, which still need ~10min to install all the deps. So I want to know that is the cache really works with this setting?

### Platform

ubuntu-latest

### Version

latest
