### ISSUE TITLE
How to properly publish to TestPyPI?

### ISSUE THREAD

**Issue by willigott** [astral-sh/uv#12050]
### Question

First of all, thank you very much for your work, using `uv` has been a great experience so far!

My goal is to publish a package to TestPyPI, afterwards to PyPI, everything should be facilitated through GitHub actions. My entire pipeline is using `uv` to check formatting using `ruff`, linting etc. and also for the `build` using `uv build --no-sources` and you can see the pipeline files [here](https://github.com/willigott/biophysical-assay-data-analysis/tree/main/.github). I struggle with the publishing to TestPyPI.

The relevant section in my `pyproject.toml` looks like this:
```lang-ini
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"  # pipeline fails when using /simple instead of /legacy
publish-url = "https://test.pypi.org/legacy/"
```
and in my `release.yaml` I have the following section:
  
```lang-yaml
publish-testpypi:
    name: Publish to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment: release-testpypi
    permissions:
      id-token: write  # Required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish to TestPyPI
        run: uv publish --index testpypi dist/*
```
So, like this, everything works fine, I see the build artifacts on GitHub and also the wheels on TestPyPI.

However, originally, I used (based on [the documentation][1]):
```lang-ini
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
```
and then my pipeline fails with all kind of errors mentioning version issues referring to `https://test.pypi.org/simple/`, interestingly still in the part of the pipeline not related to the TestPyPi part (copied below); when debugging, I just changed the `url` to `publish-url` to see whether the errors change, but then it all worked out.

So, I guess I do not fully understand what `url` is for. When I check [the documentation][2], it says for the argument `--index`:

>     The index `url` will be used to check for existing files to skip duplicate uploads.

and in [the documentation on `publish-url`][3] itself it says

> The URL of the upload endpoint (not the index URL).
> 
> Note that there are typically different URLs for index access (e.g.,
> `https:://.../simple`) and index upload.
> 
> Defaults to PyPI’s publish URL (<https://upload.pypi.org/legacy/>).
> 
> May also be set with the UV_PUBLISH_URL environment variable.

I have a few related questions:

- For my own package, what should I choose for `url`? Should it link to my own package on TestPyPI, so e.g. `https://test.pypi.org/project/bada/` (which ,unfortunately, does not work)? 
- How can I properly check whether the files have already been uploaded? Combining `--check-url` and `--index` is not permitted, so it again boils down to identifying the correct index url.
- Why does the pipeline fail at a stage where the `index` is not obviously triggered?

# The error I get when not using `url = "https://test.pypi.org/legacy/"`:

The error looks very similar when I use `url = "https://test.pypi.org/simple/"`; it's just much longer as it lists all kind of hatchling versions.

> Run uv run pyright .
> Using CPython 3.12.3 interpreter at: /usr/bin/python3
> Creating virtual environment at: .venv
>    Building bada @ file:///home/runner/work/biophysical-assay-data-analysis/biophysical-assay-data-analysis
> Downloading scipy (35.[6](https://github.com/willigott/biophysical-assay-data-analysis/actions/runs/13724604697/job/38387936243#step:4:7)MiB)
> Downloading numpy (15.4MiB)
> Downloading pygments (1.2MiB)
> Downloading dtaidistance (2.9MiB)
> Downloading setuptools (1.2MiB)
> Downloading pydantic-core (1.9MiB)
> Downloading ruff (10.[7](https://github.com/willigott/biophysical-assay-data-analysis/actions/runs/13724604697/job/38387936243#step:4:8)MiB)
> Downloading plotly (14.1MiB)
> Downloading pandas (12.1MiB)
> Downloading pyright (5.4MiB)
>   × Failed to build `bada @
>   │ file:///home/runner/work/biophysical-assay-data-analysis/biophysical-assay-data-analysis`
>   ├─▶ Failed to resolve requirements from `build-system.requires`
>   ├─▶ No solution found when resolving: `hatchling`
>   ╰─▶ Because there are no versions of hatchling and you require hatchling, we
>       can conclude that your requirements are unsatisfiable.
> 
>       hint: `hatchling` was found on https://test.pypi.org/project/bada/,
>       but not at the requested version (all versions of hatchling). A
>       compatible version may be available on a subsequent index (e.g.,
>       https://pypi.org/simple). By default, uv will only consider versions
>       that are published on the first index that contains a given package, to
>       avoid dependency confusion attacks. If all indexes are equally trusted,
>       use `--index-strategy unsafe-best-match` to consider all versions from
>       all indexes, regardless of the order in which they were defined.
> Error: Process completed with exit code 1.

# UV version
I have an action defined like this that is reused across the entire pipeline:

```
name: "install uv"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.4"
```

  [1]: https://docs.astral.sh/uv/guides/package/#publishing-your-package
  [2]: https://docs.astral.sh/uv/reference/cli/#uv-publish--index
  [3]: https://docs.astral.sh/uv/reference/cli/#uv-publish--publish-url

**Comment by willigott** [comment]
OK, trying with

```
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/ bada"
publish-url = "https://test.pypi.org/legacy/"
```

and 

```
  publish-testpypi:
    name: Publish to TestPyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment: release-testpypi
    permissions:
      id-token: write  # Required for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish to TestPyPI
        run: uv publish --index testpypi dist/*
```

now got rid of the error above but now gives

> Run uv publish --index testpypi dist/*
> Publishing 2 files https://test.pypi.org/legacy/
> Uploading bada-0.1.0-py3-none-any.whl (8.2KiB)
> Uploading bada-0.1.0.tar.gz (35.3KiB)
> error: Failed to publish `dist/bada-0.1.0.tar.gz` to https://test.pypi.org/legacy/
>   Caused by: Upload failed with status code 400 Bad Request. Server says: 400 File already exists ('bada-0.1.0.tar.gz', with blake2_25[6](https://github.com/willigott/biophysical-assay-data-analysis/actions/runs/13724999696/job/38389225709#step:5:7) hash 'b4772c755da3244f8eda1be22a[7](https://github.com/willigott/biophysical-assay-data-analysis/actions/runs/13724999696/job/38389225709#step:5:8)7c7510e902e1b0953eb625372808ec34f5174'). See https://test.pypi.org/help/#file-name-reuse for more information.
> Error: Process completed with exit code 2.

Is that expected behavior? My hope was that `--index` would check whether the files exist and if so, move on. How would I set this up properly?

Thanks!

**Comment by zanieb** [comment]
There's an example at https://docs.astral.sh/uv/guides/package/#publishing-your-package

You want

```toml
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
```
