### ISSUE TITLE
With explicit indexes, uv still pre-fetches from implicit indexes in some cases

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#12056]
I noticed that given:

```toml
[project]
name = "project"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "torch"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
```

The logs indicate that we still fetch `torch` from PyPI (in addition to correctly fetching it from the PyTorch index; we then use the PyTorch index, so the PyPI fetch is purely extraneous and "ignored"). I think this is a bug in the resolver.
