### ISSUE TITLE
Pinning Indirect dependencies to index does not work

### ISSUE THREAD

**Issue by 07pepa** [astral-sh/uv#12065]
### Summary

consider this pyproject.toml

```toml
[project]
name = "test"
version = "0.1.0"
description = "test"
requires-python = ">=3.12,<3.13"
dependencies = [
    "docling[tesserocr]>=2.25.1",
]

[tool.uv]
package = false

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
```

but it produces lockfile with
```lock
...
[[package]]
name = "torch"
version = "2.6.0"
source = { registry = "https://pypi.org/simple" }
...
```

this is likely unexpected

### Platform

Darwin 24.3.0 arm64

### Version

uv 0.6.5 (Homebrew 2025-03-06)

### Python version

Python 3.12.4
