### ISSUE TITLE
Can't resolve dependencies with git dependency

### ISSUE THREAD

**Issue by adriangb** [astral-sh/uv#12141]
### Summary

I am getting at least a confusing error message if not a bug with the following dependencies:

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "opentelemetry-api==1.31.0",
  "opentelemetry-instrumentation-asgi@git+https://github.com/open-telemetry/opentelemetry-python-contrib.git@v0.52b0#subdirectory=instrumentation/opentelemetry-instrumentation-asgi",
]
```

```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of opentelemetry-api==1.31.0 and your project depends on opentelemetry-api==1.31.0, we can conclude that your project's requirements are unsatisfiable.
```

I find this error message rather confusing: clearly `opentelemetry-api==1.31.0` _does_ exist, but it must be getting filtered out. Saying it doesn't exist is confusing.

Note that I pointed it specifically to the rev `v0.52b0` which is the rev corresponding to the version released on PyPi: https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.52b0

Without the git dependency resolution works:

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "opentelemetry-api==1.31.0",
  "opentelemetry-instrumentation-asgi==0.52b0",  # should be the same as the version in git
]
```

### Platform

macOS Darwin 24.3.0 arm64

### Version

uv 0.6.6 (Homebrew 2025-03-12)

### Python version

3.12
