### ISSUE TITLE
uv `0.6.6` fails to build arm64 packages in the CI?

### ISSUE THREAD

**Issue by harshil21** [astral-sh/uv#12207]
### Summary

My github CI action failed for the github arm64 runner after updating from uv 0.6.5 to uv 0.6.6, with no changes in the lockfile between the two versions.

Here's the associated PR - https://github.com/NCSU-High-Powered-Rocketry-Club/AirbrakesV2/pull/179

Example of a passing job, prior to that PR - https://github.com/NCSU-High-Powered-Rocketry-Club/AirbrakesV2/actions/runs/13743565044/job/38435717408

Example of a failing job, in that PR - https://github.com/NCSU-High-Powered-Rocketry-Club/AirbrakesV2/actions/runs/13888432712/job/38856321885?pr=179

Notice how the project successfully builds on x86_64, but doesn't on arm64, and the only thing which changed was updating `uv` to 0.6.6. If I pin the uv version to 0.6.5, the build and the job pass.

I thought it could be a problem with `faster-fifo`, even though there is no new version released since then, so I tried debugging via a new job:

```
  name: Test arm64 failure

  on:
    pull_request:
      branches:
        - '**'  # Matches all branch names, for PRs
    push:
      branches:
        - 'main'  # Run tests on main branch

  jobs:
    pytest:
      name: pytest
      runs-on: ${{ matrix.os }}
      timeout-minutes: 5
      strategy:
        matrix:
          os: [ubuntu-24.04-arm]
        fail-fast: False
      steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: "pyproject.toml"

        - name: Install the project
          run: uv pip -v install --system faster-fifo

        - name: Run python and import faster_fifo
          run: |
            PYTHON_JIT=1 uvx --with faster_fifo python -c "import faster_fifo; print(faster_fifo.Queue)"
```

but this passes successfully, so I'm not sure what the underlying issue is. Do I need to install gcc/g++ for the arm64 runner separately? Why does it work for uv 0.6.5 then?

### Platform

Linux x86_64 and arm64 on github CI

### Version

uv 0.6.6

### Python version

Python 3.13.2
