### ISSUE TITLE
`uv lock` creates a lockfile that can't be installed

### ISSUE THREAD

**Issue by s-banach** [astral-sh/uv#12241]
## Basic question
My `pyproject.toml` specifies `python >= 3.11`.
My actual `.venv` has python 3.12.
When I run `uv lock`, it creates a lockfile that works for python 3.11, but fails for python 3.12.
Is this the intended behavior?

## Specific details
My company has our own internal pypi index. It has some oddities.
For example, `numpy==2.2.4` is available for python 3.11, but not yet available for newer versions of python.
If I run `uv lock`, it creates a lockfile that specifies `numpy==2.2.4`.
If `uv` chose `numpy==2.2.3` instead, it would be installable on `3.11, 3.12, 3.13`.

## Why I'm confused.
The `uv.lock` file lists various wheels for `python 3.11, 3.12, 3.13`, so it seems to be _trying_ to build  a lockfile that works for those three versions. But the lockfile it eventually produces can't be installed on any version except `3.11`.

**Comment by s-banach** [comment]
Actually, it just builds the same lock file, but adds a section for win_64 with `numpy-2.2.3.tar.gz` instead of wheels.
Idk, I can't make it work.

**Comment by charliermarsh** [comment]
I don't think we look at `python_version` at all in that setting. There's an open issue tracking it. I can look at it soon. You should really just pin `numpy` to PyPI rather than getting it from your own repository via an explicit index source?

**Comment by s-banach** [comment]
I'm sorry for wasting your time with stupid stuff. My company blocks pypi, we have our "internal pypi" which has some bogus security scanner that blocks certain versions.

**Comment by charliermarsh** [comment]
That's ok, I understand. Let me re-open.

**Comment by sanmai-NL** [comment]
@charliermarsh 



```toml
[tool.uv]
environments = [
  "platform_system == 'Darwin' and platform_machine == 'arm64'",
  "platform_system == 'Linux' and (platform_machine == 'x86_64' or platform_machine == 'aarch64')",
  "platform_system == 'Windows' and (platform_machine == 'amd64')",
]
required-environments = [
  "platform_system == 'Darwin' and platform_machine == 'arm64'",
  "platform_system == 'Linux' and (platform_machine == 'x86_64' or platform_machine == 'aarch64')",
  "platform_system == 'Windows' and (platform_machine == 'amd64')",
]
no-build = true
required-version = "==0.6.11"
```

```console
$ uv sync
TRACE Resolver derivation tree before reduction
term root==0a0.dev0
  root==0a0.dev0 depends on mypackage*
  term mypackage*
    term mypackage==2025.2.26.12.0.0
      mypackage==2025.2.26.12.0.0 depends on lingua-language-detector==2.1.0
      lingua-language-detector==2.1.0 no `platform_machine == 'amd64' and sys_platform == 'win32'`-compatible wheels
    no versions of mypackage<2025.2.26.12.0.0 | >2025.2.26.12.0.0
TRACE Resolver derivation tree after reduction
term mypackage==2025.2.26.12.0.0
  mypackage==2025.2.26.12.0.0 depends on lingua-language-detector==2.1.0
  lingua-language-detector==2.1.0 no `platform_machine == 'amd64' and sys_platform == 'win32'`-compatible wheels
  × No solution found when resolving dependencies for split (platform_machine == 'amd64' and sys_platform == 'win32'):
  ╰─▶ Because lingua-language-detector==2.1.0 has no `platform_machine == 'amd64' and sys_platform == 'win32'`-compatible wheels and your project depends on
      lingua-language-detector==2.1.0, we can conclude that your project's requirements are unsatisfiable.
```

Even though https://pypi.org/project/lingua-language-detector/#lingua_language_detector-2.1.0-cp312-cp312-win_amd64.whl exists.

Nothing on https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/ or the values obtained via the functions in https://docs.python.org/3/library/platform.html suggests how to match against the wheel tag `win_64`.
