### ISSUE TITLE
`--no-install-project` being ignored during a sync

### ISSUE THREAD

**Issue by VERBOSE-01** [astral-sh/uv#12265]
### Question

I'm trying a [partial installation](https://docs.astral.sh/uv/concepts/projects/sync/#partial-installations) (all dependencies, except my project) using the `--no-install-project` flag but unfortunately, `uv` still tries to install the project itself.

#### Tree
```
> my_personal_project
--> # src folders and files
--> pyproject.toml
--> .python-version
```

#### Terminal

```bash
PS C:\Users\verbose\Desktop\my_personal_project> uv sync --no-install-project
Using CPython 3.13.2 interpreter at: C:\Users\verbose\AppData\Local\Programs\Python\Python313\python.exe
Creating virtual environment at: .venv
⠋ my_personal_project==1.3.1
```

`.python-version`
```
3.13.2
```

`pyproject.toml`
```toml
[project]
name = "my_personal_project"
version = "1.3.1"
authors = [
    { name = "VERBOSE", email = "a@b.c" },
]
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4==4.12.2",
    "openpyxl==3.1.5",
    # ... others
]

[dependencies-groups]
dev = [
    "pytest==6.2.5",
    "ruff==0.11.0",
]
```

#### Some context
I'm dropping `requirements.txt` and `requirements-dev.txt` in favor of `uv.lock`. It means that I have no reqs files anymore and the `pyproject.toml` was created manually (before installing `uv`).

### Platform

Windows 10

### Version

0.6.7
