### ISSUE TITLE
`uv run --project` doesn't allow resolving module imports on windows

### ISSUE THREAD

**Issue by leokeba** [astral-sh/uv#12270]
### Summary

In my python project, I have a `scripts` folder where I keep various utilities that need to import code from the main `app` folder. When running it on macOS, I just use `uv run scripts/test.py --project .` and everything works as expected. On my windows system, when I try `uv run scripts\test.py --project .` i get the following error : `ModuleNotFoundError: No module named 'app'`.

I tried using an absolute path instead and various tricks to make it work, and also using the `--folder` argument instead, but nothing helps. Am I misunderstanding something or is this a bug ?

### Platform

Windows 11 x86_64

### Version

0.6.6

### Python version

3.13.2

**Comment by nbaju1** [comment]
Isn't `--project .` the same as running without the flag? If so do you get the same result without it?

**Comment by nbaju1** [comment]
Not able to reproduce.

Folder structure:
```markdown
project/
├── app/
|   └── foo.py
├── scripts/
|   └── test.py
└── pyproject.toml
```

foo.py
```python
def bar():
    print("bar")
```

test.py
```
from app.foo import bar

bar()
```

Running `uv run .\scripts\test.py` (without or without `--project .`) outputs `bar`.

**Comment by leokeba** [comment]
I reproduced your example and still get the same error on Windows 11.

What are the contents of your pyproject.toml ?

**Comment by nbaju1** [comment]
pyproject.toml
```toml
[project]
name = "project"
version = "0.1.0"
description = "Project"
requires-python = ">=3.12"
````

Note that I also have placed the venv inside the project root, if that matters.

**Comment by leokeba** [comment]
The only difference is that I was using python 3.13 instead of 3.12, but i tried changing the version and I still get the same result.

I am using a .venv placed in the project root as well. Any ideas for a workaround ?

**Comment by nbaju1** [comment]
Adding this to the pyproject.toml file 

```toml
[project.scripts]
test = "scripts.test:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "app"
```
(wrapping the `bar()` call in a `main` function in test.py) and running `uv run test` works though.
