### ISSUE TITLE
Cache issue when installing multiple python versions in Github Actions

### ISSUE THREAD

**Issue by NF-ada** [astral-sh/uv#12275]
### Summary

When copying the example from the Github Actions section, installing python fails with: 
```sh
Error: Cache path /home/runner/work/_temp/setup-uv-cache does not exist on disk. This likely indicates that there are no dependencies to cache. Consider disabling the cache input if it is not needed.
```
Based on action:
```yml
name: Example
on: [push]

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.7"
          python-version: ${{ matrix.python-version }}
```

### Platform

ubuntu-latest

### Version

0.6.7

### Python version

3.10-13
