### ISSUE TITLE
Allow setting default `uv init` settings in persistent configuration files

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#12305]
### Summary

There have been a few requests to allow changing the `uv init` defaults in a persistent location. This issue tracks the general concept.

### Example

```toml
[init]
vcs = "none"
python = "3.14"
```
