### ISSUE TITLE
Comments for `pyproject.toml` dependencies get shifted unexpectedly

### ISSUE THREAD

**Issue by christeefy** [astral-sh/uv#12333]
### Summary

Hi there, 

I encountered an behaviour where comments for `pyproject.toml` dependencies gets shifted unexpectedly.

## Minimal Reproducible Example
Given an initial `pyproject.toml` file:
```toml
[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "jedi>=0.19.2", # This is a test comment
    "typer>=0.15.2"
]
```

Upon running `uv add pydantic` (note how `pydantic` would be inserted right under `jedi` and the comment), I expect to get:
```toml
[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "jedi>=0.19.2", # This is a test comment
    "pydantic>=2.10.6", 
    "typer>=0.15.2"
]
```

Instead, comment associated with `jedi` has shifted to the line with `pydantic`:
```toml
[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "jedi>=0.19.2",  
    "pydantic>=2.10.6", # This is a test comment
    "typer>=0.15.2"
]
```

## Notes
In my testing, the bug occurs only when:
- the comment is applied on a non-terminal dependency — a dependency that isn't the first or last in the list
- a new dependency is inserted right below the commented one

---

### Contributing Back
`uv` is an amazing project, and I'd love to contribute back to it. 
I have some Rust experience, but I'm not familiar with the repo structure. If you can so kindly point me to the relevant section/crate in the repo, I'm happy to help resolve this bug 😊 

### Platform

Darwin 24.3.0 arm64

### Version

uv 0.6.8 (c1ef48276 2025-03-18)

### Python version

Python 3.12.2
