### ISSUE TITLE
Override build dependency and backend metadata, similiar to dependency-metadata

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#12447]
### Summary

Currently it's possible to override a packages [dependency metadata](https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata), e.g.

```toml
[[tool.uv.dependency-metadata]]
name = "chumpy"
version = "0.70"
requires-dist = ["numpy>=1.8.1", "scipy>=0.13.0", "six>=1.11.0"]
```

It would be nice to do that for build dependency and backend metadata, there are two scenarios I can see this being useful in:

1. A new version of a build backend gets released with backwards incompatibilities, only a small number of unmaintained dependencies need fixing to pin to an older version of the build backend
2. A user dependency on a legacy setuptools project and it would work except for the fact the project is unmaintained and does not provide a pyproject.toml

I'm a little unsure on my second example whether in general it would be enough to specify a build backend, or if in general it would need something more. In general I may have not fully thought through the complexities, so I understand if this isn't possible. This is something I think would be helpful to the ecosystem, not something I personally need.

### Example

```toml
[[tool.uv.dependency-metadata]]
name = "foo"
version = "0.8.0"
requires-dist = ["numpy>=1.8.1", "scipy>=0.13.0", "six>=1.11.0"]
build-requires-dist = ["setuptools<78"]
build-backend = ["setuptools.build_meta"]
```
