### ISSUE TITLE
Instruct the resolver to drop a package

### ISSUE THREAD

**Issue by zmeir** [astral-sh/uv#12458]
### Question

In my use-case I have a project that depends on package `a` which then depends on `b`.

It looks something like this:
```toml
[project]
name = "demo"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["a"]
```

I want to override `b` with a custom distribution - say `custom_b`.  
If you `pip install b` or `pip install custom_b`, both will put `b.py` in your site-packages.

So if I do something like this:
```toml
dependencies = ["a", "custom_b"]
```

Then when I run `uv sync` the following happens:
1. `a` brings `b` which will put `b.py` in my site-packages
2. `custom_b` will put a different `b.py` in my site-packages
Whichever `b.py` wins depends on the order in which they were installed.

I want to be able to tell the resolver to drop `b` altogether.  
Similarly to how I can instruct it to override the required version set by `a`:
```toml
[tool.uv]
override-dependencies = ["b==0.0.1+not.what.a.required"]
```
I want to do something like this:
```toml
[tool.uv]
override-dependencies = ["b==<DROP>"]
```

Is there a way to do this?

### Platform

Darwin 23.6.0 arm64

### Version

uv 0.6.4 (04db70662 2025-03-03)

**Comment by charliermarsh** [comment]
This is typically solved by doing something like:

```
[tool.uv]
override-dependencies = ["b ; python_version < 0"]
```

**Comment by zmeir** [comment]
That's exactly what I needed. Thanks @charliermarsh !

Small edit - I had to change your example to this in order to make it work:
```toml
[tool.uv]
override-dependencies = ["b ; python_version < '0'"]
```
