### ISSUE TITLE
Explain what `default = true` means in the configuration docs

### ISSUE THREAD

**Issue by mcrumiller** [astral-sh/uv#12450]
### Summary

In https://docs.astral.sh/uv/configuration/files/, the sample configuration for an index-url is

```toml
[[tool.uv.index]]
url = "https://test.pypi.org/simple"
default = true
```

There is no explanation what `default = true` means. Is that required to use the index? Why?
