### ISSUE TITLE
There is no available `triton` in windows but it required when I download torch==2.1.0+cu118

### ISSUE THREAD

**Issue by MrXnneHang** [astral-sh/uv#12460]
### Summary

```toml
[project]
name = "Auto-Caption-Generate-Offline"
version = "2.4.0"
requires-python = "==3.11.11"
dependencies = [
    "torch==2.1.0",
    "torchaudio==2.1.0",

]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", marker = "platform_system != 'Darwin'"  },
]
torchaudio = [
  { index = "pytorch-cu118", marker = "platform_system != 'Darwin'"  },
]

```

error:

```shell
PS D:\program\Auto-Caption-Generator-Offline> uv sync
Using CPython 3.11.11
Removed virtual environment at: .venv
Creating virtual environment at: .venv
Resolved 13 packages in 2.13s
error: Distribution `triton==2.1.0 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're on Windows (`win_amd64`), but `triton` (v2.1.0) only has wheels for the following platforms: `manylinux_2_17_x86_64`, `manylinux2014_x86_64`
```

list of tritons: [https://download.pytorch.org/whl/triton/](https://download.pytorch.org/whl/triton/)

### Platform

windows11 x86_64

### Version

uv 0.6.9 (3d9460278 2025-03-20)

### Python version

3.11.11
