### ISSUE TITLE
duplicate cache: uv add cannot use cache from uv pip install

### ISSUE THREAD

**Issue by xiejx5** [astral-sh/uv#12480]
### Summary

Duplicate packages from uv add and uv pip commands. Minimum steps to reproduce:

`
uv cache clean
uv venv test
# first download
uv pip install numpy --directory test
uv init --bare
# second download, did not use cache
uv add numpy
`

### Platform

Linux 4.18.0

### Version

uv 0.6.10

### Python version

Python 3.13.2

**Comment by charliermarsh** [comment]
I can take a look.

**Comment by Aditya-PS-05** [comment]
@charliermarsh , can I take a look at this issue and solve it?

**Comment by charliermarsh** [comment]
I have an idea on what the problem is but I think it will be challenging to solve correctly. (There’s an “easy” fix that will regress a different, small bug.)

**Comment by charliermarsh** [comment]
Oh sorry. This is because in `uv sync` (or `uv add`), we require hashes to be present. But in `uv pip install`, we don't. So we have to re-download the wheel to hash it.

**Comment by xiejx5** [comment]
Thank you for the answer. Is there any setting to avoid these duplicates? As uv pip can use the cache from uv add.

**Comment by charliermarsh** [comment]
I think we could plausibly add `--generate-hashes` to `uv pip install` which would avoid this problem.

**Comment by xiejx5** [comment]
> I think we could plausibly add `--generate-hashes` to `uv pip install` which would avoid this problem.

Thank you. Unfortunately, `--generate-hashes` only exists in `uv pip compile` while not `uv pip install`.

Anyway, thanks a lot for your development and reply.

**Comment by LoSealL** [comment]
What about add from an external index? Such as torch. For instance there are two projects both requires torch==2.7.1:

```toml
# pyproject.toml
dependencies = ["torch>=2.7.1"]

[tool.uv.sources]
torch = { index = "pytorch" }
torchaudio = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
```

```shell
# project 1
uv add torch  # download and make a cache in `archive-v0`
```

```shell
# project 2
uv add torch  # download and make another cache in `archive-v0`
```
