### ISSUE TITLE
Allow `--constraints` in `uv sync`

### ISSUE THREAD

**Issue by D3nn3** [astral-sh/uv#12490]
### Summary

In the past couple of releases, the support for the `--constraints` flag was added in multiple places to allow an external constraint file when e.g. adding a dependency. What my team is missing is the ability to define a constrain file for `uv sync`.

### Example

In a project using Airflow we have airflow as an dependency which requires a constraint file. Currently the following isn't possible:

```bash
uv sync --constraint https://url.com/path/to/remote/constraint/file/constraints.txt
```

This would allow us to easily update all dependency (e.g. also dev dependencies) respecting the constraints without the need for workarounds.

**Comment by zanieb** [comment]
We're generally hesitant to support constraints in this form. We added them in `uv add` for import purposes. Allowing them in arbitrary `uv lock` and `sync` operations feels contrary to encoding constraints into the project. e.g., would you expect the lockfile to change here?

**Comment by D3nn3** [comment]
Hey @zanieb , thanks for getting back to me! I totally get your point. Let me maybe explain in more detail what challenges we're facing (which is why I created the ticket). It could also be that our challenges can be solved in a different way 🙂 

Like probably a lot of people opening issues regarding external constraint files, we also have a project for defining airflow DAGs. Our `pyproject.toml` file has airflow as an dependency and the dependency section might look something like this:

```
...

dependencies = [
    "apache-airflow == 2.10.3"
]

[dependency-groups]
dev = [
    "ruff ~= 0.11"
]

...
``` 

Doing a `uv sync` in the project without a `uv.lock` file present will (currently) install `apache-airflow-providers-http==5.2.1`. This might become a problem, since the official Docker image of airflow v2.10.3 (which runs in our Production environment) uses `apache-airflow-providers-http==4.13.2`. Because of the major version bump, breaking changes are expected which in our case already caused a problem.

Versions used for dependencies in the Docker image are specified in external constraint files by airflow, e.g. https://raw.githubusercontent.com/apache/airflow/constraints-2.10.3/constraints-3.9.txt.

When deploying to Production, we just update the DAGs, which are normal Python modules mounted into the Docker container with a volume (which is the recommended way proposed by airflow). Developing DAGs locally and testing them therefore becomes a bit of a challenge since versions of dependencies differ and unexpected errors on Production can occur like mentioned above.

We are facing two challenges:
- We'd like to install required dependencies while respecting the constraints defined in the external constraint file by airflow (without listing all of them in our pyproject.toml). This is to guarantee that versions of dependencies are exactly the same as in our Production environment.
- We'd like a way to easily update unrelated dependencies (like ruff in the example) by e.g. doing something like `uv sync` or `uv lock --upgrade` while respecting the constraints defined in the external constraint file.

The idea we had was to add the `--constraint` flag to e.g. `uv sync`, since in the last couple of release it was added to other commands as well.

Regarding your question if we'd expect the lockfile to change here: The behavior shouldn't actually differ from the current one! We imagine the `--constraint` flag to be an additional source for version constraints when checking for compatible versions of dependencies. E.g. in the example mentioned above, uv would see that `apache-airflow-providers-http` is required as a dependency by airflow, would check the version constraints in the `pyproject.toml` file and additionally from the constraint file and pick the appropriate version (if one exists). Essentially: it would be the exact same behavior as if we'd copy/paste the constraints from the required dependencies from the external constraint file into the `pyproject.toml` file.

As far as we know there is a workaround involving exporting the dependencies in the `pyproject.toml` file into a `requirements.txt` file and installing them via pip which supports the constraint flag. But this workaround is a bit cumbersome and an easier (and uv native) solution would be highly appreciated!

**Comment by jabbera** [comment]
I've recently run into this issue as well but for a totally different reason. We are an enterprise, and we publish a global constraint file that everyone in the company uses. It's essentially a ban list for packages, copied below. We systematically create the [PIP,UV]_CONSTRAINT environment variable for everyone doing python work so they are, by default, opted into our constraint list but can easily opt out if needed. We need lockfiles to respect this as it's a really convenient way for us to fix a bad package company wide, really quickly, without needing to publishing a package that everyone needs to upgrade to get the latest version of.

```
pyodbc!=5.0.0,!=4.0.34
bokeh!=3.3.*  # https://github.com/bokeh/bokeh/issues/13521
pydantic!=2.5.0 # https://github.com/pydantic/pydantic/issues/8096
osqp!=1.0.2 # https://github.com/osqp/osqp/issues/728. Busted wheels
```

**Comment by emiliadecaudin** [comment]
Hi all; as a heavy Airflow user, I'm wrestling this question as well. One solution that I'd be interested in would be to support putting constraint URLs directly in `tool.uv.constraint-dependencies`. This would allow having a fixed reference to a constraints URL (which could be compiled to an actual list of constraints in uv.lock) and obviate the need to paste a whole list of constraints into `tool.uv.constraint-dependencies`, as well as the worry that running `uv lock --upgrade` will undo any constraints added using `uv add --constraint`.

**Comment by guilhem-dvr** [comment]
I've faced the challenges described by @D3nn3 multiple times, in the past with a pyspark project running in Databricks, and now in an airflow project running in Cloud Composer. Both services provide constraints files/lists:

- Databricks Runtime images: https://docs.databricks.com/aws/en/release-notes/runtime/16.4lts#installed-python-libraries
- Cloud Composer images: https://cloud.google.com/composer/docs/composer-versions#images-composer-3

A solution could be to manually lock the constraints in the project, but:

1. it's a tedious process - those constraints files can be fairly large - and it forces the user to install all the dependencies when developing
2. it makes upgrading a service version much harder

Having at least a `--constraint` option on `uv lock` would be convenient to a. safely upgrade dependencies and b. check that a project still matches some external constraints.

Edit: I just found the [constraint-dependencies](https://docs.astral.sh/uv/reference/settings/#constraint-dependencies) setting, which solves most of the issues I faced. It would be nice to be able to populate/update this constraint list from a constraint file.

**Comment by Logan-Pageler** [comment]
I'm also in favor of @emiliadecaudin idea of supporting constraint urls with `tool.uv.constraint-dependencies` .

We use a constraint file to mange a bunch of jupyter environments and a cluster of computers for parallel computing. We want our workspaces to follow this constraint file, but currently we just copy and paste it into the `pyproject.toml` file when we make updates. It would be very useful to not have to do this as its easy to forget.

**Comment by prakharcode** [comment]
Just here to add, that I am facing the same problem. 
Adding a large constraint file (copy pasted) from airflow to the `pyproject.toml` is very prone to errors. 

Supporting a file based constraints would be ideal. Currently there is a way to do `uv pip install -r requirements.txt --constraints constraints.txt` but this is not nice and 'non' uv way.

**Comment by zanieb** [comment]
@prakharcode sounds like you could use https://github.com/astral-sh/uv/issues/16508

**Comment by hvanvoorhis** [comment]
or maybe 
```
[tool.uv]
constraint-dependency-urls = ['http://airflow...','http://databricks']
``` 
then we can specify the external constraint URL like Databricks, airflow etc use.

**Comment by hterik** [comment]
Pointing to external urls sounds a bit dodgy. Just having a way to point [`constraint-dependencies`](https://docs.astral.sh/uv/reference/settings/#constraint-dependencies) to a local `constraints.txt` file would be a huge improvement. It's easy to download and checkin a copy of the airflow provided constraints.

**Comment by jabbera** [comment]
> Pointing to external urls sounds a bit dodgy.

It's how UV_CONSTRAINT and PIP_CONSTRAINT work today. It doesn't seem any less dodgy?

**Comment by hterik** [comment]
> > Pointing to external urls sounds a bit dodgy.
> 
> It's how UV_CONSTRAINT and PIP_CONSTRAINT work today. It doesn't seem any less dodgy?

Ok, if that's the case then that has already been settled earlier. I was also under the incorrect impression that this could affect reproducibility, but in the end it's always the `uv.lock` that wins when using `sync --locked`, so this is less of a concern.

Dodgy or not, if avoiding remote files in favour of local only files would reduce the scope of this implementation, most of the value will still be achieved. 😌

**Comment by torran-g** [comment]
We migrated from Poetry to uv specifically because Poetry forces you to manually replicate all Airflow constraint pins in pyproject.toml (since it has no -c constraints.txt support). uv's uv pip compile --constraint <url> solved that cleanly for generating our MWAA requirements.txt.

The remaining gap is uv sync/uv lock: to keep the local dev environment aligned with MWAA we've had to inline ~114 version pins as constraint-dependencies in pyproject.toml — the exact same problem we left Poetry to escape. The workaround is also arguably more contrary to the principle of "encoding constraints into the project" than a URL reference would be: a URL makes the external dependency explicit and single-sourced, while inlining 114 pins obscures where they came from and makes them immediately stale on the next Airflow release.

A constraint-dependencies-url (or equivalent) in [tool.uv] that accepts the same URLs uv pip compile --constraint already handles would close the loop.

**Comment by jabbera** [comment]
The constraint needs to be applied at lock time IMO but makes perfect sense as a feature there. Hopefully one day!

**Comment by bckohan** [comment]
+1 support for this. I'd also like to get tox/nox out of all my CI and simply rely on uv/justfiles. The only thing really standing in the way is not being able to do something like:

``uv run --exact --isolated --constraint ./constraints.txt pytest``

I can do this using the pip interface but when I do that I start reimplementing something that looks a lot like tox/nox.

**Comment by zanieb** [comment]
@bckohan can you explain what the constraints are for in your use-case?

**Comment by bckohan** [comment]
> [@bckohan](https://github.com/bckohan) can you explain what the constraints are for in your use-case?

Outputs from the github action strategy matrix. This is for middle stream packages that have to be tested against a wide range of dependency version combinations. So for example, my package might support Django 4.2-6 - but I need to run tests against each of those minor lines to reliably claim that in my classifiers.

**Comment by zanieb** [comment]
Thanks that's really helpful! Can you explain how you generate that file / matrix or link to an example?

**Comment by bckohan** [comment]
Certainly - I have something like this in mind:

```yaml

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: py311-dj42
          python-version: "3.11"
          constraints: |
            Django==4.2.*
        - name: py311-dj51
          python-version: "3.11"
          constraints: |
            Django==5.1.*
            sqlparse<0.5
      
    env:
      CONSTRAINTS: ${{ matrix.constraints }}
    steps:
    - name: Run Tests
       shell: bash
       run: |
         printf "%s\n" "$CONSTRAINTS" > constraints.txt
         uv run --exact --isolated --group test --constraint constraints.txt pytest
```

I can make this work with the pip interface but then I start having thoughts like "wait where is the venv again and am I definitely using it?".

**Comment by zanieb** [comment]
Would you be willing to define your constraints in groups in the `pyproject.toml`? (just trying to explore your needs a bit more here)

**Comment by bckohan** [comment]
For anyone else stumbling across this, @zanieb is suggesting something like:

```yaml

jobs:
  test-linux:
    runs-on: ubuntu-latest
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        django-version:
          - 'dj42'
          - 'dj52'
          - 'dj60'
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      DJANGO_VERSION: ${{ matrix.django-version }}
    steps:
      # .... elided
    - name: Run Unit Tests
       run: |
         uv run --exact --isolated -p "$PYTHON_VERSION" --group "$DJANGO_VERSION" pytest
```

with ``pyproject.toml``:

```toml
[project]
dependencies = [
    "Django>=4.2,<6.1",
]

[tool.uv]
package = true
conflicts = [
  [
    { group = "dj42" },
    { group = "dj52" },
    { group = "dj60" },
  ],
]

[dependency-groups]
# for CI and testing
dj42 = [
    "Django~=4.2",
]
dj52 = [
    "Django~=5.2",
]
dj60 = [
    "Django~=6.0; python_version >= '3.12'",
]
```

Yeah this is fine actually. There's something about doing this with constraints that maps more cleanly into my brain and this is a smidge more verbose but I can't really poke any functional holes in this so I am happy with it! thank you @zanieb

**Comment by MrTango** [comment]
Until there is a buildind solution, i wrote a small helper which can read constraints from local or remote and write all constraints into `tool.uv.constraint-dependencies`. It also allows overwriting some of those constraints with a local custom-constraints.txt.
https://pypi.org/project/uv-import-constraint-dependencies/
Hope that might help some people. I know it would be best, to not have to relay on constraints files, as packages should define clean dependendcies and let UV do it's job, but real life looks different out there and bigger projects have sometimes big constraints.txt files.

**Comment by hy144328** [comment]
Just to join the choir, sharing my user story here, too.

Our data platform team lets us run workloads (Airflow, Spark, etc.) by providing container images, respectively.
The data platform team provides base images with pre-existing Python dependencies that we extend by installing our own Python libraries, dependencies, etc.
We manage multiple such Python libraries as UV projects in a mono-repo.
Ideally, we want dependency resolution in a convenient way such that (i) base image constraints become available in UV projects, and (ii) UV project dependencies consistent with the base image are available when building another container image for deployment.
(ii) is important for production because the data platform is ultimately operated by another team, and we want to stick as closely as possible to their supported base image.
(i) is important for development because we want to have a local environment that is both faithful and lean, the latter for rapid iterations and unit tests.

Re base image -> UV project (i), we consider `uv.lock` to be the pivot point in order to be consistent between all development and production environments.
In general, we are happy to freeze the installed dependencies in the base image and to list the constraints under `tool.uv.constraint-dependencies`:
```
docker run --platform=linux/amd64 <base image> pip list --format freeze | sed 's/.*/    "&",/'
```
`uv lock` will create a consistent `uv.lock` file, or point out inconsistent dependencies.
As mentioned, it would improve the quality of life to be able to skip the manual copy and paste into `constraint-dependencies`.
For our user story, it would not be useful to have commands to manage individual constraints because it is not evident if indirect constraints are to be removed or not.
If we bump the version of our base image, we will instead perform another full freeze, and replace `constraint-dependency` as a whole.
So it would be enough to have uv commands to write/overwrite a constraints file to `constraint-dependencies`, or to drop `constraint-dependencies` entirely.
As a next step, I am wondering about the case of one UV project complying to multiple base images.
It does not make sense to expect one `uv.lock` to be able to satisfy multiple freezes because it is very likely that the equality constraints are mutually exclusive.
It would be nice (i) to have multiple, optional constraint _groups_ in `pyproject.toml`, and (ii) to generate custom lock files by specifying up to one constraint group.
But this is getting too complicated.
Long story short, we are happy with `constraint-dependencies` for a single base image and accept a little toil.

Re UV project -> base image (ii), I want to mention for completeness that I have opened a separate issue #17226 .
In short, `uv export`, unlike `uv pip compile`, does not allow to fine tune to the target platform if you decide to pass dependencies from UV project to base image via `requirements.txt`.
No need to go into detail here but this is the dual of the user story here.

**Comment by SebastianJL** [comment]
> As far as we know there is a workaround involving exporting the dependencies in the `pyproject.toml` file into a `requirements.txt` file and installing them via pip which supports the constraint flag. But this workaround is a bit cumbersome and an easier (and uv native) solution would be highly appreciated!

@D3nn3 I was wondering how you install the dependencies in the Airflow container without using pip? I couldn't get uv to install the dependencies in the correct location. Do you have an example script?

**Comment by D3nn3** [comment]
Hi @SebastianJL !

I can share some details about how we set up and manage our Airflow server. One thing worth noting upfront: we currently run Airflow using `uv` on a dedicated VM — no Kubernetes or anything similar.
For this, we maintain a dedicated Git repository containing a `pyproject.toml` and a `uv.lock` file.

Our `pyproject.toml` look something like this:

```toml
[project]
name = "airflow-server"
version = "1.0.0"
requires-python = ">=3.11.15,<3.12" # Must match the Python version defined in the Constraints file below!
...


####################
### Dependencies ###
####################

dependencies = [
    # Must match the Airflow version defined in the Constraints file below!
    "apache-airflow==3.1.8",
    # Versions for the following packages are provided by the constraints section.
    "apache-airflow-providers-docker",
    "apache-airflow-providers-google",
    "apache-airflow-providers-http",
    ...
]

###################
### Constraints ###
###################

[tool.uv]
# Constraints to apply when resolving the project's dependencies.
# These restrict which versions of dependencies are selected during resolution.
# Note: listing a package here as a constraint does not trigger its installation —
# it must be requested elsewhere in the project's first-party or transitive dependencies.
#
# Airflow version: 3.1.8
# Python version: 3.11
# Constraints file URL: https://raw.githubusercontent.com/apache/airflow/constraints-3.1.8/constraints-3.11.txt
constraint-dependencies = [
    ... # Copied directly from the Constraints file linked above
]
```

After running `uv sync`, all Airflow commands can be invoked via `uv` — for example: `uv run airflow webserver --port 8080`.

This approach lets us manage everything through `uv` and gives us full control over our dependencies, both core Airflow ones and any additional optional packages. Updating Airflow and/or Python is fairly straightforward with this setup. The only tedious part is copying and pasting the dependencies from the constraints file, but since we don't do this often, it's manageable. It would be great to have the option to simply link to a remote constraints file instead. Perhaps something worth considering  @zanieb ?

Hope this helps!

**Comment by SebastianJL** [comment]
@D3nn3 ahh, thank you very much😊. Very ilucidating. I somehow inferred from my own situation that you would be using Docker.
Is it a lot of hassle to setup Airflow without the Docker Image?

**Comment by D3nn3** [comment]
> [@D3nn3](https://github.com/D3nn3) ahh, thank you very much😊. Very ilucidating. I somehow inferred from my own situation that you would be using Docker. Is it a lot of hassle to setup Airflow without the Docker Image?

You'd need to ask our IT department 😄 That said, I'm fairly confident you can create custom Docker images using the official ones as a base image without too much hassle. Since we don't have it set up this way, I can't provide an example, but it seems like the following link might be of help though: https://airflow.apache.org/docs/docker-stack/build.html#example-of-adding-pypi-package-with-uv

**Comment by SebastianJL** [comment]
Should we maybe open a new issue where we could discuss allowing a file (local or remote) in `tool.uv.constraint-dependencies`? The ideas here are many, but they do not fit the original question in the issue about adding a `--constraints` flag to `uv sync`.

**Comment by tamird** [comment]
I hit the same gap while trying to make an existing project the
canonical uv workspace under a repo-wide constraints file.

With uv 0.11.28:

```toml
# pyproject.toml
[project]
name = "repro"
version = "0"
dependencies = ["setuptools"]
```

```text
# constraints.txt
setuptools<79
```

```console
$ UV_CONSTRAINT="$PWD/constraints.txt" uv lock --upgrade
$ grep -A2 'name = "setuptools"' uv.lock
name = "setuptools"
version = "83.0.0"
```

`uv lock --constraint constraints.txt` is not accepted either.

The environment reference says `UV_CONSTRAINT` is equivalent to the
constraints argument, so I expected the project lock to satisfy
`setuptools<79`. If project locking intentionally does not consume
external constraints, a checked-in constraints-file input for `uv lock`
would solve this without copying the file into
`tool.uv.constraint-dependencies`. Otherwise this looks like a
project-lock environment-variable bug.

The project-lock path already has the needed resolver hook:
`LockOperation::with_constraints` feeds external constraints into the
resolver, and `uv add` already uses it. `uv lock` is missing the
CLI/settings plumbing and the constraints-file read before it creates the
lock operation. Because external constraints are not recorded in
`uv.lock`, a non-empty input also has to force re-resolution instead of
accepting an otherwise current lock.

A local patch that wires only `--constraint`/`UV_CONSTRAINT` through
that existing path passes an existing-lock regression: it first locks
`anyio==3.7.0` unconstrained, then re-locks with `idna<3.4` and
updates `idna` from 3.6 to 3.3. The adjacent existing
`tool.uv.constraint-dependencies` lock test still passes.
