### ISSUE TITLE
`uv sync --dry-run --reinstall` does not check access to indexes

### ISSUE THREAD

**Issue by LewisGaul** [astral-sh/uv#12493]
### Summary

I'm testing out using a custom index with the following config:
```toml
[project]
name = "test-pkg"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["pyyaml"]

[[tool.uv.index]]
name = "foo-pypi"
url = "https://.../foo-pypi-local/simple"
explicit = true

[tool.uv.sources]
pyyaml = { index = "foo-pypi" }
```

I can then install `pyyaml` from the "foo" index with: `UV_INDEX_FOO_PYPI_PASSWORD=$TOKEN uv sync` as expected (and `--dry-run` works fine here too).

If I try to reinstall the package without the token being provided this errors, as expected:
```
   > uv sync --reinstall
Resolved 2 packages in 0.75ms
x Failed to download `pyyaml==0.0.1`
  |-> Failed to fetch: `https://.../foo-pypi-local/pyyaml/0.0.1/pyyaml-0.0.1-py3-none-any.whl`
  `-> HTTP status client error (403 Forbidden) for url
      (https://.../foo-pypi-local/pyyaml/0.0.1/pyyaml-0.0.1-py3-none-any.whl)
  help: `pyyaml` (v0.0.1) was included because `test-pkg` (v0.1.0) depends on `pyyaml`
```

However with `--dry-run` there is no indication of the error:
```
   > uv sync --reinstall --dry-run
Discovered existing environment at: .venv
Resolved 2 packages in 0.78ms
Found up-to-date lockfile at: uv.lock
Would download 1 package
Would uninstall 1 package
Would install 1 package
 - pyyaml==0.0.1
 + pyyaml==0.0.1
```

I appreciate this is a bit niche/low priority but thought the issue would be appreciated by a team that has such an impressive attention to detail!

### Platform

RHEL8 x86_64

### Version

uv 0.6.10

### Python version

Python 3.11.4
