### ISSUE TITLE
concurrent `uv run` is very slow even with cache

### ISSUE THREAD

**Issue by terrykong** [astral-sh/uv#12525]
### Summary

Hi team. I've been playing around with `ray`'s new [uv+ray integration](https://www.anyscale.com/blog/uv-ray-pain-free-python-dependencies-in-clusters) and I've been unable to figure out why `uv` is so slow when there are many concurrent actors launched on a ray cluster.

Here is a simple script I've been using to benchmark creating multiple `.venv`s which is my best guess of what's happening on the ray cluster:

```sh
#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $SCRIPT_DIR

if [[ ! -f /usr/bin/time ]]; then
  apt update && apt install -y time
fi

echo "Cleaning up workspaces"
find workspaces -type d -exec rm -rf {} + 2>/dev/null || rm -rf workspaces
mkdir -p workspaces

N=1
foobar() {
for i in $(seq 1 $N); do
    # Create a temporary directory for this iteration
    TEMP_DIR="${SCRIPT_DIR}/workspaces/${i}"
    mkdir -p "$TEMP_DIR"
    cd "$TEMP_DIR"
    rsync -ah $SCRIPT_DIR/pyproject.toml $SCRIPT_DIR/uv.lock $SCRIPT_DIR/foobar $TEMP_DIR/
    uv venv
    /usr/bin/time -v uv run -v echo helloworld 2>&1 | while IFS= read -r line; do echo "[$(date '+%Y-%m-%d %H:%M:%S')] $line"; done | tee $SCRIPT_DIR/workspaces/log-$i &
done

echo waiting....
wait
}
export -f foobar

time foobar 2>&1 | tee $SCRIPT_DIR/workspaces/log
echo "done!"

echo cleaning up...
for i in $(seq 1 $N); do
    ( rm -rf $SCRIPT_DIR/workspaces/${i} ; echo deleted $i ) &
done
echo 'waiting.... for cleanup'
wait
echo 'alllll done'
```

When I run with `N=1` it takes about 3.72 seconds to execute the `uv run` command, but when I set `N=32` all the `uv run`s take about 56 seconds to run which seems to suggest they are all waiting on something? The debug logs also show a large parse here (between `23:12:47` and ` 23:13:28`):
```
[2025-03-27 23:12:44] DEBUG File already exists (initial attempt), overwriting: /test-workspaces/workspa
ces/21/.venv/lib/python3.12/site-packages/nvidia/__init__.py
[2025-03-27 23:12:44] DEBUG File already exists (subsequent attempt), overwriting: /test-workspaces/work
spaces/21/.venv/lib/python3.12/site-packages/nvidia/__init__.py
[2025-03-27 23:12:47] DEBUG File already exists (subsequent attempt), overwriting: /test-workspaces/work
spaces/21/.venv/lib/python3.12/site-packages/opencensus/common/__init__.py
[2025-03-27 23:13:28] Installed 149 packages in 51.85s
[2025-03-27 23:13:28]  + aiohappyeyeballs==2.6.1
[2025-03-27 23:13:28]  + aiohttp==3.11.14
```

Here is the pyproject.toml for this dummy `foobar` package:

```toml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foobar"
requires-python = ">=3.10"
version = "0.0.1"
dependencies = [
"torch==2.6.0",
"transformers",
"vllm",
"ray[default]==2.43.0",
]

[tool.setuptools]
packages = ["foobar"]

[project.optional-dependencies]
emoji = [
    "emoji",
]
pyfiglet = [
    "pyfiglet",
]

# NOTE: using symlink b/c ray temp-dir is on diff file system than uv-cache
[tool.uv]
link-mode = "symlink"
```

I'm very interested in using `uv` with ray, but the user experience for folks launching with ray isn't ideal since it takes minutes to just start the job despite having all the dependencies available in the uv cache.

Is this performance expected?

### Platform

Ubuntu 22.04.5 LTS (Jammy Jellyfish)

### Version

uv 0.6.8

### Python version

Python 3.12.9
