### ISSUE TITLE
Even with `uv sync --no-dev`, development dependencies are still installed when workflow executes.

### ISSUE THREAD

**Issue by WitherZuo** [astral-sh/uv#12558]
With the documentation of uv, I used `uv sync --no-dev` in order to not install the development dependencies while the GitHub Actions workflow is running, however the switch `--no-dev` doesn't seem to work while the workflow is running, with this switch it still installs all of the dependencies including the development dependencies. using `uv sync --no-dev` locally works perfectly fine and does not install development dependencies when installing dependencies.

## GitHub Actions workflow and log:  

For my project, `Ruff` is the only dev dependency.  

- **`pyproject.toml` file:**  

```toml  
[project]
name = "newsphoto"
version = "1.0.0"
description = "NewsPhoto everyday."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pangu>=4.0.6.1",
    "playwright>=1.51.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
```

- **GitHub Actions workflow file `main.yml`:**    

<details>
<summary>Click here to expand.</summary>  

```yaml  
name: Create NewsPhoto
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Greeting text:'
        required: false
        default: '……'
        type: string
      style:
        description: 'NewsPhoto style:'
        required: true
        default: 'light'
        type: choice
        options:
          - light
          - dark
          - springfestival

jobs:
  generate_newsphoto:
    name: Generate NewsPhoto
    runs-on: windows-latest
    steps:
    - name: Set timezone to Asia/Shanghai
      uses: WitherZuo/set-timezone@v1.0.0
      with:
        timezoneWindows: "China Standard Time"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: WitherZuo/NewsPhoto

    - name: Install uv and Python.
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.10"
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"

    - name: Install dependencies
      run: uv sync --no-dev

    - name: Install Pandoc
      run: choco install -y pandoc

    - name: Create markdown sources and convert to HTML
      run: |
        uv run main.py --greeting "${{ inputs.greeting }}" --style ${{ inputs.style }}
        Get-ChildItem -Path .\sources\
        Get-ChildItem -Path .\outputs\

    - name: Generate screenshot
      run: |
        uv run save-as-image.py --browser chrome
        Get-ChildItem -Path .\outputs\

    - name: Upload NewsPhoto - Webpage
      uses: actions/upload-artifact@v4
      with:
        name: newsphoto-webpage
        path: outputs/NewsPhoto.html

    - name: Upload NewsPhoto - Image
      uses: actions/upload-artifact@v4
      with:
        name: newsphoto-image
        path: outputs/NewsPhoto.png
```

</details>  

- **Workflow log:**  

**For full log**, you can visit **[here](https://github.com/WitherZuo/NewsPhoto/actions/runs/14153678743/job/39650104473)**.  

<details>
<summary>Click here to expand.</summary>  

```
Sun, 30 Mar 2025 07:05:44 GMT
Run uv sync --no-dev
Sun, 30 Mar 2025 07:05:45 GMT Using CPython 3.13.2 interpreter at: C:\hostedtoolcache\windows\Python\3.13.2\x64\python.exe
Sun, 30 Mar 2025 07:05:45 GMT Creating virtual environment at: .venv
Sun, 30 Mar 2025 07:05:45 GMT Resolved 12 packages in 1ms
Sun, 30 Mar 2025 07:05:46 GMT Downloading playwright (33.2MiB)
Sun, 30 Mar 2025 07:05:52 GMT  Downloaded playwright
Sun, 30 Mar 2025 07:05:52 GMT Prepared 10 packages in 7.06s
Sun, 30 Mar 2025 07:05:52 GMT Installed 10 packages in 52ms
Sun, 30 Mar 2025 07:05:52 GMT  + certifi==2025.1.31
Sun, 30 Mar 2025 07:05:52 GMT  + charset-normalizer==3.4.1
Sun, 30 Mar 2025 07:05:52 GMT  + greenlet==3.1.1
Sun, 30 Mar 2025 07:05:52 GMT  + idna==3.10
Sun, 30 Mar 2025 07:05:52 GMT  + pangu==4.0.6.1
Sun, 30 Mar 2025 07:05:52 GMT  + playwright==1.51.0
Sun, 30 Mar 2025 07:05:52 GMT  + pyee==12.1.1
Sun, 30 Mar 2025 07:05:52 GMT  + requests==2.32.3
Sun, 30 Mar 2025 07:05:52 GMT  + typing-extensions==4.13.0
Sun, 30 Mar 2025 07:05:52 GMT  + urllib3==2.3.0

.......  

Sun, 30 Mar 2025 07:06:16 GMT
Run uv run main.py --greeting "……" --style dark
Sun, 30 Mar 2025 07:06:16 GMT Downloading ruff (10.8MiB)
Sun, 30 Mar 2025 07:06:19 GMT  Downloaded ruff
Sun, 30 Mar 2025 07:06:19 GMT Installed 1 package in 3ms
```

</details>

**Comment by charliermarsh** [comment]
By default, `uv run` will ensure that your project environment and lockfile are up-to-date. By default, `dev` dependencies are enabled (see: `https://docs.astral.sh/uv/reference/settings/#default-groups`). So if you use `uv run`, we will install the `dev` dependencies if they're missing. `uv run` does not "remember" what you passed to `uv sync` -- it's not a stateful command.

A few options:

- Remove `dev` from `default-groups`, so `dev` dependencies always need to be enabled explicitly (`uv run --group dev`).
- Pass `--no-sync` to `uv run` (`uv run --no-sync`) so that `uv run` doesn't install new dependencies.

**Comment by DimasInchidi** [comment]
> Remove `dev` from `default-groups`, so `dev` dependencies always need to be enabled explicitly (`uv run --group dev`).

\cc @charliermarsh 

is there any env var i can use for not passing `--no-sync` for each `uv run` after `uv sync`? it could be useful to make `uv sync` feels like stateful for this kind of use case.

**Comment by zanieb** [comment]
You can use `UV_NO_SYNC`

**Comment by zanieb** [comment]
You can also use `UV_NO_DEV` instead of `--no-dev`.

**Comment by bartektrybala** [comment]
In your case you can just add this to the pyproject.toml:
```
[tool.uv]
# This prevents 'uv run' and 'uv sync' from including dev dependencies by default
default-groups = []
```

**Comment by oPromessa** [comment]
Although this issue is Closed ... the mentioned solution is not working for me.

I have a monorepo with a tool check_live_metadata which depends on osxphotos from Pypi. 
For which I also have a local repository for osxphotos as I'm also a contributor.

As mentioned on this issue, my goal is similar and I would like to be able to have two environments:
* dev: where I source osxphotos locally and --editable from `"osxphotos @ file:///${PROJECT_ROOT}/../osxphotos",`
* prod: where I would like uv sync to get osxphotos from PyPi official site.

What am I doing wrong?

```
-- monorepo
--- pyproject.toml
--- tools/check_live_metadata
------ pyproject.toml
-- osxphotos
```

### macOS 26.4.1 25E253

<details>
<summary>

### Main pyproject.toml

</summary>

```toml
[project]
name = "photos-tools"
version = "0.3.3"
requires-python = ">=3.12"
dependencies = []
# This prevents 'uv run' and 'uv sync' from including dev dependencies by default
default-groups = []

[tool.uv]
package = false
constraint-dependencies = [
    "pyobjc-framework-avfoundation>=12.0",
    "pyyaml>=6.0.2",  
]

[tool.uv.workspace]
members = [
    "tools/check_live_metadata",
]

[dependency-groups]
dev = [
    "osxphotos @ file:///${PROJECT_ROOT}/../osxphotos",
    "black",
]

```

</details>

<details>
<summary>

### tools/check_live_metadata/pyproject.toml

</summary>

```toml
[project]
name = "check_live_metadata"
version = "0.3.3"
description = "check_live_metadata."
requires-python = ">=3.12"
dependencies = [
    "click",
    "osxphotos",
]

[project.scripts]
check_live_metadata = "check_live_metadata.check_live_metadata:main"

# Use hatchling build backend
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Required, Specify folder name, if different from tool_name
[tool.hatch.build.targets.wheel]
packages = ["check_live_metadata"]
```
</details>

### Install DEV: installs commands work fine

* using uv 0.11.6

```bash
$ uv venv --clear --python 3.13
Using CPython 3.13.13 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate

$ uv sync --all-packages --group dev --editable --python 3.13
Resolved 171 packages in 454ms
Installed 148 packages in 488ms
 + annotated-types==0.7.0
(...)
 + check-live-metadata==0.3.3 (from file:///Users/user/Documents/GitHub/Export/tools/check_live_metadata)
(...)
 + osxphotos==0.75.9 (from file:///Users/user/Documents/GitHub/osxphotos)
```

### Install PROD 

* using uv 0.11.6
* I rename ../osxphotos  to ../DUMMY to prevent using the local copy.

```bash
$ uv venv --clear --prompt Apps /Users/user/Pictures/Pictures/Apps/.venv --python 3.13
Using CPython 3.13.13 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: /Users/user/Pictures/Pictures/Apps/.venv
Activate with: source /Users/user/Pictures/Pictures/Apps/.venv/bin/activate

$  uv sync --all-packages --no-editable --python /Users/user/Pictures/Pictures/Apps/.venv
error: Distribution not found at: file:///Users/user/Documents/GitHub/osxphotos
$
```

**Comment by charliermarsh** [comment]
Your default-groups is in the wrong table. I think you want something like:

```toml
[tool.uv]
package = false
default-groups = []

[dependency-groups]
dev = [
  "osxphotos",
  "black",
]

[tool.uv.sources]
osxphotos = { path = "../osxphotos", editable = true, group = "dev" }
```

Then you can pass the no-sources flag to sync your prof dependencies.
