### ISSUE TITLE
how to install a dynamically updated wheel package

### ISSUE THREAD

**Issue by pplmx** [astral-sh/uv#12594]
### Question

I have a wheel package that is updated daily in a directory named "latest". Each day, the package version is unique. For example, the package URLs look like this:

- https://xxx.url/latest/app-1.0.0+build.20250322.whl
- https://xxx.url/latest/app-1.0.0+build.20250325.whl

I would like to install this wheel using UV sources without having to update the version manually every day. How can this be achieved?

### Platform

Linux

### Version

uv 0.6.11

**Comment by charliermarsh** [comment]
You can probably do something like:

```toml
[[tool.uv.index]]
name = "my-index"
url = "https://xxx.url/latest"
format = "flat"
explicit = true

[tool.uv.sources]
app = { index = "my-index" }
```
