### ISSUE TITLE
Fails to parse `channels` in `environment.yml`

### ISSUE THREAD

**Issue by lnicola** [astral-sh/uv#12596]
### Summary

I have a project with a `requirements.txt` that starts like this:

```yaml
name: pzero
channels:
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.2.0=h57928b3_0
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
```

`uv add -r` and `uv pip install -r` fail with: `error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement at envs/pzero-env2.yml:3:3`, presumably because of the `channels` key.

### Platform

Linux 6.14.0-63.fc42.x86_64 x86_64 GNU/Linux

### Version

uv 0.6.11

PS: I've never really used `uv` or Conda. Not sure if you're planning to support channels.
