### ISSUE TITLE
An error occurs when adding torch from https://download.pytorch.org/whl/cu118

### ISSUE THREAD

**Issue by Ruoc26** [astral-sh/uv#12620]
### Question

uv add torch==2.3.1 --index torch=https://download.pytorch.org/whl/cu118

Using CPython 3.10.0 interpreter at: D:\miniconda3\envs\py3.10\python.exe
Creating virtual environment at: .venv
Resolved 25 packages in 9.54s
error: Distribution `markupsafe==3.0.2 @ registry+https://download.pytorch.org/whl/cu118` can't be installed because it doesn't have a source distribution or wheel for the current platform

hint: You're using CPython 3.10 (`cp310`), but `markupsafe` (v3.0.2) only has wheels with the following Python implementation tag: `cp313`

**Comment by zanieb** [comment]
Have you read the `pytorch` guide? https://docs.astral.sh/uv/guides/integration/pytorch/

**Comment by sglbl** [comment]
> Have you read the `pytorch` guide? https://docs.astral.sh/uv/guides/integration/pytorch/

I think because of markupsafe problem, the guide about using torch with extra's doesn't work anymore.

@CRH26 I solved this issue by adding a compatible markupsafe version:
In my case I use torch with cpu,

`uv add torch==2.5.1+cpu markupsafe==2.1.5 --index https://download.pytorch.org/whl/cpu --index-strategy unsafe-best-match
`
But because of this every other package had conflicts about torch too so I added this to the toml file

```toml
[tool.uv]
index-strategy = "unsafe-best-match"
```

**Comment by fritol** [comment]
i applied what @sglbl said
`pyproject.toml:`

```toml
# pyproject.toml

[project]
name = "my-cuda-pytorch-project"
version = "0.1.0"
description = "A project set up for PyTorch with CUDA support using uv."
requires-python = ">=3.9" # Adjust this to your specific Python version (e.g., >=3.10, >=3.11)

dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "markupsafe==2.1.5", # Pinned to a version known to work for some users
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Configuration for uv
[tool.uv]
index-strategy = "unsafe-best-match" # Crucial for resolving complex dependency conflicts
```

then use 
`uv sync --index-url https://download.pytorch.org/whl/cu124 --extra-index-url https://pypi.org/simple --python 3.13.3`
