### ISSUE TITLE
Strange behavior with tools.uv.sources and tools.uv.index

### ISSUE THREAD

**Issue by khaume** [astral-sh/uv#12666]
### Summary

I'm experimenting with using our private package repository for certain packages.

`pyproject.toml` file:

```toml
dependencies = [
    "private_package>=2.7"
]

[tool.uv.sources]
private_package = { index = "IndexName" }

[[tool.uv.index]]
name = "IndexName"
url = "https://pkgs.dev.azure.com/company/_packaging/ArtifactName/pypi/simple/"
explicit = true
```

when running `uv sync`, it complains about authorization unless I add the environment variables `UV_INDEX_INDEXNAME_NAME` and `UV_INDEX_INDEXNAME_PASSWORD`, just as expected (based on [this discussion](https://github.com/astral-sh/uv/issues/6421#issuecomment-2427738561) even though `UV_INDEX` is defined with a full user:password index url.

However, when I build a Docker image and run `uv sync` in the build instruction, it works when having defined `UV_INDEX`, i.e., it does not require `UV_INDEX_INDEXNAME_NAME` and `UV_INDEX_INDEXNAME_PASSWORD`.

This is also the case when running the resulting docker image.. Inside the container I can do `uv add private_package -U` without having the specific environment variables defined. It works if just `UV_INDEX` is defined.

Is this a windows/ubuntu issue or am I missing something?

### Platform

Windows 11 / Linux 5.15

### Version

uv 0.6.12 (e4e03833f 2025-04-02)

### Python version

Python 3.11
