### ISSUE TITLE
`uv run --with` uses different dependencies when prefixed with `python`

### ISSUE THREAD

**Issue by provinzkraut** [astral-sh/uv#12691]
### Summary

```toml
[project]
name = "uv-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typing-extensions==4.13.1",
    "pytest"
]
```

```python
from importlib.metadata import version

def test():
    assert version("typing_extensions") == "4.13.0"
```

**This works**
`uv run --with=typing-extensions==4.13.0 python -m pytest test.py`

**This fails**
`uv run --with=typing-extensions==4.13.0 pytest test`
Because the version specified in the `pyproject.toml` (`4.13.1`) is used, i.e. the version specified in `--with` is ignored.

I would have expected this to work in both cases, as the documentation states that
> `uv run file.py` is equivalent to `uv run python file.py`

### Platform

Ubuntu 24.10 x86_64

### Version

0.6.12

### Python version

3.13.0
