### ISSUE TITLE
"flat index" option not work for pytorch install

### ISSUE THREAD

**Issue by Cloud0310** [astral-sh/uv#12709]
## bug details
Using uv version 0.6.12, the issue still exists with the following config 
```toml
[tool.uv.souces]
torch = { index = "torch" }
torchvision = { index = "torch" }
[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/torch_stable.html"
format = "flat"
explicit = true
```
with error throwing from `uv add --verbose torch==1.8.0+cu111`
```
DEBUG Searching for a compatible version of torch (==1.8.0+cu111)
DEBUG No compatible version found for: torch
DEBUG Recording unit propagation conflict of torch from incompatibility of (project name)
```
but after following the document about (find-links)[https://docs.astral.sh/uv/reference/settings/#find-links]
with config
```toml
[tool.uv]
find-links = ["https://download.pytorch.org/whl/torch_stable.html"]
```
You can resolve the dependency resolve problem.

### Platform

Ubuntu 20.04

### Version

uv 0.6.12

### Python version

Python 3.8.20

**Comment by charliermarsh** [comment]
Hmm, this locks fine for me:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = ["torch"]

[tool.uv.sources]
torch = { index = "torch" }
torchvision = { index = "torch" }

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/torch_stable.html"
format = "flat"
explicit = true
```

Please include a complete example.
