### ISSUE TITLE
uv bootstraps itself with `required-version`

### ISSUE THREAD

**Issue by juftin** [astral-sh/uv#12787]
### Summary

[required-version](https://docs.astral.sh/uv/reference/settings/#required-version) has been very useful for my team to ensure that we don't get bit by LockFile invalidations when we enable `UV_LOCKED` mode.

> [required-version](https://docs.astral.sh/uv/reference/settings/#required-version)
>>Enforce a requirement on the version of uv.
>>
>>If the version of uv does not meet the requirement at runtime, uv will exit with an error.
>>
>> Accepts a [PEP 440](https://peps.python.org/pep-0440/) specifier, like ==0.5.0 or >=0.5.0.

Rather than exiting with an error, it would be very useful if `uv` was able to bootstrap itself with a compatible version of `uv` to run the command with (likely via `uvx`)

### Example

You have `uv==0.4.0` on your local machine and the following `pyproject.toml`:
```toml
[project]
name = "example"
version = "1.2.3"
description = "Example Project Description"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "apache-airflow==2.8.0"
]

[tool.uv]
required-version = ">=0.6.0,<0.7.0"
```

Rather than raising an error that your `uv` version doesn't comply with the `required-version` when running `uv lock`, `uv` would instead essentially run `uvx "uv>=0.5.0,<0.6.0" lock`
