### ISSUE TITLE
Does UV provide any tooling to make packaging easier in a monorepo?

### ISSUE THREAD

**Issue by risky-rickman** [astral-sh/uv#12795]
### Question

My directory structure looks something like:

- project_a
- project_b
- shared_lib

I want to be able to package project_a and shared_lib together for a deployment. As far as i can tell the only way to do this is to either:

upload shared_lib and project_a to a package repo
create a temp directory with project_a and shared_lib, and then moving project_a's pyproject.toml into the folder root before running my build.  

I'm hesitant to commit to either of these as it feels like there must be an easier way.  I'd love to hear some opinions on how i might accomplish this.

**Comment by zanieb** [comment]
As in, you want `shared_lib` to be vendored into `project_a`'s source distribution or wheel?

**Comment by risky-rickman** [comment]
Yes exactly!

**Comment by Tremeschin** [comment]
This is more of a build backend problem than uv I reckon, it can be done with [hatchling](https://hatch.pypa.io/1.13/config/build/#packages) pretty easily:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "shared_lib",
    "project_a",
    "project_b"
]
```

Running `uv build --wheel` creates a monorepo wheel that includes both projects and itself.

However, I'd advise against this from experience, as each subproject will miss their dist info, importlib metadata fails. Instead, list all projects in the main `[tool.uv.workspace]`, let each project match the monorepo's version in their pyproject:

```toml

[tool.hatch.version]
path = "../shared_lib/version.py"

[project]
dynamic = ["version"]
# ...
dependencies = [
    "shared_lib==1.0.0",
]
```

Then build all projects with `uv build --all`. Can get fancy with build hooks automating the version there, but I digress.
