### ISSUE TITLE
Support named index from `tool.uv.index` When running the `uv add` command

### ISSUE THREAD

**Issue by EATSTEAK** [astral-sh/uv#12796]
### Summary

Currently, the `uv add` command only supports custom indexes by specifying the full URL.
This proposal suggests adding support for named indexes defined in the `tool.uv.index` section, so users don’t have to provide the full index URL every time.
To achieve this, a new `--index-name` parameter would be introduced for `uv add` and other index-related commands.

### Example

```toml
# in pyproject.toml
[[tool.uv.index]]
name = "custom"
url = "https://custom.pypi.index/pypi/simple/"
explicit = true
```

Select a `custom` index using only its name:

**AS-IS**
```bash
uv add custom-dependency --index custom=https://custom.pypi.index/pypi/simple/
```

**TO-BE**
```bash
uv add custom-dependency --index-name custom
```
