### ISSUE TITLE
support `uv tool install --from=. cmd`

### ISSUE THREAD

**Issue by Wurstnase** [astral-sh/uv#12828]
### Summary

It would be nice to install a local package with different scripts in it.

### Example

my project looks like this:

```toml
[project]
name = "toolbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[project.scripts]
toolbox = "toolbox:app"
tb = "toolbox:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

while

```
uv tool install .
```

is working

```
uv tool install --with=. tb
```

is not.
