### ISSUE TITLE
uv-pep440 `VersionSpecifiers::contains` incorrect with prereleases

### ISSUE THREAD

**Issue by baszalmstra** [astral-sh/uv#12834]
### Summary

The `uv_pep440` crate yields an incorrect result when matching `0.1a1` against the version specifier `<0.1a2`.

However, solving the following `pyproject.toml` does correctly yield the correct prerelease version (`0.1a1`):

```toml
[project]
name = "uv-prerelease"
version = "0.1.0"
dependencies = [
    "rpi-kms <0.1a2"
]
```

### Simple reproducer test case

The following test program asserts:

```rust
use uv_pep440::{Version, VersionSpecifiers};

fn main() {
    let version: Version = "0.1a1".parse().unwrap();
    let version_specifier: VersionSpecifiers = "<0.1a2".parse().unwrap();
    assert!(version_specifier.contains(&version));
}
```

### Platform

Windows 11 x86_64

### Version

uv 0.6.14

### Python version

Python 3.13
