### ISSUE TITLE
python_full_version does not match pyproject.toml and .python-version

### ISSUE THREAD

**Issue by oseymour** [astral-sh/uv#12900]
### Question

I'm working on project which requires mmsegmentation and mmcv. With the `pyproject.toml` below, I can run `uv sync` and then `uv add mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.0/index.html` and mmcv 2.0.0 is successfully installed into the environment. `.python-version` contains "3.10".

``` toml
[project]
name = "usfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mmsegmentation>=1.2.2",
    "torch==2.0.1",
]

[tool.uv]
allow-insecure-host = ["https://download.openmmlab.com/mmcv/dist"]
```

I'd like to set up the project to install everything with just `uv sync` and modified the `pyproject.toml` to this:
``` toml
[project]
name = "usfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mmcv==2.0.0",
    "mmsegmentation>=1.2.2",
    "torch==2.0.1",
]

[tool.uv]
allow-insecure-host = ["https://download.openmmlab.com/mmcv/dist"]

[tool.uv.sources]
mmcv = { index = "mmcv" }

[[tool.uv.index]]
name = "mmcv"
url = "https://download.openmmlab.com/mmcv/dist/cpu/torch2.0/index.html"
```

But when I run `uv sync` I get this error:
![Image](https://github.com/user-attachments/assets/e26cda70-3921-43eb-b2e9-9a02b442330b)

**My question is:** Why is this error happening? I've specified Python 3.10. In the error message image I can see that Python 3.10 is being used to initialize the venv. Why is the resolver checking against Python 3.12?

### Platform

Windows 10 x64

### Version

uv 0.6.2 (6d3614eec 2025-02-19)
