### ISSUE TITLE
How to ensure indirect dependency is fetched from internal PyPI index?

### ISSUE THREAD

**Issue by LewisGaul** [astral-sh/uv#13035]
### Question

I have an internal JFrog Artifactory PyPI instance set up, and am interested in avoiding cases of dependency confusion. I've read through and followed the instructions at https://docs.astral.sh/uv/configuration/indexes/#pinning-a-package-to-an-index. The docs and uv config provided are great, however I think there's a case that perhaps isn't fully catered for.

Here's an example `pyproject.toml`:
```toml
[project]
name = "myorg-pkg"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    # Standard dependencies
    "typing_extensions",
    # Internal dependencies
    "myorg-foo",
]

[[tool.uv.index]]
# Set the env var UV_INDEX_MYORG_PASSWORD to use this index.
name = "myorg"
url = "https://.../artifactory/api/pypi/myorg-local/simple"
explicit = true

[tool.uv.sources]
myorg-foo = { index = "myorg" }
```

The problem is: what if a direct internal dependency depends on another internal dependency? In the example above `myorg-pkg` declares a direct dependency on `myorg-foo`, but that package could depend on `myorg-foo-core` as well.

If `explicit = true` is removed from the `myorg` index config then this does achieve the desired behaviour, but `explicit = true` can be useful when you don't want the index to be favoured for all packages. This is the workaround I'm currently using/recommending internally.

I thought maybe the top-level package could declare all internal dependencies (including indirect) in `tool.uv.sources`, even though not ideal since it breaks abstraction. However, it appears this doesn't work without also adding those indirect dependencies to the project's direct dependencies (only top-level packages are installed from an index with `explicit = true`). Should this work?

I realise there's no way for `myorg-foo` to declare that some of its dependencies should be obtained from the same index (or explicitly specify the index), and that any uv project config it might have isn't available at install time... so I'm not sure what the solution should be here.

Note that when dropping `explicit = true`, there can then in theory be the need to pin packages to public PyPI, e.g. with this config:
```toml
[[tool.uv.index]]
# Set the env var UV_INDEX_MYORG_PASSWORD to use this index.
name = "myorg"
url = "https://.../artifactory/api/pypi/myorg-local/simple"

[[tool.uv.index]]
name = "public"
url = "https://pypi.org/simple"
default = true

[tool.uv.sources]
myorg-foo = { index = "myorg" }
typing_extensions = { index = "public" }
```

Of course in practice it's best to just disallow the `typing_extensions` name on the internal PyPI. However, this isn't a solution in all cases - even if we only allow package names that aren't on public PyPI, they could still later be uploaded there (perhaps deliberately as part of a dependency confusion attack).

Furthermore, this uv config has the same problem as above: the `tool.uv.sources` config only applies to direct dependencies! So if `myorg-foo` depended on a package that had a name clash across internal and public PyPI then this would be problematic (would need adding to the direct dependencies, or perhaps consider swapping the index priority order...).

### Platform

Linux x86_64

### Version

uv 0.6.14
