### ISSUE TITLE
How to configure uv to use two azure package registry?

### ISSUE THREAD

**Issue by krasnikau-andrei** [astral-sh/uv#13044]
### Question

My current .netrc
```netrc
machine pkgs.dev.azure.com
    login repo1
    password <PAT1>
machine pkgs.dev.azure.com
    login repo2
    password <PAT2>
```

Part of pyproject.toml
```toml
...

[[tool.uv.index]]
name = "repository1"
url = "https://pkgs.dev.azure.com/repo1/Project1/_packaging/some-other-repo/pypi/simple/"
explicit = true

[[tool.uv.index]]
name = "repository2"
url = "https://pkgs.dev.azure.com/repo2/Project2/_packaging/some-repo/pypi/simple/"
explicit = true
...
```

`repo2` works, but `repo1` shows an authorization error. Suppose I remove the `repo2` credential from .netrc, the `repo1` starts to work. I assume the current .netrc just overrides the previous record. How to make it work together?

Also, I tried a config like this, but no result
```toml
...
[[tool.uv.index]]
name = "repository2"
url = "https://repo2@pkgs.dev.azure.com/repo2/Project2/_packaging/some-repo/pypi/simple/"
explicit = true
...
```

### Platform

Windows 11

### Version

uv 0.6.14 (a4cec56dc 2025-04-09)
