### ISSUE TITLE
optional-dependency not synced with docker

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [astral-sh/uv#13071]
### Summary

I'm running `jupyterlab` within a docker container for my pytorch experiments. All was working well until I added an optional dependency `customlib` which depends on a private index:

**Note: Edited to take [charliermarsh's comment](https://github.com/astral-sh/uv/issues/13071#issuecomment-2824998485) into account**

Here is my (simplified for sake of clarity) setup, I'm not sure whether it is a bug or a misconfiguration:

**Dockerfile**
```Dockerfile
FROM pytorch/pytorch:2.2.0-cpu
COPY --from=ghcr.io/astral-sh/uv:0.6.16 /uv /bin/uv

# Setting working directory to the root user default home directory
WORKDIR /home/app

# Handle cache and target being on different filesystems
ENV UV_LINK_MODE=copy

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-install-workspace --extra jupyter --extra optional
```

**pyproject.toml**
```pyproject.toml
[project]
name = "experiment"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "numpy>=1.22",
    "lightning>=2.4.0",
    "astconfig==0.2.0",
]

[project.optional-dependencies]
jupyterlab = ['jupyterlab>=4.3.3']
optional = ["customlib==1.0.0"]

[tool.uv]
package = true # forces packaging this project

[tool.uv.sources]
customlib = { index = "private" }

[[tool.uv.index]]
name = "private"
url = "https://gitlab.private.com/pypi/simple"
```

**docker-compose.yaml**
```yaml
services:
  jupyter:
    build: . # Builds the image from the Dockerfile in the current directory
    image: app:latest
    hostname: "${HOSTNAME}" # environment variable defined in your .profile for instance
    command: ["uv", "run", "--with", "jupyter", "jupyter", "lab", "--port=${JUPYTERLAB_PORT}", "--ip=${HOSTNAME}", "--allow-root", "--no-browser"]
    ports:
        - ${JUPYTERLAB_PORT}:${JUPYTERLAB_PORT}
    environment:
      JUPYTERLAB_PORT: ${JUPYTERLAB_PORT}
    volumes:
      - .:/home/app
      - /home/app/.venv
    shm_size: '1g'
    env_file:
      - .env # Load environment variables from .env file which includes keys from the private index
```

After creating the container from scratch
```bash
docker compose build --no-cache
```

The dependencies resolver of `uv` tries to search `wheel` into the private index, while it should be fetched from default Pypi.
```
0.386   × Failed to download `wheel==0.43.0`
0.386   ├─▶ Failed to fetch:
0.386   │   `https://gitlab.private.com/api/pypi/files/<random-key>/wheel-0.43.0-py3-none-any.whl`
0.386   ╰─▶ HTTP status client error (401 Unauthorized) for url
0.386       (https://gitlab.private.com/api/pypi/files/<random-key>/wheel-0.43.0-py3-none-any.whl)
0.386   help: `wheel` (v0.43.0) was included because `experiment` (v0.1.0) depends
0.386         on `astconfig` (v0.2.0) which depends on `astunparse` (v1.6.3) which
0.386         depends on `wheel`
------
failed to solve: process "/bin/sh -c uv sync --frozen --no-install-project --no-install-workspace --extra jupyterlab --extra das" did not complete successfully: exit code: 1
```

The `.env` file, loaded with the `docker-compose.yaml` holds the credentials for the private index:
```
UV_INDEX_PRIVATE_USERNAME=__token__
UV_INDEX_PRIVATE_PASSWORD=key
```

Anyone could help ?
Thanks in advance.

### Platform

Ubuntu 22.04.4 LTS

### Version

0.6.16

### Python version

Python 3.11.9
