### ISSUE TITLE
Source is ignored with extra/group when conflict table is present

### ISSUE THREAD

**Issue by watsonjj** [astral-sh/uv#13073]
### Summary

I wish to specify separate package sources for different extras/groups of the same dependency. I have a "dev-local" group/extra which installs the dependency in editable mode from a local path, and a "dev-remote" group/extra which clones the package from a git repo. The conflict table avoids conflicts between the sources. However, for a private package which does not exist in a package index, it does not work.

I have a simple demonstration so it can be reproduced. A simple package called `foo` is created with `uv init`. Then a second package is created called `bar` which has the following pyproject.toml:

(both dev-local and dev-remote have the same source for the purpose of a simple demonstration)

```toml
[project]
name = "bar"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["foo"]

[dependency-groups]
dev-local = ["foo"]
dev-remote = ["foo"]

[project.optional-dependencies]
dev-local = ["foo"]
dev-remote = ["foo"]

[tool.uv]
conflicts = [
    [
        { extra = "dev-remote" },
        { extra = "dev-local" },
        { group = "dev-remote" },
        { group = "dev-local" },
    ]
]

[tool.uv.sources]
"foo" = [
    {path = "../foo", editable = true, group = "dev-local"},
    {path = "../foo", editable = true, extra = "dev-local"},
    {path = "../foo", editable = true, group = "dev-remote"},
    {path = "../foo", editable = true, extra = "dev-remote"},
]
```

Running:
```bash
$ uv sync --group dev-local

  × No solution found when resolving dependencies:
  ╰─▶ Because there are no versions of foo and your project depends on foo, we can conclude that your project's requirements are unsatisfiable.
```

The pip interface works fine:
```bash
$ uv pip compile --group dev-local pyproject.toml

Resolved 1 package in 3ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --group dev-local pyproject.toml
-e ../foo
    # via
    #   bar (pyproject.toml)
    #   bar (pyproject.toml:dev-local)
```

If I clone a package which is present in the default package index (e.g. `pytest`), and replace foo with the package in the pyproject.toml, then it works:

```toml
[project]
name = "bar"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["pytest"]

[dependency-groups]
dev-local = ["pytest"]
dev-remote = ["pytest"]

[project.optional-dependencies]
dev-local = ["pytest"]
dev-remote = ["pytest"]

[tool.uv]
conflicts = [
    [
        { extra = "dev-remote" },
        { extra = "dev-local" },
        { group = "dev-remote" },
        { group = "dev-local" },
    ]
]

[tool.uv.sources]
"pytest" = [
    {path = "../pytest", editable = true, group = "dev-local"},
    {path = "../pytest", editable = true, extra = "dev-local"},
    {path = "../pytest", editable = true, group = "dev-remote"},
    {path = "../pytest", editable = true, extra = "dev-remote"},
]
```

```bash
$ uv sync --group dev-local

Resolved 10 packages in 3.33s
      Built pytest @ file:///Users/Jason/Software/uv_issue/pytest
Prepared 7 packages in 1.90s
Installed 7 packages in 18ms
 + exceptiongroup==1.2.2
 + iniconfig==2.1.0
 + packaging==25.0
 + pluggy==1.5.0
 + pygments==2.19.1
 + pytest==8.4.0.dev459+g33b26e429 (from file:///Users/Jason/Software/uv_issue/pytest)
 + tomli==2.2.1
```

Furthermore, with the foo dependency, if I remove the conflict table and specify just a single source, then it works:

```toml
[project]
name = "bar"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["foo"]

[dependency-groups]
dev-local = ["foo"]
dev-remote = ["foo"]

[project.optional-dependencies]
dev-local = ["foo"]
dev-remote = ["foo"]

[tool.uv.sources]
"foo" = [
    {path = "../foo", editable = true, group = "dev-local"},
]
```

```bash
$ uv sync --group dev-local

Resolved 2 packages in 34ms
      Built foo @ file:///Users/Jason/Software/uv_issue/foo
Prepared 1 package in 1.23s
Uninstalled 7 packages in 27ms
Installed 1 package in 2ms
 - exceptiongroup==1.2.2
 + foo==0.1.0 (from file:///Users/Jason/Software/uv_issue/foo)
 - iniconfig==2.1.0
 - packaging==25.0
 - pluggy==1.5.0
 - pygments==2.19.1
 - pytest==8.4.0.dev459+g33b26e429 (from file:///Users/Jason/Software/uv_issue/pytest)
 - tomli==2.2.1
```

I don't see why the original pyproject.toml should not work. It would be an extremely useful design. I have seen similar concepts requested in many issues, but none that point out this bug:
#9258 #12539 #11941 #9537 #7945 #11632 #12681 #12013

Connected to this issue, when I use a remote git url for the "dev-remote" group, I observe it cloning from the url even if I am using the "dev-local" group which uses a local path:

```bash
$ UV_GIT_LFS=1 uv sync --group dev-local

    Updated https://gitlab.desy.de/corel/corel-asyncio (a97cf59862e8040bc400e708f3f6f8a1129ef81a)
  × No solution found when resolving dependencies:
  ╰─▶ Because corel-asyncio was not found in the package registry and your project depends on corel-asyncio, we can conclude that your project's requirements are unsatisfiable.
```

### Platform

macOS 13.6 amd64 (Darwin 22.6.0 x86_64)

### Version

uv 0.6.16 (Homebrew 2025-04-22)

### Python version

Python 3.10.13

**Comment by watsonjj** [comment]
Potentially related to #13070

**Comment by konstin** [comment]
You can fix this by removing `foo` from `dependencies` (`dependencies = []`): It is possible to do an installation without any group or extra, and in that case, foo doesn't have any associated source entry. You could also add `{ path = "../foo", editable = true },` to add a source the foo base case, but I assume that errors for the real use case.

**Comment by watsonjj** [comment]
Thanks for the reply! Indeed, removing `foo` from `dependencies` helps the resolution, but this is not ideal as foo is no longer treated as a required dependency of the package (for wheels or for other package managers).

> You could also add { path = "../foo", editable = true }, to add a source the foo base case, but I assume that errors for the real use case.

This would be the perfect solution, but it does not work if the paths are different between sources:

```toml
[project]
name = "bar"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["foo"]

[dependency-groups]
dev-local = ["foo"]
dev-remote = ["foo"]

[project.optional-dependencies]
dev-local = ["foo"]
dev-remote = ["foo"]

[tool.uv]
conflicts = [
    [
        { extra = "dev-remote" },
        { extra = "dev-local" },
        { group = "dev-remote" },
        { group = "dev-local" },
    ]
]

[tool.uv.sources]
"foo" = [
    {path = "../foo", editable = true},
    {path = "../foo_local", editable = true, group = "dev-local"},
    {path = "../foo_local", editable = true, extra = "dev-local"},
    {path = "../foo_remote", editable = true, group = "dev-remote"},
    {path = "../foo_remote", editable = true, extra = "dev-remote"},
]
```

```bash
$ uv sync --extra dev-local

error: Requirements contain conflicting URLs for package `foo` in all marker environments:
- ../foo
- ../foo_remote
```

I suppose this would need a way to add the base case to the conflict table? Though it would be intuitive for it to work by default, as I am explicitly overriding the source with the extra.

**Comment by watsonjj** [comment]
Hmm, in the single-source example, the dev-local source seems to be used by default, even when not explicitly requested, even with a fresh env and cache:

```bash
$ uv sync

Using CPython 3.10.14 interpreter at: /usr/local/Caskroom/miniforge/base/envs/ultrasat/bin/python3
Creating virtual environment at: .venv
Resolved 2 packages in 4ms
      Built foo @ file:///Users/Jason/Software/ultrasat/uv_issue/foo
Prepared 1 package in 1.68s
Installed 1 package in 1ms
 + foo==0.1.0 (from file:///Users/Jason/Software/ultrasat/uv_issue/foo)
```

Is this expected?

**Comment by konstin** [comment]
@BurntSushi do you know if that's expected?

**Comment by BurntSushi** [comment]
For [this specific comment](https://github.com/astral-sh/uv/issues/13073#issuecomment-2826939152), I'm not sure. Conflicts aren't involved in this case. Whether `dev-local` should be used by default in this case isn't quite clear to me. Maybe a question for @zanieb?

But for [this comment](https://github.com/astral-sh/uv/issues/13073#issuecomment-2826933592), it seems like the logic for detecting source URLs is maybe not accounting for conflicting extras? It seems like it _ought_ to, but no, I don't believe I added any special code paths for that specifically.

**Comment by eriktaubeneck** [comment]
I just ran into this issue and found this comment, so wanted to provide one more use case that's presumably relatively common:

I have `packageA` which depends on `packageB`, and often when debugging locally, I need to depend on a local and editable version of `packageB`. Ideally, I'd have a group, e.g., `--group local-packageB` which I could turn on when needed, but by default, `packageB` comes from my package manager or a git link. Most non-developer users of `packageA` will never need the local version of `packageB`. I was hoping to solve this by having two groups, using the `group` filter in the `[tool.uv.sources]` entry, and setting one group as a default, but to no avail.

I currently solved this by just having a commented out line in `[tool.uv.sources]` and instruction in my docs for developers.

**Comment by watsonjj** [comment]
The original motivation I had to attempt something like this is to effectively override the remote sources with a local source, as I might need to develop both packages in parallel. Normally other developers would rely on the remote source, as they don't need to edit the dependency package. 

Other solutions to this problem have also been proposed in the discussions of #11632 and #6772, which tackle the problem with a local override configuration file. The downside of that approach is potentially not being able to switch off the overrides at the cmdline, but this could be explicitly supported together with the override implementation. But I still think supporting the different sources in the pyproject.toml, and selecting between them using the extras, is a more elegant solution.

Since my initial post, my solution so far has been to stick to the `uv pip` interface/workflow, as it allows me to select between the sources. This problem currently blocks me from adopting the proper uv workflow in my packages.

**Comment by watsonjj** [comment]
As there was some related activity in #19106, I decided to revisit this issue and test if it is solved in v0.12.

To improve the reproducibility, and to better demonstrate the problem I would like fixed, I have created two repos:
https://github.com/watsonjj/foo-uv-13073
https://github.com/watsonjj/bar-uv-13073

Inside these repos, I have a simple "foo" project to be used as a dependency:
```toml
# pyproject.toml
[project]
name = "foo-uv-13073"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []
```

And a simple "bar" project that depends on "foo", and specifies two sources for foo, selected with the extra.

```toml
[project]
name = "bar-uv-13073"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["foo-uv-13073"]

[project.optional-dependencies]
local = ["foo-uv-13073"]
remote = ["foo-uv-13073"]

[tool.uv]
conflicts = [
    [
        { extra = "local" },
        { extra = "remote" },
    ]
]

[tool.uv.sources]
"foo-uv-13073" = [
    {extra = "local", path = "../foo-uv-13073", editable = true},
    {extra = "remote", git = "https://github.com/watsonjj/foo-uv-13073.git", rev = "616aaa4"},
]
```

The environment can be prepared with the following commands:
```bash
mkdir uv_13073
cd uv_13073
git clone https://github.com/watsonjj/foo-uv-13073.git
git clone https://github.com/watsonjj/bar-uv-13073.git
cd bar-uv-13073
uv venv
source .venv/bin/activate
```

Then to demonstrate the issue
```
$ uv sync --extra local

  × No solution found when resolving dependencies for split (excluded: bar-uv-13073[local], bar-uv-13073[remote]):
  ╰─▶ Because foo-uv-13073 was not found in the package registry and your project depends on foo-uv-13073, we can conclude that your project's requirements are unsatisfiable.
```
```
$ uv sync --extra remote

  × No solution found when resolving dependencies for split (excluded: bar-uv-13073[local], bar-uv-13073[remote]):
  ╰─▶ Because foo-uv-13073 was not found in the package registry and your project depends on foo-uv-13073, we can conclude that your project's requirements are unsatisfiable.
```

But works fine with `uv pip`

```
$ uv pip install '.[remote]'
Resolved 2 packages in 405ms
      Built bar-uv-13073 @ file:///Users/watsonjj/Software/uv_13073/bar-uv-13073
Prepared 1 package in 529ms
Installed 2 packages in 1ms
 + bar-uv-13073==0.1.0 (from file:///Users/watsonjj/Software/uv_13073/bar-uv-13073)
 + foo-uv-13073==0.1.0 (from git+https://github.com/watsonjj/foo-uv-13073.git@616aaa4b2169285676063e8e26794672665acb4c)
```
