### ISSUE TITLE
How to handle custom `.venv` location in multi lib repos

### ISSUE THREAD

**Issue by andresliszt** [astral-sh/uv#13089]
### Question

Hello Thanks for this amazing project!. 

```
my-project/
├── Makefile
├── py_project/
│   ├── uv.lock
│   └── Makefile
└── rs_project/
    └── Makefile
```

Each `Makefile` has command to build the respective project, and the top level `Makefile` forwards the ref to the inners. I'm having problems in my CI/CD when:

-  using the [set-up uv action](https://github.com/astral-sh/setup-uv), it creates a `.venv` in the root (`my-project`) and what I want is that the venv be at `py_project/.venv`, any `uv` command will create a new `.venv` at the right location (as desired) and I'm getting this warning:
  ```warning: 
`VIRTUAL_ENV=/home/runner/work/my-project/py_project/.venv` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
Using CPython 3.10.17
Creating virtual environment at: .venv
```

In there a way to tell uv to work inside `py_project` always? I have tried several things reading the docs but I haven't been able to do it.

This warning can be handled with the --active, but I'm having several problem with other tools that manage their own venvs such as codspeed, when uv recreates a new venv it breaks everything

------------ Command snippets --------------

```Makefile
.DEFAULT_GOAL := help

#-------------------------------------------------
# Root Makefile for my-project
#-------------------------------------------------

.PHONY: help pymoors-% moors-%

# Proxy targets into subdirectories
pymoors-%:  ## Run target in pymoors/Makefile
	@$(MAKE) -C pymoors $*

moors-%:  ## Run target in moors/Makefile
	@$(MAKE) -C moors $*
```

and the py project reduced makefile

```Makefile
.DEFAULT_GOAL := help
SOURCES      = python/pymoors tests

#-------------------------------------------------
# Environment checks & pre‑commit helpers
#-------------------------------------------------
.PHONY: .uv .pre-commit pre-commit-install pre-commit-run
.uv:     ## Check for uv
	@uv -V \
	  || echo 'Please install uv: https://docs.astral.sh/uv/getting-started/installation/'
.pre-commit:   ## Check for pre-commit
	@uv run pre-commit --version \
	  || echo 'Please install pre-commit: https://pre-commit.com/'

pre-commit-install: .pre-commit   ## Install git hooks via pre-commit
	@echo "Installing pre-commit hooks…" \
	  && uv run pre-commit install

pre-commit-run:                   ## Run all enabled hooks against all files
	@echo "Running pre-commit on all files…" \
	  && uv run pre-commit run --all-files

#-------------------------------------------------
# Python/PyO3 (pymoors)
#-------------------------------------------------
.PHONY:  lock build-dev build-release \
        lint-python lint-rust pyright \
        test test-benchmarks test-all \
        coverage docs

lock:   ## Rebuild Python lockfile
	@echo "[pymoors] rebuilding lockfile" \
	  && uv lock --upgrade

build-dev:  ## Build & install in dev mode
	@echo "[pymoors] dev build" \
	  && uv sync --group dev \
	  && uv run maturin develop --uv
```

And using it in the action as

```yaml

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Pymoors (production)
        run: make pymoors-build-dev
```

This is the PR where I'm working on those changes : https://github.com/andresliszt/pymoors/pull/98

**Comment by konstin** [comment]
CC @eifinger this sounds like setup-uv more than uv.

**Comment by eifinger** [comment]
I literally merged https://github.com/astral-sh/setup-uv/pull/381 minutes ago 😆 

I will release v6.0.0 of `setup-uv` shortly which adds the input `working-directory`

**Comment by eifinger** [comment]
https://github.com/astral-sh/setup-uv/releases/tag/v6.0.0 is released. Let me know if this solves your errors 😃

**Comment by andresliszt** [comment]
Thank you for the quick turnaround on the new release!

I’m running into a strange issue with `uv run pip install` in my Actions workflow. Here’s a simplified version of my `benchmarks` job:

```yaml
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          enable-cache: true
          working-directory: pymoors

      - name: Build optimized pymoors wheel
        id: build
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: --release --out dist --interpreter ${{ env.DEFAULT_PYTHON }}
          rust-toolchain: stable
          working-directory: pymoors

      - name: Capture wheel path
        id: find_wheel
        run: |
          # …debug logic to set $WHEEL_FULL…
          echo "wheel=$WHEEL_FULL" >> $GITHUB_OUTPUT

      - name: Install built wheel & inspect venv
        working-directory: pymoors
        run: |
          echo "🔍 Wheel path: ${{ steps.find_wheel.outputs.wheel }}"
          echo "🏗️ Creating virtual environment"
          uv venv

          echo "📦 Installing the wheel (no build isolation)"
          uv run pip install "${{ steps.find_wheel.outputs.wheel }}" \
            --no-build-isolation \
            --force-reinstall

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          working-directory: pymoors
          run: make test-benchmarks
        env:
          CODSPEED_RUNNER_MODE: "walltime"
```

**What I’m seeing**  
Despite passing the absolute wheel path, pip falls back to:

```
Building pymoors @ file:///home/runner/work/pymoors/pymoors/pymoors
…  
maturin pep517 build-wheel … --editable  
Permission denied: `/home/runner/work/pymoors/pymoors/pymoors/target/wheels` (os error 13)
```

In other words, pip never installs my wheel; it rebuilds the current directory as an editable package and hits the permission error. **I can confirm that the wheel path is passed well**.

**Temporary workaround**  
Switching to a plain Python install works, but the same permission error resurfaces later in the `Run benchmarks` step:

```yaml
- name: Install wheel via python -m pip
  working-directory: pymoors
  run: |
    echo "🔍 Wheel path: ${{ steps.find_wheel.outputs.wheel }}"
    echo "🏗️ Creating virtual environment"
    uv venv

    echo "⚙️ Bootstrapping pip"
    python -m ensurepip --upgrade
    python -m pip install --upgrade pip

    echo "📦 Installing wheel (no build isolation)"
    python -m pip install -vvv --no-build-isolation --force-reinstall \
      "file://${{ steps.find_wheel.outputs.wheel }}"
```

This installs the wheel correctly, as I said, the next step 

```yaml
  - name: Run benchmarks
    uses: CodSpeedHQ/action@v3
    with:
      working-directory: pymoors
      run: make test-benchmarks
    env:
      CODSPEED_RUNNER_MODE: "walltime"
```
step still triggers the editable build and the same permission error, where

```Makefile
test-benchmarks:  ## Run only benchmarks tests
	@echo "[pymoors] benchmarks only" \
	  && uv sync --group testing \
	  && uv run pytest tests/benchmarks --codspeed
```

---

**Questions**  
1. Is there a way to make `uv run pip install` reliably pick up my pre-built wheel without falling back to a PEP-517 rebuild?  
2. Can I configure `uv` so its pip shim respects `--no-build-isolation`?  
3. Or is there a recommended pattern for installing wheels inside a `uv venv` that avoids this?
