### ISSUE TITLE
Can I make a script accessible across all directories within a python monorepo using uv?

### ISSUE THREAD

**Issue by jbcoe** [astral-sh/uv#13095]
### Question

I have a python monorepo with a top-level `pyproject.toml`. The monorepo contains a projects directory each with its own python package and `pyproject.toml` file. Some of these projects define scripts:

```
[project.script]
aaa = "aaa.something:main"
```

Within the given project directory, I can run the script with `uv run aaa`. Outside of the project directory the script cannot be found.

What can I do to make the project script accessible with uv run across the workspace?

**Comment by konstin** [comment]
What is the content of the top level `pyproject.toml`? For a script to be accessible, the package containing it must be installed.

**Comment by jbcoe** [comment]
I've tried to follow https://docs.astral.sh/uv/concepts/projects/workspaces/ which suggests a top-level non-installable pyproject.toml.

I can run a script that's defined in a project directory with:

`uv run --project project/aaa_project aaa`

but that's unpleasantly verbose and I'd rather do: `uv run aaa`.

Maybe we could set an entry in the to level project file to define workspace scripts? 

```
[tool.uv.workspace.scripts]
scripts = [...]
```

That's not currently supported and I am hoping there's an easier way to concisely run a script defined in a workspace project.

**Comment by konstin** [comment]
When you run `uv sync`, does the project defining `aaa` get installed, and if not, what is installed?

**Comment by jbcoe** [comment]
> When you run `uv sync`, does the project defining `aaa` get installed, and if not, what is installed?

That depends on which project I'm in when I run `uv sync`. Running `uv sync` will install dependencies and scripts for the package I'm in. Running `uv sync --all-packages` will install every script so that's a working solution but I'm conscious that it might be a bit heavyweight if some of the packages need compilation steps. 

Ideally I'd like a workspace-level scripts or tools solution.

**Comment by konstin** [comment]
Does placing the package with the script in the [default-groups](https://docs.astral.sh/uv/reference/settings/#default-groups) of the workspace root work for you?

**Comment by jbcoe** [comment]
The script is defined in another `pyproject.toml` file rather than as part of a dependency group in the workspace root. I'm not sure how I'd go about adding a project to default-groups.

**Comment by konstin** [comment]
This is an example structure that uses dependency groups to make a workspace member be installed by default:

```
tree
.
├── packages
│   └── script_provider
│       ├── pyproject.toml
│       ├── README.md
│       └── src
│           └── script_provider
│               ├── __init__.py
│               └── py.typed
├── pyproject.toml
└── uv.lock
```

Top-level `pyproject.toml`:

```toml
[project]
name = "xyz-workspace"
version = "0.1.0"
requires-python = ">=3.12"

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
script_provider = { workspace = true }

[tool.uv]
default-groups = ["scripts"]

[dependency-groups]
scripts = ["script_provider"]
```

script_provider `pyproject.toml`:

```toml
[project]
name = "script-provider"
version = "0.1.0"
requires-python = ">=3.13"

[project.scripts]
aaa = "script_provider:say_hi"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Running `uv sync` in the root installs the script provider package and the script:

```
$ uv sync
Resolved 2 packages in 2ms
Installed 1 package in 12ms
 + script-provider==0.1.0 (from file:///.../packages/script_provider)
$ aaa
Hello from script-provider!
```
