### ISSUE TITLE
`uv export` breaks with local dev sources unlike `poetry export`

### ISSUE THREAD

**Issue by MarkusSintonen** [astral-sh/uv#13100]
### Summary

We have issues with cases where pyproject dev dependencies are using various locally existing sources. Following used to work with `poetry export` but it breaks with `uv export` giving errors like:
```
0.357 error: Failed to generate package metadata for `xxx==1.0.0 @ editable+../xxx`
0.357   Caused by: Distribution not found at: file:///xyz/xxx
```

Here is a stripped down example of pyproject and Dockerfile (its heavily simplified example of the issue and not something that is actually used):

Dockerfile
```dockerfile
FROM ghcr.io/astral-sh/uv:0.6.5-python3.13-bookworm-slim

# Not copying the dev local sources to the image
COPY pyproject.toml uv.lock ./

# This used to work with Poetry-pyproject:
# RUN poetry export --without-hashes --without-urls > tmp-requirements.txt
# But uv export fails with errors:
RUN uv export --no-dev --no-editable --no-emit-project --no-hashes > tmp-requirements.txt

# Various other things happening etc...

# Install via the exported requirements file to some target(s)
RUN uv pip install --requirement tmp-requirements.txt --target .
```

pyproject.toml
```toml
[project]
name = "foo"
version = "1.0.0"
requires-python = "==3.13.*"

dependencies = ["a", "b", "c"]

[dependency-groups]
dev = ["xxx", "yyy", "zzz"]

[tool.uv.sources]
# Various editable dev sources which are not copied in Dockerfile
xxx = { path = "../xxx", editable = true }
yyy = { path = "../yyy", editable = true }
zzz = { path = "../zzz", editable = true }
# Can also include some custom indexes
c = { index = "some_pypi" }
```

I have tried various different parameters for `uv export` but it always fails and does not respect the `no-dev` or `no-editable` flags. I dont understand why it tries to look into the layer paths that do not exist in built docker image eventhough they are omitted in export command.

Thanks for the great work here!

### Platform

Darwin 24.4.0 arm64

### Version

0.6.5

### Python version

3.13.3
