### ISSUE TITLE
Can tool.uv.sources recognize home directory tilde

### ISSUE THREAD

**Issue by BoltonBailey** [astral-sh/uv#13113]
### Summary

Using uv, I was trying to make a dependency on something I had locally built, I used this in my pyproject.toml:

```toml
[tool.uv.sources]
pantograph = { path = "~/Documents/MyDocuments/Professional/PyPantograph/dist/pantograph-0.3.0-cp310-cp310-macosx_14_0_arm64.whl" }
```

But it didn't work.

```
error: Distribution not found at: file:///Users/boltonbailey/Documents/MyDocuments/Professional/my-uv-project/~/Documents/MyDocuments/Professional/numina-all-files/PyPantograph/dist/pantograph-0.3.0-cp310-cp310-macosx_14_0_arm64.whl
```

I needed to replace the `~` with the name of my home directory:

```toml
[tool.uv.sources]
pantograph = { path = "/Users/boltonbailey/Documents/MyDocuments/PyPantograph/dist/pantograph-0.3.0-cp310-cp310-macosx_14_0_arm64.whl" }
```

After this, it worked. However, it would have been nice if `uv` had recognized that my path starting with `~` was meant to be relative to my home directory.

Can uv be made to interpret paths starting with `~` as non-relative paths?

### Example

The example would be that

```toml
[tool.uv.sources]
pantograph = { path = "~/Documents/MyDocuments/Professional/PyPantograph/dist/pantograph-0.3.0-cp310-cp310-macosx_14_0_arm64.whl" }
```

described above works out-of-the-box
