### ISSUE TITLE
UV is unable to install rocm torch if I use a sys_platform marker

### ISSUE THREAD

**Issue by TheAyes** [astral-sh/uv#13197]
### Summary

I'm currently trying to use uv for it's ease of use but I can't seem to get the platform markers to work correctly.

Here's my pyproject.toml:
```toml
[project]
name = "iona"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools",
    "wheel",
    "transformers",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "torchaudio>=2.6.0",
    "accelerate"
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2"
explicit = true
```

As you can see I'd like to use the rocm version of torch. However this always results in:
```
  × No solution found when resolving dependencies for split (sys_platform == 'linux'):
  ╰─▶ Because only torch{sys_platform == 'linux'}<=2.5.1+rocm6.2 is available and your project depends on torch{sys_platform == 'linux'}>=2.6.0, we can conclude that your project's requirements are unsatisfiable.
```

Even If I decide to downgrade to 2.5.1 it suddenly becomes:
```
× No solution found when resolving dependencies for split (sys_platform == 'linux'):
  ╰─▶ Because there is no version of pytorch-triton-rocm{python_full_version < '3.13' and platform_machine == 'x86_64' and sys_platform == 'linux'}==3.1.0 and torch==2.5.1+rocm6.2 depends on
      pytorch-triton-rocm{python_full_version < '3.13' and platform_machine == 'x86_64' and sys_platform == 'linux'}==3.1.0, we can conclude that torch==2.5.1+rocm6.2 cannot be used.
      And because only the following versions of torch{sys_platform == 'linux'} are available:
          torch{sys_platform == 'linux'}<2.5.1
          torch{sys_platform == 'linux'}==2.5.1+rocm6.2
      and your project depends on torch{sys_platform == 'linux'}>=2.5.1, we can conclude that your project's requirements are unsatisfiable.
```

So the only workaround I know of right now is removing the environment marker which resolves the issue but will install the wrong index unless I change it manually each time.

### Platform

NixOS 25.05.20250423.8a2f738 (Warbler) x86_64

### Version

uv 0.6.16

### Python version

3.13 (can't check cause of  the dependency issue)

**Comment by charliermarsh** [comment]
The first error looks correct: there is no `torch>=2.6.0` on the ROCm6.2 index, so that's impossible to resolve.

The second issue looks correct too. You need to tell uv to look for `pytorch-triton-rocm` on the PyTorch index, probably something like this:

```toml
[project]
name = "iona"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools",
    "wheel",
    "transformers",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "torchaudio>=2.6.0",
    "accelerate",
    "pytorch-triton-rocm ; sys_platform == 'linux'",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-rocm", marker = "sys_platform == 'linux'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
]
pytorch-triton-rocm = { index = "pytorch-rocm" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2"
explicit = true
```
