### ISSUE TITLE
BUG: `uv run --no-sync` incorrectly resets CPython 3.14 venv in version 0.7

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/uv#13233]
### Summary

The following CI job failed with uv 0.7.0 (and 0.7.1), but succeeded with 0.6.x

https://github.com/neutrinoceros/inifix/actions/runs/14757311421/job/41428805320

Essentially, it can be boiled down to
```yaml
jobs:
  build:
    name: py${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
        - '3.14'
        - 3.14t

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: false
    - name: Configure uv
      run: |
        echo "RUST_LOG=uv=debug" >> $GITHUB_ENV

    - name: Set PYTHON_GIL
      if: ${{ endswith( matrix.python-version , 't' ) }}
      run: |
        echo "PYTHON_GIL=0" >> $GITHUB_ENV

    - run: uv lock --upgrade --prerelease=allow
    - run: uv sync --frozen --no-editable --group test
    - name: Run tests
      run: |
        uv run --no-sync pytest --color=yes
```
The final error is:
```
error: Failed to spawn: `pytest`
  Caused by: No such file or directory (os error 2)
```
If I understand logs correctly, this is caused by uv incorrectly (and needlessly) re-creating my env on `uv run`:
https://github.com/neutrinoceros/inifix/actions/runs/14757311421/job/41428805320#step:8:31

This happens with both builds of Python 3.14 (gil-enabled, and free-threading). I can reproduce this locally too with
```
export UV_PYTHON=3.14
uv sync --group test --frozen --no-editable
uv run --no-sync pytest
```

pasting the last command's output:
```
Using CPython 3.14.0a6
Removed virtual environment at: .venv
Creating virtual environment at: .venv
error: Failed to spawn: `pytest`
  Caused by: No such file or directory (os error 2)
```

I read the release notes but didn't find anything that looked related. Is this change somehow intentional ?

### Platform

ubuntu-latest

### Version

uv 0.7.1

### Python version

3.14.0a6
