### ISSUE TITLE
Cannot override dependency metadata of source dependency

### ISSUE THREAD

**Issue by toslunar** [astral-sh/uv#13297]
### Summary

To reproduce, `uv sync` at `a/` with the files below causes
```
  × No solution found when resolving dependencies:
  ╰─▶ Because only b==0.1.0 is available and b==0.1.0 depends on numpy<2, we can conclude that all versions of b
      depend on numpy<2.
      And because your project depends on b and numpy>=2, we can conclude that your project's requirements are
      unsatisfiable.
```

`a/pyproject.toml`
```toml
[project]
name = "a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["b", "numpy>=2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
b = { path = "../b", editable = true }

[[tool.uv.dependency-metadata]]
name = "b"
requires-dist = ["numpy"]
```

`a/src/a.py`
```python
...
```

`b/pyproject.toml`
```toml
[project]
name = "b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy<2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

`b/src/b.py`
```python
...
```

---

Note that for PyPI dependency we can override `requires-dist` (`numpy<1.29.0,>=1.22.4` in `scipy==1.12.0`) by

`c/pyproject.toml`
```toml
[project]
name = "c"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["scipy==1.12.0", "numpy>=2"]

[[tool.uv.dependency-metadata]]
name = "scipy"
requires-dist = ["numpy"]
```

### Platform

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 GNU/Linux

### Version

uv 0.7.2

### Python version

3.12.9

**Comment by charliermarsh** [comment]
I can't remember why it works this way, but it _does_ work if you specify the version:

```toml
[[tool.uv.dependency-metadata]]
name = "b"
version = "0.1.0"
requires-dist = ["numpy"]
```
