### ISSUE TITLE
uv sync incorrectly determining dependencies

### ISSUE THREAD

**Issue by NeilGirdhar** [astral-sh/uv#13315]
### Summary

Minimum working example
===
With a `pyproject.toml`:
```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blah"
version = "1.0"
requires-python = ">=3.13, <3.14"
dependencies = ["ray[tune]>=2.45.0"]
```
Add a subdirectory called `blah` with an empty `__init__.py`

Then:
```
❯ uv lock -U
Resolved 28 packages in 117ms
❯ uv sync
Resolved 28 packages in 1ms
  × Failed to build `pyarrow==17.0.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

...
      CMake Error at CMakeLists.txt:266 (find_package):
        By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Arrow", but
        CMake did not find one.

        Could not find a package configuration file provided by "Arrow" with any of
        the following names:

          ArrowConfig.cmake
          arrow-config.cmake

        Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
        "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
        provides a separate development package or SDK, be sure it has been
        installed.

      
      error: command '/usr/bin/cmake' failed with exit code 1

      hint: This usually indicates a problem with the package or the build environment.
  help: `pyarrow` (v17.0.0) was included because `blah` (v1.0) depends on `ray[tune]` (v2.45.0) which depends on `pyarrow`
```
But why do we have pyarrow at all?  Ray only depends on pyarrow for the Darwin platform, and I'm on Ubuntu.

### Platform

Ubuntu 25.04

### Version

Latest

### Python version

3.13

**Comment by charliermarsh** [comment]
We typically try to minimize the number of selected versions for a given package. So we'd attempt to use `pyarrow` 17 here in the resolver. You can add a constraint to force uv to select the higher version on non-macOS.

**Comment by NeilGirdhar** [comment]
@charliermarsh I tried that, but it still didn't work:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blah"
version = "1.0"
requires-python = ">=3.13, <3.14"
dependencies = [
    "ray[tune]>=2.45.0",
    "pyarrow>=19.0",
]
```
❯ uv lock -U
  × No solution found when resolving dependencies for split (platform_machine == 'x86_64' and sys_platform == 'darwin'):
```

**Comment by charliermarsh** [comment]
Yeah that correctly doesn't work, because now on macOS ARM you're asking for `pyarrow>=19` and `pyarrow<18`.

I think you want this:

```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blah"
version = "1.0"
requires-python = ">=3.13, <3.14"
dependencies = [
    "ray[tune]>=2.45.0",
]

[tool.uv]
constraint-dependencies = [
    "pyarrow>=19.0 ; platform_machine != 'x86_64' or sys_platform != 'darwin'"
]
```

**Comment by NeilGirdhar** [comment]
Thanks!  It's unfortunate that the solution is uv-specific.  Why doesn't the resolver choose the latest version on linux?  Can setup.py for Ray be changed in some way to force it to do that?

**Comment by charliermarsh** [comment]
You can just do this if you want, it's not uv-specific but it means you're encoding a direct dependency on `pyarrow`:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blah"
version = "1.0"
requires-python = ">=3.13, <3.14"
dependencies = [
    "ray[tune]>=2.45.0",
    "pyarrow>=19.0 ; platform_machine != 'x86_64' or sys_platform != 'darwin'"
]
```

Yes, Ray could be changed to increase their lower-bound from 9.0.0 to something higher.
