### ISSUE TITLE
Universal resolution with `only-binary`

### ISSUE THREAD

**Issue by tkukushkin** [astral-sh/uv#13332]
### Question

Hello! I have a small problem with universal resolution for pymssql.

First circumstance:
- [pymssql==2.3.4](https://pypi.org/project/pymssql/2.3.4/#files) doesn't have wheels for Windows x86-64
- [pymssql==2.3.3](https://pypi.org/project/pymssql/2.3.3/#files) doesn't have wheels for linux

Second circumstance: it's not very easy to install pymssql on windows without wheels.

So I generate requirements.txt like that:

```
echo 'pymssql' | uv pip compile --universal --only-binary pymssql -
```

but I get:

```
Resolved 1 package in 589ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --universal --only-binary pymssql -
pymssql==2.3.4
```

I tried to add uv.toml with
```toml
required-environments = [
  "sys_platform == 'win32' and platform_machine == 'x86_64'",
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
```
but it didn't help.

How can I ask uv to take into consideration availability of wheels for some specific environments?

### Platform

Darwin 24.3.0 arm64

### Version

uv 0.7.2 (481d05d8d 2025-04-30)
