### ISSUE TITLE
Failed to fetch ssh+git dependencies when host is not known

### ISSUE THREAD

**Issue by mia-trilo** [astral-sh/uv#13356]
### Summary

`uv sync` seems to fail to install dependencies from an git link with SSH when the host isn't known. Based on the log it seems to be stuck on the "yes/no/fingerprint" prompt when ssh into a new host for the first time. Interestingly, cancelling and re-running `uv sync` again solves this problem, but it can be consistently reproduced with the `--no-cache` flag

To reproduce this issue:

1. Create an empty project with the following `pyproject.toml`
```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["uv"]

[tool.uv.sources]
uv = {git = "ssh://git@github.com/astral-sh/uv.git"}
```
2. Run `ssh-keygen -R github.com`. You can also manually delete all sources of `github.com` in `.ssh/known_hosts`
3. Run `uv sync --no-cache`, observe that this process hangs

### Platform

macOS 15, M3. Also encountered on Raspberry Pi 4B

### Version

0.7.3

### Python version

3.12.4
