### ISSUE TITLE
Cannot install dependecy groups

### ISSUE THREAD

**Issue by PabloVD** [astral-sh/uv#13377]
### Question

I have a pyproject.toml like the one below. It does not have dependencies but has dev dependencies for the documentation and tests. I would be able to install them in a dev environment, but I could not get it. I tried with `uv sync`, `uv sync --dev` but that is not working. Am I missing something?

```toml
[project]
name = "projectname"
version = "0.1.0"
description = "Description"
authors = [
    { name = "Me", email = "whatever@gmail.com" },
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.10"

[dependency-groups]
dev = [
    "matplotlib",
    "mkdocs",
    "mkdocstrings[python]",
    "mkdocs-material>=9.6.12",
    "tqdm"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

### Platform

Ubuntu

### Version

uv 0.7.2
