### ISSUE TITLE
`uv lock && uv lock --check` fails

### ISSUE THREAD

**Issue by NellyWhads** [astral-sh/uv#13373]
### Summary

Hey guys,

I've:
* unset all UV related variables from the env
* ensured that the first command does run idempotently (second run of `uv lock` does not update the lock file, but the first one does)
* tried on multiple machines

The key change I made was from this setup:

```toml
...
[dependency-groups]
rospy = [
  "rospy>=1.15",
]
...

[[tool.uv.index]]
name = "rospy"
url = "https://rospypi.github.io/simple/"
```

To this one to be more specific:
```toml
...
[dependency-groups]
rospy = [
  "rospy>=1.15",
  "roscpp",
  "rosgraph",
  "roslib",
  "genpy",
  "genmsg",
  "std-msgs",
  "rosgraph-msgs",
]
...

[tool.uv.sources]
...
rospy = [{ index = "rospy" }]
roscpp = [{ index = "rospy" }]
rosgraph = [{ index = "rospy" }]
roslib = [{ index = "rospy" }]
genpy = [{ index = "rospy" }]
genmsg = [{ index = "rospy" }]
std-msgs = [{ index = "rospy" }]
rosgraph-msgs = [{ index = "rospy" }]
...

[[tool.uv.index]]
name = "rospy"
url = "https://rospypi.github.io/simple/"
explicit = true
```

Am I missing something? Running with `--verbose` prints a rather lot bit of output which I'd like to avoid human-parsing. The entire polylithic monorepo locks ~850 packages.

### Platform

MacOS 14, Ubuntu 22.04

### Version

0.16.13, 0.16.17, 0.7.3

### Python version

3.10.15
