### ISSUE TITLE
uv add doesn't adds the exact package version to pyproject.toml or to a script

### ISSUE THREAD

**Issue by me-kell** [astral-sh/uv#13381]
### Summary

when adding a package (e.g. `requests`) without version with `uv add requests --constraints constraints.txt` but with the exact version specified in `constraints.txt` `uv` will add the version specified in `constraints.txt` (i.e. `requests==2.31.0`) as expected.

But in `pyproject.toml` it will add `requests>=2.31.0` instead of `requests==2.31.0`).

I'd expect `requests==2.31.0` to be added in `pyproject.toml`. Is this intended? When I delete `.venv` and `uv.lock` and call `uv sync` or `uv lock` it will add a newer version of requests.

**To reproduce it**

```sh
mkdir myproject
cd myproject

uv init
cat <<'EOF' | tee constraints.txt
requests==2.31.0
EOF
uv add requests --constraints constraints.txt
cat pyproject.toml
```
```toml
[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.31.0",
]
```
And adding a package to a script with `--constraints` will not add any version at all:

```shell
uv init --script myscript.py
uv add --script myscript.py requests --constraints constraints.txt

head -n 6 myscript.py
```
```python
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "requests",
# ]
# ///
```

### Platform

Linux 5.10.0-19-amd64 x86_64 GNU/Linux

### Version

uv 0.7.3

### Python version

Python 3.13.3
