### ISSUE TITLE
Is there a way for one extra to include another extra?

### ISSUE THREAD

**Issue by nikhilweee** [astral-sh/uv#13387]
### Question

**Background**
Extras in `[project.optional-dependencies]` are flat lists of requirements, so as I understand currently there is no way for one extra to include another.

```toml
[project.optional-dependencies]
dev  = ["pytest","flake8"]
docs = ["sphinx","mkdocs"]
# no syntax for docs to include dev
```

By contrast, `[dependency-groups]` does support [native inclusion](https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-group-include):
```toml
[dependency-groups]
dev  = ["pytest","flake8"]
docs = ["sphinx","mkdocs"]
docs = [
    "sphinx",
    "mkdocs",
    {include-group = "dev"}, # native inclusion
]
```

**Question**
Does `uv` currently support, or plan to support a way for one `extra` to include other extras?  If not, what’s the recommended way to avoid copy‑&‑paste beyond installing multiple extras (e.g. `uv sync --extra dev --extra docs`)? 

I understand that it might not be easy to change the existing spec for `[project.optional-dependencies]` to match `[dependency-groups]` since that would involve raising a PEP, but I wonder if it's worth adding something in `[tool.uv]` since `uv` has full control over that table.

### Platform

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 GNU/Linux

### Version

uv 0.7.3

**Comment by charliermarsh** [comment]
Yes:

```toml
[project]
name = "foo"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = [
    "foo[docs]",
]
docs = [
    "sphinx>=8.2.3",
]
```

**Comment by nikhilweee** [comment]
That's interesting, I was under the impression that uv would try to fetch the published package from pypi (and fail if not found) rather than look in the local pyproject. This makes me wonder, how does uv know where to fetch a dependency from?

```toml
[project]
name = "foo"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = [
    "foo[docs]",
    "pandas[excel]", 
]
docs = [
    "sphinx>=8.2.3",
]
```

Is it as simple as looking for the dependency in the local pyproject and fallback to pypi (or the relevant source)?
