### ISSUE TITLE
uv tool install mercurial succeeds for Windows on GitHub Actions but fails to run

### ISSUE THREAD

**Issue by nth10sd** [astral-sh/uv#13408]
### Summary

I first installed uv via on Windows on GitHub Actions:

```
Run pip install --upgrade uv
  pip install --upgrade uv
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.10.11\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.10.11\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.11\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.11\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.11\x64
    SSH_AUTH_SOCK: /tmp/ssh-mFNvKyRcmejn/agent.1756
    SSH_AGENT_PID: 1757
Requirement already satisfied: uv in c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages (0.7.3)
```

I tried installing Mercurial 7.0.2 via `uv tool install`:

```
$env:PATH = "$env:USERPROFILE`\.local`\bin;$env:PATH" ; uv tool install mercurial ; hg --version -q
```

And got the following:

```
Resolved 1 package in 29ms
Downloading mercurial (6.3MiB)
 Downloading mercurial
Prepared 1 package in 749ms
Installed 1 package in 392ms
 + mercurial==7.0.2
Installed 2 executables: hg, hg.exe
abort: couldn't find mercurial libraries in [C:\Users\runneradmin\.local\bin C:\hostedtoolcache\windows\Python\3.10.11\x64\python310.zip C:\hostedtoolcache\windows\Python\3.10.11\x64\Lib C:\hostedtoolcache\windows\Python\3.10.11\x64\DLLs C:\Users\runneradmin\.local\bin C:\hostedtoolcache\windows\Python\3.10.11\x64 C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages]
(check your install and PYTHONPATH)
```

How should the "couldn't find mercurial libraries" message be solved? Mercurial installed via other methods (e.g. choco) seem to run fine.

I'm not sure if this is a uv or a Mercurial or a GitHub Actions runner image issue:

```
Current runner version: '2.323.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20250504.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20250504.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20250504.1
Runner Image Provisioner
  2.0.422.1
```

### Platform

Windows

### Version

uv 0.7.3

### Python version

Python 3.10.11
