### ISSUE TITLE
Updating `uv lock` with win32 dependency in uv.sources under linux fails with "Distribution not found at"

### ISSUE THREAD

**Issue by Timoses** [astral-sh/uv#13487]
### Summary

Using the following `pyproject.toml`:

```toml
[project]
name = "uv-tests"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "test ; sys_platform == 'win32'"
]


[tool.uv.sources]
test = { path = "C:/local/test" , marker = "sys_platform == 'win32'" }
```

Running `uv lock` results in
```
error: Distribution not found at: file:///opt/code/uv-tests/C:/local/test
```

The reason why I would like to lock:
On a build server I would probably want to use `uv sync --locked`, so that there are no unexpected changes in the environment, correct?

If so, wouldn't it be important to be able to keep the `uv.lock` file up-to-date even on another OS system? At least as far as that system can gather information.

Also: Shouldn't it be possible to have different local dependencies specified for various system platforms (linux, windows)? Then `uv lock` would never work as it would never find the files for other platforms.

### Platform

Debian 6.1.135-1 (2025-04-25) , Linux 6.1.0-34-amd64 x86_64 GNU/Linux

### Version

uv 0.7.4

### Python version

Python 3.11.2
