### ISSUE TITLE
uv does not respect pyproject.toml default index

### ISSUE THREAD

**Issue by eegli** [astral-sh/uv#13490]
### Summary

We are in a corporate scenario where we want to **always** use our private index and "disable" fetching from PyPi. According to [the docs](https://docs.astral.sh/uv/configuration/indexes/#defining-an-index), this can be done via the `default = true` entry.

Our only index specified in pyproject.toml:
```toml
[[tool.uv.index]]
name = "company-virtual"
url = "https://europe-west6-python.pkg.dev/xxx/simple"
default = true # note this!
```

To demonstrate the issue, let's assume we only have a single dependency **that is not available on our index**:
```toml
[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
```
Running `uv sync --refresh --reinstall --no-cache` will actually fetch `ruff` from PyPi, see the lockfile:

```toml
[[package]]
name = "ruff"
version = "0.11.10"
source = { registry = "https://pypi.org/simple" }
```

However, specifying the default index via the cli fails **as expected**:

```sh
just uv sync --refresh --default-index company-virtual
> uv sync --refresh --default-index company-virtual
  × No solution found when resolving dependencies for split (python_full_version >= '3.11'):
  ╰─▶ Because ruff was not found in the package registry ...
```

Let me know if you need more info! Thanks

### Platform

Windows 11 (MINGW64_NT-10.0-22631)

### Version

uv 0.7.3 (3c413f74b 2025-05-07)

### Python version

3.11

**Comment by charliermarsh** [comment]
Are you able to create a minimal reproduction for us? You can use https://test.pypi.org/ if you need a non-PyPI index to use for the example.

**Comment by eegli** [comment]
I tried to setup a minimal example from `uv init` and it appears that the default index is correctly registered. Sorry for the fuzz.

The actual problem may lie somewhere else and I managed to track down one weird thing. In reality, we have two indexes (provided by Google Artifact Registry):
1. one that is a PyPi mirror (second entry with `default = true`)
2. another one for internal packages (first entry)

```toml
[[tool.uv.index]]
# Internal company packages
name = "company-virtual"
url = "https://europe-west6-python.pkg.dev/xxx-virtual-repo/simple"

[[tool.uv.index]]
# Upstream repo: PyPI
name = "company-remote"
url = "https://europe-west6-python.pkg.dev/xxx-remote-repo/simple"
default = true
```

We want/need to use the `company-remote` as a default index and `company-virtual` for the internal packages.

Given **no lockfile**:

1. This does not work
 ```sh
uv sync --all-packages --refresh --no-cache
```
> × No solution found when resolving dependencies:
  ╰─▶ Because \<internal-package\> was not found in the package registry...  we can conclude that your workspace's requirements are unsatisfiable.

2. With the **exact same pyproject file**, specifying the **default index and additional index from the command line**, it works!
```sh
uv sync --all-packages --refresh --no-cache \
    --default-index company-remote=https://europe-west6-python.pkg.dev/xxx-remote-repo/simple \
    --index company-virtual"https://europe-west6-python.pkg.dev/xxx-virtual-repo/simple
```

To give some context:
- We're using workspaces with around 5 members
- Credentials are correct - otherwise, the second command above would not work

Let me know if I can provide anything else. And thank you for the amazing work!

**Comment by eegli** [comment]
Here is a more stripped down configuration that replicates the problem, which exists for both adding and syncing deps.

**pyproject.toml**
```toml
[project]
name = "company-name"
author = "authors"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = []

[[tool.uv.index]]
# Internal company packages
name = "company-virtual"
url = "https://europe-west6-python.pkg.dev/xxx-virtual-repo/simple"

[[tool.uv.index]]
# Upstream repo: PyPI
name = "company-remote"
url = "https://europe-west6-python.pkg.dev/xxx-remote-repo/simple"
default = true
```

**uv.lock** - does not exist

## Adding a public package
**Expectation**: uv picks up the default index from pyproject.
**Actual**: Only when the default index is specified via CLI flags or env variables, the default index is picked up

### Adding a public package (pyproject.toml indices)
`uv add polars --no-cache --refresh`
👉🏾 **uv uses the PyPi index, even with a custom default index defined** ❌
```toml
# results in uv.lock
[[package]]
name = "polars"
version = "1.29.0"
source = { registry = "https://pypi.org/simple" }
```

### Adding a public package (CLI/env variable indices)
`uv add polars --no-cache --refresh --index company-remote=https://europe-west6-python.pkg.dev/xxx-remote-repo/simple`
👉🏾 **uv uses the correct index** ✅
```toml
# results in uv.lock
[[package]]
name = "polars"
version = "1.29.0"
source = { registry = "https://europe-west6-python.pkg.dev/xxx-remote-repo/simple" }
```

**Comment by charliermarsh** [comment]
Unfortunately, I can't reproduce that. I ran `uv init foo`, then edited the `pyproject.toml` to:

```toml
[project]
name = "company-name"
author = "authors"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "iniconfig>=2.0.0",
]

[[tool.uv.index]]
# Upstream repo: PyPI
name = "company-remote"
url = "https://test.pypi.org/simple"
default = true
```

Then ran `uv add iniconfig`, and the `uv.lock` contains:

```toml
version = 1
revision = 2
requires-python = "==3.10.*"

[[package]]
name = "company-name"
version = "0.0.0"
source = { virtual = "." }
dependencies = [
    { name = "iniconfig" },
]

[package.metadata]
requires-dist = [{ name = "iniconfig", specifier = ">=2.0.0" }]

[[package]]
name = "iniconfig"
version = "2.0.0"
source = { registry = "https://test.pypi.org/simple" }
sdist = { url = "https://test-files.pythonhosted.org/packages/d7/4b/cbd8e699e64a6f16ca3a8220661b5f83792b3017d0f79807cb8708d33913/iniconfig-2.0.0.tar.gz", hash = "sha256:2d91e135bf72d31a410b17c16da610a82cb55f6b0477d1a902134b24a455b8b3", size = 4646, upload-time = "2023-01-07T11:08:16.826Z" }
wheels = [
    { url = "https://test-files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl", hash = "sha256:b6a85871a79d2e3b22d2d1b94ac2824226a63c6b741c88f7ae975f18b6778374", size = 5892, upload-time = "2023-01-07T11:08:14.843Z" },
]
```

**Comment by eegli** [comment]
I also cannot reproduce the issue outside of our corporate setup using test.pypi.org. Let's close the issue, could be that there are other factors involved outside of uv's control, such as our internal HTTP proxy. For now, we'll be using env variables for explicit resolution - it all works with those in our case.

Thanks a lot for looking into it!

**Comment by charliermarsh** [comment]
I don't _think_ I'd expect it to manifest this way, but some indexes will automatically redirect to PyPI if you provide invalid credentials or similar. That _could_ be what's going on here?

**Comment by eegli** [comment]
I have traced that and could not find a redirect. Looking at the requests through my local HTTP proxy from the _previous_ example, all requests go directly to pypi.org. Using `--verbose` when the index is **only** defined in pyproject gives me the entry:
> DEBUG No cache entry for: https://pypi.org/simple/polars/

However, I noticed that if I _move_ the index from pyproject to `uv.toml`, **it is picked up correctly**:

```toml
# pyproject
[project]
name = "temp"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["polars>=1.29.0"]
```

```toml
# uv.toml
[[index]]
# Upstream repo: PyPI
name = "company-remote"
url = "https://test.pypi.org/simple"
default = true
```

Runinng `just uv sync --refresh --no-cache --verbose` **works** and results in the lockfile:
```toml
[[package]]
name = "polars"
version = "1.29.0"
source = { registry = "https://europe-west6-python.pkg.dev/xxx-remote-repo/simple" }
```
> DEBUG No cache entry for: https://europe-west6-python.pkg.dev/xxx-remote-repo/simple/polars/


It almost appears as if specifying the index in pyproject is the issue on my Windows machine. Do you have any idea on how to debug this?

**Comment by eegli** [comment]
The issue has now been identified. In all previous examples, I've had a minimal `uv.toml` config file for my user:
```toml
native-tls = true
```
It appears that the **sheer presence of a user** `uv.toml` config - **even if empty** - somehow results in the PyPi being included as the default index.

Getting rid of the config file (`unset UV_CONFIG_FILE`) and relying solely on the following pyproject config:
```toml
[project]
name = "temp"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["polars>=1.29.0"]

[[tool.uv.index]]
# Upstream repo: PyPI
name = "axach-remote"
url = "https://europe-west6-python.pkg.dev/axach-inetbuildingzonereg-ibz/pypi-remote-repo/simple"
default = true
```
Runinng just uv sync --refresh --no-cache --verbose **works** and results in the lockfile:

```toml
[[package]]
name = "polars"
version = "1.29.0"
source = { registry = "https://europe-west6-python.pkg.dev/xxx-remote-repo/simple" }
```
