### ISSUE TITLE
Support exact Python version in generating `pylock.toml`

### ISSUE THREAD

**Issue by ketozhang** [astral-sh/uv#13497]
### Summary

Currently, `uv pip compile SRC_FILE -o pylock.toml  --python-version 3.12.10` resolves to: 

```toml
# ...
lock-version = "1.0"
created-by = "uv"
requires-python = ">=3.12.10"
# ...
```

In the use case of deploying reproducible environments including the installation of Python, it would be nice to not need to also specify `--python` or the `.python_version` file.
