### ISSUE TITLE
`uv export` does not respect custom index setting from `[tool.uv.sources]` when exporting to `requirements.txt`

### ISSUE THREAD

**Issue by ShIRannx** [astral-sh/uv#13572]
# `uv export` does not respect custom index setting from `[tool.uv.sources]` when exporting to `requirements.txt`

## Description

When using a custom index via `[[tool.uv.index]]` and mapping it in `[tool.uv.sources]`, the `uv export` command does not include the associated source in the exported `requirements.txt`.

## Example `pyproject.toml`

```toml
[project]
dependencies = [ "example-package>=0.1.dev4" ]

[[tool.uv.index]]
name = "example"
url = "https://example.com/simple"
explicit = true

[tool.uv.sources]
example = { index = "example" }
````

## Command Used

```bash
uv export --quiet --group dev --all-extras --format requirements-txt --output-file requirements.txt
```

## Resulting `requirements.txt`

```text
example-package==$uv-resolved-version \
    --hash=sha256:... \
    --hash=sha256:...
```

## Expected Output

I expected the export to also include the index URL pointing to the custom source, e.g.:

```text
example-package @ https://example.com/packages/$uv-resolved-package.whl \
    --hash=sha256:... \
    --hash=sha256:...
```

Let me know if any additional logs or minimal reproducible projects are needed.

```

You can save this to a file called `uv-export-custom-index-issue.md` or paste it directly into a GitHub issue. Let me know if you'd like me to prepare it as a downloadable file.
```
