### ISSUE TITLE
Incorrect source registry after using uv lock with custom indexes

### ISSUE THREAD

**Issue by praisethedeviI** [astral-sh/uv#13590]
### Summary

When using a custom index configuration in pyproject.toml, the `uv lock` command incorrectly sets the source.registry for ALL packages to the custom index URL, even for packages that should come from PyPI

-----
### My toml configuration files

1. I have pyproject.toml
```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "==3.11.*"
dependencies = [
    "assistant-core>=7.0.7,<8",
]


[tool.uv]
package = false

[[tool.uv.index]]
name = "assist-core"
# It's actually different domain with gitlab on it
url = "https://gitlab.com/api/v4/groups/949/-/packages/pypi/simple"
explicit = true

[tool.uv.sources]
assistant-core = { index = "assist-core" }
```

2. I use uv.toml or UV_INDEX with authentication:
```toml
[[index]]
name = "assist-core"
# different domain
url = "https://__token__:<TOKEN>@gitlab.com/api/v4/groups/949/-/packages/pypi/simple"
```

--------
### Expected behavior

* Only packages specified in `[tool.uv.sources]` should have the custom registry as their source
* All other packages should maintain `source = { registry = "https://pypi.org/simple" }`
* Manually correcting the lockfile and re-running `uv lock` should not revert the changes

-------
### Actual behavior

* All packages in the lockfile get `source = { registry = "https://gitlab.com/..." }`
* Manually correcting the registry to PyPI and re-running `uv lock` doesn't update the lockfile (suggesting uv doesn't detect this as a change that needs resolution)

-------
### Additional Context
* The issue occurs regardless of whether authentication is provided via uv.toml or UV_INDEX environment variable
* The workaround of manually editing the lockfile is not sustainable as it needs to be redone after every dependency update

-------
### Also:

After changing the index URL in uv.toml (but index URL in the pyproject.toml hasn't been changed) to `url = "https://__token__:<TOKEN>@gitlab.com/api/v4/packages/pypi/simple"`, the lockfile was fixed. However:
* `uv sync --locked` and `uv lock --check` report that the lockfile needs updating
* Meanwhile, `uv lock`, `uv lock --dry-run` and `uv sync --check` report no updates needed and don't modify the file

### Platform

Darwin 24.4.0 arm64

### Version

uv 0.7.3 (3c413f74b 2025-05-07)

### Python version

Python 3.11.11
