### ISSUE TITLE
Request: A `uv init` command to generate a pyproject.toml

### ISSUE THREAD

**Issue by imbev** [astral-sh/uv#1360]
A downside of the "pip-tools style" interface is that there is no way to automatically generate a compatible pyproject.toml with the necessary fields. For those using the modern pyproject.toml format, it can be difficult or tedious to create an appropriate pyproject.toml file manually.

I suggest that uv adopt behavior similar to Poetry's [`poetry init`](https://python-poetry.org/docs/cli/#init), so that uv would prompt or allow the user to specify the name, description, author, python version, and build backend (or no build backend) for the project.

**Comment by zanieb** [comment]
Hi! Thanks for the feedback. A `poetry init` experience is on our roadmap.

**Comment by DimitarVanguelov** [comment]
The overall poetry experience is quite good and ergonomic (though perhaps not always ideal). By that I mean having the other poetry commands as well, not just `poetry init`:

- `poetry new`
- `poetry add`*
- `poetry shell`
- `poetry run`
- `poetry build`
- `poetry publish`
- etc

There are of course other nice features of poetry, as well as downsides (picking Python versions seems to still be awkward) which I know `uv` is planning on addressing, but having `uv` versions of the above would be a big incentive to switch.

But perhaps the _biggest incentive_ to switch would be poetry-like management of a pyproject.toml file and lock file.

* I know `uv add` might be controversial since it already offers `uv pip install` which is a minimal change from just `pip install` but having `uv add` instead of `uv pip install` as a higher level API would be nice as it would save us a few keystrokes (and we're a lazy bunch) but again, it keeps close to the poetry API that a lot of us appreciate.

Kudos on this effort, will be following closely and looking forward to what it can mean for (the unmitigated train wreck that is) Python dependency/environment management.

**Comment by zanieb** [comment]
The full project management workflow provided is on our roadmap. We've put the `pip` compatibility commands in a separate namespace explicitly so we have room for things like `uv install`.

**Comment by alelavelli** [comment]
Can you write an example of pyproject.toml for uv? Thank you

**Comment by imbev** [comment]
> Can you write an example of pyproject.toml for uv? Thank you

```toml
# pyproject.toml

[project]
name = "my-project"
version = "0.1.0"
description = "my description"
authors = [
  {name = "My Name", email = "myemail@example.com"},
]
requires-python = ">= 3.11"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
```
