### ISSUE TITLE
Support for Dual Git/Editable Dependencies Configuration

### ISSUE THREAD

**Issue by heelee-amitai-hs** [astral-sh/uv#13655]
## Summary
We're looking for a way to support both Git dependencies and local editable dependencies for the same packages in UV, which would be essential for multi-package development workflows.

## Current Challenge

In development environments with multiple interconnected packages, developers need to switch between:
1. **Git dependencies** for normal development (using specific tags/branches)
2. **Local editable dependencies** when actively developing multiple packages simultaneously

We're looking for a way to configure both options and choose between them at runtime rather than configuration time.

## Current Workflow in PDM

PDM allows us to work around this with separate dependency groups, though it's not the most elegant solution:

```toml
[project.optional-dependencies]
inner = [
    "package-a @ git+ssh://git@github.com/org/package-a.git@1.2.3",
    "package-b @ git+ssh://git@github.com/org/package-b.git@4.5.6",
]

[dependency-groups]
editable-inner = [
    "-e file:///${PROJECT_ROOT}/../package-a#egg=package-a",
    "-e file:///${PROJECT_ROOT}/../package-b#egg=package-b",
]
```

We can switch modes with different commands:
```bash
pdm sync -G inner           # Use Git dependencies
pdm sync -G editable-inner  # Use local editable dependencies
```

While this works, it requires maintaining the same packages in two different places.

## Current Approach in UV

We understand that `tool.uv.sources` defines one source per package. We can configure either:

Git source:
```toml
[tool.uv.sources]
"package-a" = { git = "ssh://git@github.com/org/package-a.git", tag = "1.2.3" }
```

Or editable path:
```toml
[tool.uv.sources]
"package-a" = { path = "../package-a", editable = true }
```

But not both simultaneously.

For editable dependencies, we've tried these approaches:

### Workaround 1: Runtime Configuration Modification
```bash
cp pyproject.toml pyproject.toml.backup
uv add --editable ../package-a --frozen
# ... work with editable
mv pyproject.toml.backup pyproject.toml
```

### Workaround 2: Bypass UV's Dependency Management
```bash
uv sync --group dev  # Install core dependencies
uv pip install -e ../package-a  # Bypass UV for editables
```

Both approaches are problematic:
- Option 1 is hacky and error-prone
- Option 2 breaks UV's dependency tracking

### Option A: Group-Based Sources
Allow sources to be associated with dependency groups:

```toml
[tool.uv.sources]
"package-a" = { git = "ssh://git@github.com/org/package-a.git", tag = "1.2.3" }

[tool.uv.sources.editable-group]
"package-a" = { path = "../package-a", editable = true }

[dependency-groups]
editable-group = ["package-a"]
```

Usage:
```bash
uv sync --extra inner           # Use Git sources
uv sync --group editable-group  # Use editable sources
```

### Option B: Multi-Source Support with Mode Selection
Allow multiple sources per package with runtime selection:

```toml
[tool.uv.sources]
"package-a" = [
    { git = "ssh://git@github.com/org/package-a.git", tag = "1.2.3", mode = "default" },
    { path = "../package-a", editable = true, mode = "editable" }
]
```

Usage:
```bash
uv sync --extra inner                    # Use default mode (Git)
uv sync --extra inner --editable-mode   # Use editable mode
```

## Use Cases

This feature is particularly valuable for:
- Organizations with multiple interdependent packages
- Development teams that frequently work across package boundaries
- CI/CD pipelines that need both modes for different stages
- Maintaining consistency between development and production dependencies

## Impact

Supporting this workflow would:
- Enable easier migration from PDM to UV for complex projects
- Improve developer experience in multi-package environments
- Maintain UV's dependency tracking benefits
- Reduce the need for hacky workarounds

## Additional Context

We're currently evaluating UV for migration from PDM across multiple projects, and this is our primary concern preventing adoption. The performance improvements UV offers are compelling, but losing this workflow capability is a significant consideration.

Would the UV team be open to implementing one of these approaches or discussing alternative solutions?
