### ISSUE TITLE
Presence of UV_CONFIG_FILE disables keyring provider in pyproject.toml

### ISSUE THREAD

**Issue by eegli** [astral-sh/uv#13752]
### Summary

Assume this pyproject.toml with `keyring-proivider = "subprocess"`:

```toml
[project]
name = "foo"
version = "1.0.0"
requires-python = ">=3.11, <4"
dependencies = []
[tool.uv]
keyring-provider = "subprocess"
```

and an **empty** `custom-uv.toml` in the same directory.

✅ Keyring is picked up from pyproject.toml when no config file is specified:
```sh
uv sync --show-settings | grep keyring
>             keyring_provider: Subprocess,
```
❌ Specifying a config file with no keyring sets `keyring_provider` to disabled:
```sh
uv sync --config-file custom-uv.toml --show-settings | grep keyring
>            keyring_provider: Disabled,
```
likewise
```sh
UV_CONFIG_FILE=custom-uv.toml uv sync --show-settings | grep keyring
>            keyring_provider: Disabled,
```
This is related to #13490.
 

### Platform

MINGW64_NT-10.0-26100 3.5.7-463ebcdc.x86_64 x86_64 Msys

### Version

uv 0.7.8 (0ddcc1905 2025-05-23)

### Python version

3.13
