### ISSUE TITLE
A package (`RoboVerse`) can only be installed with editable flag with `uv add` but can be installed with both editable and no-editable flag with `uv pip install`.

### ISSUE THREAD

**Issue by YouJiacheng** [astral-sh/uv#13843]
### Summary

`RoboVerse` can only be installed with editable flag with `uv add` but can be installed with both editable and no-editable flag with `uv pip install`. (All are local installations)

I want to know why.

Its `pyproject.toml` is here:
https://github.com/RoboVerseOrg/RoboVerse/blob/main/pyproject.toml

When I `uv sync` with following `pyproject.toml` (with above repo cloned into `RoboVerse`), it will install `roboverse_py-0.1.17.dist-info` into `site-packages`.
```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "roboverse-py",
]

[tool.uv.sources]
roboverse-py = { path = "RoboVerse", editable = true }

```
but if I removed `editable = true` and `uv sync` again, it will remove it.
```
Uninstalled 1 package in 1ms
 - roboverse-py==0.1.17 (from file:///.../RoboVerse)
```

If I run `uv pip install ./RoboVerse`, it will install `metasim` into `site-packages`.
If I run `uv pip install -e ./RoboVerse`, it will install `roboverse_py-0.1.17.dist-info`  into `site-packages`.

I suspect this is caused by the name mismatch?

### Platform

Linux 5.15.0-136-generic x86_64 GNU/Linux

### Version

uv 0.7.10

**Comment by charliermarsh** [comment]
Hmm, I think it's because the package doesn't have a `[build-system]` on it, and so we treat it as a "virtual" package when used as a dependency in the project APIs (`uv sync`, etc.). We're probably going to change the default around that in the future.

You can use:

```toml
[tool.uv.sources]
roboverse-py = { path = "RoboVerse", package = true }
```
