### ISSUE TITLE
uv 7.0 introduces 401 errors with developing private package projects

### ISSUE THREAD

**Issue by ketozhang** [astral-sh/uv#13856]
### Summary

This feature was introduced by https://github.com/astral-sh/uv/pull/12805 where ...

> When using the [first-index strategy](https://docs.astral.sh/uv/configuration/indexes/#searching-across-multiple-indexes), uv will stop searching across indexes if an HTTP 401 Unauthorized or HTTP 403 Forbidden status code is encountered. The one exception is that uv will ignore 403s when searching the pytorch index (since this index returns a 403 when a package is not present).
> — https://docs.astral.sh/uv/configuration/indexes/#ignoring-error-codes-when-searching-across-indexes

The implementation however forces any project that is intended to be uploaded to a private package index to either always be authenticated while developing (e.g., during editable installs) or to add a `ignore-error-codes = [401]` to your `[[tool.uv.index]]` array. The first choice is inconvenient and the second choice opts out of this security feature: to avoid installing similarly named private packages from pypi.org.

Here's an example. Notice there are no dependencies and this package is intended to be published to `private-index`. I expected to still be able to develop this project since I have the source code.

```toml
[project]
name = "my-private-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
name = "private-index"
url = "https://my.private.pypi.com/simple/"  
publish-url = "https://my.private.pypi.com"  
```

```
# Reproduced if the index url exists and return 401
$ uv sync
  × No solution found when resolving dependencies:
  ╰─▶ Because my-private-package was not found in the package registry and your project depends on mypackage, we can conclude that your project's requirements are
      unsatisfiable.

      hint: An index URL (https://my.private.pypi.com/simple/) could not be queried due to
      a lack of valid authentication credentials (401 Unauthorized).
```

### Platform

Darwin 24.4.0 x86_64

### Version

uv 0.7.10 (Homebrew 2025-06-03)

### Python version

Python 3.12.10
