### ISSUE TITLE
`uv add --index <name>` assumes a path in the local directory as the index?

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#13874]
### Summary

```
❯ uv init example
Initialized project `example` at `/Users/zb/workspace/uv/example`
❯ cd example
❯ uv add requests --index test
Using CPython 3.13.2
Creating virtual environment at: .venv
Resolved 6 packages in 3ms
Installed 5 packages in 5ms
 + certifi==2025.4.26
 + charset-normalizer==3.4.2
 + idna==3.10
 + requests==2.32.3
 + urllib3==2.4.0
```

results in

```toml
[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "requests>=2.32.3",
]

[[tool.uv.index]]
url = "file:///Users/zb/workspace/uv/example/test"
```

### Platform

macOS

### Version

0.7.10

### Python version

n/a
