### ISSUE TITLE
uv rebuilds dependencies if they take too long to install

### ISSUE THREAD

**Issue by saagarjha** [astral-sh/uv#13896]
### Summary

Some dependencies take a long time to install. For example, installing PyTorch from source (yes, I know it doesn't work out of the box with build isolation: just bear with me). Most packages from pypi have a max-age for 600 seconds, so if the build takes longer than this uv will consider them to be stale and trigger another build for anything that depends on them. This seems undesirable. I understand the idea of respecting the header but it seems really odd to me that you wouldn't consider the dependency to be valid across a single command-line invocation.

I've attached a log with an attempt at building PyTorch. Again, I understand that PyTorch installs are not supported by uv at the moment. My concern is solely why it goes around to build it again once it's finished resolving packages.

If you want to reproduce this, here's my pyproject.toml:

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
]

[tool.uv.sources]
torch = { path = "deps/pytorch", editable = true }
```

Just dump a fresh PyTorch clone into the folder. But I think this is really more a problem with any build that takes forever, so take your pick of a large project. That said, here's a log: [log.txt](https://github.com/user-attachments/files/20636932/log.txt)

### Platform

Ubuntu 22.04 arm64

### Version

uv 0.7.12

### Python version

Python 3.10.12
