### ISSUE TITLE
Dependency resolver says no version available, when there are

### ISSUE THREAD

**Issue by signed-log** [astral-sh/uv#13900]
### Summary

I setup the above pyproject to pull torch from pytorch rocm nightly

```toml
[project]
name = "comfyai"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[tool.uv.sources]
torch = { index = "pytorch-nightly-6.4" }
torchaudio = { index = "pytorch-nightly-6.4" }
torchvision = { index = "pytorch-nightly-6.4" }
pytorch-triton-rocm = { index = "pytorch-nightly-6.4" }

[[tool.uv.index]]
name = "pytorch-nightly-6.4"
url = "https://download.pytorch.org/whl/nightly/rocm6.4"
explicit = true

[[tool.uv.index]]
name = "pytorch-stable-6.3"
url = "https://download.pytorch.org/whl/rocm6.3"
explicit = true

[tool.uv]
index-strategy = "unsafe-best-match"
```

When I try running 

```bash
uv add --pre torch torchvision torchaudio
```
No solution found when resolving dependencies for split (python_full_version >= '3.12'):
  ╰─▶ Because there is no version of pytorch-triton-rocm{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.0+git96316ce5 and
      torch<=2.8.0.dev20250520+rocm6.4 depends on pytorch-triton-rocm{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.0+git96316ce5, we can conclude
      that torch<=2.8.0.dev20250520+rocm6.4 cannot be used.
      And because only the following versions of torch are available:
          torch==2.8.0.dev20250418+rocm6.4
          torch==2.8.0.dev20250419+rocm6.4
          torch==2.8.0.dev20250420+rocm6.4
          torch==2.8.0.dev20250421+rocm6.4
          torch==2.8.0.dev20250422+rocm6.4
          torch==2.8.0.dev20250423+rocm6.4
          torch==2.8.0.dev20250424+rocm6.4
          torch==2.8.0.dev20250425+rocm6.4
          torch==2.8.0.dev20250426+rocm6.4
          torch==2.8.0.dev20250427+rocm6.4
          torch==2.8.0.dev20250428+rocm6.4
          torch==2.8.0.dev20250430+rocm6.4
          torch==2.8.0.dev20250501+rocm6.4
          torch==2.8.0.dev20250502+rocm6.4
          torch==2.8.0.dev20250511+rocm6.4
          torch==2.8.0.dev20250512+rocm6.4
          torch==2.8.0.dev20250513+rocm6.4
          torch==2.8.0.dev20250514+rocm6.4
          torch==2.8.0.dev20250515+rocm6.4
          torch==2.8.0.dev20250516+rocm6.4
          torch==2.8.0.dev20250517+rocm6.4
          torch==2.8.0.dev20250518+rocm6.4
          torch==2.8.0.dev20250519+rocm6.4
          torch==2.8.0.dev20250520+rocm6.4
          torch==2.8.0.dev20250521+rocm6.4
          torch==2.8.0.dev20250522+rocm6.4
          torch==2.8.0.dev20250523+rocm6.4
          torch==2.8.0.dev20250524+rocm6.4
          torch==2.8.0.dev20250525+rocm6.4
          torch==2.8.0.dev20250526+rocm6.4
          torch==2.8.0.dev20250527+rocm6.4
          torch==2.8.0.dev20250528+rocm6.4
          torch==2.8.0.dev20250529+rocm6.4
          torch==2.8.0.dev20250530+rocm6.4
          torch==2.8.0.dev20250531+rocm6.4
          torch==2.8.0.dev20250601+rocm6.4
          torch==2.8.0.dev20250602+rocm6.4
          torch==2.8.0.dev20250603+rocm6.4
          torch==2.8.0.dev20250604+rocm6.4
          torch==2.8.0.dev20250605+rocm6.4
          torch==2.8.0.dev20250606+rocm6.4
          torch==2.8.0.dev20250608+rocm6.4
      we can conclude that torch<2.8.0.dev20250521+rocm6.4 cannot be used. (1)

      Because there is no version of pytorch-triton-rocm{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.1+gitc8757738 and
      torch>=2.8.0.dev20250521+rocm6.4 depends on pytorch-triton-rocm{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.1+gitc8757738, we can conclude
      that torch>=2.8.0.dev20250521+rocm6.4 cannot be used.
      And because we know from (1) that torch<2.8.0.dev20250521+rocm6.4 cannot be used, we can conclude that all versions of torch cannot be used.
      And because your project depends on torch, we can conclude that your project's requirements are unsatisfiable.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.
```

[`pytorch-triton-rocm{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.3.0+git96316ce5`](https://download.pytorch.org/whl/nightly/pytorch_triton_rocm-3.2.0%2Bgitf9cdf582-cp313-cp313-linux_x86_64.whl) did exist at time of posting that issue.

Running

```
uv add pytorch-triton-rocm==3.3.0+git96316ce5
```

then 

```
uv add --pre torch torchvision torchaudio
```

makes pytorch install just fine

### Platform

Ubuntu 24.04

### Version

uv 0.7.10 (1e5120e15 2025-06-03)

### Python version

Python 3.13.3
