### ISSUE TITLE
Pulling wrong files from bitbucket

### ISSUE THREAD

**Issue by odellus** [astral-sh/uv#13923]
### Summary

I recently moved from an old CentOS system where I was able to successfully use a project by having my pyproject.toml file look like this

```toml
[project]
name = "test-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "repo_name @ git+ssh://git@bitbucket.org/my-development-team/repo_name.git@branch_name",
]

```

Worked like a charm on CentOS 7, but now I am seeing that uv is pulling the wrong files from bitbucket. Completely different files. Not the most recent commit to `branch_name`

Running on this version of Linux
```
Linux version 6.1.134-152.225.amzn2023.x86_64 (mockbuild@ip-10-0-33-51) (gcc (GCC) 11.5.0 20240719 (Red Hat 11.5.0-5), GNU ld version 2.41-50.amzn2023.0.3) #1 SMP PREEMPT_DYNAMIC Wed May  7 09:10:59 UTC 2025
```

### Platform

Amazon Linux

### Version

 6.1.134-152.225.amzn2023.x86_64

### Python version

3.8.20
