### ISSUE TITLE
`uv remove` mixes dependencies' end-of-line comments

### ISSUE THREAD

**Issue by Lenormju** [astral-sh/uv#13966]
### Summary

Using current latest : `uv 0.7.12`

I have this pyproject.toml file :

```toml
[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3", # this is boto3
    "requests", # this is requests
]
```

When I do `uv remove requests`, then I get :

```toml
[project]
name = "toto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3", # this is requests
]
```

So it mixes up the comments between the two lines. 

I was expecting only one line removed, but got :

```diff
-    "boto3", # this is boto3
-    "requests", # this is requests
+    "boto3", # this is requests
```

This is probably linked to #8982. Maybe to #9856 too.

### Platform

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 GNU/Linux

### Version

0.7.12

### Python version

3.13
