### ISSUE TITLE
Using different index based on --extra flag

### ISSUE THREAD

**Issue by 4rrw** [astral-sh/uv#13961]
### Question

Is it possible to point uv to use different index for a package based on a flag passed to uv sync?
I would like to achieve something like this:
```toml
[tool.uv.sources]
torch = [
  { index = "rocm", marker = "extra == 'rocm'" },
  { index = "pytorch-cpu", marker = "extra == 'cpu'" },
]


[[tool.uv.index]]
name = "rocm"
url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4.1/"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
```
and then `uv sync --extra rocm` would install torch from rocm index.

**Comment by 4rrw** [comment]
I found a solution. Example for cuda because this radeon index would not work because of file structure in it.
```toml
[project.optional-dependencies]
cpu = [
  "torch",
]
cu121 = [
  "torch",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu121" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu121", extra = "cu121" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
```
`uv sync --extra cu121` would install cuda version

**Comment by 4rrw** [comment]
I found a solution. Example for cuda because this radeon index would not work because of file structure in it.
```toml
[project.optional-dependencies]
cpu = [
  "torch",
]
cu121 = [
  "torch",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu121" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu121", extra = "cu121" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
```
`uv sync --extra cu121` would install cuda version
