### ISSUE TITLE
default-groups are not scoped to their package

### ISSUE THREAD

**Issue by Gankra** [astral-sh/uv#14005]
### Summary

In a workspace if I have the root project with:

```toml
[dependency-groups]
alpha = ["pytest"]
beta = ["iniconfig"]

[tool.uv]
default-groups = ["alpha"]
```

and a child with

```toml
[dependency-groups]
alpha = ["sniffio"]
beta = ["sortedcontainers"]

[tool.uv]
default-groups = ["beta"]
```

`uv sync --all-packages` will install sniffio (child.alpha)
`uv sync --package child` will install sortedcontainers (child.beta)

This is because we only ever read default groups *once* from *a single pyproject.toml* (whichever we consider "the main one" for the operation) and then apply those *group names* to every single package the operation selects.

### Platform

all

### Version

all
