### ISSUE TITLE
How to set folder for `tool.uv.sources`?

### ISSUE THREAD

**Issue by hongbo-miao** [astral-sh/uv#14019]
### Question

```toml
[project]
name = "my-project"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "sglang[all]",
]

[tool.uv]
package = false
required-version = ">=0.6.0"

[tool.uv.sources]
sglang = { git = "https://github.com/sgl-project/sglang.git", branch = "main" }
```

This failed with

```sh
  × Failed to download and build `sglang @ git+https://github.com/sgl-project/sglang.git@main`
  ╰─▶ /home/hongbo-miao/.cache/uv/git-v0/checkouts/b454a06192129efd/8ab7d93c does not appear to be a Python project, as neither `pyproject.toml` nor `setup.py` are present in the directory
````

Because `sglang` is a mono repo, I need go to folder [sgl-kernel](https://github.com/sgl-project/sglang/tree/main/sgl-kernel)

How to set folder for `tool.uv.sources`? Thank you!

### Platform

Linux 6.11.0-26-generic x86_64 GNU/Linux

### Version

uv 0.7.8 (0ddcc1905 2025-05-23)
