### ISSUE TITLE
Introduce source preference for conflicting dependencies

### ISSUE THREAD

**Issue by j-adamczyk** [astral-sh/uv#14068]
### Summary

When declaring conflicts for multiple optional groups, I want to be able to select the order of preference. If then I want to install 2 groups with conflicting dependency, `uv` will select and install one that is more preferred. Adding an option to CLI for `--all-extras` to specify this would also be ok.

Use case is ML with PyTorch. I have multiple groups, e.g. `preprocessing`, `training`, `inference`. Only `training` uses GPU, all others use CPU. They need to be separated to enable building separate Docker containers. For development, I need to install everything locally, but with GPU. Currently, I have to specify separate options. With a lot of groups, this gets pretty inconvenient.

With current `uv` state, I have two options. First, push all PyTorch to separate optional group and install it separately. With many groups, this results in PyTorch far from the actual dependency group, making `pyproject.toml` hard to read. Also, I have to pass `--extra` to each group, and need to somehow specify what group uses what version, e.g. search with regex for "train" in dependency group name, which is really not intuitive nor readable. Second option is to use `extra` markers, e.g. specify dependency as `"torch==2.2.*; extra == 'pytorch-cpu'", add source, index, conflicts etc. as [in uv docs](https://docs.astral.sh/uv/guides/integration/pytorch/). Here, the problem is that I can't install all dependency groups at the same time, as PyTorch has conflict between groups.

I basically want to translate the Poetry workflow from https://github.com/python-poetry/poetry/issues/6409#issuecomment-1911735833. My Poetry `pyproject.toml` is:
```
[tool.poetry.group.train_model.dependencies]
torch = {version = "2.2.*", source = "pytorch-gpu", markers = "extra!='pytorch-cpu'"}

[tool.poetry.group.inference.dependencies]
torch = {version = "2.2.*", source = "pytorch-cpu", markers = "extra=='pytorch-cpu'"}

[tool.poetry.extras]
pytorch-cpu = []

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"
```

In Poetry, when I do `poetry sync`, it will prefer CPU version. However, if I only install `train_model` group, it will pick up the GPU source.

**Comment by konstin** [comment]
What about the following example from the docs:

```toml
[project]
name = "debug"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "torch>=2.7.0",
  "torchvision>=0.22.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

Additionally, you can include one extra in another extra:

```toml
[project]
name = "foo"
version = "0.1.0"

[project.optional-dependencies]
a = ["numpy"]
b = ["scipy", "foo[a]"]
```
