### ISSUE TITLE
Using extra's as markers

### ISSUE THREAD

**Issue by scarere** [astral-sh/uv#14090]
### Question

I'm curious if it is possible to use extra's as markers when defining sources but still install the package from pypi when the requirement is not met.

For example, I'd like to include `nnunetv2` as a project dependency, but optionally install from a git source when told to do so by the user. Based on the documentation it seemed that this would be possible using the extra's flag using something like this:
```toml
[project]
name = "example"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
     "nnunetv2>=2.6.2"
]

[project.optional-dependencies]
usegit = ["nnunetv2>=2.6.2"]

[tool.uv.sources]
nnunetv2 = { git = "link/to/fork/of/nnunet", tag = "custom tag", marker = "extra == 'usegit'"}
```

This however does not work. When I include `--extra usegit` in the `uv sync` command the package is installed from the git source, but when the extra is not included then `nnunetv2` is not installed at all and is removed from the repository. However based on the documentation I would expect it to always install nnunetv2, and to just switch the source when the marker condition is met. For some reason this is only an issue with the 'extra' marker. If I use the 'sys_platform` marker instead like in the example in the documentation, then the package is properly installed from pypi when then marker condition is not met, but installs from the alternate git source when the marker condition is met. 

Lastly, I noticed that in the working example with the 'sys_platform' marker, if I run `uv sync` and the marker condition is true (i'm on linux and i set the marker to "sys_platform == 'linux'") it installs from the git source, but then if I change the pyproject.toml file to make the marker condition false (marker = "sys_platform == 'darwin'") then uv does not recognize that nnunetv2 is installed from the 'wrong' source. It only installs from the correct source if I use the `--reinstall` flag. Would it be a desirable feature for uv to automatically recognize when packages that have dependencyy specifications are installed incorrectly?

Overall I'm just wondering if there is any way to install dependencies from different sources using a user flag, but still install from pypi by default if that flag is not passed by the user.

**Comment by zanieb** [comment]
Hm, something doesn't seem quite right here, e.g.

```toml
[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "httpx",
]

[project.optional-dependencies]
git = ["httpx"]

[tool.uv.sources]
httpx = { git = "https://github.com/encode/httpx.git", extra = "git" }
```

Always uses the git source. We'll look into this.

**Comment by zanieb** [comment]
I think this is a bug

**Comment by konstin** [comment]
CC @oconnor663 for the sources behavior

**Comment by charliermarsh** [comment]
@zanieb -- This works as expected if you use a package-level conflict... Like if you add:

```toml
[tool.uv]
conflicts = [[{ package = "example" }, { package = "example", extra = "git" }]]
```

Then you do indeed get the expected behavior. I guess that should work "automatically"?

**Comment by svetly-todorov** [comment]
@charliermarsh How did you verify that the package-level conflict produces the correct result? I'm trying to do something very similar (install pytorch from a different index when passing `--extra cpu`) and this is the error I'm seeing:

```
$ uv sync --locked --extra cpu --preview-features package-conflicts
Resolved 106 packages in 10ms
error: Extra `cpu` and package `example` are incompatible with the declared conflicts: {`example[cpu]`, example}
```

From this snippet of pyproject.toml:
```toml
[project.optional-dependencies]
cpu = [
    "torch",
    "sentence-transformers>=5.1.0",
]
gpu = [
    "sentence-transformers>=5.1.0",
]

[tool.uv]
conflicts = [[{ package = "example" }, { package = "example", extra = "cpu" }]]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu-index", extra = "cpu"},
]

[[tool.uv.index]]
name = "pytorch-cpu-index"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

Version:
```
$ uv self version
uv 0.8.22
```

**Comment by ameicler** [comment]
Encountering same issue, as described in duplicated #16379 ticket:

When using a source override with a marker like:

``` toml
[tool.uv.sources]
habitat-sim = { path = "...", marker = "extra == 'cuda'" } # e.g, `path. = "cuda/habitat_sim-0.3.3-cp310-cp310-linux_x86_64.whl"`
```
Expected: When marker doesn't match, fall back to registry
Actual: uv lock only captures the path source, ignores marker, and fails to install when marker is false

This prevents environment-specific wheel usage (CUDA vs CPU builds).

Platform
Linux 5.10.242-239.961.amzn2.x86_64 x86_64 GNU/Linux

Version
uv 0.9.4

Python version
Python 3.10.19
