### ISSUE TITLE
How to pin a specific cuda version?

### ISSUE THREAD

**Issue by sorenwacker** [astral-sh/uv#14129]
### Question

I need a specific CUDA version on my deployment system, but I cannot figure out how to do this properly.
My pyproject.toml has these relevant entries:

```
dependencies = [
  ...
  "torch~=2.7.1",
  "torchvision~=0.22.1",
  "torchaudio~=2.7.1",
  "torchmetrics~=1.7.3",
  ...
]

...

[tool.uv.sources]
nx-cugraph-cu12 = { index = "nvidia" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[[tool.uv.index]]
name = "torch-gpu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

```

But when I deploy this I get:

```
uv run python -c "import torch; print(f'Torch: {torch.__version__}, CUDA available: {torch.cuda.is_available()}, CUDA version: {torch.version.cuda}')"
Torch: 2.7.1+cu126, CUDA available: True, CUDA version: 12.6
```

What am I doing wrong?

### Platform

Ubuntu

**Comment by charliermarsh** [comment]
You should add:

```toml
[tool.uv.sources]
torch = { index = "torch-gpu" }
torchvision = { index = "torch-gpu" }
torchaudio = { index = "torch-gpu" }
torchmetrics = { index = "torch-gpu" }
```

Since `torch-gpu` is marked as `explicit = true`, it will _only_ be used for dependencies that are assigned to it explicitly.
