### ISSUE TITLE
Caching does not work when using an extra index

### ISSUE THREAD

**Issue by pschmutz** [astral-sh/uv#14121]
### Summary

I have the following `pyproject.toml`

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = []

[[tool.uv.index]]
url = "https://pypi.nvidia.com"

```

If I then execute

```bash
uv add nvidia-nvjitlink-cu12
uv remove nvidia-nvjitlink-cu12
uv add nvidia-nvjitlink-cu12
```

The package is downloaded twice. I would expect that it is found in the cache and not downloaded. Please note that this happens with several other packages as well, I just picked a smaller one to reproduce this. I originally found this when installing 

```bash
uv add 'isaacsim[all,extscache]==4.5.0'
```

I attached the verbose output of the commands listed above.

[uv_output.txt](https://github.com/user-attachments/files/20785422/uv_output.txt)

### Platform

Ubuntu 24.04

### Version

uv 0.7.13

### Python version

Python 3.10.0
