### ISSUE TITLE
`tool.uv.sources.editable` not respected when conditional on `group`

### ISSUE THREAD

**Issue by SpencerMcO** [astral-sh/uv#14139]
### Summary

**Summary:**
I have a dependency in my `tool.uv.sources` section of my `pyproject.toml`, and I'm providing two entries for that dependency - one where `editable = true` using `group = 'dev'` and one where `editable = false` using `group = 'container'`. When I run `uv sync` (which includes the `dev` dependency group by default), everything works as expected - the dependency is installed in editable mode. However, when I run `uv sync --no-dev --group container`, nothing happens. It seems to think the dependency is already installed as intended. Even if I delete and recreate the virtual environment and run `uv sync --no-dev --group container`, it installs my dependency as an editable install, despite the explicit `editable = false` flag I gave it.

**Details & Minimal Reproduction:**
I have a monorepo where there's a "utils" folder/package I'm trying to install into each of the other "services" or apps in the monorepo. The folder structure/layout can be seen below:
```sh
foo
├── services
│   └── myapp
│       ├── main.py
│       ├── pyproject.toml
│       ├── README.md
│       └── uv.lock
└── utils
    ├── pyproject.toml
    ├── README.md
    ├── src
    │   └── utils
    │       ├── __init__.py
    │       └── main.py
    └── uv.lock
```

The `utils` directory was created with `uv init --package utils` and has the default files and layout. The only modifications I made were (1) moving the "hello world" code from the `__init__.py` to a `main.py`, (2) changing the "hello world" string that's printed, and (3) calling the main function within `if __name__ == '__main__':`.

The `myapp` directory was created with `uv init myapp`. The only changes I made to this directory include (1) modifying the `main.py`:
```python3
from utils.main import main as utils_main

def main():
    print("Hello from myapp!")
    utils_main()


if __name__ == "__main__":
    main()
```

(2) adding the `utils` dir as an editable dependency: `uv add --editable ../../utils`; and (3) updating the `pyproject.toml` to indicate dependency groups, conflicts, and a non-editable install of `utils` if the `container` dependency group was used:
```toml
[project]
name = "myapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "utils",
]

[dependency-groups]
dev = ["utils"]
container = ["utils"]

[tool.uv]
conflicts = [[{ group = 'dev' }, { group = 'container' }]]

[tool.uv.sources]
utils = [{ path = "../../utils", editable = true, group = 'dev' }, { path = "../../utils", editable = false, group = 'container' }]
```

Once all of this is set up, you can run `uv sync` to install the `dev` dependency group, and you can run `uv run main.py` from the `myapp` directory to verify it works. You can also modify the print statement inside of the `foo/utils/src/utils/main.py` file and re-run `uv run main.py` inside the `myapp` directory to verify that the print statement updates without needing to reinstall `utils`.

Next, we come to the issue - if you run `uv sync --no-dev --group container`, that should remove the `dev` dependency group's dependencies and install the `container` group's dependencies, which SHOULD install `utils` as a non-editable dependency. However, when I change the print statement in the `utils` script and run `uv run --no-sync main.py` from the `myapp` folder,  then the print statement changes when it shouldn't (since `utils` shouldn't be an editable dependency now).

Interestingly, if I comment out the line in the `myapp/pyproject.toml` that indicates `editable = true` (as seen below) and try running `uv sync --no-dev --group container` again, and then repeat the tests from the prior paragraph, THEN I get the behavior I expected - the print statement logged to the console doesn't change despite my edits to the `utils/src/utils/main.py` script.

```toml
[project]
name = "myapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "utils",
]

[dependency-groups]
dev = ["utils"]
container = ["utils"]

[tool.uv]
conflicts = [[{ group = 'dev' }, { group = 'container' }]]

[tool.uv.sources]
utils = [
#	{ path = "../../utils", editable = true, group = 'dev' },
	{ path = "../../utils", editable = false, group = 'container' }
]
```

### Platform

macOS 15 arm64

### Version

uv 0.7.13

### Python version

Python 3.12.8
