### ISSUE TITLE
Seeking for suggestions to install axolotl

### ISSUE THREAD

**Issue by hongbo-miao** [astral-sh/uv#14178]
### Question

I recently try to install axolotl by

pyproject.toml

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl==0.10.0",
  "torch==2.7.1",
]

[tool.uv]
package = false
required-version = ">=0.6.0"

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

`uv sync` will return error

```sh
  × No solution found when resolving dependencies for split (python_full_version >= '3.11.0' and python_full_version < '3.12' and sys_platform == 'linux'):
  ╰─▶ Because axolotl==0.10.0 depends on torch==2.6.0 and your project depends on axolotl==0.10.0, we can conclude that your project depends on torch==2.6.0.
      And because your project depends on torch==2.7.1, we can conclude that your project's requirements are unsatisfiable.
error: Recipe `uv-install-dependencies` failed on line 5 with exit code 1
```

However, based on https://github.com/axolotl-ai-cloud/axolotl/issues/2812#issuecomment-2991192914
they requires installing `torch==2.7.1` first and then `axolotl`.

I am trying to install by `uv sync` instead of `uv pip install xxx`.
I am wondering is this something axolotl side need improve or uv side have a way for this partical case? Thank you! ☺️

### Platform

Linux 6.11.0-26-generic x86_64 GNU/Linux

### Version

uv 0.7.13 (62ed17b23 2025-06-12)

**Comment by FishAlchemist** [comment]
https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata
I looked through the documents, and perhaps this could solve your problem, though it might mean losing cross-platform capability. But I think this should work as a temporary solution.
You could also look for relevant content in the documents; perhaps there's a better way.
```toml
[[tool.uv.dependency-metadata]]
name = "axolotl"
version = "0.10.0"
requires-dist = ["torch==2.7.1"]
```
Run on Google Colab
![Image](https://github.com/user-attachments/assets/fa832004-ed73-4ba9-9e0a-8de737ee139d)

**Comment by hongbo-miao** [comment]
Thank you @FishAlchemist !
I found to be able to run

```sh
uv run axolotl fetch examples
uv run axolotl preprocess examples/qwen3/8b-qat-fsdp2.yml
uv run axolotl train examples/qwen3/8b-qat-fsdp2.yml
```

I need do

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl==0.10.0",
  "deepspeed==0.17.1",
  "flash-attn==2.8.0.post2",
  "torch==2.7.1",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
no-build-isolation-package = ["flash-attn"]

[[tool.uv.dependency-metadata]]
name = "axolotl"
version = "0.10.0"
requires-dist = [
  "torch==2.7.1",
  "colorama==0.4.6",
  "click==8.2.1",
  "python-dotenv==1.1.0",
  "requests==2.32.4",
  "pydantic==2.11.7",
  "transformers==4.52.4",
  "bitsandbytes==0.46.0",
  "peft==0.15.2",
  "addict==2.4.0",
  "fastcore==1.8.4",
  "datasets==3.6.0",
  "pillow==11.2.1",
  "fire==0.7.0",
  "numba==0.61.2",
  "axolotl-contribs-lgpl==0.0.6",
  "hf-transfer==0.1.9",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

Note

1. `"axolotl[flash-attn,deepspeed]==0.10.0"` does not help install `flash-attn` and `deepspeed` when provide `[[tool.uv.dependency-metadata]]` for `axolotl`. So I provide `"deepspeed==0.17.1"` and `"flash-attn==2.8.0.post2"` under `dependencies`.
2. When I provide `"torch==2.7.1"` under `dependencies`, it will install newer versions:
```
 - nvidia-cublas-cu12==12.6.4.1
 + nvidia-cublas-cu12==12.8.3.14
 - nvidia-cuda-cupti-cu12==12.6.80
 + nvidia-cuda-cupti-cu12==12.8.57
 - nvidia-cuda-nvrtc-cu12==12.6.77
 + nvidia-cuda-nvrtc-cu12==12.8.61
 - nvidia-cuda-runtime-cu12==12.6.77
 + nvidia-cuda-runtime-cu12==12.8.57
 - nvidia-cudnn-cu12==9.5.1.17
 + nvidia-cudnn-cu12==9.7.1.26
 - nvidia-cufft-cu12==11.3.0.4
 + nvidia-cufft-cu12==11.3.3.41
 - nvidia-cufile-cu12==1.11.1.6
 + nvidia-cufile-cu12==1.13.0.11
 - nvidia-curand-cu12==10.3.7.77
 + nvidia-curand-cu12==10.3.9.55
 - nvidia-cusolver-cu12==11.7.1.2
 + nvidia-cusolver-cu12==11.7.2.55
 - nvidia-cusparse-cu12==12.5.4.2
 + nvidia-cusparse-cu12==12.5.7.53
 - nvidia-nvjitlink-cu12==12.6.85
 + nvidia-nvjitlink-cu12==12.8.61
 - nvidia-nvtx-cu12==12.6.77
 + nvidia-nvtx-cu12==12.8.55
```

However, I still met

> CUDA error: an illegal memory access was encountered

but I think this is out of scope of this issue.

I am wondering if the author of axolotl could provide something like unsloth https://github.com/unslothai/unsloth/blob/db8185dd114b799256e5429fbc1708418b54e944/pyproject.toml#L342-L346

```toml
[project.optional-dependencies]
cu128-torch270 = [
    "unsloth[huggingface]",
    "bitsandbytes>=0.45.5",
    "unsloth[cu128onlytorch270]",
]
```

so I can install by `unsloth[cu128-torch270]` for certain torch version.

I posted the question at https://github.com/axolotl-ai-cloud/axolotl/issues/2812#issuecomment-2993483933

But if anyone has better suggestions, please let me know, thank you! ☺️

**Comment by FishAlchemist** [comment]
@hongbo-miao It seems that using ``override-dependencies`` works too.
https://docs.astral.sh/uv/concepts/resolution/#dependency-overrides
```toml
[tool.uv]
override-dependencies = ["torch==2.7.1"]
```

By the way, the ``no build isolation`` flag that https://github.com/axolotl-ai-cloud/axolotl/issues/2812#issuecomment-2991192914 mentioned actually exists in uv, but it seems to be more useful with uv pip.
I can't find a way to make it work properly with ``uv sync``.
https://docs.astral.sh/uv/reference/environment/#uv_no_build_isolation

**Comment by hongbo-miao** [comment]
Thank you @FishAlchemist ! Now it is much cleaner!

```toml
[project]
name = "hm-axolotl"
version = "1.0.0"
requires-python = "~=3.11.0"
dependencies = [
  "axolotl[deepspeed]==0.10.0",
  "flash-attn==2.8.0.post2",
]

[tool.uv]
package = false
required-version = ">=0.6.0"
no-build-isolation-package = ["flash-attn"]
override-dependencies = ["torch==2.7.1"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
```

Note, `no-build-isolation-package = ["flash-attn"]` does not work on `axolotl[deepspeed,flash-attn]`, so I add `"flash-attn==2.8.0.post2"` individually under `dependencies`.

I think I can close for now. Thanks!
