### ISSUE TITLE
Install package via wheel

### ISSUE THREAD

**Issue by GitRon** [astral-sh/uv#14257]
### Question

Hi there!

I need to install a uv lockfile which contains `python-ldap` which I have to install manually via a wheel file on windows. I checked the docs but couldn't find a way of telling this to uv.

When I run `uv sync --frozen`, the setup fails and that's it.

Anything that I can do differently?

Thx in advance ❤ 

### Platform

Windows 11

### Version

0.7.6

**Comment by charliermarsh** [comment]
Can you share the `pyproject.toml`? Typically, you'd add something like:

```toml
[tool.uv.sources]
python-ldap = { path = "./path/to/wheel" }
```

**Comment by GitRon** [comment]
Hi @charliermarsh 

thx for the fast reply! ❤ 

That's a good idea, I'll try this out. My - and probably others, too - use case is that I have a unix based Docker image but I want to install the packages locally, too for performance and simplicity reasons. In other package managers this package will just be ignored and I can install it manually.

Here, the process fails and I can't continue. Can you think of a way of making my edge case work?

Thx!

**Comment by GitRon** [comment]
````toml
[tool.uv.sources]
python-ldap = { path = "./path/to/wheel" }
````

Works like a charm! Would be awesome to have some kind of condition so I can commit it but still: It works.
