### ISSUE TITLE
Cannot specify multiple uv.sources which depend on platform markers

### ISSUE THREAD

**Issue by adstalla** [astral-sh/uv#14289]
### Summary

Hi all, I'm trying to build an application using pytorch which will be distributed to multiple platforms.
I'm trying to write my pyproject.toml so that it /just works/ for my team, where we develop and deploy to both x86 and aarch64.

I have found some prebuilt Jetson Orin wheels from dustynv over at https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048

I have the following in my pyproject.toml:

```toml
[project]
dependencies = [
    "torch>=2.3.0",
    "torchvision>=0.20.0",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
override-dependencies = [
    "torch==2.3.0; platform_machine == 'aarch64'",
    "torchvision>=0.18.0; platform_machine == 'aarch64'",
]

[[tool.uv.index]]
name = "pytorch-stable-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { path = "whl/torch-2.3.0-cp310-cp310-linux_aarch64.whl", marker = "sys_platform == 'aarch64'" }
torchvision = { path = "whl/torchvision-0.18.0a0+6043bc2-cp310-cp310-linux_aarch64.whl", marker = "sys_platform == 'aarch64'" }
torch = { index = "pytorch-stable-cu128", marker = "sys_platform == 'x86_64'" }
torchvision = { index = "pytorch-stable-cu128", marker = "sys_platform == 'x86_64'" }
```

The gist of what I'm trying to do here is:
- make uv use pytorch cu128 repository for x86
- make uv use my local prebuilt wheel for aarch64

The problem with this toml of course is that I have duplicate keys in `tool.uv.sources`. For now I am mostly OK just leaving out the x86 declaration, but I'm imaging at some point I will want to add cpu only support for say `darwin` platform, etc. I feel like I'm not seeing a proper mechanism to leverage platform markers when specifying my build sources.

Could I get some guidance on whether I am using uv the way its intended here, and if there is a common strategy others are using to solve multi-arch pyproject configuration?
