### ISSUE TITLE
Allow specifying tool.uv.default-groups only used by workspace members

### ISSUE THREAD

**Issue by genevieve-me** [astral-sh/uv#14377]
### Summary

We have a UV workspace which contains a library and some non-package projects which use that library. By non-package project I mean things like Flask apps which don't have a build backend and don't define `dependencies` in pyproject.toml.

For these apps we use we are now using `dependency-groups` to declare their dependencies, and use UV's excellent guide on building containers to package them. There doesn't seem to be a standard name for this use case, so their `pyproject.toml` uses the group name `main`, like so:

```toml
[project]
name = "something"
version = "2.3.4"
requires-python = ">=3.12"

[dependency-groups]
main = ["sth-lib"]
```

And the workspace pyproject.toml (which I believe is pretty standard) looks like:

```toml
[project]
name = "internal-workspace"
version = "1.2.3"
requires-python = ">=3.12"
dependencies = []
license = "LicenseRef-Proprietary"

[tool.uv.sources]
something = { workspace = true }
sth-lib = { workspace = true }

[tool.uv.workspace]
members = ["apps/something", "libs/sth-lib"]
```

When using `uv` to prepare the virtual environment for one of these apps, we use a command like `uv sync --package something --group main`, which works well.

For local development, however, we want to install all main dependencies, but without using `--all-groups`. We wanted to add `main` to `tool.uv.default-groups` for this reason and avoid passing `--group main` to all our commands:

```toml
[tool.uv] # in the workspace pyproject.toml
default-groups = ["dev", "main"]
```

However, this causes uv to fail with: `error: Default group `main` (from `tool.uv.default-groups`) is not defined in the project's `dependency-groups` table`.

This is kind of surprising, because `--group main` did not require that group to be defined for the workspace root, only for some (not all) workspace members. Would it be possible to remove the requirement for `default-groups` to be defined at the top level?

### Example

A better experience for enabling certain dependency-groups by default in uv workspaces; please see above.

**Comment by genevieve-me** [comment]
I should note that there is a pretty simple workaround of just defining an empty `main` under `[dependency-groups]` in the workspace `pyproject.toml`:

```toml
[dependency-groups]
dev = [ "ruff~=0.12.1" ]
main = []
```
