### ISSUE TITLE
Can't compile pyproject.toml to requirements.txt

### ISSUE THREAD

**Issue by Pixel-Minions** [astral-sh/uv#1619]
Hi,

I am running issues with the compilation of pyproject.toml to requirements.txt, I am using:
`uv pip compile pyproject.toml -o requirements.txt.

![image](https://github.com/astral-sh/uv/assets/1145623/ad32cf05-5ab6-4951-b1a0-a7d1160556f8)

This is the content of the toml:

```toml
[tool.poetry]
name = "test package"
version = "1.0.0"
description = "test team"
authors = ["test <test@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.29"
QtPy = "^2.4"
Fileseq = "^1.15"
sentry-sdk = "^1.35"
qtmodern = "^0.2"
pystray = "^0.19"
rpyc = "^5.3"
```
