### ISSUE TITLE
`uv pip compile` does not respect `tool.setuptools.dynamic` dependencies

### ISSUE THREAD

**Issue by adamtheturtle** [astral-sh/uv#1644]
With the following files, `pip-compile` output includes the `ruff` dependency, `uv pip compile` does not:

`pyproject.toml`:

```toml
[project]
name = "demo-project"
version = "0.1"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
```

`requirements.txt`:

```
ruff
```

`pip-compile` includes `ruff`:

```
> pip-compile pyproject.toml
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile pyproject.toml
#
ruff==0.2.2
```

`uv` does not:

```
> uv pip compile pyproject.toml 
Resolved 0 packages in 174ms
# This file was autogenerated by uv v0.1.4 via the following command:
#    uv pip compile pyproject.toml
```

I expect `uv`'s behaviour to match `pip-compile`'s, or for the difference to be documented.

```
> pip-compile --version
pip-compile, version 7.4.0
> uv --version
uv 0.1.4
```
