### ISSUE TITLE
Changes to pyproject.toml dependency versions not updated on install

### ISSUE THREAD

**Issue by RonNabuurs** [astral-sh/uv#1913]
Say I have the following `pyproject.toml`

```toml
[project]
name = "example"
version = "0.0.0"
dependencies = [
  "httpcore==1.0.2"
]
requires-python = ">=3.8"
```

To create a venv I would run `uv venv`. This creates a venv in which I can install packages. For comparison I'll also install pip in that environment `uv pip install pip`. 

Now I can run the following command to create an editable install with httpcore installed:

```bash
uv pip install -e .
```

This results in an venv with httpcore and it's dependencies installed. 

Now comes the issue, when I change dep versions in the pyproject.toml uv will not reinstall that package. E.g.

Change the pyproject.toml to:
```toml
[project]
name = "example"
version = "0.0.0"
dependencies = [
  "httpcore==1.0.1"
]
requires-python = ">=3.8"
```

Run uv again `uv pip install -e .`. This results in 
```bash
Audited 1 package in 3ms
```

Though if I run the same command with pip it will reinstall the new version:
```
.venv/bin/pip install -e .

...
  Attempting uninstall: example
    Found existing installation: example 0.0.0
    Uninstalling example-0.0.0:
      Successfully uninstalled example-0.0.0
Successfully installed example-0.0.0 httpcore-1.0.1
```

**Comment by charliermarsh** [comment]
You can run with `--reinstall` to force uv to reinstall it.

**Comment by danielhollas** [comment]
Just noting that I have also ran into this yesterday with uv v0.1.8.
In my case I was changing dependencies in `setup.cfg` (`pyproject.toml` only containing the `build-system` table),
and `uv` was not picking up the changes upon subsequent invocations.

**Comment by charliermarsh** [comment]
I can improve this.

**Comment by charliermarsh** [comment]
For onlookers, we have a new API whereby you can add additional files to consider when invalidating the cache. You can also include the current Git commit (i.e., invalidate whenever the SHA changes).

Looks like this:

```toml
[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "requirements.txt" }, { git = true }]
```

See: https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata.
