### ISSUE TITLE
Recursive extra dependencies don't compile like pip-tools

### ISSUE THREAD

**Issue by jdawang** [astral-sh/uv#1987]
Essentially the same issue as https://github.com/jazzband/pip-tools/issues/1685. When you have a recursive extras in a `pyproject.toml` for a private project, `uv pip compile` fails. If the project is uploaded to an index, then it looks in the index first, but I'd expect it to prioritize the self-reference in `pyproject.toml`.

**Info**
- Platform: macOS Sonoma 14.3
- uv version: v0.1.10
- command: `uv pip compile pyproject.toml --extra=dev`

**Reproducible example (from pip-tools issue)**

Minimal `pyproject.toml`
```toml
[project]
name = "privateproject"
version = "0.0.1"
dependencies = [
    "tomli",
]

[project.optional-dependencies]
test = [
    "pep517",
]
dev = [
    "privateproject[test]",
]
```

With pip-tools, this is the output:
```bash
❯ pip-compile pyproject.toml --extra=dev
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --extra=dev pyproject.toml
#

pep517==0.13.1
    # via privateproject
privateproject[test] @ file:///...
    # via file:///...
tomli==2.0.1
    # via
    #   pep517
    #   privateproject
    #   privateproject (pyproject.toml)
```

With uv, this is the output:
```bash
❯ uv pip compile pyproject.toml --extra=dev
  × No solution found when resolving dependencies:
  ╰─▶ Because privateproject[test] was not found in the package registry and privateproject depends on privateproject[test], we can conclude that
      the requirements are unsatisfiable.
```
