### ISSUE TITLE
Unable to activate VIRTUAL_ENV when CONDA_PREFIX exists

### ISSUE THREAD

**Issue by YuShigurey** [astral-sh/uv#2028]
I'm trying out uv, together with [hatch-pip-compile](https://github.com/juftin/hatch-pip-compile) (and hatch). venv creation works fine, and speed is significantly faster, great!

Except when I try to run command with created virtual env, error raises

```
(base)  test-hatch-pip-compile$ hatch run default1:python
error: Both VIRTUAL_ENV and CONDA_PREFIX are set. Please unset one of them.
```

The error message is clean, that's great, and I can fix it on my computer in 5 seconds (conda deactivate).
I just wonder if there is any difficulty makes this "user action" necessary?

Here is the hatch.toml (very likely unrelated imo since hatch is just an invoker and after I deactivated conda environment everything looks ok)
```toml
[env]
requires = [
    "hatch-pip-compile",
]

[envs.default]
path = ".venv/default"

[envs.default1]
path = ".venv/default1"
type = "pip-compile"
pip-compile-installer = "uv"
pip-compile-resolver = "uv"
```

Thank you!
