### ISSUE TITLE
Cannot install extras from pyproject.toml and poetry

### ISSUE THREAD

**Issue by bschoenmaeckers** [astral-sh/uv#2801]
Given the following pyproject.toml, `uv pip install -r pyproject.toml` work great but  `uv pip install -r pyproject.toml --extra test` gives an error.
`error: Requested extra not found: test`

It feels like this is a bug.

```toml
[tool.poetry]
name = "poetry-extras"
version = "0.1.0"
description = ""
authors = ["Astral Software Inc. <hey@astral.sh>"]

[tool.poetry.dependencies]
python = "^3.10"
anyio = "^4"
pytest = { version = "*", optional = true }

[tool.poetry.extras]
test = ["pytest"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
