### ISSUE TITLE
potential breaking change / bug in `uv==0.1.30`

### ISSUE THREAD

**Issue by zzstoatzz** [astral-sh/uv#2941]
the following GHA step
```
- name: Install packages
  run: |
    python -m pip install -U uv
    uv pip install --upgrade --system -e .[dev]
```

started failing after the release of `0.1.30` with
```console
Run python -m pip install -U uv
Collecting uv
  Downloading uv-0.1.30-py3-none-manylinux_2_17_x86_64.manylinux20[14](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629#step:6:15)_x86_64.whl.metadata (26 kB)
Downloading uv-0.1.30-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 125.0 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.1.30

Notice:  A new release of pip is available: 23.0.1 -> 24.0
Notice:  To update, run: pip install --upgrade pip
Built 1 editable in 1.[17](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629#step:6:18)s
error: Attempted to wait on an unregistered task
Error: Process completed with exit code 2.
```

full CI [run](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629) (not much else as far as logs unfortunately)

pinning to `0.1.29` appeared to resolve the issue

---

#### more potentially useful context

we use the following step before the install step, pending `setup-python` support
```
      - name: UV Cache
        # Manually cache the uv cache directory
        # until setup-python supports it:
        # https://github.com/actions/setup-python/issues/822
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: uvcache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements-client.txt', 'requirements.txt', 'requirements-dev.txt') }}
```

---
I don't have a strong hypothesis for why this error is occurring, sorry. let me know if there's anything useful I can provide
