### ISSUE TITLE
GUI scripts open a terminal window

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/uv#2956]
GUI scripts, when installed via `uv pip` and launched from VS Code, open a terminal window. They should not do that. `pip` doesn't do it, either.

`pyproject.toml`
```toml
[project]
name = "bug"
version = "0.0.1"
dependencies = ["PySide6-Essentials"]

[project.gui-scripts]
bug = "bug.main:main"
```

`bug/main.py`
```python
from PySide6.QtWidgets import QApplication, QMainWindow

def main() -> None:
    print("Starting")
    app = QApplication()
    window = QMainWindow()
    window.show()
    app.exec()
```

```
pip install --force-reinstall . && bug
```

![image](https://github.com/astral-sh/uv/assets/12128514/d8968c6e-8c15-494f-ae75-0ff358aeb1c5)

```
uv pip install --force-reinstall . && bug
```

![image](https://github.com/astral-sh/uv/assets/12128514/b8b62c0b-d85f-4f59-b47d-f55ac6e9f356)

This is `uv 0.1.31 (7bcca28b1 2024-04-09)`.
