### ISSUE TITLE
uv pip compile --include-self

### ISSUE THREAD

**Issue by elbaro** [astral-sh/uv#3091]
Feature Request: Add `--include-self` option to `uv pip compile` so that the current package is added in the resulting `requirements.txt`.

With the pyproject.toml below, --include-self adds 'my-pkg' to requirements.txt. Then we can ship `requirements.txt` and `uv sync` to install my-app. This can be done outside uv, but --include-self looks cleaner.

```toml
[project]
name = "my-app"
dependencies = [
  "a",
  "b",
]
```
