### ISSUE TITLE
empty `requirements.txt` when importing from `pyproject.toml`

### ISSUE THREAD

**Issue by BBBmau** [astral-sh/uv#3817]
When attempting to import from an existing `pyproject.toml` file I get an empty generated `requirements.txt` file, for context I am currently attempting to import from using `poetry` to using `uv` which could be what's causing it. Is their currently a workaround for this?

`uv pip compile pyproject.toml -o requirements.txt`    # Read a pyproject.toml file.

uv version: `uv 0.2.2 (e52ae0e2b 2024-05-22)`

**Comment by konstin** [comment]
We don't support poetry's format currently, only the standardized (PEP 621) [`[project]` table](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements).

**Comment by charliermarsh** [comment]
It works as expected for me with:

```toml
[tool.poetry]
name = "poetry-test"
version = "0.1.0"
description = ""
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>"]
packages = [{ include = "poetry_test" }]

[tool.poetry.dependencies]
python = "^3.10.0"
anyio = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
