### ISSUE TITLE
feat: add a namespace in pyproject.toml for dependency override

### ISSUE THREAD

**Issue by Di-Is** [astral-sh/uv#3834]
Are there any plans to add a namespace in pyproject.toml that can be used with the dependency override feature?

For example, if we could add "tool.uv.override-dependencies" as follows and define the dependencies to be overridden, it would further improve the usability of uv.

```toml
[project]
name = "ml-frameworks"
version = "1.0.0"
dependencies = [
  "torch ==2.2.2",
  "torchvision >=0.17.0",
  "tensorflow[and-cuda] ==2.16.1",
  "jax[cuda12]==0.4.23"
]

[tool.uv]
override-dependencies = [
  "nvidia-cublas-cu12 == 12.3.4.1",
  "nvidia-cuda-cupti-cu12 == 12.3.101",
  "nvidia-cuda-nvcc-cu12 == 12.3.107",
  "nvidia-cuda-nvrtc-cu12 == 12.3.107",
  "nvidia-cuda-runtime-cu12 == 12.3.101",
  "nvidia-cudnn-cu12 == 8.9.7.29",
  "nvidia-cufft-cu12 == 11.0.12.1",
  "nvidia-curand-cu12 == 10.3.4.107",
  "nvidia-cusolver-cu12 == 11.5.4.101",
  "nvidia-cusparse-cu12 == 12.2.0.103",
  "nvidia-nccl-cu12 == 2.19.3",
  "nvidia-nvjitlink-cu12 == 12.3.101"
]

[tool.uv.sources]
# Pin a dependency for a specific registry.
torch = { index = "torch-cu121" }

# See "Indexes".
[tool.uv.indexes]
torch-cu121 = "https://download.pytorch.org/whl/cu121"
```
