### ISSUE TITLE
CI (Github Actions): Installed uv script does not detect any Python interpreters

### ISSUE THREAD

**Issue by jenisys** [astral-sh/uv#3861]
I try using `uv` to speed up Python package installations in the CI (concrete: Github Actions).

## SYNDROME:

When I use the following `workflow` snippet, I run into a problem that `uv` cannot find any Python interpreters.

```yaml
# -- CI WORKFLOW SNIPPET: With Python3
  ...
  - name: "Install Python package dependencies (with: uv)"
    run: |
      python -m pip install -U uv
      # -- FAILURE-POINT: On next line
      uv pip install -U pip setuptools wheel 
```

Running Github Actions CI causes errors on `ubuntu-latest` (hint: `windows` works fine):

```
...
Installing collected packages: uv
Successfully installed uv-0.2.4
error: No Python interpreters found in virtual environments
Error: Process completed with exit code 2.
```

SEE ALSO:
* https://github.com/jenisys/parse_type/actions/runs/9252100544

## WORK-AROUND

Use `uv` as python module to run `uv`, like:

```yaml
# -- CI WORKFLOW SNIPPET:
  - name: "Install Python package dependencies (with: uv)"
    run: |
      python -m pip install -U uv
      python -m uv pip install -U pip setuptools wheel
```
