### ISSUE TITLE
universal-lock: audit data structures to ensure they can handle multiple versions of the same package

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#3927]
Basically, it is suspected that there are some parts of our resolver that implicitly rely on the fact that there is only one version of a package available in resolution. This often leads to things like indexing on just package name. But we probably need to index on version (and possibly extra name?).

This was first brought up by @charliermarsh in https://github.com/astral-sh/uv/pull/3831#pullrequestreview-2086236974

**Comment by charliermarsh** [comment]
Here's an example failing `pyproject.toml` that should resolve:

```toml
[project]
name = "black"
version = "0.1.0"
description = "Default template for a Flit project"
authors = [
    {name = "konstin", email = "konstin@mailbox.org"},
]
dependencies = [
  "iniconfig @ https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl ; python_version >= '3.12'",
  "iniconfig @ https://files.pythonhosted.org/packages/9b/dd/b3c12c6d707058fa947864b67f0c4e0c39ef8610988d7baea9578f3c48f3/iniconfig-1.1.1-py2.py3-none-any.whl ; python_version < '3.12'"
]
requires-python = ">=3.11,<3.13"
license = {text = "MIT"}

[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"
```
