### ISSUE TITLE
uv lock: relative sdist for relative path dependencies

### ISSUE THREAD

**Issue by considerate** [astral-sh/uv#3965]
Given a `requirements.txt` file that includes a relative path to a directory containing a distribution:

```
../my-package
```

With `uv pip compile --unstable-uv-lock-file requirements.txt` the generated lock has the package resolved to absolute paths like the following:
```toml
[[distribution]]
name = "my-package"
version = "0.1.0"
source = "directory+file:///home/me/path/to/my-package"

[distribution.sdist]
url = "file:///home/me/path/to/my-package"
```

This is not ideal since I want to commit the lock file to a git repo shared with other people and they won't have the same directory structure I have.

1. Is it possible to update the lock files to instead retain the relative path that was specified in the requirements.txt file?
2. Is there any other way to declare relative path dependencies that would not have this absolute path resolution?
