### ISSUE TITLE
Marker expressions in lockfile should be simplified

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4002]
Not certain on this but in https://github.com/astral-sh/uv/pull/3998, the test I added yields an entry in the lockfile like:

```toml
[[distribution]]
name = "typing-extensions"
version = "4.7.1"
source = "registry+https://pypi.org/simple"
marker = "python_version < '3.8' or python_version < '3.11'"
```

The marker can be simplified to `python_version < '3.8'`.
