### ISSUE TITLE
`uv pip compile` perf regression in 0.2.6

### ISSUE THREAD

**Issue by blueraft** [astral-sh/uv#4040]
There's a significant performance regression in `uv 0.2.6` for projects that rely on [setuptools_scm](https://github.com/pypa/setuptools_scm/).

### MRE
1. Initialize a blank git repo.
2. Copy the following pyproject.toml.
```toml
[build-system]
requires = ["setuptools<69.3.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = 'foobar'
dynamic = ["version"]
requires-python = ">=3.9"

dependencies = ["flask"]

[tool.setuptools_scm]
```

Benchmarks from an Ubuntu machine (I am able to reproduce this on MacOS too):
1. `uv 0.2.6`
```sh
❯ uv --version
uv 0.2.6
❯ hyperfine 'uv pip compile pyproject.toml'
Benchmark 1: uv pip compile pyproject.toml
  Time (mean ± σ):     604.1 ms ±   5.2 ms    [User: 515.1 ms, System: 96.1 ms]
  Range (min … max):   596.4 ms … 611.8 ms    10 runs
```

2. `uv 0.2.5`
```sh
❯ uv --version
uv 0.2.5
❯ hyperfine 'uv pip compile pyproject.toml'
Benchmark 1: uv pip compile pyproject.toml
  Time (mean ± σ):      58.2 ms ±   1.3 ms    [User: 41.6 ms, System: 23.7 ms]
  Range (min … max):    55.1 ms …  61.0 ms    50 runs
```
