### ISSUE TITLE
Enforce constraints eagerly when forking on markers

### ISSUE THREAD

**Issue by blueraft** [astral-sh/uv#4099]
Despite specifying urllib3>=1.22.0 in my dependencies, uv lock traverses down to an incompatible version urllib3==1.2.1, which fails to build on my machine.

```toml
[project]
name = 'foobar'
dynamic = ["version"]
requires-python = ">=3.9, <4"

dependencies = [
  'urllib3>=1.22.0',
  'elasticsearch==7.17.1',
  'dockerspawner==13.0.0',
]
```

It works fine with `uv pip compile` though.
