### ISSUE TITLE
`==3.11.*` doesn't satisfy `Python>=3.11,<4`

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4132]
`requires-python = "==3.11.*"` doesn't satisfy `Python>=3.11,<4` for a project that depends on it, while `requires-python = ">=3.11, <4"` does an resolves without problem.

Example:

```toml
[project]
name = "warehouse"
version = "1.0.0"
requires-python = "==3.11.*"
# requires-python = ">=3.11, <4"
dependencies = [
  "linehaul",
]
```

```
$ cargo run -q -- lock --preview
  × No solution found when resolving dependencies:
  ╰─▶ Because the requested Python version (>=3.11.dev0, <3.12.dev0) does not satisfy Python>=3.11,<4 and all versions of linehaul depend
      on Python>=3.11,<4, we can conclude that all versions of linehaul cannot be used.
      And because only the following versions of linehaul are available:
          linehaul==1.0.0
          linehaul==1.0.1
      and warehouse==1.0.0 depends on linehaul, we can conclude that warehouse==1.0.0 cannot be used.
      And because only warehouse==1.0.0 is available and warehouse depends on warehouse, we can conclude that the requirements are
      unsatisfiable.

      hint: The `Requires-Python` requirement (>=3.11.dev0, <3.12.dev0) defined in your `pyproject.toml` includes Python versions that
      are not supported by your dependencies (e.g., all versions of linehaul only supports >=3.11, <4). Consider using a more restrictive
      `Requires-Python` requirement (like >=3.11, <4).
```
