### ISSUE TITLE
`uv lock` should not treat non-compliant `pyproject.toml` fields as dynamic

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4142]
e.g. with an invalid dependency section

```toml
[project.dependencies]
python = "^3.12"
msgspec = "^0.18.4"
twine = "^4.0.2"
hatchling = "^1.20.0"
chevron-blue = "^0.2.1"
setuptools = "^69.1.1"
pypiserver = { version ="^2.0.1", optional = true}
watchfiles = { version = "^0.21.0",  optional = true}
pyyaml = "^6.0.1"
```

`uv lock` happily locked this project because I had retained the Poetry dependency section too

```toml
[tool.poetry.dependencies]
python = "^3.12"
msgspec = "^0.18.4"
twine = "^4.0.2"
hatchling = "^1.20.0"
chevron-blue = "^0.2.1"
setuptools = "^69.1.1"
pypiserver = { version ="^2.0.1", optional = true}
watchfiles = { version = "^0.21.0",  optional = true}
pyyaml = "^6.0.1"
```

With verbose logs, I can see that the invalid data means that we treat the entire `pyproject.toml` as dynamic and presumably use the build backend (Poetry) to get the dependencies?

> `DEBUG No static pyproject.toml available for: packse @ file:///Users/zb/workspace/packse (DynamicPyprojectToml(Toml(Error { inner: Error { inner: TomlError { message: "invalid type: map, expected a sequence", raw: Some("[project]\nname = \"packse\"\nversion = \"0.0.0\"\ndescription = \"\"\nauthors = [\"Zanie <contact@zanie.dev>\"]\nreadme = \"README.md\"\nkeywords = [\n  \"uv\", \"packse\", \"requirements\", \"packaging\", \"testing\"\n]\nclassifiers = [\n  \"Development Status :: 4 - Beta\",\n  \"Environment :: Console\",\n  \"Intended Audience :: Developers\",\n  \"Operating System :: OS Independent\",\n  \"License :: OSI Approved :: MIT License\",\n  \"License :: OSI Approved :: Apache Software License\",\n  \"Programming Language :: Python\",\n  \"Programming Language :: Python :: 3.12\",\n  \"Programming Language :: Python :: 3 :: Only\",\n  \"Topic :: Software Development :: Quality Assurance\",\n  \"Topic :: Software Development :: Testing\",\n  \"Topic :: Software Development :: Libraries\",\n]\n\n\n[project.scripts]\npackse = \"packse.cli:entrypoint\"\n\n[project.dependencies]\npython = \"^3.12\"\nmsgspec = \"^0.18.4\"\ntwine = \"^4.0.2\"\nhatchling = \"^1.20.0\"\nchevron-blue = \"^0.2.1\"\nsetuptools = \"^69.1.1\"\npypiserver = { version =\"^2.0.1\", optional = true}\nwatchfiles = { version = \"^0.21.0\",  optional = true}\npyyaml = \"^6.0.1\"\n\n[project.optional-dependencies]\nindex = [\"pypiserver\"]\nserve = [\"pypiserver\", \"watchfiles\"]\n\n[tool.uv]\ndev-dependencies = [\n  \"syrupy>=4.6.0\",\n  \"pytest>=7.4.3\",\n  \"psutil>=5.9.7\",\n]\n\n[tool.poetry]\nname = \"packse\"\nversion = \"0.0.0\"\ndescription = \"\"\nauthors = [\"Zanie <contact@zanie.dev>\"]\nreadme = \"README.md\"\nkeywords = [\n  \"uv\", \"packse\", \"requirements\", \"packaging\", \"testing\"\n]\nclassifiers = [\n  \"Development Status :: 4 - Beta\",\n  \"Environment :: Console\",\n  \"Intended Audience :: Developers\",\n  \"Operating System :: OS Independent\",\n  \"License :: OSI Approved :: MIT License\",\n  \"License :: OSI Approved :: Apache Software License\",\n  \"Programming Language :: Python\",\n  \"Programming Language :: Python :: 3.12\",\n  \"Programming Language :: Python :: 3 :: Only\",\n  \"Topic :: Software Development :: Quality Assurance\",\n  \"Topic :: Software Development :: Testing\",\n  \"Topic :: Software Development :: Libraries\",\n]\n\n\n[tool.poetry.scripts]\npackse = \"packse.cli:entrypoint\"\n\n[tool.poetry.dependencies]\npython = \"^3.12\"\nmsgspec = \"^0.18.4\"\ntwine = \"^4.0.2\"\nhatchling = \"^1.20.0\"\nchevron-blue = \"^0.2.1\"\nsetuptools = \"^69.1.1\"\npypiserver = { version =\"^2.0.1\", optional = true}\nwatchfiles = { version = \"^0.21.0\",  optional = true}\npyyaml = \"^6.0.1\"\n\n[tool.poetry.extras]\nindex = [\"pypiserver\"]\nserve = [\"pypiserver\", \"watchfiles\"]\n\n[tool.poetry.group.dev.dependencies]\nsyrupy = \"^4.6.0\"\npytest = \"^7.4.3\"\nruff = \"^0.1.12\"\npsutil = \"^5.9.7\"\n\n[build-system]\nrequires = [\"poetry-core\"]\nbuild-backend = \"poetry.core.masonry.api\"\n\n[tool.ruff.lint]\nextend-select = [\"I\", \"W292\"]\npreview = true\nexclude = [\"src/packse/templates/**/*\", \"build/**/*\", \"dist/**/*\"]\n"), keys: ["project", "dependencies"], span: Some(786..1054) } } })))`
