### ISSUE TITLE
Support relative path wheel dependencies

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4355]
Currently, we only support locking relative path for directory and source dist dependencies. We need to also support relative paths for wheels. To implement this, we need to add the install path vs. lock path split to `PathBuiltDist`, just as we do with `PathSourceDist`.

Failing example:

```toml
[project]
name = "project"
version = "0.1.0"
dependencies = [
  "tqdm"
]
requires-python = ">=3.8"

[tool.uv.sources]
tqdm = { path = "./tqdm-4.66.4-py3-none-any.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

The lockfile entry should have the relative path, not the absolute path:

```toml
[[distribution]]
name = "tqdm"
version = "4.66.4"
source = { path = "/home/konsti/projects/uv/debug/dummy/tqdm-4.66.4-py3-none-any.whl" }
dependencies = [
    { name = "colorama", marker = "platform_system == 'Windows'" },
]
wheels = [
    { url = "file:///home/konsti/projects/uv/debug/dummy/tqdm-4.66.4-py3-none-any.whl", hash = "sha256:b75ca56b413b030bc3f00af51fd2c1a1a5eac6a0c1cca83cbb37a5c52abce644" },
]
```
