### ISSUE TITLE
Other dependencies in forked package are not filtered by fork markers

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4414]
With the dependencies below, we fork on anyio over `python_version`. Currently, b1 and b2 are part of both splits, even though we know that the `anyio==4.4.0` split does not include b2 (and `anyio==4.3.0` doesn't include b1). This can cause unnecessary conflicts through the transitive dependencies of b1 and b2

```toml
dependencies = [
  # Force a split
  "anyio==4.4.0 ; python_version >= '3.12'",
  "anyio==4.3.0 ; python_version < '3.12'",
  "b1 ; python_version >= '3.12'",
  "b2 ; python_version < '3.12'",
]
```
