### ISSUE TITLE
Allow `uv add` to specify optional dependency groups

### ISSUE THREAD

**Issue by blueraft** [astral-sh/uv#4585]
I didn't see an issue related to this so figured I'd create one.

`pdm` allows extra dependency groups by  by providing -G/--group <name> option, similar functionality for `uv` would be nice to have.

[pdm reference](https://pdm-project.org/en/latest/usage/dependency/#add-dependencies)

**Comment by charliermarsh** [comment]
I think you should rephrase the issue around supporting dependency groups if that's what you're looking for. We started with a single dev dependency group for simplicity (though internally it's implemented more generically) and `uv add` already supports `--dev`. So the request here is really around supporting multiple dependency groups. We want to get more signal on why that's necessary before increasing the user complexity.

**Comment by blueraft** [comment]
I think this is not really about dependency groups as in poetry, if that's what you're referring to here.

This is about adding additional dependencies to extra groups defined in `optional-dependencies`. 

```toml
[project]
name = "foo"
version = "0.1.0"
dependencies = ["requests"]

[project.optional-dependencies]
scraping = ["beautifulsoup4"]
```

In the above case `pdm add -G scraping selenium` adds `selenium` to the scraping group.

```toml
[project]
name = "foo"
version = "0.1.0"
dependencies = ["requests"]

[project.optional-dependencies]
scraping = [
    "beautifulsoup4",
    "selenium>=4.22.0",
]
```

Of course it's fine not to support that, I can manually add it in the toml file.
