### ISSUE TITLE
No error when version specifier doesn't match requirement source

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#4604]
Similar to https://github.com/astral-sh/uv/issues/4603, we should verify the version of a source matches the specifier. For example,
```toml
dependencies = [
    "uv-public-pypackage==0.0.2",
]

[tool.uv.sources]
uv-public-pypackage = { git = "https://github.com/astral-test/uv-public-pypackage", tag = "0.0.1" }
```
