### ISSUE TITLE
`uv add` hangs with circular dependencies in the lock file.

### ISSUE THREAD

**Issue by blueraft** [astral-sh/uv#4629]
Originally posted in #4599 

I've encountered a consistent hang when there's a circular dependency in the lock file.

```toml
name = "foo"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["poetry"]
```

When I run `uv lock` followed by `uv add flask`, the process hangs indefinitely.

Did a little digging myself and I found a loop in the lock.rs file that appears to cause the issue. Adding a check to skip the loop iteration if the key already exists in the map seems to fix the problem for me.

https://github.com/astral-sh/uv/blob/796171e1e6d55dae095effebb6d815ac91727c2c/crates/uv-resolver/src/lock.rs#L354-L380
