### ISSUE TITLE
Python version limited requirement in universal locking

### ISSUE THREAD

**Issue by davidfritzsche** [astral-sh/uv#4668]
With uv 0.2.18 the following fails

```shell
$ echo 'uv;python_version>="3.8"' | uv pip compile -p 3.7 --universal -
warning: uv is only compatible with Python 3.8+, found Python 3.7.17.
  × No solution found when resolving dependencies:
```

Which on one hand makes sense, as there really is no version of uv supporting Python 3.7. On the other hand, `uv==X; python_version>="3.8"` could be installed under Python 3.7 for any version X.

In non-universal locking, `uv;python_version>="3.8"` can be compiled for Python 3.7:

```shell
$ echo 'uv;python_version>="3.8"' | uv pip compile -p 3.7 -
warning: uv is only compatible with Python 3.8+, found Python 3.7.17.
Resolved 0 packages in 0.77ms
# This file was autogenerated by uv via the following command:
#    uv pip compile -p 3.7 -
```

**Comment by charliermarsh** [comment]
Oh thank you, I think this is the same as #4669 -- sorry, I missed that you created this.

**Comment by charliermarsh** [comment]
I'm going to merge into #4669. Good bug!

**Comment by charliermarsh** [comment]
Re-opening because this case is a little different than the NumPy one and they'll have separate PRs.

**Comment by houbie** [comment]
I'm facing a related issue: using python 3.9, `uv pip install pdm` correctly installs pdm version 2.17.3, but `echo 'pdm==2.17.3'| uv pip compile --universal -` fails:
```
(px-uvdir) % echo 'pdm==2.17.3'| uv pip compile --universal -
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of truststore{python_version >= '3.10'} are available:
          truststore{python_version >= '3.10'}==0.1.0
          truststore{python_version >= '3.10'}==0.2.0
          truststore{python_version >= '3.10'}==0.3.0
          truststore{python_version >= '3.10'}==0.4.0
          truststore{python_version >= '3.10'}==0.5.0
          truststore{python_version >= '3.10'}==0.6.0
          truststore{python_version >= '3.10'}==0.6.1
          truststore{python_version >= '3.10'}==0.7.0
          truststore{python_version >= '3.10'}==0.8.0
          truststore{python_version >= '3.10'}==0.9.0
          truststore{python_version >= '3.10'}==0.9.1
      and the requested Python version (>=3.9.17) does not satisfy Python>=3.10, we can conclude that any of:
          truststore{python_version >= '3.10'}<0.9.0
          truststore{python_version >= '3.10'}>0.9.0
       are incompatible.
      And because truststore{python_version >= '3.10'}==0.9.0 was yanked (reason: Doesn't work for CPython 3.13, upgrade to 0.9.1), we can conclude that all versions of truststore{python_version >= '3.10'} are incompatible.
      And because pdm==2.17.3 depends on truststore{python_version >= '3.10'} and you require pdm==2.17.3, we can conclude that the requirements are unsatisfiable.
```

pdm has a dependency on truststore `Requires-Dist: truststore; python_version >= "3.10"`
`uv pip compile` should retain this dependency with the python constraint instead of failing on it

**Comment by charliermarsh** [comment]
@houbie -- Think that's the same as https://github.com/astral-sh/uv/issues/4668.

**Comment by charliermarsh** [comment]
On main there's now a workaround for this:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["uv ; python_version >= '3.8'"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
environments = ["python_version < '3.8'", "python_version >= '3.8'"]
```

**Comment by DanCardin** [comment]
I'm encountering something similar, where the environments workaround doesn't appear to work. It works with **only** the `"numpy >= 2.0; python_version >= '3.9'"` dependency, but not with certain other dependencies in combination.

```toml
[project]
name = "foo"
version = "0.0.0"
description = ""
requires-python = ">=3.8,<4"
dependencies = [
  "pydantic",
  "numpy >= 2.0; python_version >= '3.9'",
]

[tool.uv]
environments = ["python_version < '3.9'", "python_version >= '3.9'"]
```
This ^ will attempt to install numpy (which then fails for me), which i think it shouldnt even be attempting. 

I'm not sure what significance `pydantic` has here, it only depends on `pydantic-core`, `typing-extensions` and `annotated-types`. And explicitly stating those dependencies (locked to the locked versions) individually instead doesn't fail.
