### ISSUE TITLE
Tracking issue: Stabilize `uv.lock` format

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4893]
This is a tracking issue for making breaking changes the schema and contents of `uv.lock` before the release.

- [x] https://github.com/astral-sh/uv/issues/4888
- [x] https://github.com/astral-sh/uv/issues/4889
- [x] Move the resolution options (resolution lowest, exclude newer, prerelease mode) under a newer header resolver-options to group them and make them distinct from the rest of the top level entries.
- [x] Rename distribution to package or packages. This is not a distribution entry, the distributions are the source dists and wheels. package is also a more familiar name and closer to PEP 751, packages would be the same as PEP 751.
- [x] If only one index is used, move the source = { registry = "https://pypi.org/simple" } to the top of the file and out of the [[distribution]]. This shrinks the file a bit and removed the duplication.
- [x] Try to make the lockfile more concise. Could we e.g. remove redundant `source` line? The lockfile is long and should try to get it as small as possible without sacrificing readability and diffability.

**Comment by T-256** [comment]
> * Try to make the lockfile more concise. Could we e.g. remove redundant `source` line?

it could use `source` at top-level which implies that distributions without `source` are using it:
```toml
version = 1
source = { registry = "https://pypi.org/simple" }
# or:
# source.registry = "https://pypi.org/simple"

[[distribution]]
name = "a"
version = "0.1.0"
sdist = { url = "https://example.com", hash = "sha256:37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3", size = 0 }

[[distribution]]
name = "a"
version = "0.1.1"
sdist = { url = "https://example.com", hash = "sha256:37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3", size = 0 }

[[distribution]]
name = "b"
version = "0.1.0"
sdist = { url = "https://example.com", hash = "sha256:37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3", size = 0 }
```
