### ISSUE TITLE
Support dependencies into git workspaces

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4920]
Say we have our local workspace with a package `a`, and another workspace in a git repository with `c` and `d`. We have `a -> c`, `c -> d`. Currently, this fails by resolving `c` to the git repository but `d` to pypi.

To reproduce:

```toml
[project]
name = "a"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["c"]

[tool.uv.sources]
c = { git = "https://github.com/konstin/workspace-git-path-dep-test", subdirectory = "packages/c" }
```

https://github.com/konstin/workspace-git-path-dep-test contains the packages `c` and `d`.
