### ISSUE TITLE
uv pip installs installs override that does not match requested environment markers

### ISSUE THREAD

**Issue by sbidoul** [astral-sh/uv#4976]
This is a variant of #4826, with uv 0.2.24

pyproject.toml:

```toml
[project]
name = "demo"
version = "1.0"
dependencies = [
   "importlib_metadata; python_version<'3.8'"
]
```

override.txt

```
importlib-metadata==4.6.4
```

In a python 3.10 venv, `uv pip install --override override.txt .` installs `importlib-metadata==4.6.4`, where I expect it not to, because my project does not depend on it for python >= 3.8.

This maybe raises interesting questions about the precise semantics of --override.
