### ISSUE TITLE
how can to change the pip source in a virtual environment, use the following command

### ISSUE THREAD

**Issue by dividduang** [astral-sh/uv#4983]
```
python --version
Python 3.8.19

uv --version
uv 0.2.20

os--windows
```
```
C:\Users>uv pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
error: unrecognized subcommand 'config'
```

thanks !

**Comment by charliermarsh** [comment]
We don't have a `config` command right now. But you could add this to a `uv.toml` in that directory:
```toml
[pip]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
```
