### ISSUE TITLE
`uv pip compile --no-build` won't build when using dynamic metadata for dependencies in `pyproject.toml`

### ISSUE THREAD

**Issue by 9ao9ai9ar** [astral-sh/uv#4985]
I am trying to use the [secure installs](https://pip.pypa.io/en/stable/topics/secure-installs/) mechanism of `pip`, but encounters a problem when I specify the dependencies as dynamic metadata inside my `pyproject.toml` file:
```toml
[build-system]
requires = ["setuptools >= 65.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "my-project"
version = "2024.07.11"
requires-python = ">= 3.10"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools.dynamic]
dependencies = { file = ["requirements/base.in"] }
optional-dependencies.dev = { file = ["requirements/dev.in"] }

[tool.uv]
native-tls = true

[tool.uv.pip]
emit-index-url = true
generate-hashes = true
no-build = true
no-deps = true
python-version = "3.10"
require-hashes = true
strict = true
universal = true
upgrade = true
```

The output:
```powershell
> uv pip compile .\pyproject.toml --verbose --output-file=requirements.txt
DEBUG uv 0.2.23
DEBUG Starting Python discovery for Python 3.10
DEBUG Looking for exact match for request Python 3.10
DEBUG Searching for Python 3.10 in system path or `py` launcher
DEBUG Found cpython 3.12.4 at `[omitted]` (active virtual environment)
DEBUG Found cpython 3.12.4 at `[omitted]` (virtual environment)
DEBUG Found cpython 3.12.4 at `[omitted]` (search path)
DEBUG Looking for Python installation with any version
DEBUG Searching for Python interpreter in system path or `py` launcher
DEBUG Found cpython 3.12.4 at `[omitted]` (active virtual environment)
DEBUG Using Python 3.12.4 interpreter at .venv\Scripts\python.exe for builds
warning: The requested Python version 3.10 is not available; 3.12.4 will be used to build dependencies instead.
DEBUG Using request timeout of 30s
error: Building source distributions is disabled
```

The same configuration seems to work fine in `pip-tools`. I can work around this in `uv` if I specify `dependencies` and `optional-dependencies` statically; or by commenting out the `no-build = true` line, but then an unwanted `my-project.egg-info` directory gets created, which doesn't happen with the first workaround (`my-project` is in flat layout intended to be run as a script).

Is this intended behavior or a bug?

**Comment by charliermarsh** [comment]
If you set `no-build = true`, we won't run the arbitrary Python code required to determine your project's dependencies, because such builds are explicitly disabled. So I think this is intended?

**Comment by 9ao9ai9ar** [comment]
Dumb question: what is the "arbitrary Python code" required to determine my project's dependencies? Can I whitelist it using `--no-binary`? What I don't understand is why the same configuration works when the dependencies aren't set external to `pyproject.toml`? I could also run `pip install --only-binary=:all: --use-pep517 -r .\requirements\base.in` without problems, if the flags are supposed to mean the same thing.

Something is clearly wrong with Python's packaging story when like half of all PEPs revolve around it. But I digress. I still want to list my dependencies in a requirements file to save typing those `"` and `,`, and because it is cleaner and more VCS-friendly. Anyways, if I understood the article section [The problem with pinning Python packages](https://lil.law.harvard.edu/blog/2019/05/20/improving-pip-compile-generate-hashes/#the-problem-with-pinning-python-packages) correctly, specifying `no-build = true` is actually more susceptible to supply chain attacks than `no-binary = true`, so I might just not use it.

**Comment by charliermarsh** [comment]
Yeah, you can actually do this:

```toml
[tool.uv.pip]
no-build = true
no-binary = ["my-project"]
```

To "override" the `no-build` setting, and allow that specific package.
