### ISSUE TITLE
"uv --preview lock" does not read uv.toml or pyproject.toml settings

### ISSUE THREAD

**Issue by dsully** [astral-sh/uv#5022]
The `uv --preview lock` command does not find/respect settings in either a `pyproject.toml` or a `uv.toml` file, and thus resolution fails for internal Pypi repositories:

```toml
[pip]
extra-index-url = [
  "https://artifactory/artifactory/api/pypi/pypi-internal/simple",
  "https://artifactory/artifactory/api/pypi/pypi-external/simple",
]
index-url = "https://server/pypi/simple"
```

Or in `pyproject.toml`:
```toml
[tool.uv.pip]
extra-index-url = [
  "https://artifactory/artifactory/api/pypi/pypi-internal/simple",
  "https://artifactory/artifactory/api/pypi/pypi-external/simple",
]
index-url = "https://server/pypi/simple"
```

```shell
$ uv --preview lock --show-settings
...
LockSettings {
    python: None,
    refresh: None(
        Timestamp(
            SystemTime {
                tv_sec: 1720813419,
                tv_nsec: 61301000,
            },
        ),
    ),
    settings: ResolverSettings {
        index_locations: IndexLocations {
            index: None,
            extra_index: [],
            flat_index: [],
            no_index: false,
        },
        index_strategy: FirstIndex,
        keyring_provider: Disabled,
        resolution: Highest,
        prerelease: IfNecessaryOrExplicit,
        config_setting: ConfigSettings(
            {},
        ),
        exclude_newer: None,
        link_mode: Clone,
        upgrade: None,
        build_options: BuildOptions {
            no_binary: None,
            no_build: None,
        },
    },
}
```

Passing `--index-url` and `--extra-index-url` on the command line *does* work.

**Comment by zanieb** [comment]
Hi! We don't read the `tool.uv.pip` settings outside the `uv pip` CLI — instead use the top-level `tool.uv` options that correspond to their pip-specific counterparts.

**Comment by dsully** [comment]
That doesn't appear to work with `pyproject.toml`:

```toml
[tool.uv]     ■ Additional properties are not allowed ('extra-index-url', 'index-url' were unexpected)
extra-index-url =
```

And emits a schema validation error. 

In `uv.toml` if I remove any section wrapper and just have the raw key/value assignments, that works, but emits the same schema validation error.

**Comment by zanieb** [comment]
Both of the following work for me?

```toml
[tool.uv]
index-url = "https://test.pypi.org/simple"
extra-index-url = ["https://test.pypi.org/simple"]
```

Are you on the latest version?

Yeah `uv pip` will inherit these settings. If you set them in `[tool.uv.pip]` that will take precedence over the top-level one.
