### ISSUE TITLE
uv can't read pyproject.toml with extra-index-url

### ISSUE THREAD

**Issue by kimdwkimdw** [astral-sh/uv#5095]
with pyproject.toml below, uv can't read pyproject.toml correctly.
```
[tool.uv.pip]
index-url = "https://pypi.org/simple"
extra-index-url = "https://pypi.custom.domain"
```

always shows warning
```
warning: Failed to parse `pyproject.toml` during settings discovery; skipping...
```

uv 0.2.25 in ubuntu 22.04

**Comment by j178** [comment]
`extra-index-url` should be an array:

```toml
[tool.uv.pip]
index-url = "https://pypi.org/simple"
extra-index-url = ["https://pypi.custom.domain"]

```
