### ISSUE TITLE
uv lock should redact username and password from  source

### ISSUE THREAD

**Issue by ewianda** [astral-sh/uv#5119]
eg 

```
 
 [[distribution]]
 name = "absl-py"
 version = "2.0.0"
source = { registry = "https://username:secrete-token@private-registry/registry/pypi/simple/" }
```

to

```
[[distribution]]
 name = "absl-py"
 version = "2.0.0"
source = { registry = "https://private-registry/registry/pypi/simple/" }

similar to 

https://github.com/astral-sh/uv/issues/3106
```

**uv --version**
     uv 0.2.24

similar https://github.com/astral-sh/uv/issues/3106

**Comment by zanieb** [comment]
Also related https://github.com/astral-sh/uv/issues/1714

**Comment by charliermarsh** [comment]
Not sure what to do here -- do we really want to strip the credentials entirely? If so, how would users install from the lockfile?

**Comment by ewianda** [comment]
Won't redefining the index url with the authorization in cli or environment variable work?. I see two issues 
1. Keeping the username and password means the lock file cannot be checked into version control.
2. For Google artifact registry for example, the password is user specific authorization token that expires

**Comment by zanieb** [comment]
How are the credentials being provided in the first place here?

**Comment by charliermarsh** [comment]
Should we just omit username and password entirely then from the lockfile, in all cases? AFAICT that's the only option available to us.

**Comment by ewianda** [comment]
> How are the credentials being provided in the first place here?

UV_INDEX_URL=https://oauth2accesstoken:${ARTIFACT_REGISTRY_TOKEN}@us-python.pkg.dev/private/private/simple/

**Comment by zanieb** [comment]
I presume the environment variable is being resolved by your shell then? e.g. the first case in

```
❯ export VAR='SECRET'
❯ echo "$VAR"
SECRET
❯ echo '$VAR'
$VAR
```

If so, we don't know anything about the use of an environment variable and cannot use it to template the URL. I guess we might need to encourage setting the index URL with `'` so it's preserved and we resolve it to a value ourselves?

Ideally we'd _at least_ retain the username. However, sometimes it's ambiguous if we should use something in the username position as a password.

**Comment by charliermarsh** [comment]
If we drop the credentials from the lockfile itself, then re-run with the index URL provided as above, do we properly propagate them?

**Comment by zanieb** [comment]
I don't think we do any environment variable propagation today, we'd need to add that.

**Comment by paveldikov** [comment]
> How are the credentials being provided in the first place here?

We use `uv.toml` for this same purpose. We largely regard the choice of registry as a centrally-mandated choice -- in fact, given a choice, I would actively want to disregard a reference to an unapproved registry, and always force downloads to go through our internal mirrors.

**Comment by chrisrodrigue** [comment]
I think environment variable parsing/propagation from `pyproject.toml` would be important to hide secrets in both the repo and CI/CD.

For example, I expected this to work:
```
[tool.uv.pip]
native-tls = true
index-url = "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@mycompany.com/repository/pypi-proxy/simple/"
```
I expected `uv` to only pull from the configured `index-url` and not fall back to default pypi, for security purposes (to prevent typosquatting/malicious package replacements upstream).

In GitHub/GitLab, project level variables can be pulled in the same way to install `uv` into a container that already has `pip`.

Below is a GitLab hidden job template that can be extended for python-related jobs in the pipeline with an example showing how environment variables are useful in CI/CD:

```yaml
.job-template:
  image: python:3.12-alpine
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"
  cache:
    key:
      files:
        - uv.lock
    paths:
      - .cache/pip
      - .cache/uv
      - .venv
    policy: pull
    - pip config set global.cert /my_company.pem
    - pip config set global.index-url "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@mycompany.com/repository/pypi-proxy/simple/"
    - pip install uv
    - uv sync
```

**Comment by charliermarsh** [comment]
@chrisrodrigue -- I think that's actually intended to work, I'm somewhat surprised that it doesn't. But isn't it more common for those env vars to be expanded automatically by the shell, such that the value written to the pip config _does_ include the raw credentials?

**Comment by charliermarsh** [comment]
```toml
[tool.uv.pip]
index-url = "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@mycompany.com/repository/pypi-proxy/simple/"
```

This will not fall back to PyPI, but it's only used at all in the `uv pip` interface. If you want the index URL to apply to _all_ uv commands, omit the `pip`:

```
[tool.uv]
index-url = "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@mycompany.com/repository/pypi-proxy/simple/"
```

**Comment by charliermarsh** [comment]
I added https://github.com/astral-sh/uv/issues/5734.

**Comment by chrisrodrigue** [comment]
> @chrisrodrigue -- I think that's actually intended to work, I'm somewhat surprised that it doesn't. But isn't it more common for those env vars to be expanded automatically by the shell, such that the value written to the pip config _does_ include the raw credentials?

Yes they are expanded, and the value written to the pip config shows the raw credentials. I don't _think_ this is a security issue since the pipeline container is ephemeral and only used by the CI.

GitLab has a feature that masks the expanded variables from job logs... I assume GitHub supports a similar feature?

![image](https://github.com/user-attachments/assets/25a8ce7e-a7d5-4401-96f4-09b00865ff18)

**Comment by chrisrodrigue** [comment]
But I don't think the masking extends to other files/artifacts such as the `uv.lock`. 

I think some solutions would be for the `uv.lock` to either 

(1) Completely strip the username/password fields

```toml
source = { registry = "https://actual_username:actual_password@mycompany.com/repository/pypi-proxy/simple/" }
```
to
```toml
source = { registry = "https://mycompany.com/repository/pypi-proxy/simple/" }
```

or 

(2) retain the environment variable name without expansion, which could provide more useful context to a user attempting to debug or reproduce the environment

```toml
source = { registry = "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@mycompany.com/repository/pypi-proxy/simple/" }
```

**Comment by chrisrodrigue** [comment]
The Hatch project has a slight more verbose but flexible syntax for denoting [paths](https://hatch.pypa.io/latest/config/context/#paths) and [environment variables](https://hatch.pypa.io/latest/config/context/#environment-variables):

Paths (`root | home`) support several modifiers (`uri | real | parent`):

```toml
[tool.hatch.envs.test]
dependencies = [
    "example-project @ {root:parent:parent:uri}/example-project",
]
```

Environment variables utilize a PowerShell style (`env:VARIABLE`) rather than Bash style (`$VARIABLE | ${VARIABLE}`) and support setting default values if they are not set, e.g. `{env:PATH:DEFAULT}`)
```toml
[tool.hatch.envs.test.scripts]
display = "echo {env:FOO:{env:BAR:{home}}}"
```
