### ISSUE TITLE
Uv script install into .venv overwrites python

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#5152]
- Install python 3.12.3 with uv.
- Create a new package (pyproject below)
- uv venv -p 3.12.3
- Uv creates a virtualenv that has symlink .venv/bin/python -> ~/.local/share/uv/python/cpython-3.12.3-linux-x86_64-gnu/bin/python3
- Current package is named `python`. It has a script called `python`
- uv sync -v
- Actual Result: When installing the script to .venv/bin/python it overwrites the target of the symlink. This ruins the installed python version.
- Expected Result: Don't follow the symlink. Probably throw an error somewhere before.

Based on https://github.com/astral-sh/rye/issues/1235. I think this is could be a bug in Uv?

Tested and reproduced with uv only (then uv 0.2.24, not the latest, I'm sorry).

uv 0.2.24
platform: linux (x86_64)

```toml
[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
dependencies = []
requires-python = ">= 3.12"

[project.scripts]
"python" = "python:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/python"]
```

```python
# src/python/__init__.py
def main() -> int:
    print("Hello from python!")
    return 0
```

```python
# src/python/__main__.py
import python
import sys

sys.exit(python.main())
```
