### ISSUE TITLE
`uv init` should respect `workspace.exclude`

### ISSUE THREAD

**Issue by j178** [astral-sh/uv#5254]
Here is the root package:
```toml
[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = []

[tool.uv]
dev-dependencies = []

[tool.uv.workspace]
exclude = ['pkg-*']
```

Within the root package, we create a sub-package `pkg-a`, it is added to the workspace members, despite it should be excluded:
```sh
$ uv init pkg-a
Adding pkg-a as member of workspace E:\tmp\work
Initialized project pkg-a in E:\tmp\work\pkg-a

$ cat pyproject.toml
[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = []

[tool.uv]
dev-dependencies = []

[tool.uv.workspace]
exclude = ['pkg-*']
members = ["pkg-a"]
```
