### ISSUE TITLE
`--directory` should resolve relative paths relative to current working directory

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5613]

**Comment by bluss** [comment]
Uv run's external command is opaque (in meaning), so it's not possible to translate those arguments. One part of the solution for uv run could be either to never change current directory, or set cwd back to the original for the child process.

**Comment by charliermarsh** [comment]
I was thinking that we’d remove the current set_directory call, and then pass around a project directory as dictated by the directory flag.

**Comment by abdok96** [comment]
Do you have any timeline for this change by any chance? I'm currently using the hidden `--directory` option but it would be great if it can be made public (and ideally add an environment variable for it). Also resolving the paths relative to the passed directory is causing very weird issues in different places. I think this change is the correct choice.
 
Thanks for uv it is looking great!

**Comment by zanieb** [comment]
per https://github.com/astral-sh/uv/issues/6733#issuecomment-2315983710 our existing behavior matches the Git and Cargo CLIs so we're very unlikely to change it.

The pre-commit example is great though. How do people work around this in other tools? Why do you need to use `--directory` in this situation? Maybe we need an environment variable to toggle.

**Comment by abdok96** [comment]
Thanks for the quick reply. 
In our case, the simplified project structure was briefly something like:

my-project/
|__ app/
|    |__ main.py
|    |__ pyproject.toml  
|__ docker/
|__ docs/
|__ bin/
|__ docker-compose.yml
|__ .pre-commit.config.yaml

We also have a local hook for mypy something like:

```
  - repo: local
    hooks:
      - id: mypy
        name: run mypy check
        language: system
        entry: uv run --directory app -- mypy
        types_or: [python, pyi]
        require_serial: true
        args:
          - --config-file=pyproject.toml
```

We want to run the mypy command from the virtual environment that has all the python dependencies so that mypy can resolve and follow all the imports when running the type checks.

Because of the behavior of `--directory` we are passing config-file as `pyproject.toml` instead of `app/pyproject.toml` but that's okay since we can control it. 

However, when the commit hook is triggered by pre-commit, we have less control.
Let's say `app/main.py` was changed, the command executed by pre-commit will be something like:
`uv run --directory app -- mypy --config-file=pyproject.toml app/main.py`

And since the paths are resolved relative to the `--directory` param, mypy won't find a module matching `app/app/main.py`.

In our case, we managed to get around it in my case by moving the `pyproject.toml` to the root directory which is probably a more suitable place.  However, there might be similar cases that are a bit harder to avoid.

**Comment by abdok96** [comment]
Btw, I'm not sure if it helps, but we are in the process of migrating from poetry to uv. I can confirm that in the case of poetry, the behavior is not similar to cargo or git. It resolves paths based on the working directory.  

For example, this is the same hook I mentioned in my previous comment, before the migration to uv:

```
  - repo: local
    hooks:
      - id: mypy
        name: run mypy check
        language: system
        entry: poetry --directory app run mypy
        types_or: [python, pyi]
        require_serial: true
        args:
          - --config-file=app/pyproject.toml
```

Notice how despite the --directory param, we used to pass the `--config-file` relative to the working directory not `/app`.
I guess both options have good arguments. A toggle like you suggested might help.
