### ISSUE TITLE
Allow top level dev decencies in top level workspace

### ISSUE THREAD

**Issue by jpambrun-vida** [astral-sh/uv#5650]
I feel like the workspace top level virtual workspace would be the ideal place to have dev dependencies such as mypy, pytest, etc.

```toml
[tool.ruff]
line-length = 120

[tool.mypy]
ignore_missing_imports = true

[tool.uv.workspace]
members = [
  "a/b",
  "c/d",
]

[tool.uv]
dev-dependencies = [
  "mypy~=1.11.0",
  "pytest~=8.3.2",
  "coverage~=7.6.0",
]
```

As of now, uv seems to ignore them.
