### ISSUE TITLE
Allow setting virtual environment options in `pyproject.toml`

### ISSUE THREAD

**Issue by chrisrodrigue** [astral-sh/uv#5737]
When running `uv venv`, the user may specify the options `--system-site-packages` and `--relocatable`. These values persist in `.venv/pyenv.cfg` as shown:

```txt
home = C:\WinPython\python-3.12.4.amd64
implementation = CPython
uv = 0.2.33
version_info = 3.12.4
include-system-site-packages = true
relocatable = true
```

The `uv sync` command implicitly creates a virtual environment in `.venv`, which is awesome. However, it is not possible to pass these options to `uv sync` or set them in the `tool.uv` section (or a `tool.uv.venv` section) of  `pyproject.toml`. The virtual environment created with `uv sync` always defaults to setting `include-system-site-package` and `relocatable` to `false`.

I propose that `uv` be capable of reading these from `pyproject.toml`, and also when passed to `uv sync`.

Maybe a generalized approach to file-based configuration (both `uv.toml` and `pyproject.toml`) of `uv` behavior could be to support a section corresponding to each `uv` command for all available options:

pyproject.toml
```toml
[uv.tool.venv]
relocatable = true
system-site-packages = true
# Generalization
[uv.tool.command]
option = value
```

**Comment by charliermarsh** [comment]
This seems reasonable to me though want a second opinion before adding any configuration.

**Comment by chrisrodrigue** [comment]
Another, perhaps cleaner alternative (similar to `pdm` as shown here - [passing constant arguments to every pdm invocation](https://pdm-project.org/en/latest/usage/config/#passing-constant-arguments-to-every-pdm-invocation)):
```toml
[tool.uv.options]
sync = ["--relocatable", "--system-site-packages", "--all-extras"]
venv = ["--relocatable", "--system-site-packages"]
```
