### ISSUE TITLE
Questions about dependency annotation in `pyproject.toml`

### ISSUE THREAD

**Issue by chrisrodrigue** [astral-sh/uv#5767]
Hello all,

I've been browsing the documentation/issues and I'm having trouble finding examples on annotating dependencies in `pyproject.toml`.

My current use case is to be able to install an editable local dependency, such as another python project nested in my project as a submodule.

I would also like to support users who don't like to use submodules and would rather install my project directly from git.

See below for my comments/questions?

```toml
[project]
dependencies = [
    "some_dependency"
    # Where would the editable option go?
   # Would this also work?
   # "some_dependency @ ssh://git@gitlab.mycompany.com/project/some_dependency.git"
]

# Is this section even needed if the URL/path is already in the dependency list using the dep @ url notation?
[tool.uv.sources]
# Submodule approach
some_dependency = { path = "./some_dependency/"}
# Package manager approach
some_dependency = { git = "ssh://git@gitlab.mycompany.com/project/some_dependency.git"}
```

**Comment by chrisrodrigue** [comment]
Can workspaces be pulled in from a remote source?

```toml
[project]
dependencies = [
    "some_dependency >=0.1.0,<1"
]

[tool.uv.sources]
project = { workspace = true }

[tool.uv.workspace]
include = [
  "packages/some_dependency @ ssh://git@gitlab.mycompany.com/project/some_dependency.git"
]
```
