### ISSUE TITLE
Allow defining persistent command options in `pyproject.toml`

### ISSUE THREAD

**Issue by chrisrodrigue** [astral-sh/uv#5811]
I’m wishing for a way to specify persistent options for `uv` commands in `pyproject.toml`.

This is a generalized solution to issues such as #5737.

## Example

```toml
[tool.uv.options]
venv = [ "--relocatable" ]
pip = { install = [ "--offline", "--no-build-isolation" ] }
```

Invoking `uv venv` would then implicitly pass the option  `--relocatable`. 

Perhaps it could print a message to let the user know that options were collected from `pyproject.toml` to respect the principle of least astonishment.
