### ISSUE TITLE
Don't create forks the are disjoint with requires-python

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5818]
Usually, we only consider the lower bound of requires-python in the resolver. For when forking, it doesn't make sense to consider forks above the upper bound, e.g. with `==3.11.*`, a fork `python_version >= '3.13'` doesn't make sense.

`pyproject.toml`:

```toml
[project]
name = "warehouse"
version = "1.0.0"
requires-python = "==3.11.*"
dependencies = [
  "pydantic",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Head of `uv.lock`:

```toml
version = 1
requires-python = ">=3.11, <3.12"
environment-markers = [
    "python_version < '3.13'",
    "python_version >= '3.13'",
]
```
