### ISSUE TITLE
`uv lock --upgrade-package` has no effect

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5900]
Reproducer: Start with

```toml
[project]
name = "foo"
version = "1.0.0"
requires-python = "==3.11.*"
dependencies = [
  "pydantic<=2.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Run `uv.lock`. pydantic 2.8.0 is locked. Remove the bound:

```toml
[project]
name = "foo"
version = "1.0.0"
requires-python = "==3.11.*"
dependencies = [
  "pydantic",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Run `uv lock --upgrade-package pydantic`. Nothing happens.

Run `uv lock --upgrade`. We see the correct updates:

```
Updated pydantic v2.8.0 -> v2.8.2
Updated pydantic-core v2.20.0 -> v2.20.1
```
