### ISSUE TITLE
Sync with system Python?

### ISSUE THREAD

**Issue by b-phi** [astral-sh/uv#5964]
I'm trying to use uv to synchronize environments across a cluster. This involves creating a lock file and then using it to install dependencies everywhere. As far as I can tell, `uv sync` only supports installing dependencies in a uv managed venv. Is there anyway to run sync against a target environment, the system Python in this case?

**Comment by b-phi** [comment]
I was able to workaround this by activating the environment dynamically, but this does feel like a bit of a hack since it doesn't guarantee that the environments are actually synced. This is with a dask cluster, I'm not aware of an easy way to "switch" to the new venv if the workers are started with the system python.
```python
import runpy

runpy.run_path('.venv/bin/activate_this.py')
```

**Comment by charliermarsh** [comment]
Na this isn't supported yet.

**Comment by chrisrodrigue** [comment]
I think you can use `uv venv --system-site-packages` but `uv sync` is not yet aware of requirements that are already satisfied by the system/inherited environment.

**Comment by Samuel-Therrien-Beslogic** [comment]
In the mean time, I'm addind the venv's bin (or Scripts on Windows) folder to PATH as per https://github.com/jakebailey/pyright-action/tree/v2/?tab=readme-ov-file#using-pyright-from-path :
```yaml
jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: canopeum_backend
    steps:
      - uses: actions/checkout@v4
      - name: Install uv using the standalone installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync --locked --extra dev
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - run: mypy . --python-version=3.12

  pyright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: canopeum_backend
    steps:
      - uses: actions/checkout@v4
      - name: Install uv using the standalone installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync --locked --extra dev
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v2
        with:
          version: PATH
          python-version: "3.12"
          working-directory: canopeum_backend
```
