### ISSUE TITLE
Feature request: Generate `requirements.txt` from `uv.lock`

### ISSUE THREAD

**Issue by zeevro** [astral-sh/uv#6007]
It would be beneficial to me (and I think in general) to be able to generate a `requirements.txt` file from the `uv.lock` file. It would be useful for installing requirements without having to resolve dependencies using a different installer in environments where `uv` is not installed, and also for having other tools that don't support the `uv.lock` file format (e.g. Dependabot) be able to know the project's pinned dependencies.

**Comment by charliermarsh** [comment]
I think something like this is reasonable but it probably won't happen immediately. ([PEP 751](https://peps.python.org/pep-0751/) is ultimately a better solution but I'd still support `requirements.txt` in the short-term.)

**Comment by chrisrodrigue** [comment]
Chiming in to mention the [SBOM](https://www.cisa.gov/sbom). 

CycloneDX is one such SBOM standard. Would be cool if `uv` could emit an SBOM in one of the industry standard formats such as CycloneDX.

**Comment by zeevro** [comment]
Also, we already have a way to generate `requirements.txt` in the form of `uv pip compile` but it's rather tricky to have that match my `uv.lock`, especially if it's done after a while and some dependencies have had new versions release.

**Comment by zanieb** [comment]
It doesn't really seem like a great outcome for users to have _both_ a `uv.lock` and `requirements.txt` though

**Comment by Samuel-Therrien-Beslogic** [comment]
> It doesn't really seem like a great outcome for users to have _both_ a `uv.lock` and `requirements.txt` though

If using `uv sync` which creates a `uv.lock` file in a Docker, does `uv sync` take care of setting up references to the venv correctly ?
https://docs.astral.sh/uv/guides/integration/docker/#installing-a-package makes no mention of `uv sync` or `uv.lock`

**Comment by zanieb** [comment]
Can you clarify what you mean by "references to the venv"?

I haven't written documentation for using the new APIs in Docker yet.

**Comment by Samuel-Therrien-Beslogic** [comment]
> Can you clarify what you mean by "references to the venv"?

I'm talking about this section of the doc:
> To use the system Python environment by default, set the UV_SYSTEM_PYTHON variable:
> ```Dockerfile
> ENV UV_SYSTEM_PYTHON=1
> ```
> Alternatively, a virtual environment can be created and activated:
> ```Dockerfile
> RUN uv venv /opt/venv
> # Use the virtual environment automatically
> ENV VIRTUAL_ENV=/opt/venv
> # Place entry points in the environment at the front of the path
> ENV PATH="/opt/venv/bin:$PATH"
> ```

I'm assuming if I use `RUN uv sync --locked` instead, that I don't need to mess around with venv setup ? (I just need to update my docker entry point command to use `uv run` instead of `python`, ref to our current transition to UV https://github.com/BesLogic/releaf-canopeum/pull/195/files#diff-1fc9c5328b5af6b1065537cb89aa7298eb7ba1d338b5bee8fd07553b6f56576f )

> I haven't written documentation for using the new APIs in Docker yet.

That's a simple explanation as to why it's not referenced ^^

**Comment by zanieb** [comment]
`uv sync` always creates a virtual environment right now, so yeah you'd either need to opt for configuring it (as described above) or use `uv run` instead of invoking `python`. 

We may add support for syncing to a system environment (as requested in https://github.com/astral-sh/uv/issues/5964) to make this a little simpler in CI and containers.

> I'm just ensuring that the uv.lock file should be usable in Docker

Yeah it definitely is. I'll try to update the documentation soon.

**Comment by matmair** [comment]
> It doesn't really seem like a great outcome for users to have _both_ a `uv.lock` and `requirements.txt` though

I have this use case right now; maybe the insight is useful. There are strict requirements only to deploy stable software in the deployment targets. That rules out uv on the deployment targets by our current rules. The devs still want to use uv and uv project management and it is pretty confusing to have the `requirements.txt` that is used for deployments and the `uv.lock` within the repo.

This can be solved by CI/CD but reducing steps and complexity is the signature of uv/ruff for me.

**Comment by zanieb** [comment]
What makes uv unstable?

Thanks for sharing your use-case! Glad you like the tools :)

**Comment by matmair** [comment]
SemVer. I do not make the rules sadly.

**Comment by jfgordon2** [comment]
I also am finding a need to produce a requirement.txt, but just for deployed packages.  The current path I have in our pipeline looks something like:

```shell
uv sync --no-dev
uv pip freeze > requirements.txt
```

Then we can check that requirement file against `safety` (or dependabot) for vulnerabilities, then do a `uv pip install -r requirements.txt --target dist` so we can package it up along with src into a zip file to deploy to a lambda function.

It definitely would be easier to operate directly against the `uv.lock`, but in the meantime converting that directly into a `requirements.txt` for compatibility with other tools would be great.

**Comment by chrisrodrigue** [comment]
I think supporting `requirements.txt` input and output is wise to maintain compatibility with legacy tooling that isn’t yet caught up with PEP 621.

I have documented one such use case for `requirements.txt` here: #6422

**Comment by phi-friday** [comment]
As you mentioned in #6429 , will there be a feature to create a `requirements.txt` including `tool.uv.dev-dependencies`?

**Comment by charliermarsh** [comment]
Yeah, that would probably be included in the scope of this.

**Comment by zeevro** [comment]
I'm using this as a make-shift solution for now.
```sh
uvx --from=yq tomlq -r '.package[]|.name+((.source|" @ "+(.url//"git+\(.git//empty)"))//"==\(.version)")' uv.lock >requirements.txt
```

**Comment by charliermarsh** [comment]
Respect!

**Comment by SamEdwardes** [comment]
I like the idea of `uv export`!

I am curious what are the implications of doing this:

```bash
uv pip compile pyproject.toml -o requirements.txt
```

In this case is my `uv.lock` ignored and there is a risk the generated requirements.txt will be different?

**Comment by charliermarsh** [comment]
> In this case is my uv.lock ignored and there is a risk the generated requirements.txt will be different?

Yeah, the `uv pip` interface never touches the lockfile. You _can_ use the `uv pip` workflow if you want, but you lose the benefits of the unified `uv sync`, `uv lock`, `uv run` APIs.

**Comment by C-Loftus** [comment]
Curious if anyone has tips / tools they like to keep requirements.txt in sync with uv.lock so you get the benefits of uv while still being easy to use for code reviewers. Even though I know it is recommended to just use uv, I develop libraries where it is easier to team members to quickly use pip and might not be familiar with uv. 

I am just using a simple github action but wasnt sure if there is a better way.

```yml
name: Validate Requirements

on:
  workflow_dispatch:
  push:
    paths:
      - "pyproject.toml"  # Trigger on changes to pyproject.toml
      - "requirements.txt"
  pull_request:
    paths:
      - "pyproject.toml"  # Trigger on changes to pyproject.toml
      - "requirements.txt"

jobs:
  validate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Generate new requirements.txt
        run: |
          uv export --format requirements-txt > new_requirements.txt

      - name: Compare requirements.txt
        run: |
          if ! diff -q new_requirements.txt requirements.txt; then
            echo "requirements.txt is out of sync with the project configuration:"
            diff -u requirements.txt new_requirements.txt
            exit 1
          fi
        shell: bash
```
