### ISSUE TITLE
Resolver should exclude forks that are disjoint with `requires-python`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6059]
For example, given:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets >= 2.19 ; sys_platform == 'darwin' ",
    "datasets >= 2.19 ; python_version > '3.10'"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

The lockfile includes:

```toml
environment-markers = [
    "python_version > '3.10' and sys_platform != 'darwin'",
    "python_version > '3.10' and sys_platform == 'darwin'",
    "python_version <= '3.10' and sys_platform != 'darwin'",
    "python_version <= '3.10' and sys_platform == 'darwin'",
]
```
