### ISSUE TITLE
`uv pip recompile requirements.txt`

### ISSUE THREAD

**Issue by arthur-st** [astral-sh/uv#6199]
It would be helpful for DRY management of the compiled dependency graphs if `uv` would have a simple command like `uv pip recompile` or some such to re-run `uv pip compile` header in the autogenerated file, if it's present.

**Comment by ChannyClaus** [comment]
probably should be a flag for `uv pip compile` rather than a entirely new command if we were to go down this path? more importantly, would having this option be significantly better than having a separate shell script or an equivalent to encode the exact invocation of the `uv pip compile`?

**Comment by arthur-st** [comment]
I could certainly see a flag being the right option here, as I'm by no means a UX expert of some sort. 

Regarding having a separate script, though, I would say that my intent/preferred outcome would be to make the generated dependency specifications being the single source of truth about themselves. Since `uv pip compile` includes the specific `uv pip compile` invocation used to generate a particular file in its header by default already, the single source of truthiness is already mostly there. Being able to "re-run" the file, e.g., to refresh `foo~=1.2.3` style pins from upstream, would serve to eliminate potential errors from having multiple copies of that invocation in different places.

Additionally, for development work on a project with a complex `uv pip compile` chain, it would be nice to have a way to re-run it that can be typed quickly, without having to set up or share a helper shell beforehand.

**Comment by charliermarsh** [comment]
I'd generally prefer users put those settings in a `uv.toml` or `pyproject.toml` file rather than relying on reading them from the header

**Comment by arthur-st** [comment]
As in, a `pyproject.toml` file that has syntax vaguely like:

```toml
[uv.compile.targets]

prod = "uv pip compile requirements.in prod.in -o requirements-prod.txt"
dev = "uv pip compile requirements.in prod.in dev.in -o requirements-dev.txt"
```

Which you would then get to call like `uv pip compile -t prod` to make up something? That would work, I feel, and I think you have the right of it with placing this closer to other project build-adjacent settings.

**Comment by charliermarsh** [comment]
I more meant, like:

```toml
[tool.uv.pip]
index-url = "..."
no-binary = "..."
output-file = "..."
```

I.e., define the settings you would typically provide on the CLI. But if you want multiple different invocations (e.g., multiple different output files) then yeah, it won't handle everything for you.
