### ISSUE TITLE
Respect pyproject.toml defined index-url & keyring-provider in 1st level commands

### ISSUE THREAD

**Issue by Eyal-Shalev** [astral-sh/uv#6230]
1st level commands such as `uv lock`, `uv add` & `uv sync` do not respect the `index-url` & `keyring-provider` parameters as they are defined in `pyproject.toml`

### `pyproject.toml`

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.uv.pip]
python = "3.12"
index-url = "https://aws@foo-012345678901.d.codeartifact.us-east-1.amazonaws.com/pypi/bar/simple/"
keyring-provider = "subprocess"

[project]
name = "my-project"
version = "0.0.0-dev"
requires-python = "~=3.12.0"
dependencies = [ "my-private-package" ]
```

### Doesn't work
```sh
uv lock --no-cache
```

```
  × No solution found when resolving dependencies for split (python_full_version < '4' and implementation_name == 'pypy'):
  ╰─▶ Because my-private-package was not found in the package registry and your project depends on my-private-package, we can
      conclude that your project's requirements are unsatisfiable.
      And because your project requires my-project, we can conclude that your projects's requirements are unsatisfiable.
```

### Works
```sh
uv lock --no-cache --index-url="https://aws@foo-012345678901.d.codeartifact.us-east-1.amazonaws.com/pypi/bar/simple/" --keyring-provider="subprocess"
```

### `uv --version`

`uv 0.2.37 (15dfb660a 2024-08-15)`

**Comment by zanieb** [comment]
Hey @Eyal-Shalev — that's because they're in the `uv.pip` section — you'll need to move them to just a `uv` section. See #6225

**Comment by Eyal-Shalev** [comment]
Indeed the following works.

@zanieb thank you very very much 😄 

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.uv]
index-url = "https://aws@foo-012345678901.d.codeartifact.us-east-1.amazonaws.com/pypi/bar/simple/"
keyring-provider = "subprocess"

[tool.uv.pip]
python = "3.12"

[project]
name = "my-project"
version = "0.0.0-dev"
requires-python = "~=3.12.0"
dependencies = [ "my-private-package" ]
```
