### ISSUE TITLE
Redact credentials in direct URL dependencies

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6270]
E.g., for:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["flask @ https://aws@files.pythonhosted.org/packages/61/80/ffe1da13ad9300f87c93af113edd0638c75138c42a0994becfacac078c06/flask-3.0.3-py3-none-any.whl"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

We should remove `aws` from the lockfile.
