### ISSUE TITLE
Panic when adding dev dependency in virtual workspace

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6288]
Given:

```toml
[tool.uv.workspace]
members = []

[tool.uv]
dev-dependencies = [
    "mkdocs>=1.6, <1.7",
    "mkdocs-material>=9.5.24, <9.6",
    # Versioning of documentation
    # (Py)Markdown extensions
    "mdx-truly-sane-lists >=1.3, <2",
    "mdx-breakless-lists >=1.0.1, <1.1",
    # Allows setting up redirects when renaming docs files
    "mkdocs-redirects >=1.2.1, <1.3",
    # Used for the CLI reference
    "mkdocs-include-markdown-plugin >=6.0.4, <6.1",
]
```

Run `uv lock`. Then `uv add mike`.
