### ISSUE TITLE
✨ How to define custom commands like `tool.rye.scripts`

### ISSUE THREAD

**Issue by jd-solanki** [astral-sh/uv#6302]
Hi 👋🏻 

I'm really happy for UV. I always wanted better python ecosystem thanks all of you for your efforts.

I want to migrate from rye to UV as I'm starting new project and wanted to add custom command like `uv run dev` that executes `uv run fastapi dev src/backend/main.py` for me.

In Rye, I used to define it under scripts section:
```toml
[tool.rye.scripts]
dev = "uvicorn aitools.main:app --reload"
migration = "alembic revision --autogenerate -m"
migrate = "alembic upgrade head"
downgrade = "alembic downgrade -1"
```

However, It looks like UV don't have this feature or isn't documented yet.

**Comment by captnswing** [comment]
I think this is done in the `[project.scripts]` table. 

See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts

**Comment by jorgebodega** [comment]
It is not exactly the same. `[project.scripts]` requires a python file to be created to execute something.

To achieve this, I'm still using [poethepoet](https://github.com/nat-n/poethepoet) inherited from poetry, and it's still working.

But yes, this would be great to have inside `uv`.

**Comment by patrick91** [comment]
`pdm` does it like this:

```
[tool.pdm.scripts]
start = "flask run -p 54321"
```

**Comment by zanieb** [comment]
Yeah we don't support this yet, but we plan to in some way.

**Comment by anthonycorletti** [comment]
this sounds really useful.

my solution for this right now is leaving scripts in a bin directory which does the trick because i don't have to remember commands or reverse-i-search forever. would love to have something like this:

```toml
# ...

[tool.uv.scripts]
clean = "rm -rf build dist *_cache"
format = "ruff format"
check = "ruff check"
test = "pytest"
dev = "uvicorn app.main:app --reload"

[tool.uv.scripts.combos]
ok = ["clean", "format", "check", "test"]

# ...
```
