### ISSUE TITLE
`uv pip compile` does not include local package

### ISSUE THREAD

**Issue by joellidin** [astral-sh/uv#6317]
I am playing around a bit with `uv` and its features and got interested in the `uv pip compile` for platform agnostic lock files. I set up a very basic project with this `pyproject.toml`:

```toml
[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "ruff>=0.6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Later I ran `uv pip compile --universal pyproject.toml -o requirements.lock` which resulted in:
```lock
# This file was autogenerated by uv via the following command:
#    uv pip compile --universal pyproject.toml -o requirements.lock
ruff==0.6.1
    # via test-uv (pyproject.toml)
```
However, my local package is not included in this lockfile which is a bit weird to me. For example if I run `rye sync` instead I get the following:

```lock
# generated by rye
# use `rye lock` or `rye sync` to update this lockfile
#
# last locked with the following flags:
#   pre: false
#   features: []
#   all-features: false
#   with-sources: false
#   generate-hashes: false
#   universal: false

-e file:.
ruff==0.6.1
    # via test-uv
```

Moreover, when doing `uv sync` it actually installs my `test-uv` package in editable mode. But, I want to explore an option where you can just use normal `pip install -r requirements.lock` and not forced to use `uv`.

Am I missing something from the documentation or is this intended behavior?

I am on Ubuntu 22.04 with the latest version of `uv 0.3.0`.
