### ISSUE TITLE
Using uv to install coverage with toml extra as a dev dep gives error when generating lock file

### ISSUE THREAD

**Issue by taranlu-houzz** [astral-sh/uv#6380]
If you install `coverage[toml]` as a dev dep, `uv` will complain about with the following error when running `uv lock`:
```
❯ uv lock
Failed to parse lockfile; ignoring locked requirements: for package `uv-coverage-with-toml-extra-bug==0.1.0 @ editable+.:dev`, found duplicate dependency `coverage==7.6.1 @ registry+https://pypi.org/simple`
Resolved 2 packages in 3ms
```

**Comment by charliermarsh** [comment]
Can you help me with a reproduction? 

```
❯ uv add "coverage" --dev --extra toml
Resolved 3 packages in 226ms
   Built foo @ file:///Users/crmarsh/workspace/puffin/foo
Prepared 3 packages in 330ms
Installed 3 packages in 1ms
 + coverage==7.6.1
 + foo==0.1.0 (from file:///Users/crmarsh/workspace/puffin/foo)
 + tomli==2.0.1
```

**Comment by charliermarsh** [comment]
Could you share the `pyproject.toml`?

**Comment by taranlu-houzz** [comment]
```toml
[project]
name = "uv-coverage-with-toml-extra-bug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "coverage[toml]>=7.6.1",
]
```
