### ISSUE TITLE
Private repository as a source

### ISSUE THREAD

**Issue by NevoleMarek** [astral-sh/uv#6421]
Hi, I d'like to transition from `poetry` to `uv`. What I am missing is a way of using private repositories as source for packages.

[Poetry](https://python-poetry.org/docs/repositories/#private-repository-example) allows to add private repositories like so:

`poetry source add --priority=supplemental foo https://pypi.example.org/simple/` 

and then to install package from the repository like so:

`poetry add --source foo private-package`

Can this be sensibly done using `uv`?

I guess it could somehow be done via HTTP URLs but that seems a bit cumbersome.

**Comment by charliermarsh** [comment]
So, today, you would do something like this:

```toml
[tool.uv]
extra-index-url = ["https://pypi.example.org/simple/"]
```

uv will then look in `https://pypi.example.org/simple/` before looking in PyPI, and if a package exists on that index, it won't check PyPI at all.

We'll likely add a more granular index API in the future that looks more like what you get in Poetry, PDM, or Rye.

**Comment by charliermarsh** [comment]
If you want to replace PyPI entirely, you can do:

```toml
[tool.uv]
index-url = "https://pypi.example.org/simple/"
```

**Comment by NevoleMarek** [comment]
Thanks for the response

I guess the setting `extra-index-url` with `index-strategy = "first-index"` will do for now.

Looking forward to more granular API in the future.

One thing I would like to prevent via the future API is dependency confusion attacks.

**Comment by charliermarsh** [comment]
Makes sense. Our default strategy is more resilient to such attacks than pip (since, if a package exists on your index, we won't even look at PyPI, even if a more recent version is available there), but we do want to add an API that allows for explicit package-to-index assignments.

**Comment by rafalkrupinski** [comment]
Regarding private source repository, is there a way to provide credentials?

**Comment by NevoleMarek** [comment]
The simplest way would be to add the private source repo as `extra-index-url` already with the credentials as follows:

```
[tool.uv]
extra-index-url = ["https://<username>:<password>@<index_url>"]
```

But as you can imagine this not the safest option. A bit more cumbersome but viable option is to specify the index and credentials with the `uv add` command and environment variables.

`uv add package --extra-index-url https://${USERNAME}:${PASSWORD}@<index_url>`

What I would like to see in the future is something similar to Poetry's way of doing this.

In addition to simple addition of sources they also provide the following way to add credentials to the sources.

`poetry config http-basic.your_index <username> <password>` [find more here](https://python-poetry.org/docs/repositories/)

There are other options that `uv` [recommends](https://docs.astral.sh/uv/configuration/authentication/#http-authentication) for http authentication but they are not the simplest either or maybe I am missing something

**Comment by rafalkrupinski** [comment]
@NevoleMarek thanks, I'll check it out!

**Comment by zanieb** [comment]
See also:

- https://github.com/astral-sh/uv/pull/6389
- #171

**Comment by rafalkrupinski** [comment]
Actually I like the idea of using keyring and KWallet integration. Way better than storing passwords in open text.

**Comment by yohann84L** [comment]
Still no alternative to the `poetry config http-basic.your_index <username> <password>` ?

**Comment by zanieb** [comment]
We support `UV_INDEX_<NAME>_USERNAME` and `UV_INDEX_<NAME>_PASSWORD` now

**Comment by hamedhsn** [comment]
@zanieb is there any env variable to set the specific private index URL? like username and password you mentioned above?

I want to use `uv pip install private_pkg` 
the `uv pip` seems not picking up `UV_INDEX_<NAME>_USERNAME and UV_INDEX_<NAME>_PASSWORD`

basically, the question is if I want to use `uv pip install private_pkg` without having pyproject.toml to set the index how can I set the credentials

**Comment by tuomastik** [comment]
For token-based authentication, like Azure Artifacts feed, you can use:

```yml
[[tool.uv.index]]
name = "azureartifacts"
url = "https://pkgs.dev.azure.com/XXX/YYY/_packaging/ZZZ/pypi/simple/"
```

Together with:

```bash
export UV_INDEX_AZUREARTIFACTS_USERNAME=<YOUR_PERSONAL_ACCESS_TOKEN>
```

**Comment by mattiamatrix** [comment]
AWS CodeArtifact worked by setting `UV_INDEX_<NAME>_PASSWORD`

**Comment by TiansuYu** [comment]
This does not solve the issue where some package wants to be specifically declared as from a private pypi. I am missing something like this from the UX: 
```toml
[project]
dependencies = [
    ...
    my-private-package = {version = ">= 0.1.0", index = "my-private-pypi" }
]

[[tool.uv.index]]
name = "my-private-pypi"
url = "https://<some-url>/simple/"
explicit = true
authenticate = "always"
```

similar process is well established within poetry. UV seems to be a bit clunky on that.

**Comment by charliermarsh** [comment]
What you're looking for exists -- it's a core feature:

```toml
[project]
dependencies = ["my-private-package>=0.1.0"]

[tool.uv.sources]
my-private-package = { index = "my-private-pypi" }

[[tool.uv.index]]
name = "my-private-pypi"
url = "https://<some-url>/simple/"
explicit = true
authenticate = "always"
```

**Comment by alanwilter** [comment]
Well, I'm coming from `poetry` and I'm having a hard time with private pypi reportlab.

I have in my `pyproject.toml`:

```toml
[project]
name = "myapp"
version = "0.1.0"
description = ""
authors = [{ name = "me", email = "me@me.com" }]
requires-python = ">=3.12,<4.0"
readme = "README.md"
dependencies = [
    "reportlab (>=4.4.3,<5.0.0)",
    "rlextra (>=4.4.3.1,<5.0.0.0)",
]

[tool.uv.sources]
rlextra = { index = "reportlab" }

[[tool.uv.index]]
name = "reportlab"
url = "https://www.reportlab.com/pypi/"
explicit = true
authenticate = "always"
```

Then I try: `uv sync` and I got:

```
⠼ rlextra==4.4.3.1                                                                                                                                         error: Failed to fetch: `https://www.reportlab.com/pypi/packages/rlextra-4.4.3.1-py3-none-any.whl`
  Caused by: HTTP status client error (403 Forbidden) for url (https://www.reportlab.com/pypi/packages/rlextra-4.4.3.1-py3-none-any.whl/)
```
