### ISSUE TITLE
Workspace member version difficult to update in project when dynamically versioned

### ISSUE THREAD

**Issue by drewfustin** [astral-sh/uv#6694]
### issue
If I update the version of a workspace member that is dynamically versioned via a `path`, `uv sync` or similar doesn't update the member version in any consistent manner between `uv.lock` and `.venv`.

I have a workspace laid out as below with a package `versioned-package` that is a dependency of the main project package `uvbug`. On initial build (`uv sync` or whatever), with `packages/versioned-package/src/versioned-package/_version.py` having `__version__ = "0.0.0"` as below, I get the versions `uvbug==0.1.0` and `versioned-package==0.0.0`, as expected.

If I update `packages/versioned-package/src/versioned-package/_version.py` to `__version__ = "0.0.1"` (e.g.), rerunning `uv sync` doesn't update the build, and I'm still left with `uvbug==0.1.0` and `versioned-package==0.0.0`. On the other hand, if I run `uv cache clean && uv remove versioned-package && uv add versioned-package`, I do get the update. The latter is the only consistent way I can get both the `uv.lock` and `.venv` to update.

My expectation would be that, at the very least (because of caching), `uv cache clean && uv sync` would produce the desired result, but it doesn't update either `uv.lock` or `.venv`. 

I've worked out the following scenarios and whether it updates the version or not:

| command | `uv.lock` updates | `.venv` updates |
| --- | :---: | :---: |
| `uv sync` | ❌ | ❌ |
| `uv cache clean && uv sync` | ❌ | ❌ |
| `uv remove versioned-package && uv add versioned-package` | ❌ | ❌ |
| `uv cache clean && uv remove versioned-package && uv add versioned-package` | ✅ | ✅ | 
| `rm uv.lock && uv sync` | ❌ | ❌ |
| `uv cache clean && rm uv.lock && uv sync` | ✅ | ❌ |
| `rm -r .venv && uv sync` | ❌ | ❌ |
| `uv cache clean && rm -r .venv && uv sync` | ❌ | ✅ |

### environment
* **platform**: macOS Sonoma 14.6.1, Apple M3 Max
* **version**: `uv 0.3.2 (c5440001c 2024-08-23)`

### project layout
```
uvbug
├── packages
│   ├── versioned-package
│   │   ├── pyproject.toml
│   │   └── src
│   │       └── versioned-package
│   │           ├── __init__.py
│   │           └── _version.py
├── pyproject.toml
├── uv.lock
└── src
    └── uvbug
        └── __init__.py
```

### `pyproject.toml`
```toml
[project]
name = "uvbug"
version = "0.1.0"
dependencies = ["versioned-package"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["packages/versioned-package"]

[tool.uv.sources]
versioned-package = { workspace = true }
```

### `packages/versioned-package/pyproject.toml`
```toml
[project]
name = "versioned-package"
dynamic = ["version"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/versioned_package/_version.py"
```

### `packages/versioned-package/src/versioned-package/__init__.py`
```python
from ._version import __version__
```

### `packages/versioned-package/src/versioned-package/_version.py`
```python
__version__ = "0.0.0"
```

**Comment by charliermarsh** [comment]
I think I'm the right person to chime in on this but need to find time to give it a close read. Thanks for the write-up.

**Comment by charliermarsh** [comment]
Can you try using [`cache-keys`](https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata) for this? Like:

```toml
[tool.uv]
cache-keys = ["src/versioned_package/_version.py"]
```

**Comment by zanieb** [comment]
Closing as stale, feel free to reply if you're still having problems.

**Comment by hbredin** [comment]
Same problem on my side, but using 

```toml
# in packages/versioned-package/pyproject.toml
[project]
version = "0.1.0"
```

and then 

```python
# in packages/versioned-package/src/versioned-package/__init__.py
import importlib.metadata
__version__ = importlib.metadata.version("pyannote-audio")
```

`__version__` does not get updated by when I update `packages/versioned-package/pyproject.toml` and then run `uv sync`.
