### ISSUE TITLE
Docs request: Workspaces -- do we add `albatross` to `tool.uv.sources`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#6786]
With `uv==0.4.0` looking at https://docs.astral.sh/uv/concepts/workspaces/#workspace-layouts, it details:
- `albatross` in `src`
- `bird-feeder` in `packages/bird-feeder/src`
- `seeds` in `packages/seeds/src`

The docs don't mention if:

- `albatross` should be added to `tool.uv.sources`
- If `workspace = true` is required, and when to use `path`

The below is what I got working, but it does not match the example shown here: https://docs.astral.sh/uv/concepts/workspaces/#workspace-sources

```toml
[tool.uv.sources]
bird-feeder = {workspace = true}
albatross = {workspace = true}

[tool.uv.workspace]
members = ["packages/*"]
```

More specifically, `albatross = {workspace = true}` is not shown in the docs. But when I remove it and run `uv lock`, I get:

```none
error: Failed to build: `aviary-hotpotqa @ file:///path/to/repo/packages/bird-feeder`
  Caused by: Failed to parse entry for: `albatross`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`
```

**Comment by charliermarsh** [comment]
What do you have in the `pyproject.toml` for `file:///path/to/repo/packages/bird-feeder`?

**Comment by jamesbraza** [comment]
Here is that `pyproject.toml`:

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
dependencies = [
    "albatross",
]
dynamic = ["version"]
name = "bird-feeder"
requires-python = ">=3.11"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."
version_file = "src/bird-feeder/version.py"

```

**Comment by charliermarsh** [comment]
Cool, so in _that_ `pyproject.toml`, you should include:

```toml
[tool.uv.sources]
albatross = { workspace = true }
```

The sources should be defined wherever the dependencies are included. Does that make sense?
