### ISSUE TITLE
`tool.uv.pip.index-url` not working

### ISSUE THREAD

**Issue by sunfkny** [astral-sh/uv#6800]
### Steps to Reproduce:

1. Create a `pyproject.toml` file with the following content:

    ```toml
    [project]
    name = "app"
    version = "0.1.0"
    dependencies = [
        "urllib3",
    ]

    [tool.uv]
    package = false

    [tool.uv.pip]
    index-url = "https://test.pypi.org/simple"
    ```

2. Run the following command:

    ```shell
    ~/app# uv sync --no-cache --upgrade --verbose 2>&1 | grep simple
    ```

3. Observe the output.

### Expected Behavior:

The output should indicate that `uv` is using the specified `index-url` (https://test.pypi.org/simple) to fetch packages.

### Actual Behavior:

The output shows that `uv` is still attempting to access the default PyPI repository:

```
DEBUG No cache entry for: https://pypi.org/simple/urllib3/
```

### Environment:

uv Platform: Ubuntu 24.04 LTS on WSL2
uv Version: uv 0.4.0
