### ISSUE TITLE
refactor `ExcludeNewer` to avoid accidentally exposing "local date" input

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#6820]
Basically, see: https://github.com/astral-sh/uv/pull/6562#pullrequestreview-2269422424

Right now, we are relying on `ExcludeNewer` in `uv-resolver` to have different implementations for `Deserialize` and `FromStr` in order to avoid allowing "local" dates in the `[tool.uv]` section. That seems very easy to accidental mess up, so we should either at least add a comment or change the code to make this harder to mess up.

**Comment by Viicos** [comment]
I would be in favor of enforcing non-ambiguous datetimes to be used, as this causes issues with lockfiles. In our case, we were setting:

```toml
[tool.uv]
exclude-newer-package = { pytest = "2026-06-01" }
```

to allow a newer version to be used (I wasn't the one who wrote this code, I assume the author wanted to allow newer `pytest` versions, but using `"0 day"` is probably better).

When locking locally (I'm UTC+2), my lockfile looks like:

```toml
[options.exclude-newer-package]
pytest = "2026-06-01T22:00:00Z"
```

but in CI, we run `uv lock --check` and it fails with _Resolving despite existing lockfile due to change of exclude newer timestamp from `2026-06-01T22:00:00Z` to `2026-06-02T00:00:00Z` for package `pytest`_.

This can easily be fixed on our end, although I'm wondering if there is a uv bug where it assumed UTC timezone in both CI and local 🤔
