### ISSUE TITLE
`uv lock` doesn't work with packages containing period in name

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#6832]
I have a workspace that looks like this:

```none
.
├── packages
│  └── seeds
│     ├── src
│     │  └── albatross
│     │     └── seeds
│     │        ├── __init__.py
│     │        ├── stub.py
│     │        ├── py.typed
│     │        └── version.py
│     └── pyproject.toml
├── src
│  └── albatross
│     ├── stub.py
│     ├── py.typed
│     └── version.py
├── pyproject.toml
└── uv.lock
```

And the name of the `seeds` package is `albatross.seeds`.

In my repo root's `pyproject.toml`, I have:

```toml
[tool.uv.sources]
albatross = {workspace = true}
"albatross.seeds" = {workspace = true}
```

Running `uv lock`, it:
- Contains `albatross-seeds` not `albatross.seeds`
- Running `pip list` I don't see `albatross-seeds` or `albatross.seeds` anywhere

Here's a subset of the `uv.lock`:

```none
version = 1

[manifest]
members = [
    "albatross",
    "albatross-seeds",
]

[[package]]
name = "albatross"
version = "0.1.dev7+gbe81ca2.d20240829"
source = { editable = "." }
dependencies = []

[package.dev-dependencies]
dev = [
    { name = "pytest" },
]

[package.metadata]
requires-dist = []

[package.metadata.requires-dev]
dev = [
    { name = "pytest", specifier = ">=8" },
]

[[package]]
name = "albatross-seeds"
version = "0.1.dev7+ga33449c"
source = { editable = "packages/seeds" }
dependencies = [
    { name = "albatross" },
]

[package.metadata]
requires-dist = [
    { name = "albatross", editable = "." },
]
```

**Comment by charliermarsh** [comment]
It’s normal for us to normalize the name like that. (Those are equivalent names from the perspective of the standards — they map to the exact same package.) Though it’s confusing that you aren’t seeing it in the environment at all? I’ll try to repro.

**Comment by jamesbraza** [comment]
> It’s normal for us to normalize the name like that.

Sounds good, though ideally the names exactly match for debugging ease.

> Though it’s confusing that you aren’t seeing it in the environment at all? I’ll try to repro.

Yeah when I run `uv sync` the name `albatross-seeds` does not show up. I have to manually `uv pip install` it for it to work

**Comment by charliermarsh** [comment]
Oh sorry, just to clarify, is `albatross.seeds` declared as a dependency of `albatross`? You might be missing this from the `albatross` `pyproject.toml`:

```toml
[project]
name = "albatross"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["albatross.seeds"]
```

**Comment by jamesbraza** [comment]
Yeah it is included as a dependency 👍 thanks for checking. That's not it in this case

**Comment by charliermarsh** [comment]
Ok thanks! I’ll take a look tomorrow.

**Comment by charliermarsh** [comment]
Does `packages/seeds/pyproject.toml` contain a build system? Do you mind sharing that section?

**Comment by jamesbraza** [comment]
> Does `packages/seeds/pyproject.toml` contain a build system? Do you mind sharing that section?

Yes it does, here's a minimal `packages/seeds/pyproject.toml`:

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
dependencies = ["albatross"]
dynamic = ["version"]
name = "albatross.seeds"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."
version_file = "src/seeds/albatross/version.py"
```

**Comment by charliermarsh** [comment]
Thanks. Sorry for all the back-and-forth, I'm just having trouble reproducing:

```
❯ uv sync
Using Python 3.12.1
Creating virtualenv at: .venv
Resolved 2 packages in 2ms
Installed 2 packages in 1ms
 + albatross==0.1.0 (from file:///Users/crmarsh/workspace/puffin/scripts/workspaces/albatross-root-workspace)
 + albatross-seeds==0.1.dev0+d20240830 (from file:///Users/crmarsh/workspace/puffin/scripts/workspaces/albatross-root-workspace/packages/seeds)

❯ uv pip list
Package         Version            Editable project location
--------------- ------------------ ------------------------------------------------------------------------------------------
albatross       0.1.0              /Users/crmarsh/workspace/puffin/scripts/workspaces/albatross-root-workspace
albatross-seeds 0.1.dev0+d20240830 /Users/crmarsh/workspace/puffin/scripts/workspaces/albatross-root-workspace/packages/seeds
```

Are you using `pip list` or `uv pip list`?

**Comment by jamesbraza** [comment]
Both `pip list` and `uv pip list` don't show `albatross.seeds` or `albatross-seeds`.

Here is my `albatross`'s `pyproject.toml`:

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
dependencies = []
dynamic = ["version"]
name = "albatross"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/albatross/version.py"

[tool.uv]
dev-dependencies = [
    "build",  # TODO: remove after https://github.com/astral-sh/uv/issues/6278
    "pytest>=8",  # Pin to keep recent
]

[tool.uv.sources]
"albatross.seeds" = {workspace = true}
albatross = {workspace = true}

[tool.uv.workspace]
members = ["packages/*"]
```

Does that help?

**Comment by charliermarsh** [comment]
Try this:

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
dependencies = ["albatross.seeds"]
dynamic = ["version"]
name = "albatross"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/albatross/version.py"

[tool.uv]
dev-dependencies = [
    "build",  # TODO: remove after https://github.com/astral-sh/uv/issues/6278
    "pytest>=8",  # Pin to keep recent
]

[tool.uv.sources]
"albatross" = { workspace = true }
"albatross.seeds" = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
```
