### ISSUE TITLE
dynamic version in editable install

### ISSUE THREAD

**Issue by pmeier** [astral-sh/uv#6860]
[PEP 621](https://peps.python.org/pep-0621/) allows for dynamic metadata in `pyproject.toml`. Tools like [`setuptools-scm`](https://pypi.org/project/setuptools-scm/) make use of this feature by computing the version of the package at build time.

Imagine I have a git repository with nothing but this `pyproject.toml` file that is committed.

```toml
[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
dynamic = ["version"]

[tool.uv]
dev-dependencies = [
    "setuptools-scm>=8.1.0",
]

[tool.setuptools_scm]
```

```shell
$ ls -lA
total 8
drwxr-xr-x 8 pmeier pmeier 4096 Aug 30 11:40 .git
-rw-r--r-- 1 pmeier pmeier  238 Aug 30 11:34 pyproject.toml
$ git log --oneline
1105907 (HEAD -> main) initial commit
```

Running `uv sync` gives me the following block in `uv.lock`

```
[[package]]
name = "foo"
version = "0.1.dev1+g1105907"
source = { editable = "." }
```

We commit that and move on with development.

```shell
$ git add uv.lock
$ git commit -m "add lock" > /dev/null
$ git log --oneline
409a76d (HEAD -> main) add lock
1105907 initial commit
```

Re-running, `uv sync` results in no changes in the lock file or venv, although we have

```shell
$ uv run python -m setuptools_scm
0.1.dev2+g409a76d
```

Running `uv sync --reinstall-package foo` installs the correct version into the venv (checked with `uv pip show foo`), but again the `uv.lock` file stays untouched. Even why I manually change the version in the lock file to `0+dynamic` (`uv` complains if the string doesn't start with a number), `uv lock` does not change the `uv.lock` file at all.

IMO, in general this is good behavior given that it is impossible to lock the version of this editable package, since its version is computed dynamically. However, I'd prefer not have a quickly outdated version number "hardcoded" in the lock file.

Would it be possible to set the version to `"dynamic"` (or a different sentinel) if the package is an editable install and declares that the version is computed dynamically?

**Comment by AbdealiLoKo** [comment]
I was using dynamic dependencies and version with setup.py/setuptools-scm and had the same issue.
So, this is kinda similar: https://github.com/astral-sh/uv/issues/6822

Currently uv aggressively caches packages, and dynamic packages are not considered. So, as per the current documentation what you are seeing is expected behavior.
https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata

It did feel confusing to me when I saw it first too - and I feel like there will be many more such issues as users use uv more :)
Maybe work enhancing !

**Comment by pmeier** [comment]
Thanks a ton for the pointer. Same as you, I did not find this in the documentation. 

In my case I don't need and more specifically don't want re-installation given that I already have an editable install for a pure Python package. I just don't want an outdated package version in my lock file. Setting it to something like `"0+dynamic"` seems to work, but I have no idea how brittle this is, i.e. does `uv` at some point simply override this?

**Comment by charliermarsh** [comment]
This is still somewhat unsolved

**Comment by spaceman-cb** [comment]
This is a problem for me as well.
I am running `uv 0.4.29 (Homebrew 2024-10-30)`

I use setup tools as my build system, and in pyproject.toml I have `dynamic = ["version"]` set.
I am using a "src layout" and my version is set in `__init__.py`: `__version__ = "3.0.0"`

When I update my version number, and run `uv sync`, the the CLI output shows that the version has changed, but it remains the same in uv.lock.

Neither setting `cache-keys` nor `reinstall-package` in pyproject.toml seem to have any effect, e.g. 

```toml
[project]
name = "drftmrks"
dynamic = ["version"]

# ...

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "src/mypackage/__init__.py" },
    { git = true }
]
reinstall-package = ["mypackage"]
```

The only way I seem to be able to force it to update the version in uv.lock is to manually delete the entry for my package there, and then run `uv sync`.
