### ISSUE TITLE
Recommend pipe fail option on GitHub actions uv install? 

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#6871]
I'd be happy to open a PR to update the docs, but it wasn't clear to me just yet if this *should* be recommended.

I set up a github workflow in my company's local github enterprise install with the following step taken from the [docs](https://docs.astral.sh/uv/guides/integration/github/#installation):

```yaml
 - name: Set up uv
   # Install latest uv version using the installer
   run: curl -LsSf https://astral.sh/uv/install.sh | sh
```

However, what I found was if the curl command fails this step can still succeed, this can happen because of either curl not being available, some network issue, or something else. I ended up replacing this step with:

```yaml
  - name: Set up uv
    shell: bash
    run: | # Install latest uv version using the installer
      set -o pipefail
      curl -LsSf https://astral.sh/uv/install.sh | sh
```

So if the curl command fails it produces an error.

Do you think the docs should be updated in general? Or do you think this is enough of an edge case not to make the instructions overly complicated?
