### ISSUE TITLE
Fix meta tags etc. to avoid showing Ruff metadata in SERPs

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6920]
![Screenshot 2024-09-01 at 2 21 43 PM](https://github.com/user-attachments/assets/8731cac6-260b-4c81-afde-1c5aa0bdae68)

**Comment by charliermarsh** [comment]
I think we need to set meta titles for every page, like:

```yaml
---
title: "Docker | uv"
description: "Using uv in Docker."
---
```
