### ISSUE TITLE
Help: Overriding package source

### ISSUE THREAD

**Issue by lambda-science** [astral-sh/uv#6927]
Hey
I work on a monolith repo, that I set up with UV workspace.
My app `b` is using my package `a` inside.
So in my app `b`  `DockerFile` I have a simple `RUN uv sync`
With a `pyproject.toml` as
```
dependencies = [
    "a==0.5.1"
```
How can I modify `RUN uv sync` so the package `a` will not be retrieved from PyPi but installed in editable mode from local folder (that will be mounted as volume in the Docker Image in a specific `Dockerfile.dev` used only during development)
Something like `RUN uv sync --override-source a /app/package/a -e` something like that ?

I found `uv sync --no-source`  but I'm fetching another package from Git, that should be fetched from git (I want to change to activate the `--no-source` for one package only

Thanks !

**Comment by lambda-science** [comment]
Solved with
```toml
[tool.uv.sources]
a = { workspace = true }

[tool.uv.workspace]
members = [
    "/code/b/pkgs/*"
]
```
and `--no-source` in prod
