### ISSUE TITLE
type stub packages (a documentation request)

### ISSUE THREAD

**Issue by KDruzhkin** [astral-sh/uv#6930]
Type stubs can be provided in separate packages. For example, a package `foo` has a companion package `types-foo` or `foo-stubs`.

With poetry, a typical _pyproject.toml_ file looks like this:

```toml
[tool.poetry.dependencies]
pandas = ">=2.2.2"
psutil = ">=6.0.0"
tqdm = "^4.66.0"

[tool.poetry.group.dev.dependencies]
mypy = ">=1.10.0"
pandas-stubs = ">=2.2.2"
types-psutil = ">=6.0.0"
types-tqdm = ">=4.66.0"
```

So, with poetry, the development virtual environment contains both `mypy` and the stub packages (used by `mypy` to check the project).

How should I handle stub packages with `uv`? Do they belong in the tool environment for `mypy`? If yes, then do I put them there?

**Comment by charliermarsh** [comment]
Good question, we can document this. In general MyPy and the type stubs should all be in `[tool.uv.dev-dependencies]`.

**Comment by KDruzhkin** [comment]
So, `mypy` is different from most other tools: it does not work well in isolation.

To be precise, _if_ you want `mypy` to follow imports:

```toml
[tool.mypy]
follow_imports = "normal"
```
... then `uv tool run mypy` is not the way to go.
