### ISSUE TITLE
Dependency resolution unnecessarily falls back to a very old pylint version

### ISSUE THREAD

**Issue by hofrob** [astral-sh/uv#6941]
# versions

- ubuntu: 22.04
- uv: 0.4.2

# pyproject.toml

```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
]

[project]
name = "uv-pylint-resolution"
version = "1"
requires-python = ">=3.12"
optional-dependencies.dev = [
    "pylint[spelling]",
]
optional-dependencies.test = [
    "astroid",
]
```

# command

Run `uv sync --all-extras` installs the following dependency tree: 

```
pylint v2.3.0
├── astroid v3.3.2
├── isort v5.13.2
└── mccabe v0.7.0
```

There is no reason to use pylint 2.3.0 as far as I can see. The current pylint version is 3.2.7.

# `uv sync --verbose --all-extras`

[uv_pylint_verbose.txt](https://github.com/user-attachments/files/16840777/uv_pylint_verbose.txt)

**Comment by charliermarsh** [comment]
You get the resolution you expect with:
```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
]

[project]
name = "uv-pylint-resolution"
version = "1"
requires-python = ">=3.12"
optional-dependencies.dev = [
    "pylint[spelling]",
]
optional-dependencies.test = [
    "astroid<3.3.0",
]
```

The issue is that the resolver is prioritizing solving for `astroid`, so you get a newer version of `astroid` (`3.3.2`) than is supported by newer versions of `pylint`. This isn't any less valid than a resolution that gives you `pylint==v3.2.7` and `astroid==v3.2.4`, though that resolution makes more sense from a user perspective.

**Comment by charliermarsh** [comment]
This also works, perhaps more intuitive:

```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
]

[project]
name = "uv-pylint-resolution"
version = "1"
requires-python = ">=3.12"
optional-dependencies.dev = [
    "pylint[spelling]>=3",
]
optional-dependencies.test = [
    "astroid",
]
```
