### ISSUE TITLE
uv.lock gets invalid value when changing pyproject.toml manually

### ISSUE THREAD

**Issue by Morgadoooo** [astral-sh/uv#6963]
Hi, 

When using `pyproject.toml` for managing dependencies, I got a weird behaviour. 
Using `python 3.9.16` and `uv 0.4.2`
My first `pyproject.toml` is this one
```toml
[project]
name = "toto"
version = "1.0.0"
requires-python = ">=3.8,<3.13"
dependencies = [
  "numpy>=1.18.5",
  "pandas>=1.1.5",
]

....
```
When i do `uv lock` everything is fine and I also can do `uv sync`
I noticed that for python 3.12 you cannot use numpy <1.26.4, so I decided to update the pyproject.toml manually like this.
```toml
[project]
name = "toto"
version = "1.0.0"
requires-python = ">=3.8,<3.13"
dependencies = [
  "numpy>=1.18.5; python_version<'3.12'",
  "numpy>1.26.4; python_version=='3.12'",
  "pandas>=1.1.5; python_version<'3.12'",
  "pandas>=2.1.0; python_version=='3.12'",
]

...
```
But now if I try to do `uv lock` and then `uv sync` in python 3.9.16 uv tries to install numpy==2.1.0 which is only available for python >= 3.10

Deleting the `uv.lock` and doing again `uv lock` fixes the issue
