### ISSUE TITLE
Ignore workspace in local dependency with `uv lock`

### ISSUE THREAD

**Issue by helderco** [astral-sh/uv#7055]
I have a library `dagger-io` that is vendored locally in a `./sdk` directory in a new project `main` (structured as a library):

```toml
[project]
name = "main"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["dagger-io"]

[tool.uv.sources]
dagger-io = { path = "sdk", editable = true }

[build-system]
requires = ["hatchling==1.25.0"]
build-backend = "hatchling.build"
```

The `dagger-io` library has a workspace with a `codegen` member during development, but not available when vendored (copied into `./main/sdk/pyproject.toml`):
```toml
[project]
name = "dagger-io"
# ...

[tool.uv]
dev-dependencies = ["codegen"]

[tool.uv.sources]
codegen = { workspace = true }

[tool.uv.workspace]
members = ["codegen"]
```

So, when I create a lock file (`uv lock`) for project `main`, I get the following error:
```
error: Failed to build: `dagger-io @ file:///src/e864914331058348cb7b498167502588bd163773f866206b82eb4c4758730712/sdk`
  Caused by: Failed to parse entry for: `codegen`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`
```

I want to ignore the workspace information in `dagger-io` when installed as a dependency since that workspace is for developing the `dagger-io` library, in a separate repo.

Or is there another solution to this?
