### ISSUE TITLE
Can I constraint build requirements with uv build?

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#7082]
I tried using the new uv build with a pyproject.toml that looks like this:

```toml
[build-system]
requires = ["setuptools==74.1.1", "wheel==0.44.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minimal_project"
version = "0.1.0"
```

I created a `build-constraints.txt` file that looks like this (the versions contradict the build requires and hashes are purposefully wrong):

```
setuptools==69.0.0 --hash=sha256:fc91b5f89e392ef5b77fe143b17e32f65d3024744fba66dc3afe07201684d766
wheel==0.40.0 --hash=sha256:2376a90c98cc337d18623527a97c31797bd02bad0033d41547043a1cbfbe4481
```

I then set `UV_BUILD_CONSTRAINT` to point to my `build-constraints.txt`, and then I ran `uv build .`, but I did not get an error that these versions or hashes are wrong. 

Is there a way to constrain build requirements during building? I specifically think of scenarios where I don't control the contents of an sdist, or there are recursive build requirements I want to constrain.
