### ISSUE TITLE
Remove `{ workspace = true}` requirement for sources

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#7143]
We error if a package is in the workspace but isn't marked as `{ workspace = true }`. Should we just infer this? As-is, you need to specify the members up to three times (once in members, once in dependencies, and once in sources).

**Comment by charliermarsh** [comment]
I think this _probably_ makes sense. The downside is, if this is omitted by default, then we lose the behavior that we error if you mark `workspace = true` but the package _isn't_ found.

**Comment by mmerickel** [comment]
I could be missing some nuance but I don't really see the logic in the current behavior. If I add the packages to the workspace then it'd be quite surprising to me for them to not be found/installed from the workspace when other packages depend on them. So to me it's only an improvement to add them to the list of sources by default to avoid having to duplicate them. It's even worse because the original workspace declaration is a glob for me hiding the details, and then I need to explicitly list the packages anyway.

```toml
[project]
# this can technically contain a subset of the packages so it makes sense to declare them here as default dependencies of the workspace
dependencies = ["my-foo", "my-bar", "..."]

# it'd be nice to get rid of this
[tool.uv.sources]
my-foo = { workspace = true }
my-bar = {workspace = true }
# ...

[tool.uv.workspace]
members = ["src/*"]
```

**Comment by mmerickel** [comment]
I should also point at that rye's workspaces don't have this extra sources requirement. In rye the packages are automatically workspace-packages when added to `tool.rye.workspace.members`.

**Comment by charliermarsh** [comment]
Just to be explicit: if a package is defined in the workspace but not declared as a source, we error rather than proceeding. So we're just being strict in asking users to specify the source explicitly. It might be more annoying than helpful though.

**Comment by charliermarsh** [comment]
I think I'm fine to remove this. If a user does it explicitly, we can then error if the package isn't found in the workspace but is marked as `{ workspace = true }`. I guess this is breaking, though... any applications that would be affected by it would _already_ error today, so maybe not.

\cc @konstin @zanieb

**Comment by konstin** [comment]
This behavior was carried over from cargo, which intentionally requires `{ workspace = true }`.  In cargo, with `workspace = true` and `registry = "..."` you can always tell just from `Cargo.toml` where a dependency comes from, you have to explicitly annotate if you want a dependency that's not from the default registry.

I don't expect this change to be breaking, iirc `workspace = true` is a read-only check that doesn't actually change dependency lowering, you'd just have to remote this check:

https://github.com/astral-sh/uv/blob/56cc0c9b3cac860b072d2b22556d441d602a0eb0/crates/uv-distribution/src/metadata/lowering.rs#L47-L63

**Comment by charliermarsh** [comment]
@konstin -- Any opinion on changing it?

**Comment by konstin** [comment]
I like the explicitness in cargo but I see the awkwardness when applied in a split-table dependencies vs. sources scenario.

**Comment by Tremeschin** [comment]
Having implicit `workspace=true` in sources allows for having private packages/insiders repositories part of the venv glob listed in `members`. I've already migrated to `uv` and failed to notice this beforehand, not breaking for me but not ideal.

Somewhat related, but I find it weird having to re-define the workspace packages in `dev-dependencies` (without a version) for any `[project.scripts]` defined in member projects to create their entry points in the `venv` bin directory. Maybe I'm doing something wrong, most documentation points to `uv run {cmd}` which I don't really find ideal;

point is, listing a package in a rye workspace implies all of that, I had to lurk to get it working 🙂

**Comment by tsudol-plaid** [comment]
An additional point: this would be nice to have because the [workspace docs](https://docs.astral.sh/uv/concepts/projects/workspaces/) recommend using a glob for workspace members. What's the point of accepting a glob for `tool.uv.workspace.members` when you have to go define `tool.uv.sources` for each one anyway?

```toml
[tool.uv.sources]
bird-feeder = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/seeds"]
```

But I'll admit that cargo requiring this is a strong argument in its favor.

**Comment by hterik** [comment]
This may be a naive idea but what about allowing the workspace and source to be declared together:
```toml
[tool.uv.sources]
bird-feeder = { workspace = true, workspace_path = "packages/bird-feeder" }
seeds = { workspace = true, workspace_path = "packages/seeds" }
```
vs how that looks like today
```toml
[tool.uv.sources]
bird-feeder = { workspace = true }
seeds = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/bird-feeder", 
    "packages/seeds", 
]
```
One wide table with everything in one place is easier to manage than keeping two separate tables in sync. Assuming you are not using globs.

You could take this idea further by infering `workspace = true` when `workspace_path` is set.
