### ISSUE TITLE
`uv sync` and `uv pip install -e .` do different things when virtual packages are in the workspace

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#7145]
`uv sync` omits them, while `uv pip install -e .` installs them as non-editable. This seems bad. At the very least, I'd say that `uv pip install -e .` should install them as editable.

**Comment by charliermarsh** [comment]
\cc @zanieb for input on the correct behavior

**Comment by zanieb** [comment]
Can you share a bit more details on what a reproduction looks like?

**Comment by charliermarsh** [comment]
If you `uv init foo` then `cd foo` and `uv init bar`, and add `bar` as a dependency:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["bar"]

[tool.uv.workspace]
members = ["bar"]

[tool.uv.sources]
bar = { workspace = true }
```
