### ISSUE TITLE
The result package dependencies of  ``uv build`` cannot be Git.

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/uv#7167]
**uv version:** uv 0.4.7 (a178051e8 2024-09-07)
If a project depends on a package that doesn't exist on PyPI, the resulting wheel from uv build will also be unusable.
![image](https://github.com/user-attachments/assets/d8fa64c2-9d2c-4c56-872e-9630d5319bbc)
Due to this problem, I am unable to depend on private packages.

```toml
[project]
name = "temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-world",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
python-world = { git = "https://github.com/ceddlyburge/python_world" }
```
**Note:** I didn't verify the contents of the Git repository. I simply found a package name that doesn't exist on PyPI.
**Note:** I'm using URL dependencies for wheels, but since it's a private package, I've found another way to reproduce the same issue.
[dist.zip](https://github.com/user-attachments/files/16918152/dist.zip)
