### ISSUE TITLE
`uv build` does not include package contents in wheel when the project name is different from the package

### ISSUE THREAD

**Issue by albireox** [astral-sh/uv#7227]
I have a project with the following relevant (?) `pyproject.toml`

```toml
[project]
name = "lvm-ln2fill"
requires-python = ">=3.12,<4"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
packages = ["src/ln2fill"]

[tool.hatch.build.targets.wheel]
packages = ["src/ln2fill"]
```

The directory structure is

```
|
|— src/
|—— ln2fill/
|——— __init__.py
|——— ...
|— pyproject.toml
```

so that the project name (`lvm-ln2fill`) is different from the package to include `src/ln2fill`.

When I do `uv build` the source file looks fine and has all the files in `src/ln2fill` but the wheel only contains the metadata and no code files. With the same configuration, if I do `uvx hatch build` both the source and wheel look fine.

**Comment by charliermarsh** [comment]
What does `python -m build` give you?

**Comment by albireox** [comment]
It seems the same happens with `python -m build`. The source tar file looks fine but the wheel doesn't include any code, so maybe this is an issue with `hatch`.

**Comment by albireox** [comment]
For what it's worth. This works with `setuptools` for both source and wheel.

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["ln2fill*"]
```
