### ISSUE TITLE
Questions: Migrating from poetry

### ISSUE THREAD

**Issue by EdgyEdgemond** [astral-sh/uv#7245]
I came here looking for information on `poetry env info` but found another comment on a closed issue that covered a few other points. So I hijacked that comment.

_Originally posted by @mikeleppane in https://github.com/astral-sh/uv/issues/6668#issuecomment-2311845394_

After using Poetry for years, I've decided to try uv. And it's great 👏. Here are some thoughts I had while using uv. Some of these may have been discussed already.
- export only dev-dependencies from uv.lock to requirements-dev.txt (this is useful at least in the CI); _poetry export --without-hashes --without-urls  --only=dev -o requirements-dev.txt_
- _uv sync/pip install_ only dev-dependencies (like above useful in the CI) 
- show the latest version but only for outdated packages; _poetry show --outdated_ / _poetry show --outdated --only=dev_ has been useful. 
- how do get info about the current virtual env? E.g. Poetry has _poetry env info_ command to display info about current env
- is it possible to only update dev-dependencies like _poetry update --only=dev_?

Thanks!

_Originally posted by @mikeleppane in https://github.com/astral-sh/uv/issues/6668#issuecomment-2311845394_

**Comment by charliermarsh** [comment]
A lot of different questions here but I'll try to answer them:

> export only dev-dependencies from uv.lock to requirements-dev.txt (this is useful at least in the CI); poetry export --without-hashes --without-urls --only=dev -o requirements-dev.txt

> uv sync/pip install only dev-dependencies (like above useful in the CI)

These don't exist right now, see #6472.

> show the latest version but only for outdated packages; poetry show --outdated / poetry show --outdated --only=dev has been useful.

`--outdated` isn't supported yet, see https://github.com/astral-sh/uv/issues/2150.

> how do get info about the current virtual env? E.g. Poetry has poetry env info command to display info about current env

We intentionally don't support using an arbitrary virtual environment for the uv "project" APIs (`uv sync`, `uv lock`, etc.), it also lives in `.venv`. What information would you want here?

> is it possible to only update dev-dependencies like poetry update --only=dev?

Same thing, we don't support this kind of only-dev workflow right now.

> to add to this, I can see how to do forks in resolving dependencies, and adding sources. Is the following case covered in uv currently?


You can accomplish this without `tool.uv.sources`, i.e., using only standards-compliant metadata, but `tool.uv.sources` doesn't support a list like that right now (see https://github.com/astral-sh/uv/issues/3397):

```toml
[project]
dependencies = [
    torch @ https://download.pytorch.org/whl/cpu/torch-2.0.1-cp310-none-macosx_11_0_arm64.whl ; sys_platform == 'darwin' and platform_machine == 'arm64'
    torch @ https://download.pytorch.org/whl/cpu/torch-2.0.1-cp310-none-macosx_10_9_x86_64.whl ; sys_platform == 'darwin' and platform_machine == 'x86_64'
    torch==2.0.1 ; sys_platform != 'darwin' or platform_machine != 'arm64' or platform_machine != 'x86_64'
]
```

Then you'd set `https://download.pytorch.org/whl/cpu` as your `extra-index-url`.

That last feature (`explicit` pinning) is tracked in #171.
