### ISSUE TITLE
Can't install `chumpy`

### ISSUE THREAD

**Issue by YouJiacheng** [astral-sh/uv#7291]
uv version
```
uv 0.4.7 (a178051e8 2024-09-07)
```

Reproduce:
```
uv add chumpy
```

![image](https://github.com/user-attachments/assets/39974291-bb11-46f0-9d97-a27baefbeae8)

It's similar to #1551 but the solution don't work:
1. Use `uv init --lib` to create a project that allows `[build-system]`
2. Modify the `[build-system]` to
![image](https://github.com/user-attachments/assets/526a64ae-6560-45c1-967b-89803f551666)
3. Use `uv add chumpy`, and get an error
![image](https://github.com/user-attachments/assets/19d75c21-95e3-4e76-950f-9d0a48dcafa8)

`uv add pip`/`uv pip install pip` then `uv add chumpy`/`uv pip install chumpy` don't work.

`uv add pip`/`uv pip install pip` then `uv run pip install chumpy`/`uv run python -m pip install chumpy` don't work. (NOTE: they work when there is a cached wheel.)

![image](https://github.com/user-attachments/assets/fa0e709a-7f82-4810-859f-a1bd411486a6)

But pixi can handle this.
```
pixi add python pip
pixi run pip install chumpy
```
![image](https://github.com/user-attachments/assets/ce437983-71fc-481f-84a4-295fc8bdc973)

**Comment by charliermarsh** [comment]
Sadly this is an issue with `chumpy` itself. The package is not properly structured -- it's documented as such here: https://github.com/astral-sh/uv/issues/2252#issuecomment-1981978204. For example, it also won't work if you run `pip install chumpy --use-pep517`, which will eventually be the default:

```console
❯ pip install chumpy --use-pep517
Collecting chumpy
  Downloading chumpy-0.70.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'pip'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/crmarsh/.local/share/rtx/installs/python/3.12.3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/crmarsh/.local/share/rtx/installs/python/3.12.3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ...
```

(In the pixi example you included, that's just pixi running `pip` within an environment, there's no special handling there that differs from `pip install`.)

You can either use `uv pip install chumpy --no-build-isolation`, or see the docs on using [build isolation](https://docs.astral.sh/uv/concepts/projects/#build-isolation) with `uv add` and related APIs.

**Comment by YouJiacheng** [comment]
Thanks! I should google "uv can't install chumpy" instead of the error message! Hope this pointer can help others who google the error message!

Here are verified solutions following [build isolation](https://docs.astral.sh/uv/concepts/projects/#build-isolation):
Solution 1:
```toml
[project]
name = "smpl-preprocess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy<1.24",
    "scipy<2",
    "chumpy",
]

[tool.uv]
no-build-isolation-package = ["chumpy"]

```
Run
```pwsh
uv venv
uv pip install pip setuptools
uv sync

```
![image](https://github.com/user-attachments/assets/e507a36d-f0a3-43e2-9b96-e820b9754a03)

Solution 2:
```toml
[project]
name = "smpl-preprocess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy<1.24",
    "scipy<2",
]

[project.optional-dependencies]
build = ["setuptools", "pip"]
run = ["chumpy"]

[tool.uv]
no-build-isolation-package = ["chumpy"]

```
It won't work if we follow [build isolation](https://docs.astral.sh/uv/concepts/projects/#build-isolation)
```pwsh
uv sync --extra build
uv sync --extra run

```
![image](https://github.com/user-attachments/assets/73d7cd5f-271b-4a30-98bc-7142137ea9c3)
But I found that it will work if we run `uv lock` first: (@charliermarsh do you know why?)
```
uv lock
uv sync --extra build
uv sync --extra run
```
![image](https://github.com/user-attachments/assets/d6fcd127-ddaf-4129-a6d6-f7a29f00b1e5)
