### ISSUE TITLE
uv run and pyproject configuration

### ISSUE THREAD

**Issue by patrickporto** [astral-sh/uv#7313]
I searched some similar issue but I didn't find anything.

I have the following structure in my project:

```
workspace
├──  packages
│   ├── package-a
│   │    ├── pyproject.toml
│   └──  package-b
│          └── pyproject.toml
└──  pyproject.toml 

```

I have installed `pytest` and `pytest-env` at `package-a`. After that, I put the following configuration on package-a's pyproject.toml:

```toml
[tool.pytest_env]
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_REGION = ""
```

Finally I have tried to execute `uv run --package package-a pytest` from workspace root when I got a error for it didn't find the configuration on pyproject.toml. I only got execute this one if it is executed on package folder.

uv platform: Linux
uv version: 0.4.9
