### ISSUE TITLE
Project's name interferes with resolution logic

### ISSUE THREAD

**Issue by nhedger** [astral-sh/uv#7329]
When attempting to `add` or `sync` a dependency to a project, if the dependency depends on a package whose name matches the name in your pyproject.toml, resolution fails.

---

Create the following **pyproject.toml**

```toml
[project]
name = "dagster"
version = "0.0.0"
description = "Add your description here"
requires-python = ">=3.12"
```

Run `uv add dagster-webserver --verbose` (`dagster-webserver` depends on `dagster`)

[log.txt](https://github.com/user-attachments/files/16980042/log.txt) (too big to paste)

Changing the name in pyproject.toml makes it work correctly.

Running on macOS 14.6.1 (23G93), with uv 0.4.9 (Homebrew 2024-09-10)
