### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by pkucmus** [astral-sh/uv#7341]
Hello.

[UV: 0.4.6, Python: 3.12.4]

(I'm using Poetry since it's inception, so I might be opinionated, but I'm learning a lot when going through the issues here - if something might sound like a "Poetry user's opinion" feel free to call me out :))

I'm also quite opinionated when it comes to the project directory structure, what you propose [here](https://docs.astral.sh/uv/guides/projects/#project-structure), for projects leads into other challenges down the line, like being forced to "dance around" the `.venv` directory in Docker.

```
.
├── .venv
│   ├── bin
│   ├── lib
│   └── pyvenv.cfg
├── .python-version
├── README.md
├── hello.py
├── pyproject.toml
└── uv.lock
```

Where if you were to "`src` the project", like so:

```
.
├── .venv
│   ├── bin
│   ├── lib
│   └── pyvenv.cfg
├── src
│   └── my_project
│       └── hello.py
├── .python-version
├── README.md
├── pyproject.toml
└── uv.lock
```

Then a few things can happen:

1. You can Docker volume everything that's in `src` 

```yaml
services:
  my_project:
    ...
    volumes:
      - ./src:/app/src
```

2. You can leverage Docker cache in build time if the dependencies did not change

```Dockerfile
FROM python:3.12
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

...

WORKDIR /app

COPY uv.lock pyproject.toml ./

ARG INSTALL_DEV=false
RUN uv sync --frozen --no-install-project
COPY . .  
RUN uv sync --frozen
```

don't redo the dependency installation if uv.lock or pyproject.toml did not change

3. you can explicitly reference your root project with 

```python
from my_project import hello
```

This approach should be doable with a pyproject.toml addition of:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "src/my_project",
]
```

but for some reason my_project is not available for import.
