### ISSUE TITLE
`uv lock` Improvement: a consistent environment for `prepare_metadata_for_build_wheel`.

### ISSUE THREAD

**Issue by YouJiacheng** [astral-sh/uv#7390]
https://github.com/astral-sh/uv/issues/7291
Currently, `uv lock` runs in the Python interpreter specified by "Python options" (shown by `uv lock --help`).
![image](https://github.com/user-attachments/assets/0013c39f-f366-44f9-8dc6-bb41cd95c85e)

However, as discussed in #7291 , even managed Python Interpreters can have an environment inconsistent with the default virtual environment created by `uv venv`.
Let `uv lock` be "polluted" by the system Python Interpreter with an arbitrary environment sounds even worse.

Ideally we can specify this in `pyproject.toml` with a default to an environment **equivalent** to the one created by `uv venv`.
And we can also specify `index-url`.
Expectation by example:
```toml
[tool.uv]
lock-dependencies-default = []

[tool.uv.lock-index-url]
torch = "https://download.pytorch.org/whl/cu124"

[tool.uv.lock-dependencies]
flash-attn = ["setuptools", "packaging"]
chumpy = ["setuptools", "pip"]
```
OR 
```toml
[[tool.uv.lock-resolution]]
name = "torch"
index-url = "https://download.pytorch.org/whl/cu124"
dependencies = ["setuptools"]

[[tool.uv.lock-resolution]]
name = "flash-attn"
dependencies = ["setuptools", "packaging"]

[[tool.uv.lock-resolution]]
name = "chumpy"
dependencies = ["setuptools", "pip"]
```

**Comment by charliermarsh** [comment]
There's a significant downside to this, which is that it would require that we create a virtual environment to perform `uv lock` (despite the fact that we never modify it). I'm hesitant to make that change, given that (1) build isolation is relatively rare, and (2) we want to redesign it anyway.

Can you file the second suggestion here as its own issue? I think it's separate.

\cc @zanieb

**Comment by YouJiacheng** [comment]
"the second suggestion here" -- did you mean index-url stuffs or the whole "lock resolution config" thing?

**Comment by YouJiacheng** [comment]
IIUC all package that have a dynamic metadata will need an environment to run `prepare_metadata_for_build_wheel`?

**Comment by YouJiacheng** [comment]
> we want to redesign it anyway.

is there any roadmap for this?

**Comment by charliermarsh** [comment]
I misread your second suggestion. I thought you were suggesting something like https://github.com/astral-sh/uv/issues/7393 which would also fix this by allowing you to define the Chumpy requirements upfront rather than requiring that we build it.

**Comment by charliermarsh** [comment]
The `[tool.uv.lock-index-url]` is unlikely to happen as we're adding an entirely separate API for indexes (#171).

**Comment by YouJiacheng** [comment]
Okay that sounds bad.
Useful cases are too rare.
And this can confuse the users -- "is it the dependencies for setup.py of the package or the whole package?" -- even you misread my example.

**Comment by charliermarsh** [comment]
> is there any roadmap for this?

Let me look... The main idea was that we wanted to add a new build isolation API for `uv sync` and `uv lock`, but we didn't have time so we decided to support `--no-build-isolation` like in pip. I have some unformed ideas around allowing packages to declare the dependencies that they need to pull in from the existing environment, kind of like what you had above... E.g.:

```toml
name = "flash-attn"
dependencies = ["setuptools", "packaging", "torch"]
```

...could create a virtual environment, and then give it access to the already-installed `torch` from another virtual environment. So it'd be a sort of hybrid form of isolation: the build happens in a new, isolated environment, but we link in packages that are installed in a separate environment.

**Comment by YouJiacheng** [comment]
I think `flash-attn` can be solved by #7393 + switching between two optional dependencies groups?
But yeah "hybrid form of isolation" is not bad.

**Comment by YouJiacheng** [comment]
Can we provide a first-class support for "switching between two (or more) optional dependencies groups"?
Just standardize it with inspiration from Docker multi-stage builds -- the outputs of build stages are wheels.
```toml
[[tool.uv.build-stage]]
dependencies = ["setuptools", "packaging", "psutil", "ninja", "torch"]
outputs = ["flash-attn", "some-other-packages"]
[[tool.uv.build-stage]]
dependencies = ["setuptools", "torch", "flash-attn"]
outputs = ["some-packages"]
```

**Comment by sharifhsn** [comment]
Most of this shipped as declarative build-environment configuration.

Per-package build dependencies:

```toml
[tool.uv.lock-dependencies]
flash-attn = ["setuptools", "packaging"]
chumpy = ["setuptools", "pip"]
```

Shipped as `extra-build-dependencies` in #14735 (uv 0.8.4, preview), stabilized in #17767 (uv 0.10.0):

```toml
[tool.uv.extra-build-dependencies]
flash-attn = ["setuptools", "packaging"]
chumpy = ["setuptools", "pip"]
```

For the flash-attn / torch case where the build must see the runtime version of a dependency, #15036 (uv 0.8.5) added `match-runtime`:

```toml
[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]
```

Per-package index:

```toml
[tool.uv.lock-index-url]
torch = "https://download.pytorch.org/whl/cu124"
```

Shipped as named indexes in #7481 (uv 0.4.23):

```toml
[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"

[tool.uv.sources]
torch = { index = "pytorch" }
```

Pre-defining metadata to skip the build entirely shipped as `dependency-metadata` in #7442 (uv 0.4.12):

```toml
[[tool.uv.dependency-metadata]]
name = "chumpy"
version = "0.70"
requires-dist = ["numpy", "scipy", "six"]
```

These build-isolation setups are documented together in #15326: https://docs.astral.sh/uv/concepts/projects/config/#build-isolation

Two ideas from the thread were not implemented: a global default build-dependency set (`lock-dependencies-default`), and first-class multi-stage builds (`[[tool.uv.build-stage]]` with wheel outputs). This issue is closeable if those are not in scope for uv.
