### ISSUE TITLE
Use the lockfile as constraints when doing uv run --with

### ISSUE THREAD

**Issue by delfick** [astral-sh/uv#7416]
Hello,

I'm using uv 0.4.10

I'm trying to make my [project](https://github.com/delfick/extended-mypy-django-plugin/pull/60) use uv project semantics and to get around uv not having support for conflicting requirements I have scripts to run my tests with either `uv run --with mypy==1.4.0 django-stubs==4.2.3` or `uv run --with mypy==1.11.2 --with django-stubs==5.0.2` and that works.

However, it seems that it's not using the lock file as a constraints and so it's not respecting that I have a specific version of django in my project.

Is it possible to make it so that doing a uv run using ``--with`` uses the lock file as a constraints?

**Comment by juftin** [comment]
Agreed - I came looking for a very similar issue to this. In my case I'd like to run Python CLIs in my environment without installing other tools. 

For example, in a `linting` CI/CD job I'd like to just run `ruff` which is one of my dev dependencies, without installing everything else:

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
  "requests"
]
name = "example"
readme = "README.md"
requires-python = ">=3.11,<4"
version = "0.1.0"

[tool.uv]
dev-dependencies = [
  "ruff>=0.6.5",
  "pytest>=8.3.3"
]
```

In this case I would want to run something like this and have it respect my lockfile:

```sh
uv run --with ruff ruff format .
```

Even better (for my use case), it would be nice to install ruff into my virtual environment without having to install any of my other dev dependencies:

```
uv run --only-sync ruff ruff format .
```
