### ISSUE TITLE
uv >=4.8 cache error output

### ISSUE THREAD

**Issue by pmbarrett314** [astral-sh/uv#7479]
UV 4.8 and above is outputting an error that is breaking tests that expect specific console output when caching is enabled. 4.7 works fine.

The error is: 
error: Failed to build: `curses-menu @ file:///home/runner/work/curses-menu/curses-menu`  Caused by: Failed to deserialize cache entry  Caused by: wrong msgpack marker FixArray(2)'

which comes from [this run](https://github.com/pmbarrett314/curses-menu/actions/runs/10899095053/job/30278277407).

It doesn't seem to be causing any issues running most of my tests, only the ones that are using pyte to test the visual output of my code, which leads me to believe the error itself might not be causing the break, but that it might be being output somewhere it shouldn't be (or I'm reading output from somewhere I shouldn't be).

Do I just need to suppress this error somehow or is this an actual bug?

**Comment by pmbarrett314** [comment]
Here's the relevant job from my GitHub Action

```
  initial-test:
    name: Test One Version First
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ vars.UV_VERSION }}
          enable-cache: true
      - name: Set up Python
        run: uv python install ${{ vars.MAIN_PYTHON }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - run: uv run pytest
        name: Run tests
      - run: uv run coverage lcov
        name: Generate coverage report for this run
      - name: Upload coverage report for this run to coveralls
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: .cov/coverage.lcov
          parallel: true
```
