### ISSUE TITLE
`uv sync --no-source` breaking from 0.4

### ISSUE THREAD

**Issue by lambda-science** [astral-sh/uv#7572]
Hello,

My basic TOML:
```toml
[project]
name = "pythia-streamlit"
version = "0.4.0"
dependencies = [
    "numpy",
    "pythia-client>=0.6.3",
]
requires-python = ">=3.12"

[tool.uv.sources]
pythia-client = { workspace = true }

[tool.uv.workspace]
members = [
    "../pythia-client"
]
```

In UV 0.3.5 this worked for me:
```docker
COPY --from=ghcr.io/astral-sh/uv:0.3.5 /uv /bin/uv
ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_CACHE=1
ENV PATH="/code/.venv/bin:$PATH"
# Install dependencies
WORKDIR /code
COPY pyproject.toml /code/
RUN uv sync --no-install-project --no-sources
```

`docker build .`
Output: `[+] Building FINISHED `

In UV 0.4.13 it doesn't work anymore:
```docker
COPY --from=ghcr.io/astral-sh/uv:0.4.13 /uv /bin/uv
ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_CACHE=1
ENV PATH="/code/.venv/bin:$PATH"
# Install dependencies
WORKDIR /code
COPY pyproject.toml /code/
RUN uv sync --no-install-project --no-sources
```
Output:
```docker
 => ERROR [stage-0 6/8] RUN uv sync --no-install-project --no-sources                                                                                                                                                                              0.7s 
------
 > [stage-0 6/8] RUN uv sync --no-install-project --no-sources:
0.613 Using Python 3.12.6 interpreter at: /usr/local/bin/python3
0.613 Creating virtual environment at: .venv
0.620 error: Failed to build: `pythia-streamlit @ file:///code`
0.620   Caused by: Failed to parse entry for: `pythia-client`
0.620   Caused by: Package is not included as workspace package in `tool.uv.workspace`
------
Dockerfile:18
--------------------
  16 |     WORKDIR /code
  17 |     COPY pyproject.toml /code/
  18 | >>> RUN uv sync --no-install-project --no-sources
  19 |
  20 |     COPY src/pythia_streamlit /code/pythia_streamlit
--------------------
ERROR: failed to solve: process "/bin/sh -c uv sync --no-install-project --no-sources" did not complete successfully: exit code: 2
```

My setup is a workspace with 3 parts: two app (`pythia-streamlit`, `pythia-api`) and a python package (`pythia-client`). The Dockerfile snippet is coming from production image where I want to install `pythia-client` from Pypi. In local developement environnement I remove the `--no-sources` to install from local folder (from parent directory).

The update from 0.4 broke by CI/CD pipeline, because the image would not build anymore due to the error above.
Any idea why ?
