### ISSUE TITLE
Feature Request - vu publish recognizes .pypirc file

### ISSUE THREAD

**Issue by geozeke** [astral-sh/uv#7676]
Thanks soooooooo much for the work on this amazing tool! I'm in the process of migrating the toolchain for all my Python projects to uv & ruff!

The recently-released `publish` command is a really welcome addition. When I run it, it's listed as "experimental", so I'm hoping there's still an opportunity for input on the feature. Definitely not an urgent feature need, but It would be great if `publish` recognized the `.pypirc` toml file, as specified in the [Python Packaging User Guide](https://packaging.python.org/en/latest/specifications/pypirc/). Namely:

```toml
[distutils]
index-servers =
    pypi
    testpypi
    private-repository

[pypi]
username = __token__
password = <PyPI token>

[testpypi]
username = __token__
password = <TestPyPI token>

[private-repository]
repository = <private-repository URL>
username = <private-repository username>
password = <private-repository password>
```

This would be like `twine`, but maybe add a new `-r, --repository` option that takes the shorthand name from the index servers listed in `.pypirc`. In that case, with a properly-configured `.pypirc` file like the one above in the user's home directory, publishing would be handled something like this:

To publish to `pypi` (the default), enter:

```shell
uv publish
```

To publish to `test.pypi`, enter:

```shell
uv publish -r testpypi
```

Private repos/others look like this:

```shell
uv publish -r private-repository
```
