### ISSUE TITLE
`uv init` should autofill the `authors` field in pyproject.toml

### ISSUE THREAD

**Issue by Ravencentric** [astral-sh/uv#7718]
## Feature Request

`poetry init` autofills the `authors` field:
```shell
❯ cat .\pyproject.toml
[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Ravencentric <my@example.email>"]
```
I find this quite helpful. This is usually boiler-plate that I'll have to fill anyway and not something that frequently changes so I doubt this will be controversial either. Would love to see this in `uv init`.

## Wish
I would also like it if `uv init` would autofill [license](https://peps.python.org/pep-0639/#project-source-metadata) field. [MIT](https://choosealicense.com/licenses/mit/) seems to be the [popular option as of 2018](https://snyk.io/blog/over-10-of-python-packages-on-pypi-are-distributed-without-any-license/). This might be harder to get a consensus on so I don't mind if this gets rejected. This can also be tied to a specific mode, like say `--package` and `--lib` but not with `--app` since the former two are supposed to be published and the latter isn't. Prior art example for this would be `hatch` which upon `hatch new` creates this:
```toml
[project]
name = "hello"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Ravencentric", email = "my@example.email" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []
```
along with the `license.txt`
```shell
hello
├── src
│   └── hello
│       ├── __about__.py
│       └── __init__.py
├── tests
│   └── __init__.py
├── LICENSE.txt
├── README.md
└── pyproject.toml
```

**Comment by charliermarsh** [comment]
How would we determine the `authors` in this case?

**Comment by Ravencentric** [comment]
So I just checked poetry, pdm, and hatch. Both poetry and hatch pull the author from `git`. pdm is an exception here since pdm's init interactively asks the user for author instead.

## Case 1: No git on the system OR unconfigured git

You can check that git (if installed) doesn't have a configured author by running:
```shell
$ git config user.name # no output
$ git config user.email # no output
```

Both hatch and poetry use a placeholder in this case:

- poetry
    ```
    $ poetry new --src hello-poetry && cat hello-poetry/pyproject.toml
    ```
    ```toml
    [tool.poetry]
    name = "hello-poetry"
    version = "0.1.0"
    description = ""
    authors = ["Your Name <you@example.com>"]
    readme = "README.md"
    packages = [{include = "hello_poetry", from = "src"}]

    [tool.poetry.dependencies]
    python = "^3.12"


    [build-system]
    requires = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"
    ```

- hatch
    ```shell
    $ hatch new hello-hatch && cat hello-hatch/pyproject.toml
    ```

    ```toml
    [build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

    [project]
    name = "hello-hatch"
    dynamic = ["version"]
    description = ''
    readme = "README.md"
    requires-python = ">=3.8"
    license = "MIT"
    keywords = []
    authors = [
    { name = "U.N. Owen", email = "void@some.where" },
    ]
    classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    ]
    dependencies = []
    ```

## Case 2: Configured git exists on the system

Configure git:
```
$ git config --global user.name "raven"
$ git config --global user.email "raven@email.com"
$ git config user.name
raven
$ git config user.email
raven@email.com
```
Now both poetry and hatch will pull the author field from the above git configuration:

- poetry

    ```shell
    $ poetry new --src hello-poetry && cat hello-poetry/pyproject.toml
    ```
    ```toml
    [tool.poetry]
    name = "hello-poetry"
    version = "0.1.0"
    description = ""
    authors = ["raven <raven@email.com>"]
    readme = "README.md"
    packages = [{include = "hello_poetry", from = "src"}]

    [tool.poetry.dependencies]
    python = "^3.12"


    [build-system]
    requires = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"
    ```
- hatch

    ```shell
    $ hatch new hello-hatch && cat hello-hatch/pyproject.toml
    ```
    ```toml
    [build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

    [project]
    name = "hello-hatch"
    dynamic = ["version"]
    description = ''
    readme = "README.md"
    requires-python = ">=3.8"
    license = "MIT"
    keywords = []
    authors = [
    { name = "raven", email = "raven@email.com" },
    ]
    classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    ]
    dependencies = []
    ```
