### ISSUE TITLE
Depedency with the same name as the project doesn't error

### ISSUE THREAD

**Issue by 2531** [astral-sh/uv#7731]
If you add a dependency with the same name as the project name, nothing happens. Although this may seem strange, project names are free!
The steps are as follows
```bash
uv init ruff
cd ruff
uv add ruff
```

**Comment by charliermarsh** [comment]
I guess we should have a dedicated error here? In some strange sense this is correct though... Projects do sometimes have circular dependencies.

```toml
[project]
name = "ruff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff",
]

[tool.uv.sources]
ruff = { workspace = true }
```
