### ISSUE TITLE
`uv sync` hangs forever if a git+https package requires authentication

### ISSUE THREAD

**Issue by command-tab** [astral-sh/uv#7774]
**Problem**

When running `uv sync` in a project containing a `pyproject.toml` that lists a package via git+https which requires authentication, the uv operation spins forever at "Resolving dependencies...".

When running with `uv --verbose sync`, I see an authentication prompt in the verbose output. It would be helpful if that prompt/non-OK HTTP status code was detected and either prompted about or at least errored about during a non-verbose `uv sync` rather than appearing to indicate that dependencies might resolve if you wait long enough.

**Workaround**

For a quick workaround, I expanded the read permissions of that git repo, since I control it as well.

**Example**

`pyproject.toml`
```toml
[project]
name = "myapp"
version = "1.0.0"
description = "My app"
readme = "README.md"
requires-python = ">=3.11"
# Awaiting resolution on this GitHub issue to be able to use a private pypi
# without specifying an extra index URL, which could be abused:
# https://github.com/astral-sh/uv/issues/171
dependencies = [
  "mypackagename @ git+https://git.example.com/mypackagename.git@1.2.3",
]
```

**Environment**

* macOS 15.0 Sequoia
* Python 3.11.3 (via uv)
* uv 0.4.15 (Homebrew 2024-09-21)
