### ISSUE TITLE
Workspace dependencies are not fully synced before run

### ISSUE THREAD

**Issue by mathialo** [astral-sh/uv#7838]
I'm currently testing out the workspace features of uv, and have come across something unexpected.

When running `uv run ...` in a workspace member, it will install any new packages from the member's dependencies into the venv, but it will not remove any dependencies left-over from other members. That can lead to an issue where two members needs a dependency, and it's only listed for one, but unless you manually run `uv sync` every time you move between them you will not notice.

I've set up a small project to illustrate, with two subpackages:

```
.
├── project-a
│   ├── hello.py
│   ├── pyproject.toml
│   └── README.md
├── project-b
│   ├── hello.py
│   ├── pyproject.toml
│   └── README.md
├── pyproject.toml
├── README.md
└── uv.lock
```

where `project-a` has a dependency on `pyhumps`:

``` toml
[project]
name = "project-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyhumps>=3.8.0"]
```

and `project-b` does not:

``` toml
[project]
name = "project-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
```

Both have a similar `hello.py` test script that uses `pyhumps`:
``` python
from humps import pascalize

def main():
    print(f"Hello from {pascalize('project-a')}!")

if __name__ == "__main__":
    main()
```

If I run `uv run hello.py` in `project-a` first, `uv run hello.py` will work in `project-b` after - until I manually run `uv sync` and then it stops working.

This same behavior is there for dev dependencies as well. Say if one member dev-depends on `pytest`, running `uv run pytest` anywhere else in the workspace works until manually synced.

This can of course be worked around by always running `uv sync`, but knowing myself I will forget to do that.
