### ISSUE TITLE
Docker build with workspace package

### ISSUE THREAD

**Issue by idinsmore1** [astral-sh/uv#7936]
Thanks for such an amazing tool in `uv`, it has been an awesome addition in my work as an analyst in academic research. I'm trying to build out a docker image of the workspace using the docker guide in the docs, but I'm running into the following error while trying to build the image. 

```bash
docker build . 
 > [stage-0 5/7] RUN --mount=type=cache,target=/root/.cache/uv     --mount=type=bind,source=uv.lock,target=uv.lock     --mount=type=bind,source=pyproject.toml,target=pyproject.toml     uv sync --frozen --no-install-project --no-install-workspace --compile-bytecode:
#10 5.139 Using CPython 3.11.10
#10 5.139 Creating virtual environment at: .venv
#10 8.494 error: Failed to prepare distributions
#10 8.494   Caused by: Failed to fetch wheel: dracopy==1.4.0
#10 8.494   Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
#10 8.494 --- stdout:
#10 8.494
#10 8.494 --- stderr:
#10 8.494 Traceback (most recent call last):
#10 8.494   File "<string>", line 14, in <module>
#10 8.494   File "/root/.cache/uv/builds-v0/.tmpVvUWy6/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
#10 8.494     return self._get_build_requires(config_settings, requirements=[])
#10 8.494            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#10 8.494   File "/root/.cache/uv/builds-v0/.tmpVvUWy6/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
#10 8.494     self.run_setup()
#10 8.494   File "/root/.cache/uv/builds-v0/.tmpVvUWy6/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
#10 8.494     super().run_setup(setup_script=setup_script)
#10 8.494   File "/root/.cache/uv/builds-v0/.tmpVvUWy6/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
#10 8.494     exec(code, locals())
#10 8.494   File "<string>", line 6, in <module>
#10 8.494 ModuleNotFoundError: No module named 'skbuild'
#10 8.494 ---
------
executor failed running [/bin/sh -c uv sync --frozen --no-install-project --no-install-workspace --compile-bytecode]: exit code: 2
```

My workspace looks like this:
```bash
├── Dockerfile
├── LICENSE
├── README.md
├── packages
│   ├── mircat-seg
│   │   ├── README.md
│   │   ├── pyproject.toml
│   │   └── src
│   │       └── mircat_seg
│   │           ├── __init__.py
│   │           ├── core.py
│   │           └── models
│   │               └── __init__.py
│   └── mircat-stats
│       ├── Dockerfile
│       ├── README.md
│       ├── pyproject.toml
│       └── src
│           └── mircat_stats
│               ├── __init__.py
│               ├── configs
│               │   ├── __init__.py
│               │   ├── logging.py
│               │   ├── models.py
│               │   └── statistics.py
│               ├── dicom
│               │   ├── __init__.py
│               │   └── dicom_folder.py
│               ├── models
│               │   ├── __init__.py
│               │   └── xgboost.json
│               └── statistics
│                   ├── __init__.py
│                   ├── aorta.py
│                   ├── body_and_tissues.py
│                   ├── centerline.py
│                   ├── contrast_detection.py
│                   ├── cpr.py
│                   ├── nifti.py
│                   ├── total.py
│                   └── utils.py
├── pyproject.toml
├── src
│   └── mircat
│       └── __init__.py
└── uv.lock
```
My root `pyproject.toml`:
```toml
[project]
name = "mircat"
version = "0.1.1"
description = "write description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "loguru>=0.7.2",
    "nibabel>=5.2.1",
    "numpy==1.26",
    "scipy==1.13.1",
    "threadpoolctl>=3.5.0",
    "mircat-seg",
    "mircat-stats",
    "scikit-build>=0.18.1",
]

[project.scripts]
mircat = "mircat:mircat"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
mircat-seg = { workspace = true }
mircat-stats = { workspace = true }

[tool.uv.workspace]
members = ["packages/mircat-seg", "packages/mircat-stats"]
```
and finally my Dockerfile
```dockerfile
FROM ubuntu:oracular

COPY --from=ghcr.io/astral-sh/uv:0.4.18 /uv /bin/uv

# Change the working directory to the `app` directory
RUN apt-get update && \
    apt-get install -y clang gcc g++ python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-install-workspace --compile-bytecode

# Copy the project into the image
ADD . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    && uv sync --frozen

ENTRYPOINT ["uv", "run", "mircat"]
```

Any ideas on a solution would be great. Thanks!
