### ISSUE TITLE
Configuring multiple indexes with `uv publish`

### ISSUE THREAD

**Issue by cthoyt** [astral-sh/uv#7963]
This issue is related to #7676.

I would like to switch from `twine` to `uv publish`, but in my workflow, I first upload to Test PyPI then later to vanilla PyPI. This means that I need to have configuration for the separate username and token for each index.

Currently, the only way that I saw to get the username and token into `uv publish` is by an environment variable or passing separately as flags [(ref Oct. 7th)](https://docs.astral.sh/uv/guides/publish/#publishing-your-package). This isn't so convenient to set and unset to different values during a single workflow, or require me to shuttle text through flags in a potentially messy/insecure way. Further, there are probably people who have private indexes they also want to quickly switch between vanilla PyPI, test PyPI, and their private indexes.

One solution from the PyPA was to keep track of different `index-servers` in the `.pypirc` file [(ref)](https://packaging.python.org/en/latest/specifications/pypirc/). There have been reservations about relying on text-based configurations, but currently as it is, it's not comfortable to switch to `uv publish` (even though I want to!)

**Comment by cthoyt** [comment]
The solution to https://github.com/astral-sh/uv/issues/8448 is awfully close to what’s needed here - it looks like there’s already a UV solution for specifying indexes now, so it would just require having some more dynamic env var names for the publish credentials in the same way as the index credentials

**Comment by konstin** [comment]
Can you use:

```yaml
      - name: Publish to Test PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          uv publish --publish-url https://test.pypi.org/legacy/
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish --publish-url https://test.pypi.org/legacy/
```

or could you use keyring authentication, where credentials are tagged by URL?

**Comment by cthoyt** [comment]
hi @konstin, thanks for checking in on this. If I were using something like GitHub Actions for publishing, then this is a great solution, so thanks for writing that up. Typo note for the second publish-url (shouldn't have `test.pypi`, should just be `pypi`)

Unfortunately, I am not publishing from the GitHub actions workflow, but rather from my local machine. I get that there's a push against people doing it, but that's my workflow. I'm using twine in a tox configuration like this (abbreviated):

```ini
[testenv:release]
skip_install = true
passenv =
    HOME
    TWINE_USERNAME
    TWINE_PASSWORD
deps =
    twine >= 1.5.0
    uv
commands =
    uv build --sdist --wheel --no-build-isolation
    twine upload --skip-existing dist/*
```

And I have a second environment that's basically the same but passes the `--repository testpypi` flag to twine:

```ini
[testenv:release]
skip_install = true
passenv =
    HOME
    TWINE_USERNAME
    TWINE_PASSWORD
deps =
    twine >= 1.5.0
    uv
commands =
    uv build --sdist --wheel --no-build-isolation
    twine upload --skip-existing --repository testpypi dist/*
```

If your perceptive is, uv shouldn't support this local workflow then I also understand. I think it would be a bummer though if I had to do some hacky things to get the credentials out of my `.pypirc` file to get it into the right environment variables for uv, though

Please let me know if there's more information you'd like from my side

**Comment by cthoyt** [comment]
This might be a wild idea to throw out there, but I was reading up on https://docs.astral.sh/uv/configuration/indexes/, which for now is for installing packages from certain indexes, but ultimately this is a way of defining a specific name and URL for an upload URL. Maybe this is a place there the publish URL could also be stored, then you could have in your pyproject.toml:

```toml
[[tool.uv.index]]
# Optional name for the index.
name = "testpypi"
# Required URL for the index.
url = "https://test.pypi.org/"
# Optional URL for uploading to the index
publish_url = "https://test.pypi.org/legacy/"
```

then, uv could get tricky and say, let's look for an environment variable like `UV_PUBLISH_<index.name>_TOKEN` which in this case would be `UV_PUBLISH_TESTPYPI_TOKEN`.
