### ISSUE TITLE
URL dependency of a dependency failing to resolve

### ISSUE THREAD

**Issue by ringohoffman** [astral-sh/uv#7996]
```console
$ uv --version
uv 0.4.19
```

Related:

* https://github.com/astral-sh/uv/issues/1932#issuecomment-2155660516
* https://github.com/astral-sh/uv/issues/4152

I have a package published to AWS Code Artifact that has a `pyproject.toml` that looks something like this:

```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
]

# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/
[project]
name = "my_package"
dynamic = ["version"]
dependencies = [
    "transformers[torch] @ git+https://github.com/huggingface/transformers@1f33023cfa998c237372baff36b166c014f33405#egg=transformers",
]
```

When I try to install it, I get the same error as in the 2 linked issues:

```
error: Package `transformers` attempted to resolve via URL: git+https://github.com/huggingface/transformers@1f33023cfa998c237372baff36b166c014f33405#egg=transformers. URL dependencies must be expressed as direct requirements or constraints. Consider adding `transformers @ git+https://github.com/huggingface/transformers@1f33023cfa998c237372baff36b166c014f33405#egg=transformers` to your dependencies or constraints file.
```

`pip` is able to install it though.

I would try to publish a package like this to PyPI as a MRE, but I think PyPI specifically forbids publishing packages with direct links.

So, similar to the recursive dependency in #4152, is there another case not being considered here? As in when the link is coming from the package you are trying to install.
