### ISSUE TITLE
Provide `uv sync --all-dev` for workspace projects

### ISSUE THREAD

**Issue by Wurstnase** [astral-sh/uv#8002]
I would like to install all dev dependencies in the workspaces.

Maybe you have the following structure:

```
.
├── pyproject.toml
├── uv.lock
├── cdk
│  ├── pyproject.toml
│  ├── src
│  │  └── cdk
│  │     └── __init__.py
└── sources
   ├── pyproject.toml
   ├── README.md
   └── src
      ├── service_a
      │  └── __init__.py
      └── service_b
         └── __init__.py
```

In each pyproject.toml are different `dev-dependencies`.

Currently I can install only the `dev-dependencies` once each project. E.g.

```
uv sync  # installs dev from root only
uv sync --project cdk  # installs dev from cdk only
uv sync --project sources  # installs dev from sources only
```

I can work around this issue with
```
uv sync && uv sync --project cdk --inexact && uv sync --project sources --inexact
```

But a more handy version would be very nice. Something like
```
uv sync --all-dev
```

**Comment by Wurstnase** [comment]
It seems to work as long as there is not `[project]` section in the pyproject.toml.

<details>

<summary>This did not install nested dev dependencies.</summary>

```toml
[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.12"

[tool.uv.workspace]
members = ["cdk", "sources"]

[tool.uv.sources]
sources = { workspace = true }
cdk = { workspace = true }
```

</details>

<details>

<summary>This would install nested dev dependencies.</summary>

```toml
[tool.uv.workspace]
members = ["cdk", "sources"]

[tool.uv.sources]
sources = { workspace = true }
cdk = { workspace = true }
```

</details>
