### ISSUE TITLE
`--frozen` will change behaviour of `--only-dev`

### ISSUE THREAD

**Issue by Wurstnase** [astral-sh/uv#8022]
Recursive dev dependencies are removed when `--frozen` is set.

My project:
```
.
├── mylib
│  ├── pyproject.toml
│  ├── README.md
│  └── src
│     └── mylib
│        ├── __init__.py
│        └── py.typed
├── pyproject.toml
├── README.md
└── uv.lock
```

<details>

<summary>./pyproject.toml</summary>

```toml
[tool.uv.workspace]
members = ["mylib"]
```
</details>

<details>

<summary>mylib/pyproject.toml</summary>

```toml
[project]
name = "mylib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
```
</details>

sync without `--frozen`
```
> uv sync --only-dev
Resolved 6 packages in 0.47ms
Installed 4 packages in 9ms
 + iniconfig==2.0.0
 + packaging==24.1
 + pluggy==1.5.0
 + pytest==8.3.3
```

sync with `--frozen`
```
> uv sync --only-dev --frozen
Uninstalled 4 packages in 34ms
 - iniconfig==2.0.0
 - packaging==24.1
 - pluggy==1.5.0
 - pytest==8.3.3
```
