### ISSUE TITLE
add `[tool.pyright]` section when `uv init`

### ISSUE THREAD

**Issue by sparrowsl** [astral-sh/uv#8040]
can we add this block when we do `uv init` 
```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```
- It helps avoid creating a pyrightconfig file for small _(or all)_ projects
- Helps avoid always adding it manually or creating the pyrightconfig file to add extra config.
