### ISSUE TITLE
uv sync: support `--system` to not install dependencies into venv

### ISSUE THREAD

**Issue by jgehrcke** [astral-sh/uv#8085]
`uv sync` is documented with

> If the project virtual environment (.venv) does not exist, it will be created.

That's great behavior, most of the times.

I want to use `uv sync` to install dependencies in CI. So I wondered: how can I install into "system python" directly? And so I discovered the lovely discussion in https://github.com/astral-sh/uv/issues/1526 and was super happy to read

> Calling this complete! `--system` exists.

Then I found that this flag does not exist for `uv sync`. 

I have the following pretty common use case in mind for github actions:

```yaml
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: install uv
      uses: astral-sh/setup-uv@v3
    - name: uv-install dependencies
      shell: bash
      # Install all dependencies as defined in uv.lock.
      # Straight into current/"system" python, which at this point
      # is the Python installed via actions/setup-python.
      run: uv sync --system
```

What do we think?

I think that https://github.com/astral-sh/uv/issues/7659 might have a similar motivation.
