### ISSUE TITLE
uv refuses to resolve deps with dynamic SCM version, missing tags and cylic dependencies `A:dev -> B`, `B -> A`, hinting at name shadowing

### ISSUE THREAD

**Issue by pawamoy** [astral-sh/uv#8148]
It happens in several of my projects now. Proper issue as a follow-up of #7329.

Example:

- CI job on tag 0.26.2: https://github.com/mkdocstrings/mkdocstrings/actions/runs/11307283146/job/31448849897 ("Install dependencies" step OK
- CI job on same commit (triggered via regular push): https://github.com/mkdocstrings/mkdocstrings/actions/runs/11307282883/job/31448849515 -> **"Install dependencies" step fails**

```
Using CPython 3.10.15 interpreter at: /opt/hostedtoolcache/Python/3.10.15/x64/bin/python
Creating virtual environment at: .venv
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of mkdocstrings-python-legacy are
      available:
          mkdocstrings-python-legacy<=0.2.1
          mkdocstrings-python-legacy==0.2.2
          mkdocstrings-python-legacy==0.2.3
          mkdocstrings-python-legacy==0.2.4
      and mkdocstrings-python-legacy>=0.2.1,<=0.2.2 depends on your project,
      we can conclude that mkdocstrings-python-legacy>=0.2.1,<0.2.3 depends on
      your project.
      And because mkdocstrings-python-legacy>=0.2.3 depends on your project,
      we can conclude that mkdocstrings-python-legacy>=0.2.1 depends on your
      project.
      And because mkdocstrings[python-legacy] depends on
      mkdocstrings-python-legacy>=0.2.1 and your project requires
      mkdocstrings[python-legacy], we can conclude that your projects's
      requirements are unsatisfiable.

      hint: The package `mkdocstrings-python-legacy` depends on the package
      `mkdocstrings` but the name is shadowed by your project. Consider
      changing the name of the project.
```

Here uv claims that since `mkdocstrings-python-legacy` depends on `mkdocstrings`, and my project is named `mkdocstrings`, it cannot resolve deps. My project *is* `mkdocstrings`, it's not shadowing it :sweat_smile:

In this case, `mkdocstrings` depends on `mkdocstrings-python-legacy` as an extra (optional dependency).

```toml
[project.optional-dependencies]
python-legacy = ["mkdocstrings-python-legacy>=0.2.1"]
```

But I get the same error when project `A` depends on `B` as a *development* dependency.

I'm not sure if the non-editable mode is the issue here, as I cannot reproduce this behavior locally.

**Comment by pawamoy** [comment]
Here are more verbose logs: https://github.com/mkdocstrings/griffe/actions/runs/11307459194/job/31449208076.

**Comment by pawamoy** [comment]
Ah, maybe it's because my `version` is dynamic, and since the project is shallow (tags not fetched), my build backend (pdm-backend) ends computing the version as `0.1`, which is clearly inferior to what the dev/extra-dependency requires.

**Comment by pawamoy** [comment]
Wait, no, I actually fetch all tags in this job :weary: Lemme try again with different options on the checkout action.

**Comment by pawamoy** [comment]
OK so my previous technique for fetching tag was probably not working well:

```yaml
    - name: Fetch all tags
      run: git fetch --depth=1 --tags
```

I replaced it with:

```yaml
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
```

...and now it works :hot_face:

**Comment by charliermarsh** [comment]
Thank you for following up 🙏 

Is there a bug in the error message hint then? Or is this resolved?

**Comment by pawamoy** [comment]
I wouldn't call it a bug, I would say it is confusing. Seeing this error message didn't help me understand what was going on, and the "name shadowing" hint is... incorrect? As mentioned above, I'm not shadowing a dependency name, the project and the dependency are the *same project*.

So my recommendation, if this is actually what's happening, and if it's possible, is to update the error message by showing that the computed project A version (current project, built for a non-editable install), and the version of project A required by a (dev-)dependency are not compatible.

My second suggestion above is to not even check compatibility between the current project version and the version required by dependencies, and install the current project anyway, always, maybe just showing a warning:

> Your project depends on X@1.2.3, which depends on your project>=7.8.9, but your project is currently in v4.5.6, which is incompatible. uv will install your project anyway, but things might break.

Let me know if anything is unclear :relaxed:

**Comment by pawamoy** [comment]
One argument in favor of allowing the current project version to be imcompatible with the version required by a dependency is that when forking a repository on GitHub, tags are not copied over. Then when triggering CI on your fork, the checkout action can't fetch tags since they don't exist, and uv fails to resolve. To fix this, authors of the fork have to explicitly fetch tags from upstream and push them back into their fork.

**Comment by pawamoy** [comment]
I have updated the title, and built a reproduction.

```bash
git clone git@github.com:pawamoy/repro-uv-8148-a
cd repro-uv-8148-a
uv sync  # works fine

# Now we clone a fork of the same project,
# meaning we don't have the Git tags.
cd ..
git clone git@github.com:pawamoy-forks/repro-uv-8148-a repro-uv-8148-a-fork
cd repro-uv-8148-a-fork
uv sync  # fails with the following output
```

```console
% uv sync
Using CPython 3.12.7 interpreter at: /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.12.7/bin/python
Creating virtual environment at: .venv
  × No solution found when resolving dependencies:
  ╰─▶ Because only repro-uv-8148-b==0.1.1 is available and repro-uv-8148-b==0.1.1 depends on your project, we can conclude that all versions of repro-uv-8148-b depend on
      your project.
      And because repro-uv-8148-a:dev depends on repro-uv-8148-b and your project depends on repro-uv-8148-a:dev, we can conclude that your project's requirements are
      unsatisfiable.

      hint: The package `repro-uv-8148-b` depends on the package `repro-uv-8148-a` but the name is shadowed by your project. Consider changing the name of the project.
```

**Comment by pawamoy** [comment]
I thought about and tried using dependency overrides, but it looks like it makes uv actually install the current project as a dependency, i.e. not as editable.

```toml
[tool.uv]
override-dependencies = ["mkdocstrings>=0"]
```

I also tried configuring a source for `mkdocstrings` (which, again, is the current project) like so:

```toml
[tool.uv.sources]
mkdocstrings = { workspace = true }
```

...and:

```toml
[tool.uv.sources]
mkdocstrings = { path = ".", editable = true }
```

...but it is still not installed as editable. The dependency override seems to take precedence.

**Comment by pawamoy** [comment]
Haha, I then tried this:

```toml
[tool.uv]
override-dependencies = ["mkdocstrings @ ."]
```

...which failed with this message:

```
warning: Failed to parse `pyproject.toml` during settings discovery:
  TOML parse error at line 88, column 25
     |
  88 | override-dependencies = ["mkdocstrings @ ./"]
     |                         ^^^^^^^^^^^^^^^^^^^^^
  relative path without a working directory: ./
  mkdocstrings @ ./
                 ^^

error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 88, column 25
   |
88 | override-dependencies = ["mkdocstrings @ ./"]
   |                         ^^^^^^^^^^^^^^^^^^^^^
relative path without a working directory: ./
mkdocstrings @ ./
```

And then tried this:

```toml
[tool.uv]
override-dependencies = ["mkdocstrings @ ${PWD}"]
```

...which worked :tada: but looks so weird haha

**Comment by pawamoy** [comment]
Hmm, uv already supports this env var, although it's undocumented (or at least searching for it in the docs doesn't yield anything).

What I'm not sure to understand is that it seems to be equivalent to PWD: if I enter a subdirectory and run `uv lock` from there, it says "can't build because subdirectory is not a Python project". Passing `--project ..` or `--project /abs/path/to/project` doesn't change anything. Is this because I'm not using workspaces/monorepos and there `PROJECT_ROOT` defaults to the CWD somehow?

**Comment by zanieb** [comment]
> Hmm, uv already supports this env var, although it's undocumented (or at least searching for it in the docs doesn't yield anything).

I think we need to support that to build projects that use Hatch.

**Comment by zanieb** [comment]
I guess what you're looking for here is for us to respect sources on top of overrides? I'm sort of surprised we don't, honestly.

**Comment by pawamoy** [comment]
`override-dependencies` works for me, I'm just looking for something more robust than `${PWD}` when specifying the path :slightly_smiling_face: `${PROJECT_ROOT}` is already great, even though I'm a bit confused by its behavior :smile: 

If you think there's some room for improvement in the way uv handles overrides and sources, I'm happy to help any way I can! Just to be clear, I'm only using overrides now, not declaring any source.

**Comment by pawamoy** [comment]
I prefer declaring this:

```toml
[tool.uv]
override-dependencies = ["mkdocstrings @ ${PROJECT_ROOT}"]
```

Than this:

```toml
[tool.uv]
override-dependencies = ["mkdocstrings>=0"]

[tool.uv.sources]
mkdocstrings = { workspace = true }
# or mkdocstrings = { path = "${PROJECT_ROOT}", editable = true }
```

...because even if the result is the same, it *feels* like the latter will completely disregard any constraints incompatibilities in dependencies regarding `mkdocstrings` (`>=0`), while the former will only "force" installation of the current project, while still checking that dependencies have compatible constraints about `mkdocstrings`. I don't think it's the case though, and both options completely ignore constraints regarding `mkdocstrings`. Even then, the first option is more appealing, as it requires less things to declare.

(I hope it's fine that I commented so much on this issue! Not trying to get your attention, just documenting my journey and thought process :smile:)

**Comment by pawamoy** [comment]
Ah, one more issue, with such an override, the `--no-editable` option in `uv sync` has no effect anymore :confused:

**Comment by zanieb** [comment]
@charliermarsh, wdyt about changing this interaction of sources and overrides?

**Comment by charliermarsh** [comment]
Yeah that makes sense... It seems like sources should apply to overrides and constraints too?

**Comment by charliermarsh** [comment]
In the latter two cases, did you have `repro-uv-8148-a` listed as a workspace member?

**Comment by pawamoy** [comment]
No I didn't, because I didn't think it made sense, since `repro-uv-8148-a` is the actual, main project. But if I add this anyway:

```toml
[tool.uv.workspace]
members = ["${PROJECT_ROOT}"]  # or members = ["."]
```

...I still get the "Package is not included as workspace package in `tool.uv.workspace`" error message.

**Comment by charliermarsh** [comment]
Oh thanks. What do I need to do exactly to reproduce the latter two cases? Clone `repro-uv-8148-a`, then what?

**Comment by charliermarsh** [comment]
So in this case, you're providing a source for the package itself? (Maybe I missed all the context above.)

**Comment by pawamoy** [comment]
Haha you probably missed the important bits in the wall of comments I have posted above 😄 

So, let say I'm working on project `a`. It dev-depends on `b`. And `b` depends back on `a`. Resolution conflicts can therefore happen since uv checks that `a`, the project I'm in, builds to a version that is compatible with `b` constraints.

The issue here is that my version is dynamic, and based on Git tags (pdm-backend deals with this). When there are no tags (fork, CI), pdm-backend computes version 0.1.devblabla, which is *incompatible* with what `b` requires.

Hence why I'm trying to tell uv to *ignore* constraints on the current project. The only current way to do this, is to use the configuration above:

```toml
[project]
name = "a"
dynamic = ["version"]  # dynamic version...

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
version = {source = "scm"}  # ...based on Git tags, through pdm-backend

[tool.uv]
override-dependencies = ["a"]  # tell uv to ignore constraints...

[tool.uv.sources]
a = { workspace = true }  # ...while still installing from current folder, in editable mode

[dependency-groups]
dev = [
     "b>=0.1",  # b depend on a>=1.0
 ]
```
