### ISSUE TITLE
how to specify build version with `uv build`?

### ISSUE THREAD

**Issue by struckchure** [astral-sh/uv#8162]
I'm building a Python package, and I need to add a release workflow, with a version tag too.

```yaml
name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build and publish
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
```

I basically need the equivalent of this, `poetry version $(git describe --tags --abbrev=0)`
