### ISSUE TITLE
uv tool install does not respect index-url from pyproject.toml

### ISSUE THREAD

**Issue by benjs** [astral-sh/uv#8164]
UV tool does not look into the pyproject.toml for already specified indices.

pyproject.toml:
```toml
[tool.uv]
index-url = "https://<my-index-url.com>/pypi/pypi/simple"
```

command:
```bash
uv tool install ruff
```

uv --version:
```
uv 0.4.18
```

Specifying the index url with `--index-url` worked, but is annoying :)
Thanks for this great tool!
