### ISSUE TITLE
Make UV_PYTHON_INSTALL_MIRROR configurable in pyproject.toml

### ISSUE THREAD

**Issue by benjs** [astral-sh/uv#8166]
It would be nice if we could specify all of our project's mirrors like index-url extra-index-url in a single place, for instance in the pyproject.toml.
Would it be possible to add an additional entry, for instance like this?

```
[tool.uv]
index-url = "https://<my-index-url.com>/pypi/pypi/simple"
extra-index-url = ["https://<my-index-url.com>/pypi/pypi-extra/simple"]
python-mirror-url = "https://<my-mirror-url.com>/indygreg/python-build-standalone/releases/download/"
```

uv version
```
uv 0.4.18
```

Thanks for all the great work.

**Comment by zanieb** [comment]
I'm not sure we want to mix project configuration with things that should be configured at the user and system level. Wouldn't it be surprising if your mirror wasn't respected outside the project and downloads failed or came from another source?

**Comment by benjs** [comment]
Thanks for the answer.

Yes, from the view of sharing code publicly to all kinds of people, I agree.
But when within a restricted network of a company, the mirror is always the same and has to be set additionally. It is much easier to specify it once in a configuration file instead of specifying it in every container, every laptop & every cloud code instance.

**Comment by aureliojargas** [comment]
Maybe this one can be closed as done?

I'm using uv 0.6.3 and this configuration in `pyproject.toml` works fine.

```toml
# Python mirror
[tool.uv]
python-install-mirror = "https://example.com/external-github-com/astral-sh/python-build-standalone/releases/download"

# PyPI mirror
[[tool.uv.index]]
url = "https://example.com/pypi/foo-pypi/simple/"
default = true
```
