### ISSUE TITLE
`requires-python` without `*` caused missing wheels in `uv.lock`

### ISSUE THREAD

**Issue by ringsaturn** [astral-sh/uv#8169]
- uv: 0.4.20
- platform: Apple M3 Max
- cmd: `uv lock`

With config:

```toml
[project]
name = "demo"
version = "0.1.0"
readme = "README.md"

dependencies = [
    "pymongo==4.10.0",
]

requires-python = "==3.12"
```

Output:

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/ccae5e68-9eee-4c74-a199-bdd7c974e812">

If use `requires-python = "==3.12.*"`, problem fixed.

Seems this came from https://github.com/astral-sh/uv/pull/7904
