### ISSUE TITLE
Feature request: Read dev dependencies from a packaging extra

### ISSUE THREAD

**Issue by czechnology** [astral-sh/uv#8170]
Hi, first of all, thanks for this great tool which has significantly changed how I develop and work with Python!

I would like to request **an extra configuration option to read the dev dependencies from a specific packaging extra** (i.e. a key under optional dependencies).

### Example

`uv` allows developers to configure [dev dependencies](https://docs.astral.sh/uv/reference/settings/#dev-dependencies) as part of the `uv.tool` table in pyproject.toml.
```toml
[tool.uv]
dev-dependencies = ["ruff==0.5.0"]
```

Many teams have been using an optional `dev` extra to specify the optional dependencies needed for development, testing etc.
```toml
[project.optional-dependencies]
dev = ["ruff==0.5.0"]
```

Using `tool.uv.dev-dependencies` limits the use of dev dependencies only to `uv`. It would be very helpful if we could alternatively tell `uv` to use a specific extra, something like this:
```toml
[tool.uv]
dev-dependencies.extra = "dev"
```

This would allow using dev dependencies also by other tools, such as pure `pip` (`pip install .[dev]`) and additionally help us migrate to `uv` more seamlessly.

Thanks!

---

(Side note on the suggested `pyproject.toml` notation: It reminds me of how [`setuptools` configures packages](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html) -- either set the packages as list in `tool.setuptools.packages` or configure custom discovery settings using options such as `tool.setuptools.packages.find`.)
