### ISSUE TITLE
UV_EXTRA_INDEX_URL not taking precedence over persistent configuration (pyproject.toml)

### ISSUE THREAD

**Issue by AndreuCodina** [astral-sh/uv#8248]
The documentation (https://docs.astral.sh/uv/configuration/files/) says: "Settings provided via environment variables take precedence over persistent configuration, and settings provided via the command line take precedence over both".

I use a private registry (Azure DevOps), and to develop locally, pyproject.toml uses keyring authentication:

```toml
[tool.uv]
keyring-provider = "subprocess"
extra-index-url = [
    "https://VssSessionToken@pkgs.dev.azure.com/mycompany/_packaging/MyFeed/pypi/simple/",
]
```

But when I create a Dockerfile and disable that configuration with environment variables to use the token, then it can't get the package from the private registry:

```
FROM python:3.12-slim-bookworm

ARG UV_COMPILE_BYTECODE=1
ARG UV_KEYRING_PROVIDER=disabled
ARG UV_EXTRA_INDEX_URL

ENV UV_NO_CACHE=1

COPY --from=ghcr.io/astral-sh/uv:0.4.22 /uv /bin/uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

CMD ["uv", "run", "--frozen", "--no-dev", "poe", "start"]
```

```bash
docker build \
    --tag my-image:1.0.0 \
    --build-arg UV_EXTRA_INDEX_URL=https://token@pkgs.dev.azure.com/mycompany/_packaging/MyFeed/pypi/simple/ \
    .
```

Error: `Caused by: Failed to fetch wheel: my-private-package`

**But** if I remove `extra-index-url` from pyproject.toml and build the Dockerfile, then it can get the package. In fact, it works even if I don't remove `keyring-provider`.
