### ISSUE TITLE
[Request] Allow defining named indexes in the user-level configuration file

### ISSUE THREAD

**Issue by jonasdeyson** [astral-sh/uv#8299]
It would be nice to be able to define named private indexes in the user-level configuration file), and use them in a project.

Ex:

In the user-level config file (`~/.config/uv/uv.toml`):

```toml
[[index]] 
name = "myindex" 
url = "<myindex url>" 
explicit = true
```

In a project's `pyproject.toml` file:

```toml
[tool.uv.sources]
mypackage = { index = "myindex" }
```

Currently, if I try this it gives the error:

```text
error: Failed to generate package metadata for `proj==0.1.0 @ virtual+.`
  Caused by: Failed to parse entry for: `mypackage`
  Caused by: Package `mypackage` references an undeclared index: `myindex`
```

**Comment by charliermarsh** [comment]
I can understand why it would be helpful, but just a note that this was an intentional decision in the implementation -- we didn't want to allow references to global indexes that don't exist within the project and so may not exist on other machines.

**Comment by lucas-labs** [comment]
We're facing a similar situation. We use an internal gitea repository + package index for some of our internal libraries.

If we want to use keyring for credentials, we still need set the username in the url.
Each developer has their own username and password, so we can't commit the `pyproject.toml` like this:

```toml
# pyproject.toml

[tool.uv.sources]
lib1 = { index = "private-repo" }

[[index]]
name = "private-repo"
url = "http://my.own.username@host/api/packages/org/pypi/simple/"
explicit = true
```

We ended up creating a shared user with read privileges, but that's suboptimal imo. 

Is there a workaround we haven't think of?

Cheers!
