### ISSUE TITLE
Authentication error to Google Artifactory with custom index and env variables

### ISSUE THREAD

**Issue by harteros** [astral-sh/uv#8324]
Hi team, thanks for all your hard work, uv is amazing!

We are currently trying to migrate to uv from poetry. We awaited the update to uv version 0.4.24 for the environmental variables and custom indexes but we have issues with the authentication to our private Google Artifactory.

The problem is as follows:

We have setup uv with keyring for Google Artifactory as follows:

```shell
uv tool install keyring --with keyrings.google-artifactregistry-auth
```

We have our custom index defined as follows in our `pyproject.toml`

```toml
[tool.uv]
keyring-provider = "subprocess"

[[tool.uv.index]]
name = "internal"
url = "https://<internal url>/<internal artifacts>/pypi-virtual/simple"
explicit = true

[tool.uv.sources]
internal-utils = { index = "internal" }
```

We have also set our env variable ([discussed here for Google Artifactory auth](https://github.com/astral-sh/uv/blob/05ed4bc11d31c8ef19971812d5554d9158f8823d/CHANGELOG.md#0133))

```shell
UV_INDEX_INTERNAL_USERNAME=oauth2accesstoken
```
Running `uv sync --verbose` in this way returns 

```shell
DEBUG Skipping keyring lookup for https:///<internal url>/<internal artifacts>/pypi-virtual/simple/internal-utils/ with no username
...
DEBUG No compatible version found for: custom-project
  × No solution found when resolving dependencies:
╰─▶ Because only the following versions of ... are available:
       ...
      and your project depends on ... we can conclude that your project's requirements are unsatisfiable.
```

On the other hard when we change our `pyproject.toml` to include the username in the url uv successfully pulls the credentials from the artifactory and installs the dependencies

```toml
[tool.uv]
keyring-provider = "subprocess"

[[tool.uv.index]]
name = "internal"
url = "https://oauth2accesstoken@<internal url>/<internal artifacts>/pypi-virtual/simple"
explicit = true

[tool.uv.sources]
internal-utils = { index = "internal" }
```

From my tests it seems that the env variable is either not read or appended to the URL causing the artifactory to not work.
Could you please take a look at it, as it seems to me as a possible bug.

Thanks a lot!

uv version: `uv 0.4.24 (b9cd54913 2024-10-17)`
system platform `Apple Silicon macOS`
