### ISSUE TITLE
Docker build fails with cached dependencies for a workspace

### ISSUE THREAD

**Issue by suhaskarnik** [astral-sh/uv#8380]
I've a project with the following structure:

```
app
├── pkgs
│   └── backend
│       ├── pyproject.toml
│       └── src
│           └── backend
│               ├── __init__.py
├── pyproject.toml
├── src
│   └── ui
│       ├── hello.py
```

In `pyproject.toml` I have the following:
```toml
[project]
name = "app"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
"backend ==0.1.0"
]

[tool.uv.workspace]
members = ["pkgs/backend"]

[tool.uv.sources]
backend = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/ui"]

[project.scripts]
hello = "ui.hello:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

In `backend/pyproject.toml` I have:
```toml
[project]
name = "backend"
version = "0.1.0"

requires-python = ">=3.12"
dependencies = ["..."]

[tool.hatch.build.targets.wheel]
packages = ["src/backend"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

Finally, the `hello.py` is rather simple:
```python
from backend import hello

def main():
    print("Hello from uv-workspaces!")
    print(hello())    # backend.__init__.py has a hello() method that just returns "hello from backend"

if __name__ == "__main__":
    main()
```

As you can see, this is a minimal solution to understand how workspaces can be used to deploy an (eventually) more complex project with dependencies into a Docker container. 

Now `uv sync` and `uv run hello` work fine on my machine - it prints two hello messages.  But if I follow the Dockerfile [here](https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile), it fails with the error:

```
0.125   Caused by: Failed to parse entry for: `backend`
0.125   Caused by: Package is not included as workspace package in `tool.uv.workspace`
```

The problems seems to occur because the Dockerfile does _not_ copy the project source code before doing the sync. When I added a `--mount=type=bind,source=pkgs,target=pkgs` before the `uv-sync` command in the Dockerfile, it solved the problem, but this is obviously not a good idea because then I cannot cache the dependencies.
