### ISSUE TITLE
uv tree often has no output

### ISSUE THREAD

**Issue by dimbleby** [astral-sh/uv#8382]
sometimes `uv tree` will decline to say anything

```toml
[project]
name = "foo"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "aiohttp>=3.9.5",
]
```
```shell
$ uv tree   # NB looks good
Resolved 10 packages in 19ms
foo v0.1.0
└── aiohttp v3.10.10
    ├── aiohappyeyeballs v2.4.3
    ├── aiosignal v1.3.1
    │   └── frozenlist v1.4.1
    ├── attrs v24.2.0
    ├── frozenlist v1.4.1
    ├── multidict v6.1.0
    └── yarl v1.15.5
        ├── idna v3.10
        ├── multidict v6.1.0
        └── propcache v0.2.0

$ uv tree --package propcache  # NB no output
Resolved 10 packages in 1ms

$ uv tree --package propcache --invert  # NB apparently invert will tell me something
Resolved 10 packages in 1ms
propcache v0.2.0
└── yarl v1.15.5
    └── aiohttp v3.10.10
        └── foo v0.1.0

$ uv tree --package yarl  # NB nothing to say about yarl
Resolved 10 packages in 1ms

$ uv tree --package yarl --invert  # NB even when inverted
Resolved 10 packages in 1ms
```

is there some not-so-obvious logic to this that I am missing?
