### ISSUE TITLE
Recommended way to use keyring for private package index

### ISSUE THREAD

**Issue by timchap** [astral-sh/uv#8409]
I know that uv supports keyring in subprocess mode for authenticating to private package indices. However, because the keyring CLI is installed into a Python environment, this creates a bit of a chicken-and-egg problem. In particular, it seems to me that keyring would need to be installed into my system Python for this to work. This is additionally complicated by that fact that with uv python binaries don't get installed to the system path - this means that the installation of keyring into my system Python needs to be managed entirely outside of the uv workflow.

Is my interpretation of the current functionality correct? What is the recommended solution here? Perhaps there's a simple workaround that I'm missing.

**Comment by harteros** [comment]
Hey @timchap, you can install and use keyring with the `uv tool` CLI command. After that it is pretty straightforward to use your private indexes with the new custom indexes functionality and environmental variables that were recently added.

To give you an example this is how we setup and use our private package index with uv.

1. Setup uv with keyring for Google Artifactory (you can use whatever artifactory you have your private packages at):

```shell
uv tool install keyring --with keyrings.google-artifactregistry-auth
```

2. Define the private index and link the internal package to the specific index:

```toml
[tool.uv]
keyring-provider = "subprocess"

[[tool.uv.index]]
name = "internal"
url = "https://<internal url>/<internal artifacts>/pypi-virtual/simple"
explicit = true

[tool.uv.sources]
internal-utils = { index = "internal" }
```

3. Add the index username and password to your `.bashrc` or `.zshrc` to setup the username and password of your private index:

```shell
UV_INDEX_INTERNAL_USERNAME=<your private index username>
UV_INDEX_INTERNAL_PASSWORD=<your private index password>
``` 

After that you can just run `uv sync` and everything will run smoothly with uv syncing your packages from your private index

Note: You should probably use `uv version 0.4.25` which solved an issues with env vars and keyring authentication
