### ISSUE TITLE
Specify a commit instead of tag with `tool.uv.sources`

### ISSUE THREAD

**Issue by cthoyt** [astral-sh/uv#8490]
On https://docs.astral.sh/uv/concepts/dependencies/, it gives an option to specify a git repository with a tag, but not a specific commit. Is this possible?

e.g., I would like to do

```toml
[tool.uv.sources]
wonderwords = { git = "https://github.com/mrmaxguns/wonderwordsmodule", commit = "5dfa455554e7c225a59c865d706c4293ca2c132e" }
```

Because this package https://github.com/mrmaxguns/wonderwordsmodule has made a "release" but not made a tag nor a release to PyPI
