### ISSUE TITLE
regression in uv 0.4.25's TOML comment handling during uv add

### ISSUE THREAD

**Issue by RazerM** [astral-sh/uv#8496]
The below issue does not happen on uv 0.4.24.

```
❯ uv --version
uv 0.4.25 (97eb6ab4a 2024-10-21)
```

initial `pyproject.toml`:
```toml
[project]
name = "scratch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  # Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
]
```

run
```
uv add attrs click python-gitlab rich tomlkit yarl
```

after:
```toml
[project]
name = "scratch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."attrs",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."click",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."python-gitlab",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."rich",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi.
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."tomlkit",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","attrs",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","click",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","python-gitlab",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","rich",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",# magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","tomlkit",
  # magna euismod, commodo eros at, aliquam lacus. Nulla facilisi."yarl","yarl",
]
```

A more minimal example is

```toml
[project]
name = "scratch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  #A
]
```

```
uv add attrs click
```

```toml
[project]
name = "scratch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  #A#A#A
  #A#A
  #A"attrs",
  #A"click",
]
```
