### ISSUE TITLE
uv run support for `tool.uv.scripts`

### ISSUE THREAD

**Issue by domenicocinque** [astral-sh/uv#8519]
Hi! First of all thank you for your incredible work on `uv`. 

I believe it would be great to incorporate support for predefined scripts defined in the `pyproject.toml`, similar to how `rye` handles it ([reference](https://rye.astral.sh/guide/pyproject/#toolryescripts)).  

Example:

```toml
[tool.rye.scripts]
devserver = { cmd = "flask run --debug", env = { FLASK_APP = "./hello.py" } }
```

Is this feature planned?
