### ISSUE TITLE
`uv pip sync pyproject.toml` does not install all dependencies

### ISSUE THREAD

**Issue by MtkN1** [astral-sh/uv#8527]
`pyproject.toml` (just added `requests`):

```toml
[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]
```

reproduce command:

```sh-session
$ uv venv
$ uv pip sync pyproject.toml
Resolved 1 package in 2ms
Installed 1 package in 1ms
 + requests==2.32.3
$ uv pip freeze
requests==2.32.3
```

The dependencies required by the `requests` are not installed. In fact, there are dependencies such as `urllib3`.

```sh-session
$ echo requests | uv pip compile -
Resolved 5 packages in 79ms
# This file was autogenerated by uv via the following command:
#    uv pip compile -
certifi==2024.8.30
    # via requests
charset-normalizer==3.4.0
    # via requests
idna==3.10
    # via requests
requests==2.32.3
urllib3==2.2.3
    # via requests
```

Don't you think this is a bug?
