### ISSUE TITLE
`uv tool update --all` fails if a provided `extra-index-url` is not joinable 

### ISSUE THREAD

**Issue by frague59** [astral-sh/uv#8555]
Hi,

I've defined `extra-index-url` with a private repository, only accessible on my company local network or through a VPN.

`$ cat uv.toml` 

```toml
index-strategy = "unsafe-best-match"
allow-insecure-host = ["gitlab.example.com"]  # My company gitlab repository, with a self-signed cert
extra-index-url = [
    "https://pypi.org/simple",
    "http://gitlab.example.com/api/v4/projects/117/packages/pypi/simple/",
]
```
I've installed  a mix of 'public' tool (`ruff`, `pre-commit`, `ansible-core`...) and some custom scripts installed from this private repository.

When at home, without connecting the VPN,  if  I run : 

```sh
$ uv tool update --all
⠼ Resolving dependencies...                                                     Failed to upgrade `ansible-core`: Could not connect, are you offline?
...
```

The update fails for all packages, including the "public" ones.

When I activate the VPN connection, the update is applied. 

It would be nice too have a more specific message about the unreachable repository, or that the "public" ones to be updated without caring about the down VPN.

Thanks for this great tool !
