### ISSUE TITLE
Authentication reused in two named indexes from the same GitLab

### ISSUE THREAD

**Issue by hbeukers** [astral-sh/uv#8565]
First, thank you for making uv, we are very happy with it.

Currently, we have a problem with the use of named indexes. 
The behavior showed up in the docker `ghcr.io/astral-sh/uv:0.4.26-python3.11-bookworm-slim` on GitLab for running the pipelines.

Our company has a GitLab with two different indexes from which we download packages.

Our project looks something like this:
```toml
[project]
name = "mypackage"
dependencies = [
    "firstpackage>=1.0.0",
    "secondpackage>=1.0.0",
]
requires-python = ">=3.11"

[tool.uv.sources]
firstpackage = { index = "firstindex" }
secondpackage = { index = "secondindex" }

[[tool.uv.index]]
name = "firstindex"
url = "https://gitlab.mycompany.com/api/v4/projects/2177/packages/pypi/simple"
explicit = true

[[tool.uv.index]]
name = "secondindex"
url = "https://gitlab.mycompany.com/api/v4/projects/6172/packages/pypi/simple"
explicit = true
```

Setting `UV_INDEX_FIRSTPACKAGE_PASSWORD` and `UV_INDEX_SECONDPACKAGE_PASSWORD` (and the usernames) gave the following error:

`Creating virtual environment at: .venv
error: Failed to download `secondpackage==1.0.0`
  Caused by: HTTP status client error (404 Not Found) for url (https://gitlab.company.com/api/v4/projects/6122/packages/pypi/files/d1f9d072c85428dc20d5813c9cecdcedd593284573474353487598f60d9804/secondpackage-1.0.0-py3-none-any.whl#sha256=d1f9d072c85428dc20d5813c4285782457837502540d4ac3b18033c8f60d9804)`

By playing around with the access tokens I found the following structure. We can make tokens specific for an index or general and valid for both.
The following token combinations give the following results
- first: specific, second: specific -> error
- first: general, second: specific -> works
- first: specific, second: general -> error
- first: general, second: general -> works
- first: general, second: no token set -> works

It also works if I remove firstpackage and just use a specific token for the secondpackage.

It seems that the authentication of the first index is also used for the second one. We can now solve it by using a token that is valid for both, but we would prefer to use tokens that are specific for each index. 

Is this something that is in line with how it was intended? 
Are there additional tests/outputs you would need to understand the behavior?
