### ISSUE TITLE
`uv sync` reports no solution found when `python_version>=` is used

### ISSUE THREAD

**Issue by njzjz** [astral-sh/uv#8601]
Minimal reproduced `pyproject.toml`:

```toml
[project]
name = "test-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    'jax>=0.4.33;python_version>="3.10"',
]
```

`uv sync`:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of jax{python_full_version >= '3.10'} are available:
          jax{python_full_version >= '3.10'}<=0.4.33
          jax{python_full_version >= '3.10'}==0.4.34
          jax{python_full_version >= '3.10'}==0.4.35
      and the requested Python version (>=3.9) does not satisfy Python>=3.10, we can conclude that
      jax{python_full_version >= '3.10'}>=0.4.33 is incompatible.
      And because your project depends on jax{python_full_version >= '3.10'}>=0.4.33, we can conclude that your
      project's requirements are unsatisfiable.
```

Here, I expect Python 3.9 to install nothing and Python 3.10 and above to install `jax>=0.4.33`. I don't understand uv's logic.

(In the actual project, jax is an optional dependency for extra features that are only available in Python 3.10)
