### ISSUE TITLE
specify minimum uv version in pyproject.toml

### ISSUE THREAD

**Issue by sebhoss** [astral-sh/uv#8605]
I recently noticed that the list of available python versions is hardcoded in uv and thus depends on the version of `uv` used. One of my colleagues was using an older version of `uv` and could not install python 3.13 without updating `uv` first. While updating `uv` is not a problem, I wish that there was a way to specify a minimum required version for `uv` itself when working on a project. I think this would improve developer experience because he would immediately have updated `uv` instead of debugging why the latest python version cannot be downloaded.

**Comment by nathanjmcdougall** [comment]
Just to summarize some of the thinking from the duplicates, more generally we are wanting to set _constraints_ on the version of `uv`, similar to how `project.requires-python` sets constraints on the version of Python.

Aside from a lower bound, I think the most useful constraint would be pinning/equality. I see limited value in upper bounds.

Pinning is useful in a CI pipeline to make sure breaking changes in `uv` don't break a deployment, etc. So for example, in the [setup-uv](https://github.com/astral-sh/setup-uv) GitHub Action (or other CI config), you can pin a version of `uv`. But then there can be inconsistencies between the developer's local `uv` version and the one used on CI (or different developer's local `uv` versions for that matter).

I personally had this situation recently in my organization with the release of v0.5.0 - a whole lot of pipelines failed. Pinning would have prevented this, which is what we're doing now. But now we need a hacky script which re-downloads a hard-coded version of `uv` per project - or some other workaround. If we could specify the version of `uv` in `pyproject.toml`, then this could be avoided.

A similar situation exists in regard to [pre-commit-uv](https://github.com/astral-sh/uv-pre-commit); you need to pin a version of `uv`. Actually, you're pinning the version of `pre-commit-uv` which is synchronized with `uv` itself. In any case, this introduces a similar issue where passing pre-commit depends on using the same version of `uv` as the one pinned in the pre-commit config. In addition, there is a similar issue to the one discussed at https://github.com/astral-sh/uv-pre-commit/issues/23, where the version of e.g. `ruff` needs to be synchronized between the virtual environment and the pre-commit config. In this case, the user's installed uv version can mismatch with the one used by pre-commit. This could potentially be solved by allowing the `pre-commit-uv` implementation to respect a pinned uv version in pyproject.toml.

**Comment by dmarcoux** [comment]
Regarding pinning uv's version, I have a workaround for this. Maybe in the meantime this can help others, so here's how I do it.

In my git repository, I track uv's version in the file `.uv-version`, like [this](https://github.com/dmarcoux/sports_tracker/blob/cf5288dc303df44536e840fe49b288d85e1dae6c/.uv-version). I generate this file when my development environment is started with this command `uv version | cut --delimiter=' ' --fields=2 > .uv-version`. So this file is updated whenever I update the `uv` package. It's less error-prone since I don't have to remember to update the file `.uv-version`.

As for continuous integration, this is how I pin uv's version with GitHub Actions:

```yml
(...)

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch uv's version from .uv-version
        id: uv-version
        run: echo "uv-version=$(cat .uv-version)" >> "$GITHUB_OUTPUT"

      - name: Install uv with the version in .uv-version
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ steps.uv-version.outputs.uv-version }}
          enable-cache: true

(...)
```

You can see the whole file [here](https://github.com/dmarcoux/sports_tracker/blob/cf5288dc303df44536e840fe49b288d85e1dae6c/.github/workflows/continuous_integration.yml).

Let me know if something isn't clear.
