### ISSUE TITLE
Pin package to pypi index?

### ISSUE THREAD

**Issue by TheWizier** [astral-sh/uv#8723]
Hey, I have encountered an issue where we have a package on our private package index that was published to pypi and further developed. So naturally UV refuses to install the newer version from pypi as it sees that we have an older version on our index. How can I pin the package to the pypi index?

Here is an example to perhaps make it more clear:
[project]
...
dependencies = [
    "some-pkg >= 1.2",
]

[tool.uv.sources]
some-pkg = { index = "our_index" }
problematic-pkg= { index = "pyPI" } # I want to pin this to pypi as it exists in both our_index and on pypi

[[tool.uv.index]]
name = "our_index"
url = "https://git..."

[tool.uv]
dev-dependencies = [
"problematic-pkg >= 1.4"
]

(uv 0.4.25 linux)

**Comment by charliermarsh** [comment]
I would suggest creating a named PyPI index, like:

```toml
[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
explicit = true

[tool.uv.sources]
some-pkg = { index = "our_index" }
problematic-pkg= { index = "pypi" }
```
