### ISSUE TITLE
When tool.uv.index.url contains a username, it can't be overridden in UV_INDEX

### ISSUE THREAD

**Issue by torarvid** [astral-sh/uv#8728]
Hello 👋🏻 

`uv 0.4.28`

We have an issue where our pyproject.toml has the equivalent of:

```toml
[project]
name = "foo"
version = "0.0.1"
description = "desc"
authors = [{ name = "Me", email = "me@example.com" }]
license = { text = "UNLICENSED" }
requires-python = ">=3.12.6, <3.13"
dependencies = [
    "priv_package==0.3.8",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.12.0,<1.13.0",
]
package = true

[tool.uv.sources]
priv_package = { index = "priv" }

[[tool.uv.index]]
name = "priv"
url = "https://oauth2accesstoken@europe-python.pkg.dev/foo/python/simple"
explicit = true
```
So a private package on GCP artifact registry and a public package (the public package might not matter for the bug).

By having the `oauth2accesstoken` as a username in the private package url, all human users in the company are able to export `UV_KEYRING_PROVIDER=subprocess` and use `keyring` (with `keyring-gcloud`) to hav `uv` fetch-and-refresh their gcloud access tokens automatically use it for authentication. Perfect so far 👍🏼

However, in Github we use [Renovate](https://www.mend.io/renovate/) to bump our dependencies, and for that to work, we have this in our renovate config:

```json5
{
  description: "Preset to fetch deps from Google Artifact Registry",
  hostRules: [
    {
      description: "Authenticate to GCP Artifact Registry",
      matchHost: "europe-python.pkg.dev",
      username: "_json_key_base64",
      password: "{{ secrets.OUR_ARTIFACT_REGISTRY_JSON_KEY }}",
    }
}
```

So Renovate needs a long-lived secret for authentication to be practical, but the company prefers that employees use a less-important secret (a google access token in our case).

This used to work with Renovate+uv a while ago, but it stopped working some time in the past 5–7 days. I'm not really sure how the public Renovate bot chooses the version of `uv` that they run, so I can't say on what version this started failing for us.

I can repro locally by ensuring the only `UV_<...>` env var is `UV_INDEX=https://_json_key_base64:$PASSWORD@europe-python.pkg.dev/foo/python/simple`, and then do `rm -rf .venv && uv sync --no-cache` (not sure if the `--no-cache` is needed). I can also work around the issue by changing `oauth2accesstoken` to `_json_key_base64` in pyproject.toml.

I'm not sure what I want the solution to be — not even sure this is a bug (maybe I can improve my configuration to avoid this being a problem?). But perhaps it could be an idea that if I have a url in pyproject.toml of the `https://alice@domain.tld` format and there is a `UV_INDEX=https://bob:pwd@domain.tld`, then the `bob` user should "step in" for `alice` since env vars usually are prioritized over config files (?)

Happy to hear your thoughts. Thanks for an otherwise excellent tool!
