### ISSUE TITLE
In resolver, allow source distributions with static metadata, but no `requires-python` compatibility

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#8767]
The following fails to resolve under `--python 3.11`, because `interpreters-pep-734` has no wheels, and it requires at least Python 3.13, ostensibly to get the metadata -- however, the package has static metadata in the `pyproject.toml`, so we should actually be able to resolve it without issue:

```toml
[project]
requires-python = ">=3.11"

[project.optional-dependencies]
sub = [
    "interpreters-pep-734>=0.4.1; python_version ~= '3.13'",
]
```
