### ISSUE TITLE
Allow conflicting dependency groups

### ISSUE THREAD

**Issue by ReinforcedKnowledge** [astral-sh/uv#8814]
I have noticed that `uv` doesn't the installation of a dependency group when there are conflicting dependency groups.

Example of a `pyproject.toml`:
```toml
[project]
name = "dep-groups"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[dependency-groups]
scikit = [
    "scikit-learn==1.3.2"
]
scikit-prev = [
    "scikit-learn==1.3.1"
]
```

`uv sync --group scikit` returns the error:
```
Creating virtual environment at: .venv
  × No solution found when resolving dependencies:
  ╰─▶ Because dep-groups:scikit depends on scikit-learn==1.3.2 and dep-groups:scikit-prev depends on
      scikit-learn==1.3.1, we can conclude that dep-groups:scikit and dep-groups:scikit-prev are incompatible.
      And because your project depends on dep-groups:scikit and dep-groups:scikit-prev, we can conclude that your
      project's requirements are unsatisfiable.
```

**PS**: 
I'm not opening this issue to say that `uv` should or should not. That's something that [PEP 735](https://peps.python.org/pep-0735/) left for the tools to implement their own strategy (see [lockfile generation](https://peps.python.org/pep-0735/#lockfile-generation)).
I'm opening it to provide a link to fix a typo, in my opinion, in the documentation here: https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups
The issue referred to in the note concerns optional dependencies and not dependency groups.
