### ISSUE TITLE
Library under development is not installed into virtual environment in CI

### ISSUE THREAD

**Issue by fleimgruber** [astral-sh/uv#8826]
Using a CI setup such as

```yaml
variables:
  UV_VERSION: 0.4
  PYTHON_VERSION: 3.9
  BASE_LAYER: bookworm-slim

image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER

...

doc:
  stage: build
  script:
    - uv sync
    - uv run sphinx-build -b html docs docs/_build/html
```

The `uv run sphinx-build -b html docs docs/_build/html` fails because uv does not install the library under development into the virtual environment in the `uv sync` step.

The uv.lock file shows

```lock
[[package]]
name = "libunderdev"
version = "2024.1"
source = { virtual = "." }
...
```

In local dev, `uv sync` installs the library into the virtual environment.

**Comment by zanieb** [comment]
I don't think it does install it locally if it's marked as "virtual".

What's your `pyproject.toml` look like?

Have you read the [build system documentation](https://docs.astral.sh/uv/concepts/projects/#build-systems)?

**Comment by fleimgruber** [comment]
Thanks for the quick response and pointers. Indeed I was looking at the wrong Terminal and thus pyproject.toml.

Having
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
in pyproject.toml works as expected. Sorry for the noise.
