### ISSUE TITLE
Support index declarations in uv publish

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#8864]
We want to support `uv publish --index example` with:

```toml
[[index]]
name = "example"
url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy"
```

This avoids setting the options on the CLI, moving them into configuration stored with the project instead.

It requires changing `uv publish` so that if `--index <name>` is given, we discover (and require) `pyproject.toml` to be present.

See also https://github.com/astral-sh/uv/pull/8531#issuecomment-2442698889

Todo list:
- [x] Add `publish-url` option to `[[index]]`
- [x] Add `--index` option, conflicting with `--publish-url` and `--check-url`.
- [x] When using `--index`, perform workspace discovery, find a matching index and use that
- [x] Update the docs
