### ISSUE TITLE
Prevent setting an index as both explicit and default

### ISSUE THREAD

**Issue by mkniewallner** [astral-sh/uv#8985]
Unless I'm missing a use case, it seems to me that `default = true` won't actually do anything when set on an index that also sets `explicit = true`.

Consider for instance:

```toml
[project]
name = "foo"
version = "0.0.1"
dependencies = ["mypy==1.13.0"]

[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org/simple"
explicit = true
default = true
```

`default = true` allows disabling default PyPi index, but in that specific case, it won't, which is expected, since the index is an explicit one, so `mypy` will correctly be resolved from public PyPi.

If there really is no use case for having both `explicit = true` and `default = true` for an index, should uv error out, to better convey that this is not a real use case?
