### ISSUE TITLE
Question: How to set the pip source used in uv?

### ISSUE THREAD

**Issue by slgxmh** [astral-sh/uv#9048]
For some network reason in China mainland, we usually set pip source with

```bash
pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
```

but, this config is not working in uv.  It has a slow network experience when I use `uv add ***`.

How to set source URL in uv?

**Comment by charliermarsh** [comment]
You can do `uv add *** --default-index https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple`

**Comment by charliermarsh** [comment]
Or you can set the following in your global `uv.toml`:

```toml
[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
```

See https://docs.astral.sh/uv/configuration/files/ for the location of the global `uv.toml`.
