### ISSUE TITLE
Docs lack info on setting up local tools

### ISSUE THREAD

**Issue by jbullion-astra** [astral-sh/uv#9071]
The docs have 3 pages that document "tools".

- https://docs.astral.sh/uv/concepts/tools/ 
- https://docs.astral.sh/uv/guides/tools/ 
- https://docs.astral.sh/uv/reference/cli/#uv-tool 

These docs don't proved examples of how to set up a project (or scripts in a project) as a tool. 

Documentation on how tool discovery would also be appreciated. 

My current pyproject.toml:
```toml
[project]
name = "mytool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
]

[project.scripts]
mytool = "mytool:main"
```

How do I run and install a local tool?

**Comment by zanieb** [comment]
I believe you're looking for `uv tool install -e .`. You'll need to configure a [build system](https://docs.astral.sh/uv/concepts/projects/#build-systems) too.

**Comment by MarkusGnigler** [comment]
```toml
[project]
name = 'test'
...

[project.scripts]
lint = 'pre-commit run --all-files'
```

Would it be possible to run only simple scripts without a build system like **pipenv/pdm/poetry** does with `pipenv/pdm/poetry run lint`?
