### ISSUE TITLE
(🐞) `uv add` duplicates comments in pyproject.toml

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/uv#9105]
```toml
[project]
name = "epic-based-project"
version = "1"
description = "an EPIC project that is based 😎"
requires-python = ">=3.13, <3.14"
dependencies = [
    # this is a comment
    "ruff>=0.7.3",
]
```
```
> uv add basedmypy  # we need basedmypy to be based
Resolved 6 packages in 0.01s
Prepared 1 package in 0.01s
Installed 1 package in 0.01s
 + basedmypy==2.7.0
```
```toml
[project]
name = "myhr"
version = "1"
description = "Automated testing for Queensland Health myHR"
requires-python = ">=3.13, <3.14"
dependencies = [
    # this is a comment
    "basedmypy>=2.7.0",
    # this is a comment
    "ruff>=0.7.3",
]
```
