### ISSUE TITLE
support dependency groups with different python versions

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/uv#9161]
my project supports python versions 3.8 to 3.13, but since some of my dev dependencies require python 3.9 or above, i need to split them into separate dependency groups:

```toml
[project]
requires-python = ">=3.8"

[dependency-groups]
dev = [
    # this version only supports 3.9 to 3.13
    "libcst>=1.5.0",
]
old = [
    # this version only supports 3.8 to 3.12
    "libcst==1.1.0",
]
```

in pdm this is doable by maintaining two separate lockfiles, and specifying `--python=">=3.9"` for the `dev` group:

```
pdm lock -G dev --python=">=3.9"
pdm lock -G old --lockfile pdm.old.lock
```

it would be nice if uv supported something similar. ideally two separate lockfiles wouldn't be needed though and the separate python versions could just be defined in `pyproject.toml` for each dependency group, maybe something like:

```toml
[tool.uv.dependency-group-python-versions]
dev = ">=3.9"
old = ">=3.8"
```

**Comment by charliermarsh** [comment]
I believe this works already:
```toml
[project]
name = "project"
requires-python = ">=3.8"

[dependency-groups]
dev = [
    # this version only supports 3.9 to 3.13
    "libcst>=1.5.0 ; python_version >= '3.9'",
]
old = [
    # this version only supports 3.8 to 3.12
    "libcst==1.1.0",
]

[tool.uv]
conflicts = [
    [
        { group = "dev" },
        { group = "old" },
    ],
]
```
