### ISSUE TITLE
maturin build system not always copying the compiled build into the .venv on uv build

### ISSUE THREAD

**Issue by zwing99** [astral-sh/uv#9177]
When using the maturin build system, I cannot seem to run `uv build` or `uv run maturin develop` or any set of commands that both compiles the library (rust based) and installs it to the local `.venv`. It works once, but then future builds do not copy the binary into the virtualenv. I am not sure if this is 100% UV's fault, but it seems worth reporting as I suspect many folks will be using pyo3, maturin, uv, and rust to build performant libraries going forward. Below is an example toml file.

my work around was to chain these commands:
`rm -fr .venv; uv clean; uv build; uv run ipython`
Note: the clean was very needed.

```toml
[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "factors-py"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "ipython>=8.12.3",
    "maturin>=1.7.4",
]
[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "pip>=24.3.1",
]
```
