### ISSUE TITLE
`uv lock` locks incorrect torch cpu version on macOS 

### ISSUE THREAD

**Issue by MKVatinyan** [astral-sh/uv#9209]
- uv version : uv 0.5.2 (195f4b634 2024-11-14)
- running on macOS 15.0.1, m1 chip, 2020

I am following a very simple workflow to test this situation : 
1. run `uv init torch-uv`
2. add `torch`, `torchaudio` to `pyproject.toml`

```toml
[project]
name = "torch-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4, <2.5"
]

[tool.uv.sources]
torch = { index = "torch-cpu"}

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

3. create `.venv` with `uv venv`
4. install project with `uv pip install .`. When i run `uv pip show torch` i get `Version: 2.4.1`. I can successfully `source .venv/bin/activate` and run `python`, import torch etc.
5. i run `uv lock`. Here is the problem, in the lock file i have 

```toml
[[package]]
name = "torch"
version = "2.4.1+cpu"
```

6. when i run `uv run python` i error with `error: Distribution `torch==2.4.1+cpu @ registry+https://download.pytorch.org/whl/cpu` can't be installed because it doesn't have a source distribution or wheel for the current platform`

If repeat the same process by having only "torchaudio>=2.4, <2.5" in my dependencies, torch will be downloaded but the lock file will be correct, without the `+cpu`. Am i missing something here ?

**Comment by charliermarsh** [comment]
Unfortunately this is correct. Torch doesn't publish `+cpu` wheels for macOS. They expect you to just use the `2.4.1` without `+cpu`. But if you resolve against the `https://download.pytorch.org/whl/cpu` index, then it's correct to choose the `+cpu` version. It's a duplicate of #5182.

**Comment by charliermarsh** [comment]
One option:

```
[project]
name = "torch-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4, <2.5"
]

[tool.uv.sources]
torch = { index = "torch-cpu", marker = "sys_platform != 'darwin'" }

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

**Comment by charliermarsh** [comment]
Another:
```toml
[project]
name = "torch-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch==2.4.1+cpu ; sys_platform != 'darwin'",
    "torch===2.4.1 ; sys_platform == 'darwin'"
]

[tool.uv.sources]
torch = { index = "torch-cpu" }

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

**Comment by charliermarsh** [comment]
A third:

```toml
[project]
name = "torch-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch==2.4.1",
    "torch!=2.4.1+cpu ; sys_platform == 'darwin'"
]

[tool.uv.sources]
torch = { index = "torch-cpu" }

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```
