### ISSUE TITLE
Development Dependency Overrides

### ISSUE THREAD

**Issue by iloveitaly** [astral-sh/uv#9258]
One of the things I've always missed from ruby is development dependency overrides. Here's the situation:

* You have a dependency in one of your projects that is published on pypi
* Something is broken in it. You clone it with hopes of fixing it locally before getting the patch merged upstream.
* You want to temporarily override the pypi reference to point to a path on your local filesystem _without_ modifying `pyproject.toml`

Ruby allows you to do this with:

```
bundle config set local.rack ~/Work/git/rack
```

It would be great if uv provided similar sort of functionality.

**Comment by charliermarsh** [comment]
I believe this is possible today with:

```toml
[tool.uv]
override-dependencies = ["dependency @ file:///path/to/dependency"]
```

**Comment by ReinforcedKnowledge** [comment]
I think you can also run code with the `--with` option of `uv run` command, or `--with-requirements` if you have many. That won't modify the `pyproject.toml` and the code will only run in an ephemeral virtual environment.

**Comment by iloveitaly** [comment]
This is awesome. Will try this out and report back. Thanks for all of the help.

**Comment by iloveitaly** [comment]
This does not work:

```
override-dependencies = ["activemodel @ file://./pypi/activemodel"]
```

And results in the following error:

```
relative path without a working directory: ./pypi/activemodel
```

But an absolute path does work. Am I missing some obvious configuration option here?

Also, it looks like the package is not installed as editable. What's the best way to do that?

**Comment by ReinforcedKnowledge** [comment]
Hi!

I will let the experts say why it didn't work because I don't know.

Relative paths with `override-dependencies` aren't working for me either, but I generally don't expect relative paths to work in that fashion, they're always a hassle no matter the tool. If you want to avoid hardcoding the path you can use `${PROJECT_ROOT}`, like 
```toml
[tool.uv]
override-dependencies = ["activemodel @ file:///${PROJECT_ROOT}/pypi/activemodel"]
```

As for the editable install, there is no current way for specifying editable installs in an `override-dependencies`. But at the same time, I don't think that's what you need here.

Here's how you can use your local package as editable:
```
[tool.uv.sources]
activemodel = { path = "./pypi/activemodel", editable = true }
```

Sources in `uv` will always take precedence over version contraints.

As for why `override-dependencies` are not what you need, I think, from my modest beginner understanding of the tool, it's something that you'd use to override versions of transitive dependencies, or to force a particular version constraint in a way that no matter the current or the future resolutions of `uv` (due to a change in `uv` itself or in your dependencies), that package's version is going to stay the same.

I hope someone more knowledgeable can read this and correct it if I'm wrong.

**Comment by zanieb** [comment]
There's discussion about this same problem over in https://github.com/astral-sh/uv/issues/8148#issuecomment-2496127365 that may provide some more context.

**Comment by ReinforcedKnowledge** [comment]
Oh thanks! I'll read through the thread!

**Comment by iloveitaly** [comment]
```
[tool.uv.sources]
activemodel = { path = "./pypi/activemodel", editable = true }
```

This works for local development, but doesn't solve my problem:

1. When developing locally, I want to use a local copy of the package
2. In production, I want to reference a production package
3. I don't want to have to keep a mutated copy of `pyproject.toml` locally to reference the local package

Ruby does this with:

```
bundle config set local.rack ~/Work/git/rack
```

Which does not involve mutating your Gemfile but enables you to easily debug a package with a local development override./

**Comment by zanieb** [comment]
We want to build a dedicated "patch" workflow, but we haven't designed that yet. Does using `uv run --with-editable` not work for you?

**Comment by charliermarsh** [comment]
You can run with `--no-sources` in production if you want to disable that local path.

**Comment by iloveitaly** [comment]
I wasn't aware of `uv run --with-editable` or `--no-sources`, let me try those out and report back.

**Comment by iloveitaly** [comment]
Can you specify either of these options with an ENV var?

I'm using [nixpacks](https://github.com/railwayapp/nixpacks) to build my containers and I'd rather not have to customize the install scripts and instead specify ENV configuration which uv can pick up.

**Comment by rpmcginty** [comment]
> We want to build a dedicated "patch" workflow, but we haven't designed that yet. Does using `uv run --with-editable` not work for you?

@zanieb is there an issue tracking this, or is it too early?

**Comment by zanieb** [comment]
It's sort of tracked in https://github.com/astral-sh/uv/issues/7454

I'm doing some roadmap work and will post here / there if I create a dedicated issue.

**Comment by Avasam** [comment]
I'd like to keep as much as possible compatible with `pip`, the following doesn't solve the problem I outlined in https://github.com/astral-sh/uv/issues/9683#issuecomment-2705480073

```toml
[dependency-groups]
dev = [
    "ts_utils @ file:lib", # pip compatible
]

[tool.uv]
override-dependencies = [
  "ts_utils @ file:${PROJECT_ROOT}/lib", # uv won't accept relative paths
]
```
```
  × Failed to build `typeshed @ file:///E:/Users/Avasam/Documents/Git/typeshed`
  ├─▶ Failed to parse entry in group `dev`: `ts_utils @ file:lib`
  ╰─▶ relative path without a working directory: lib
      ts_utils @ file:lib
```

**Comment by watsonjj** [comment]
> This works for local development, but doesn't solve my problem:
> 
> 1. When developing locally, I want to use a local copy of the package
> 2. In production, I want to reference a production package
> 3. I don't want to have to keep a mutated copy of `pyproject.toml` locally to reference the local package

I have a similar problem, and a partial solution - create a "local" and a "remote" group (with `[dependency-groups]`) or extra (with `[project.optional-dependencies]`). The corresponding source in `[tool.uv.sources]` can be marked with the group/extra it targets. The `conflicts` table is critical for this to work. The group/extra can then be selected during commands, e.g.:
```bash
$ uv sync --extra dev-local

Resolved 11 packages in 517ms
Uninstalled 1 package in 17ms
Installed 2 packages in 29ms
 + pygments==2.19.1
 - pytest==8.3.5
 + pytest==8.4.0.dev459+g33b26e429 (from file:///Users/Jason/Software/uv_issue/pytest)
```

```bash
$ uv sync --group dev-remote

Resolved 11 packages in 6ms
Uninstalled 1 package in 1ms
Installed 1 package in 9ms
 - pytest==8.4.0.dev459+g33b26e429 (from file:///Users/Jason/Software/uv_issue/pytest)
 + pytest==8.4.0.dev459+g33b26e429 (from git+https://github.com/pytest-dev/pytest@33b26e429817935af8eb0202aa1e5ef0476e1cad)
```

The problems with this solution are:
- The version specifier in the `dependencies` is overwritten. In some cases maybe this is desired...
- How to additionally specify a source for a default call (`uv sync`)? The `dev` group is active by default, which at first I thought could be utilised, but then a conflict occurs when trying to use `dev-local` or `dev-remote`.
- How to additionally specify a source for production? There is no way I know of to add this case to the conflict table.

Here is a simple pyproject.toml demonstration:

```toml
[project]
name = "foo"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = ["pytest~=8.3"]

[dependency-groups]
dev-local = ["pytest"]
dev-remote = ["pytest"]

[project.optional-dependencies]
dev-local = ["pytest"]
dev-remote = ["pytest"]

[tool.uv]
conflicts = [
    [
        { extra = "dev-remote" },
        { extra = "dev-local" },
        { group = "dev-remote" },
        { group = "dev-local" },
    ]
]

[tool.uv.sources]
"pytest" = [
    {path = "../pytest", editable = true, extra = "dev-local"},
    {path = "../pytest", editable = true, group = "dev-local"},
    {git = "https://github.com/pytest-dev/pytest", branch = "main", extra = "dev-remote"},
    {git = "https://github.com/pytest-dev/pytest", branch = "main", group = "dev-remote"},
]
```

Some other issues with a similar topic:
#12539 #11941 #9537 #7945 #11632 #12681 #12013
