### ISSUE TITLE
Caching of workspace on Github Action does not work well.

### ISSUE THREAD

**Issue by higumachan** [astral-sh/uv#9263]
When creating a workspace with multiple sub project, the cache for subdirectories does not work as expected.

## uv version

```
0.5.3
```

## Prerequisites

For example, when running the following in a GitHub Action:

```
      - name: "Install the project"
        run: uv sync --no-editable --all-extras --dev --frozen -vvv  --all-packages
        env:
          UV_CONCURRENT_BUILDS: 1
          UV_CONCURRENT_DOWNLOADS: 1
          UV_CONCURRENT_INSTALLS: 1
```

This issue occurs in projects using uv with multiple `pyproject.toml` files, such as the following structure:

```
.
├── pyproject.toml
└── src/
    └── packages/
        ├── package1/
        │   ├── src
        │   └── pyproject.toml
        └── package2/
            ├── src
            └── pyproject.toml
```

Here is an example `pyproject.toml`:

```toml
[project]
name = "some_project"
version = "0.1.0"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "package1",
    "package2",
]
```

## Observed Behavior

Even when configuring the uv cache directory on GitHub Actions, the cache is not applied correctly within uv.

## Cause

The issue seems to stem from a combination of two factors:
1. **Timestamp updates during `git clone`**: Files managed by Git have their timestamps updated to the clone time. As a result, the source files are always considered "newer" than the cache files, causing uv to bypass the cache.
2. **Reliance on `ctime` in uv**: Since uv uses `ctime` to determine cache freshness, workarounds like using the `touch` command cannot be applied.

### Use hash-based cache management in CI mode

Similar to the `--ci` option for `cache prune`, a `--ci` option for `sync` and `run` commands could enable hash-based cache management instead of timestamp-based.

### Use `mtime` instead of `ctime`

Using `mtime` would allow workarounds such as `touch` to function. However, as noted in #1060, this approach may have its own drawbacks and is not ideal.

---

If there are other potential solutions, please share! Especially if there's a way to resolve this issue with the current version of uv.
