### ISSUE TITLE
Document ways of having default dependency groups 

### ISSUE THREAD

**Issue by awoimbee** [astral-sh/uv#9279]
The dependency-groups documentation (<https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups>) should explain how to set default dependency groups included when running `uv synv`.

I see two ways:
```toml
[tool.uv]
default-groups = ["lint", "docs"]
```

```toml
[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "docs" },
]
```

I think this covers 95% of the use-cases of #8594
