### ISSUE TITLE
Repeated markers in `resolution-markers`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#9296]
If you lock:

```toml
[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = []

[project.optional-dependencies]
cpu = [
  "torch>=2.5.1",
  "torchvision>=0.20.1",
]
cu124 = [
  "torch>=2.5.1",
  "torchvision>=0.20.1",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
]
environments = ["platform_system != 'Darwin'", "platform_system == 'Darwin'"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

Then the top of the lockfile includes:

```toml
resolution-markers = [
    "platform_system != 'Darwin'",
    "platform_system != 'Darwin'",
    "platform_system != 'Darwin'",
    "platform_system == 'Darwin'",
    "platform_system == 'Darwin'",
    "platform_system == 'Darwin'",
]
```

And the packages have entries like:

```toml
[[package]]
name = "torch"
version = "2.5.1"
source = { registry = "https://pypi.org/simple" }
resolution-markers = [
    "platform_system != 'Darwin'",
    "platform_system != 'Darwin'",
    "platform_system != 'Darwin'",
    "platform_system == 'Darwin'",
    "platform_system == 'Darwin'",
    "platform_system == 'Darwin'",
]
```
