### ISSUE TITLE
Path resolution for packages from filepath are inconsistent

### ISSUE THREAD

**Issue by Tibiritabara** [astral-sh/uv#9327]
I have a project called `main-project` on the next route

`$HOME/project/main/apps/current-app`

This project uses two libraries on disk, on the `$HOME/project/libs/` path. These libs are:

`$HOME/project/main/libs/dep1`
`$HOME/project/main/libs/dep2`

These libraries are specified on the `current-app` project as dependencies like this:

```toml
...
dependencies = [
    "dep1 @ file:///${PROJECT_ROOT}/../../libs/dep2",
    "dep2 @ file:///${PROJECT_ROOT}/../../libs/dep1",
]
...
```

For some odd reason, it resolves the next path: `file:///$HOME/project/main/apps/dep2`, despite having exited the `apps` folder on the path definition.

UV Is unable to calculate the right path. For some reason, it is unable to exit the `apps` folder, and enter the `libs` folder, despite the route being correct.

I am currently working on a MacOS m2 machine with Python 3.12.

After more testing, I notice that the issue happens with the `main` folder. Whenever I replace the `main` folder name in the route, it resolves correctly.

I have also tested setting relative paths with `uv.tools.source`, and reached the same conclusion. The folder named `main` causes the issue.

**Comment by ReinforcedKnowledge** [comment]
Hi!

I can't seem to recreate the issue. Maybe the issue comes from naming the mismatch between `dep_{i}` and the path which is for `dep_{j}`? What `uv` version are you using?

Doing works:

```toml
[project]
name = "current-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dep1 @ file:///${PROJECT_ROOT}/../../libs/dep1",
    "dep2 @ file:///${PROJECT_ROOT}/../../libs/dep2",
]
```

Working directory: 
```
.
├── apps
│   └── current-app
│       ├── README.md
│       ├── hello.py
│       ├── pyproject.toml
│       ├── uv.lock
└── libs
    ├── dep1
    │   ├── README.md
    │   ├── hello.py
    │   └── pyproject.toml
    └── dep2
        ├── README.md
        ├── hello.py
        └── pyproject.toml
```

Running `uv sync` in `current-app`:
```
Using CPython 3.13.0
Creating virtual environment at: .venv
Resolved 3 packages in 9ms
   Built dep1 @ file:///Users/y.tahtah/Downloads/projects/test_issue/main/libs/dep1
   Built dep2 @ file:///Users/y.tahtah/Downloads/projects/test_issue/main/libs/dep2
Prepared 2 packages in 653ms
Installed 2 packages in 1ms
 + dep1==0.1.0 (from file:///Users/y.tahtah/Downloads/projects/test_issue/main/libs/dep1)
 + dep2==0.1.0 (from file:///Users/y.tahtah/Downloads/projects/test_issue/main/libs/dep2)
```

Platform: Sequoia 15.1.1 (M1)
CPython: 3.13.0
uv: 0.5.4 (c62c83c37 2024-11-20)
