### ISSUE TITLE
torch in tool.uv.source violate the pyproject.toml schema

### ISSUE THREAD

**Issue by Xiao-Chenguang** [astral-sh/uv#9328]
Minimal Example (as in the [official doc](https://docs.astral.sh/uv/guides/integration/pytorch/#using-a-pytorch-index)):
```toml
[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "torch>=2.5.1",
  "torchvision>=0.20.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "platform_system != 'Darwin'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "platform_system != 'Darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

With this configuration and `Even Better TOML` extension in vscode, there are warnings that `[{"index":"pytorch-cpu","marker":"platform_system != 'Darwin'"}] is not valid under any of the given schemas`

- uv version: 0.5.4
- platform: macos
