### ISSUE TITLE
Workspace documentation doesn't include an example of a nested package `pyproject.toml`

### ISSUE THREAD

**Issue by samuelcolvin** [astral-sh/uv#9415]
See https://docs.astral.sh/uv/concepts/projects/workspaces/

Workspace documentation doesn't include an example of a nested package `pyproject.toml` file, instead there are three examples of the `pyproject.toml` file for `name = "albatross"` the root package.

I'm trying to work out what I should put in a `pyproject.toml` file of a nested package, and it's not clear.

In particular, when working with cargo, I can include stuff like `version = { workspace = true }`, but it's not clear if I can do that with uv.

**Comment by samuelcolvin** [comment]
😞 

I tried

```toml
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
classifiers = { workspace = true }
requires-python = { workspace = true }
```

As I would do with cargo, but I get:

```
uv sync
error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 7, column 11
  |
7 | version = { workspace = true }
  |           ^^^^^^^^^^^^^^^^^^^^
invalid type: map, expected a string
```

**Comment by charliermarsh** [comment]
Ah yeah, we don't inherit workspace configuration like that. In fact, we can't right now, it would be non-standards compliant and would break a lot of other tools. It's possible that we can provide something like this in the future via our own build backend, but even then, you'd need to use our build backend (rather than, e.g., maturin).

**Comment by samuelcolvin** [comment]
Duplicating `description`, `authors`, `license` etc. is fine, but it would be really useful if I could set `version` as "dynamic" and have it shared across all packages.

I guess that might already be possible?

**Comment by samuelcolvin** [comment]
Turns out the package version stuff is easy, you can just do

```toml
[tool.hatch.version]
path = "../pyproject.toml"

[project]
dynamic = ["version"]
```

The ugly bit is if you want your packages to have a hard requirement on each other (e.g. you release `foo`, `bar` and `spam`, all have version `0.0.6b1` and you want `foo` and `bar` to depend on `spam==0.0.6b1`) then you have to hard code the version number in a bunch of places.
