### ISSUE TITLE
Tensorflow doesn't have a source distribution or wheel for the current platform

### ISSUE THREAD

**Issue by younver** [astral-sh/uv#9420]
Salute, I've been trying to solve this issue for a while, but couldn't manage to resolve it even after digging through my project like a minefield. I'd really appreciate any help!

```
$ uv sync
error: distribution tensorflow==2.8.1 @ registry+https://pypi.org/simple can't be installed because it doesn't have a source distribution or wheel for the current platform
```

current pyproject.toml:
```toml
[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "<3.11,>=3.10"
dependencies = [
    "fastapi==0.115.5",
    "uvicorn==0.32.1",
    "pydub==0.25.1",
    "soundfile==0.12.1",
    "torch==2.5.1",
    "speechbrain==1.0.2",
    "soxr<0.5.0,>=0.3.0",
    "pydantic-settings==2.6.1",
    "google-cloud-bigquery==3.27.0",
    "google-cloud-storage==2.18.2",
    "onnxruntime==1.20.1",
    "spleeter==2.4.0",
]
```

current uv platform: Apple MacBook M1 Sonoma 14.6.1
current uv version: uv 0.4.17 (Homebrew 2024-09-27)
