### ISSUE TITLE
Adding documentation for handling LSP import error when using packages from workspaces

### ISSUE THREAD

**Issue by mohit2152sharma** [astral-sh/uv#9471]
Consider the following directory structure, in this example, I have a `llm` package in the workspace.

```
.
├── README.md
├── hello.py
├── packages
│   ├── llm
│   │   ├── README.md
│   │   ├── pyproject.toml
│   │   └── src
│   │       └── llm
│   │           └── __init__.py
├── pyproject.toml
├── src
│   └── saral_backend
│       ├── main.py
│       ├── routes
│       │   ├── __init__.py
│       │   └── notes
│       │       ├── __init__.py
│       │       ├── models.py
│       │       └── route.py
├── tests
└── uv.lock
```
When I try to import this package in my `src/saral_backend/main.py` I get the `reportMissingImports` Error from `basedpyright` (or other LSPs). This error is correct as the package `llm` is not yet installed and once I install the package in the same virtual environment the error goes away. 
It would be nice to have this documented along the lines of "packages in the workspace needs to be installed in the same virtual environment for the LSPs to correctly resolve them". 

Also I couldn't find any mention of installing local packages. Currently what I do is `cd` into the package directory and run `uv run` (without any argument), this seems to build the package and install it but it also generates a message `"Provide a command or script ....."`. Not sure if using `uv run` is the right way to install local packages in the virtual environment.

(I can take a stab at the documentation, if you can point me in the right direction)

**Comment by mohit2152sharma** [comment]
yes, using the `hatchling` build system. I think this gets added automatically when I do `uv init --package`

Following is my main `pyproject.toml` (in the root directory)

```toml
[project]
name = "saral-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.5",
    "psycopg2>=2.9.10",
    "pydantic[email]>=2.10.2",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.32.1",
]

[project.scripts]
app = "saral_backend.main:main"

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages=["src/saral_backend"]

[tool.uv.workspace]
members = ["packages/saral-utils", "packages/llm"]

```

And this is my toml file from `llm` package

```toml
[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohit sharma", email = "mohitlakshya@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
llm = "llm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

**Comment by zanieb** [comment]
I don't think hatchling will use the `packages` directory by default, so maybe you need

```
[tool.hatch.build.targets.wheel]
sources = ["src", "packages"]
```

I'm not really sure on the specifics of how to configure hatchling's editable installations though.

**Comment by mohit2152sharma** [comment]
Thanks @zanieb , I tried your suggestion, but it didn't help. I made the changes to main `pyproject.toml`  (file in the root directory). I get the following error, when I attempt to build my main package.

```
ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

The most likely cause of this is that there is no directory that matches the name of your project (saral_backend).

At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/

As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]
error: Build backend failed to build wheel through `build_wheel` (exit status: 1)
```

Then I tried with the suggestions suggested by error message, I used the full path as in:

```toml
[tool.hatch.build.targets.wheel]
# packages=["src/saral_backend"]
# sources = ["src", "packages"]
packages = ["src/saral_backend", "packages/llm/src/llm", "packages/saral-utils/src/saral_utils"]
```
With this I am able to build my main package. I can see that the entire `packages` directory is included in the tar file (in the `dist` folder). However, when I do `uv pip list` to see the packages installed in the virtual environment, I don't see the two packages in the list. When I do `uv run --all-packages`, it installs all the packages in virtual environment from the workspaces.
