### ISSUE TITLE
Improve error message for workspace members with non-workspace sources

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#9479]
Given:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "repro-uv-8148-a>=1.0.1",
]

[tool.uv.workspace]
members = ["../repro-uv-8148-a"]

[tool.uv]
override-dependencies = ["repro-uv-8148-a"]

[tool.uv.sources]
repro-uv-8148-a = { path = ".", editable = true }
```

You get:

```
error: Failed to parse entry: `repro-uv-8148-a`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`
```

We should explain that you have a conflicting source here.
