### ISSUE TITLE
Platform markers are ignored when syncing optional self-dependencies

### ISSUE THREAD

**Issue by befelix** [astral-sh/uv#9499]
In the following minimal  `pyproject.toml` file, we are creating a package where the `self` optional dependency that depends on the `base` extra (the `tomli` package) through a self-dependency together with a platform marker that is not satisfied on my Linux machine. When running `uv sync --extra self` the packages from the `base` extra get installed, even though the platform marker should exclude them.

```bash
$ uv sync --extra self

Using CPython 3.13.0
Creating virtual environment at: .venv
Resolved 2 packages in 5ms
Installed 1 package in 2ms
 + tomli==2.2.1
```

```toml
[project]
name = "testing"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
base = [
    "tomli>=2.2.1",
]
self = [
    "testing[base]; platform_system == 'Windows'",
]

[tool.uv.sources]
testing = { workspace = true }
```

- platform: Linux
- uv version: 0.5.5
