### ISSUE TITLE
`constraint-dependencies` not respected outside of pyproject.toml

### ISSUE THREAD

**Issue by cdb39** [astral-sh/uv#9508]
`constraint-dependencies` specified in either a project uv.toml, or a user-level uv.toml are ignored, regardless of anything present in the pyproject.toml.  I'm using uv version 0.5.5.

The documentation on constraint dependencies is a bit light but I feel like this is surprising behaviour.

If it is expected, are there any plans to support `constraint-dependencies` specified in either the user or system-level uv configuration?

**Simple example of them working in pyproject.toml**

pyproject.toml
```toml
[project]
name = "uv-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv]
constraint-dependencies = [
    "flask<3"
]
```

Running `uv add flask` does not install a version >=3
```shell
Creating virtual environment at: .venv
Resolved 9 packages in 134ms
Prepared 7 packages in 75ms
Installed 7 packages in 2ms
 + blinker==1.9.0
 + click==8.1.7
 + flask==2.3.3
 + itsdangerous==2.2.0
 + jinja2==3.1.4
 + markupsafe==3.0.2
 + werkzeug==3.1.3
```

**Simple example of them not working in uv.toml**

pyproject.toml
```toml
[project]
name = "uv-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
```

uv.toml
```
constraint-dependencies = [
    "flask<3"
]
```

Running `uv add flask` installs version 3.1.0
```shell
Creating virtual environment at: .venv
Resolved 9 packages in 84ms
Prepared 1 package in 32ms
Installed 7 packages in 3ms
 + blinker==1.9.0
 + click==8.1.7
 + flask==3.1.0
 + itsdangerous==2.2.0
 + jinja2==3.1.4
 + markupsafe==3.0.2
 + werkzeug==3.1.3
```
