### ISSUE TITLE
`uv pip compile` doesn't propagate markers on recursive self-extras

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#9530]
E.g., given:
```toml
[project]
name = "testing"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
base = [
    "tomli>=2.2.1",
]
self = [
    "testing[base]; platform_system == 'Windows'",
]

[tool.uv.sources]
testing = { workspace = true }
```

You get:

```shell
❯ uv pip compile ./foo/pyproject.toml --universal --all-extras
Resolved 2 packages in 90ms
# This file was autogenerated by uv via the following command:
#    uv pip compile ./foo/pyproject.toml --universal --all-extras
testing @ file:///Users/crmarsh/workspace/uv/foo ; platform_system == 'Windows'
    # via testing (./foo/pyproject.toml)
tomli==2.2.1
    # via
    #   testing (./foo/pyproject.toml)
    #   testing
```

It's the same as https://github.com/astral-sh/uv/issues/9499, but for `-r pyproject.toml` which goes through a different codepath (we read the dependencies prior to hitting the resolver).
