### ISSUE TITLE
Not possible to authenticate into private registries via UV_INDEX env variables

### ISSUE THREAD

**Issue by mkravchenko-nable** [astral-sh/uv#9577]
Hello, as it described here [authorize into private registry](https://docs.astral.sh/uv/configuration/indexes/#searching-across-multiple-indexes) it should be possible to authorize into private registry, but each time I have same error:

`An index URL (https://host.com/example/api/pypi/python-local/simple) could not be queried due to a lack of valid authentication credentials (401 Unauthorized).`

In pyproject.toml I have:

```
[tool.uv]
index-strategy = "unsafe-best-match"
index-url = "https://pypi.org/simple"


[[tool.uv.index]]
name = "private"
url = "https://host.com/example/api/pypi/python-local/simple"
```

First of all, I have set two env variables: `UV_INDEX_PRIVATE_USERNAME` and `UV_INDEX_PRIVATE_PASSWORD` 
Next I'm trying to do (that bring unauthorized error):

```uv pip install -r pyproject.toml```

> If I directly providing user/password into the URL inside pyproject.toml it works as expected.

**Comment by charliermarsh** [comment]
I've confirmed that we're setting the credentials here are as expected. It's working on my side. I'd need a more complete reproduction to hep out.

**Comment by charliermarsh** [comment]
Specifically, I did:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["iniconfig"]

[tool.uv]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "private"
default = true
url = "https://pypi-proxy.fly.dev/basic-auth/simple"
```

Then this worked:

```
UV_INDEX_PRIVATE_USERNAME=public UV_INDEX_PRIVATE_PASSWORD=heron cargo run pip install -r pyproject.toml --verbose
```
