### ISSUE TITLE
Adding an explicit index with no references causes private packages to fail dependency resolution

### ISSUE THREAD

**Issue by JonZeolla** [astral-sh/uv#9587]
I was following the docs to [add pytorch](https://docs.astral.sh/uv/guides/integration/pytorch/) to a repo and found that when I add the following:

```toml
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

To my `pyproject.toml`, I start to get `uv run` failures about dependency resolving:

```
  × No solution found when resolving dependencies for split (python_full_version >= '3.12' and python_full_version < '3.12.4' and platform_system == 'Darwin'):
  ╰─▶ Because internal-package-2 was not found in the package registry and your project depends on internal-package-2>=1.2.3, we can conclude that your project's requirements are unsatisfiable.
```

This isn't intuitive to me, because I have `explicit = true` and I haven't referenced the new index in any of my dependencies. I was able to get my `pyproject.toml` down to something like the following and still experience the issue:

```toml
[project]
name = "example"
version = "0"
dependencies = [
    "internal-package-1",
    "internal-package-2>=1.2.3",
]
requires-python = ">= 3.12"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

**Comment by zanieb** [comment]
How are you providing your internal packages?

**Comment by JonZeolla** [comment]
When I install I set the `UV_EXTRA_INDEX_URL` env like [this](https://docs.astral.sh/uv/guides/integration/alternative-indexes/#aws-codeartifact)

**Comment by JonZeolla** [comment]
Uv run is `uv run ./example.py`

**Comment by zanieb** [comment]
cc @charliermarsh — I'm not sure what the expected interaction between mixing the two index interfaces is here.

I agree the behavior seems surprising though.

**Comment by charliermarsh** [comment]
I'll take a look.

**Comment by charliermarsh** [comment]
I can't reproduce this... The best I could do with public indexes is:

```toml
[project]
name = "example"
version = "0"
dependencies = [
    "jinja2"
]
requires-python = ">= 3.12"

[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org"
explicit = true
```

And then `UV_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu uv lock`.

The lockfile correctly references the PyTorch index.
