### ISSUE TITLE
Optimize '#' usage in git dependencies

### ISSUE THREAD

**Issue by minmax** [astral-sh/uv#9649]
If i have this:

```toml
[project]
name = "test"
requires-python = ">=3.11"
version = "0.0.1"
dependencies = [
    "django-types@git+https://github.com/sbdchd/django-types.git@main#d7c95ba",
]
```

and run `uv sync` 5 times, the last shows:

```bash
uv sync
# Resolved 3 packages in 131ms
# Audited 2 packages in 0.01ms
```
`0,18s` total

but when i have this:

```toml
dependencies = [
    "django-types@git+https://github.com/sbdchd/django-types.git@main",
]
```

(drop `#d7c95ba`)
`uv sync` works as fast as expected

```bash
 uv sync
# Resolved 3 packages in 1ms
# Audited 2 packages in 0.01ms
```
`0,06s` total

```
uv --version  
uv 0.5.6 (Homebrew 2024-12-03)
```
