### ISSUE TITLE
`uv` incorrectly (?) installs `dbt-clickhouse`

### ISSUE THREAD

**Issue by ivanychev** [astral-sh/uv#9693]
When installing `dbt-core` and `dbt-clickhouse`, dbt can't see ClickHouse plugin
 
* Platform: M2 Pro, macOS 15.1.1
* `uv` version: 0.5.6

# Steps to reproduce

pyproject.toml:

```toml
[project]
name = "dbt-clickhouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.9"
dependencies = [
    "dbt-clickhouse==1.8.5",
    "dbt-core==1.8.9"
]
```

```
uv lock && uv sync
uv run dbt --version
```

outputs

```
Core:
  - installed: 1.8.9
  - latest:    1.8.9 - Up to date!

Plugins:


```

# Expected behavior

Using `pyenv`:

```
pyenv shell 3.11.9
python -m venv venv
source venv/bin/activate
pip install dbt-core==1.8.9 dbt-clickhouse==1.8.5
dbt --version
```

outputs

```
Core:
  - installed: 1.8.9
  - latest:    1.8.9 - Up to date!

Plugins:
  - clickhouse: 1.8.5 - Up to date!   # <<<<<<<<<<<<<<<<
```
