### ISSUE TITLE
Massive `uv.lock` file

### ISSUE THREAD

**Issue by NellyWhads** [astral-sh/uv#9700]
Is it safe to clean up duplicate lines in the `uv.lock` file? Can this be done as part of the `lock` procedure? In my lock file's resolution-markers section, have lines repeated thousands of times.

Example:

```toml
resolution-markers = [
    "python_full_version < '3.9' and platform_machine == 'aarch64' and platform_system == 'Linux'", # (repeated more than 19,999 times)
    "platform_system == 'Darwin'", # (repeated 18,751 times)
    # ... ad nauseum
]
```

This leads to a ~190k-line lock file. Though this is quite a nice bump to my performance metrics at work, DevOps is asking why my python repository is not mostly python code 😅.
