### ISSUE TITLE
uv add with multiple (extra-)index-urls fails

### ISSUE THREAD

**Issue by legout** [astral-sh/uv#9741]
Hi guys,

we have multiple private gitlab repos with its own package index. 

When I try to add two packages to my project, I always get an error, that a package can not be downloaded.

I´ve tried the following:

Add `[[tool.uv.index]]` entries to the pyproject.toml for each package (with and without additional `[tool.uv.sources]`)

```toml

[tool.uv.sources]
package1 = { index = "package1" }
package2 = { index = "package2" }

[[tool.uv.index]]
name = "package1"
url = "https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple"

[[tool.uv.index]]
name = "package2"
url = "https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple"

```

Set the env variable `UV_EXTRA_INDEX_URL to https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple` (space seperated both package registries)

Run each add command with its own --index 
```bash
uv add package1 --index https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple
uv add package2 --index https://token1:secret1@private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/simple
```

None of these worked. It alway fails to download one of the packages.

```bash
error: Failed to fetch: `https://private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/files/5558649d00d348f5f9486dcd7d309cfa9968f06cd0f40bf01fa06e4c758e67ef/package1-0.1.0-py3-none-any.whl#sha256=5558649d00d348f5f9486dcd7d309cfa9968f06cd0f40bf01fa06e4c758e67ef`
  Caused by: HTTP status client error (404 Not Found) for url (https://private.gitlab-repo.com/api/v4/projects/12345/packages/pypi/files/5558649d00d348f5f9486dcd7d309cfa9968f06cd0f40bf01fa06e4c758e67ef/package1-0.1.0-py3-none-any.whl#sha256=5558649d00d348f5f9486dcd7d309cfa9968f06cd0f40bf01fa06e4c758e67ef)
```
