### ISSUE TITLE
`uv pip install` not working with `#subdirectory` in monorepo

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#9743]
I have something like this, both in the same GitHub repo:

```toml
# pyproject.toml

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64"]

[project]
name = "repo-pkga"
dependencies = ["repo-pkgb"]

[tool.uv.sources]
repo-pkgb = {editable = true, path = "pkgb"}
repo-pkga = {workspace = true}
```

```toml
# pkgb/pyproject.toml

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64"]

[project]
name = "repo-pkgb"
dependencies = []
```

With `uv==0.5.7`, `uv pip install` fails but `pip install` succeeds when passed:
- `"repo-pkga @ git+ssh://git@github.com/org/repo.git"`
- `"repo-pkgb @ git+ssh://git@github.com/org/repo.git#subdirectory=pkgb"`

I believe what is happening is `uv pip` is not seeing `#subdirectory` in the second install and thinks there is a conflict.

<details>
<summary><code>uv pip install</code> Fails</summary>

```none
> uv pip install "repo-pkga @ git+ssh://git@github.com/org/repo.git" "repo-pkgb @ git+ssh://git@github.com/org/repo.git#subdirectory=pkgb"
 Updated ssh://git@github.com/org/repo.git (ec479a8)
  × Failed to download and build `repo-pkga @ git+ssh://git@github.com/org/repo.git`
  ╰─▶ Package metadata name `repo-pkgb` does not match given name `repo-pkga`
```

</details>

<details>
<summary><code>pip install</code> Succeeds</summary>

```none
> pip install "repo-pkga @ git+ssh://git@github.com/org/repo.git" "repo-pkgb @ git+ssh://git@github.com/org/repo.git#subdirectory=pkgb"
Collecting repo-pkga@ git+ssh://****@github.com/org/repo.git
  Cloning ssh://****@github.com/org/repo.git to /private/var/folders/5c/20jqnfqx4sv1_6_bdkf765cr0000gn/T/pip-install-816hulg5/repo-pkga_793bf123f2524b72bb07f205e40b1397
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/org/repo.git' /private/var/folders/5c/20jqnfqx4sv1_6_bdkf765cr0000gn/T/pip-install-816hulg5/repo-pkga_793bf123f2524b72bb07f205e40b1397
  Resolved ssh://****@github.com/org/repo.git to commit ec479a820fc45779b40fb94b07f39ebef412ba58
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting repo-pkgb@ git+ssh://****@github.com/org/repo.git#subdirectory=paperscraper
  Cloning ssh://****@github.com/org/repo.git to /private/var/folders/5c/20jqnfqx4sv1_6_bdkf765cr0000gn/T/pip-install-816hulg5/repo-pkgb_22e0edec781045e0a79b343882ee612d
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/org/repo.git' /private/var/folders/5c/20jqnfqx4sv1_6_bdkf765cr0000gn/T/pip-install-816hulg5/repo-pkgb_22e0edec781045e0a79b343882ee612d
  Resolved ssh://****@github.com/org/repo.git to commit ec479a820fc45779b40fb94b07f39ebef412ba58
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```

</details>
