### ISSUE TITLE
Building and publishing uv workspace members with pinned version constraints

### ISSUE THREAD

**Issue by mtnmbr** [astral-sh/uv#9811]
Hey,

first of all. Thanks a lot for your efforts on making the python tooling ecosystem better! I love ruff and uv :). Please keep up the great work.

I am currently migrating an existing monorepo from poetry using the [poetry-monorepo-dependency-plugin](https://pypi.org/project/poetry-monorepo-dependency-plugin/) to uv.

I thought that uv workspaces should be the way to handle this usecase. 

The current setup looks somewhat like this:

```
uv_monorepo
│   .gitignore
│   .python-version
│   pyproject.toml
│   README.md
│   uv.lock
│
├───package_a
│   │   pyproject.toml
│   │   README.md
│   │
│   └───src
│       └───package_a
│               py.typed
│               __init__.py
│
├───package_b
│   │   pyproject.toml
│   │   README.md
│   │
│   └───src
│       └───package_b
│               py.typed
│               __init__.py
│
└───package_c
    │   pyproject.toml
    │   README.md
    │
    └───src
        └───package_c
                py.typed
                __init__.py
```
uv tree gives the following output to show the inter_package dependecies:
```
#uv tree
Using CPython 3.12.1
Resolved 4 packages in 13ms
package-a v0.1.0
└── package-b v0.2.0
    └── package-c v0.3.0
uv-monorepo v0.1.0
```

So my previous setup did allow me to publish the packages individually to our internal pypi mirror with pinned versions of the dependencies.

My  main pyproject.toml looks like this atm. (in reality the workspace members are added to the toplevel virtual workspace package to be able to omit the `--al--packages` on `uv sync`):

```toml
[project]
name = "uv-monorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.uv.workspace]
members = ["package_a", "package_b", "package_c"]

```

With e.g. the package_a pyproject.toml being:

```toml
[project]
name = "package-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "package-b",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
package-b = { workspace = true }

```

This demo setup has basically been fully created with several `uv init` calls.

The hope was that `uv build --package-a --wheel` would output a wheel that has the pinned lower version of the dependency `package-b` listed internally. At least this is what my previous setup did. 
Instead I get a METADATA file like this:
```
Metadata-Version: 2.3
Name: package-a
Version: 0.1.0
Summary: Add your description here
Requires-Python: >=3.12
Requires-Dist: package-b
```

When published to our pypi instance this would ofcource not resolve to the actual boundary of `package-b>=0.2.0,<0.3 ` that would be required here.

After bumping e.g. the patch version of `package-b` I would also assume that the version inside the METADATA is bumped to e.g. 0.2.1.

Is this use-case supported? What is the current approach to handle this properly? I am open for suggestions!

Best regards 
Michael
