### ISSUE TITLE
Build backend rejects underscores in entrypoint names

### ISSUE THREAD

**Issue by blueraft** [astral-sh/uv#9812]
MRE:

```toml
[project]
name = "entry-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv>=0.5.7,<0.6"]
build-backend = "uv"

[project.entry-points.'myapp.plugins']
plugin_a = "myapp_plugin_a"
```

```bash
❯ uv build
....
  ├─▶ Invalid pyproject.toml
  ╰─▶ Entrypoint names must consist of letters, numbers, dots and dashes; invalid name: `plugin_a`
```

Based on the [spec](https://packaging.python.org/en/latest/specifications/entry-points/#data-model), you're allowed to have underscores in the name.

> For new entry points, it is recommended to use only letters, numbers, **underscores**, dots and dashes (regex [\w.-]+).
