### ISSUE TITLE
(🐞) `uv remove` deletes comments

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/uv#9856]
```toml
[project]
name = "python-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    # should be in alphabetical order
    "basedmypy[faster-cache]>=2.8.1", # this is a comment
    "basedpyright>=1.18.2,<2.0.0",
]
```
```
> uv remove basedmypy
```
```toml
[project]
name = "python-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [ # this is a comment
    "basedpyright>=1.18.2,<2.0.0",
]
```
