### ISSUE TITLE
PyTorch install fails on M1 using a Debian container ?

### ISSUE THREAD

**Issue by ghsanti** [astral-sh/uv#9878]
Here trying to set up the pyproject to install torch. Currently I just tried installing within a Debian Container, on an M1. 

But [it fails with the example in the docs.](https://docs.astral.sh/uv/guides/integration/pytorch/#configuring-accelerators-with-optional-dependencies)

**Minimal Context**

uv version:

```bash
$ uv --version
uv 0.5.8
```

Config from the guide (simplified it a bit; just removed cuda and torchvision.):

```toml
[project.optional-dependencies]
cpu = [ "torch>=2.5.1"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

I've clean the cache and started a fresh venv.

**Issue**

And then running:

```bash
vscode ➜ /workspaces/project (dev) $ uv venv
Using CPython 3.10.16
Creating virtual environment at: .venv
vscode ➜ /workspaces/project (dev) $ source .venv/bin/activate
(project) vscode ➜ /workspaces/project (dev) $ uv sync --extra cpu
Resolved 85 packages in 6.05s
error: Distribution `torch==2.5.1+cpu @ registry+https://download.pytorch.org/whl/cpu` can't be installed because it doesn't have a source distribution or wheel for the current platform
```

I may be doing something wrong, but can not figure it out.
