### ISSUE TITLE
uvx CLI scripts ("tools" ?) ignore `--help` argument when using `Fire` or `Typer`

### ISSUE THREAD

**Issue by pchalasani** [astral-sh/uv#9917]
E.g. in my `langroid-examples` repo, I've enabled some scripts to be runnable as follows:

```bash
uvx --from langroid-examples chat
```

I've set up a `[project.scripts]` table with these entries:
```toml
[project.scripts]
chat = "examples.basic.chat:app"
completion = "examples.basic.completion:app"
chatdoc = "examples.docqa.chat:app"
chatsearch = "examples.docqa.chat_search:main"
```

See [here](https://github.com/langroid/langroid-examples?tab=readme-ov-file#run-scripts-with-no-repo-cloning-no-venv-setup) and the actual `chat.py` script [here](https://github.com/langroid/langroid-examples/blob/main/examples/basic/chat.py)

Note that I use `typer.Typer.app()` for running this app. 
Running `uvx --from langroid-examples chat` works fine, but when I run
```bash
uvx --from langroid-examples chat --help
```
The `--help` is ignored. 
Similarly, the `chat_search.py` uses `fire.Fire` to create the cli, and there as well the `--help` is ignored.

I don't know if this problem is specific to `uv`, or in general `--help` is ignored when CLI scripts are defined using `Fire` or `Typer`
